rules = [
  RemoveUnused,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  OrganizeImports,
  ProcedureSyntax,
]

OrganizeImports {
  groupedImports = Merge
  removeUnused = true
}

RemoveUnused {
  imports = true
}
