// Generated by CIRCT firtool-1.76.0
module Arbiter4_MI(
  input  wire        io_in_0_valid,
  input  wire        io_in_0_bits_retired,
  input  wire [6:0]  io_in_0_bits_rdTag,
  input  wire        io_in_0_bits_isBranch,
  input  wire        io_in_0_bits_isJAL,
  input  wire [1:0]  io_in_0_bits_lsType,
  input  wire        io_in_0_bits_wakeup,
  input  wire [1:0]  io_in_0_bits_opsrc1,
  input  wire [1:0]  io_in_0_bits_opsrc2,
  input  wire [1:0]  io_in_0_bits_writeRf,
  input  wire [2:0]  io_in_0_bits_exEngine,
  input  wire [5:0]  io_in_0_bits_exOp,
  input  wire [5:0]  io_in_0_bits_lsOp,
  input  wire        io_in_0_bits_exception,
  input  wire        io_in_0_bits_taken,
  input  wire [31:0] io_in_0_bits_imm,
  input  wire [4:0]  io_in_0_bits_rs1,
  input  wire [4:0]  io_in_0_bits_rs2,
  input  wire [4:0]  io_in_0_bits_rd,
  input  wire [31:0] io_in_0_bits_pc,
  input  wire [31:0] io_in_0_bits_targetPC,
  input  wire [6:0]  io_in_0_bits_rs1Tag,
  input  wire        io_in_0_bits_rs1TagReady,
  input  wire [6:0]  io_in_0_bits_rs2Tag,
  input  wire        io_in_0_bits_rs2TagReady,
  input  wire [31:0] io_in_0_bits_rs1Data,
  input  wire [31:0] io_in_0_bits_rs2Data,
  input  wire [31:0] io_in_0_bits_rdData,
  input  wire        io_in_0_bits_operandReady,
  input  wire        io_in_0_bits_flushed,
  input  wire [6:0]  io_in_0_bits_arfTag,
  input  wire        io_in_0_bits_arfValid,
  input  wire [31:0] io_in_0_bits_inst,
  input  wire        io_in_1_valid,
  input  wire        io_in_1_bits_retired,
  input  wire [6:0]  io_in_1_bits_rdTag,
  input  wire        io_in_1_bits_isBranch,
  input  wire        io_in_1_bits_isJAL,
  input  wire [1:0]  io_in_1_bits_lsType,
  input  wire        io_in_1_bits_wakeup,
  input  wire [1:0]  io_in_1_bits_opsrc1,
  input  wire [1:0]  io_in_1_bits_opsrc2,
  input  wire [1:0]  io_in_1_bits_writeRf,
  input  wire [2:0]  io_in_1_bits_exEngine,
  input  wire [5:0]  io_in_1_bits_exOp,
  input  wire [5:0]  io_in_1_bits_lsOp,
  input  wire        io_in_1_bits_exception,
  input  wire        io_in_1_bits_taken,
  input  wire [31:0] io_in_1_bits_imm,
  input  wire [4:0]  io_in_1_bits_rs1,
  input  wire [4:0]  io_in_1_bits_rs2,
  input  wire [4:0]  io_in_1_bits_rd,
  input  wire [31:0] io_in_1_bits_pc,
  input  wire [31:0] io_in_1_bits_targetPC,
  input  wire [6:0]  io_in_1_bits_rs1Tag,
  input  wire        io_in_1_bits_rs1TagReady,
  input  wire [6:0]  io_in_1_bits_rs2Tag,
  input  wire        io_in_1_bits_rs2TagReady,
  input  wire [31:0] io_in_1_bits_rs1Data,
  input  wire [31:0] io_in_1_bits_rs2Data,
  input  wire [31:0] io_in_1_bits_rdData,
  input  wire        io_in_1_bits_operandReady,
  input  wire        io_in_1_bits_flushed,
  input  wire [6:0]  io_in_1_bits_arfTag,
  input  wire        io_in_1_bits_arfValid,
  input  wire [31:0] io_in_1_bits_inst,
  input  wire        io_in_2_valid,
  input  wire        io_in_2_bits_retired,
  input  wire [6:0]  io_in_2_bits_rdTag,
  input  wire        io_in_2_bits_isBranch,
  input  wire        io_in_2_bits_isJAL,
  input  wire [1:0]  io_in_2_bits_lsType,
  input  wire        io_in_2_bits_wakeup,
  input  wire [1:0]  io_in_2_bits_opsrc1,
  input  wire [1:0]  io_in_2_bits_opsrc2,
  input  wire [1:0]  io_in_2_bits_writeRf,
  input  wire [2:0]  io_in_2_bits_exEngine,
  input  wire [5:0]  io_in_2_bits_exOp,
  input  wire [5:0]  io_in_2_bits_lsOp,
  input  wire        io_in_2_bits_exception,
  input  wire        io_in_2_bits_taken,
  input  wire [31:0] io_in_2_bits_imm,
  input  wire [4:0]  io_in_2_bits_rs1,
  input  wire [4:0]  io_in_2_bits_rs2,
  input  wire [4:0]  io_in_2_bits_rd,
  input  wire [31:0] io_in_2_bits_pc,
  input  wire [31:0] io_in_2_bits_targetPC,
  input  wire [6:0]  io_in_2_bits_rs1Tag,
  input  wire        io_in_2_bits_rs1TagReady,
  input  wire [6:0]  io_in_2_bits_rs2Tag,
  input  wire        io_in_2_bits_rs2TagReady,
  input  wire [31:0] io_in_2_bits_rs1Data,
  input  wire [31:0] io_in_2_bits_rs2Data,
  input  wire [31:0] io_in_2_bits_rdData,
  input  wire        io_in_2_bits_operandReady,
  input  wire        io_in_2_bits_flushed,
  input  wire [6:0]  io_in_2_bits_arfTag,
  input  wire        io_in_2_bits_arfValid,
  input  wire [31:0] io_in_2_bits_inst,
  input  wire        io_in_3_valid,
  input  wire        io_in_3_bits_retired,
  input  wire [6:0]  io_in_3_bits_rdTag,
  input  wire        io_in_3_bits_isBranch,
  input  wire        io_in_3_bits_isJAL,
  input  wire [1:0]  io_in_3_bits_lsType,
  input  wire        io_in_3_bits_wakeup,
  input  wire [1:0]  io_in_3_bits_opsrc1,
  input  wire [1:0]  io_in_3_bits_opsrc2,
  input  wire [1:0]  io_in_3_bits_writeRf,
  input  wire [2:0]  io_in_3_bits_exEngine,
  input  wire [5:0]  io_in_3_bits_exOp,
  input  wire [5:0]  io_in_3_bits_lsOp,
  input  wire        io_in_3_bits_exception,
  input  wire        io_in_3_bits_taken,
  input  wire [31:0] io_in_3_bits_imm,
  input  wire [4:0]  io_in_3_bits_rs1,
  input  wire [4:0]  io_in_3_bits_rs2,
  input  wire [4:0]  io_in_3_bits_rd,
  input  wire [31:0] io_in_3_bits_pc,
  input  wire [31:0] io_in_3_bits_targetPC,
  input  wire [6:0]  io_in_3_bits_rs1Tag,
  input  wire        io_in_3_bits_rs1TagReady,
  input  wire [6:0]  io_in_3_bits_rs2Tag,
  input  wire        io_in_3_bits_rs2TagReady,
  input  wire [31:0] io_in_3_bits_rs1Data,
  input  wire [31:0] io_in_3_bits_rs2Data,
  input  wire [31:0] io_in_3_bits_rdData,
  input  wire        io_in_3_bits_operandReady,
  input  wire        io_in_3_bits_flushed,
  input  wire [6:0]  io_in_3_bits_arfTag,
  input  wire        io_in_3_bits_arfValid,
  input  wire [31:0] io_in_3_bits_inst,
  output wire        io_out_valid,
  output wire        io_out_bits_retired,
  output wire [6:0]  io_out_bits_rdTag,
  output wire        io_out_bits_isBranch,
  output wire        io_out_bits_isJAL,
  output wire [1:0]  io_out_bits_lsType,
  output wire        io_out_bits_wakeup,
  output wire [1:0]  io_out_bits_opsrc1,
  output wire [1:0]  io_out_bits_opsrc2,
  output wire [1:0]  io_out_bits_writeRf,
  output wire [2:0]  io_out_bits_exEngine,
  output wire [5:0]  io_out_bits_exOp,
  output wire [5:0]  io_out_bits_lsOp,
  output wire        io_out_bits_exception,
  output wire        io_out_bits_taken,
  output wire [31:0] io_out_bits_imm,
  output wire [4:0]  io_out_bits_rs1,
  output wire [4:0]  io_out_bits_rs2,
  output wire [4:0]  io_out_bits_rd,
  output wire [31:0] io_out_bits_pc,
  output wire [31:0] io_out_bits_targetPC,
  output wire [6:0]  io_out_bits_rs1Tag,
  output wire        io_out_bits_rs1TagReady,
  output wire [6:0]  io_out_bits_rs2Tag,
  output wire        io_out_bits_rs2TagReady,
  output wire [31:0] io_out_bits_rs1Data,
  output wire [31:0] io_out_bits_rs2Data,
  output wire [31:0] io_out_bits_rdData,
  output wire        io_out_bits_operandReady,
  output wire        io_out_bits_flushed,
  output wire [6:0]  io_out_bits_arfTag,
  output wire        io_out_bits_arfValid,
  output wire [31:0] io_out_bits_inst,
  output wire [1:0]  io_chosen
);

  wire        _GEN = io_in_2_valid ? io_in_2_bits_retired : io_in_3_bits_retired;
  wire [6:0]  _GEN_0 = io_in_2_valid ? io_in_2_bits_rdTag : io_in_3_bits_rdTag;
  wire        _GEN_1 = io_in_2_valid ? io_in_2_bits_isBranch : io_in_3_bits_isBranch;
  wire        _GEN_2 = io_in_2_valid ? io_in_2_bits_isJAL : io_in_3_bits_isJAL;
  wire [1:0]  _GEN_3 = io_in_2_valid ? io_in_2_bits_lsType : io_in_3_bits_lsType;
  wire        _GEN_4 = io_in_2_valid ? io_in_2_bits_wakeup : io_in_3_bits_wakeup;
  wire [1:0]  _GEN_5 = io_in_2_valid ? io_in_2_bits_opsrc1 : io_in_3_bits_opsrc1;
  wire [1:0]  _GEN_6 = io_in_2_valid ? io_in_2_bits_opsrc2 : io_in_3_bits_opsrc2;
  wire [1:0]  _GEN_7 = io_in_2_valid ? io_in_2_bits_writeRf : io_in_3_bits_writeRf;
  wire [2:0]  _GEN_8 = io_in_2_valid ? io_in_2_bits_exEngine : io_in_3_bits_exEngine;
  wire [5:0]  _GEN_9 = io_in_2_valid ? io_in_2_bits_exOp : io_in_3_bits_exOp;
  wire [5:0]  _GEN_10 = io_in_2_valid ? io_in_2_bits_lsOp : io_in_3_bits_lsOp;
  wire        _GEN_11 = io_in_2_valid ? io_in_2_bits_exception : io_in_3_bits_exception;
  wire        _GEN_12 = io_in_2_valid ? io_in_2_bits_taken : io_in_3_bits_taken;
  wire [31:0] _GEN_13 = io_in_2_valid ? io_in_2_bits_imm : io_in_3_bits_imm;
  wire [4:0]  _GEN_14 = io_in_2_valid ? io_in_2_bits_rs1 : io_in_3_bits_rs1;
  wire [4:0]  _GEN_15 = io_in_2_valid ? io_in_2_bits_rs2 : io_in_3_bits_rs2;
  wire [4:0]  _GEN_16 = io_in_2_valid ? io_in_2_bits_rd : io_in_3_bits_rd;
  wire [31:0] _GEN_17 = io_in_2_valid ? io_in_2_bits_pc : io_in_3_bits_pc;
  wire [31:0] _GEN_18 = io_in_2_valid ? io_in_2_bits_targetPC : io_in_3_bits_targetPC;
  wire [6:0]  _GEN_19 = io_in_2_valid ? io_in_2_bits_rs1Tag : io_in_3_bits_rs1Tag;
  wire        _GEN_20 =
    io_in_2_valid ? io_in_2_bits_rs1TagReady : io_in_3_bits_rs1TagReady;
  wire [6:0]  _GEN_21 = io_in_2_valid ? io_in_2_bits_rs2Tag : io_in_3_bits_rs2Tag;
  wire        _GEN_22 =
    io_in_2_valid ? io_in_2_bits_rs2TagReady : io_in_3_bits_rs2TagReady;
  wire [31:0] _GEN_23 = io_in_2_valid ? io_in_2_bits_rs1Data : io_in_3_bits_rs1Data;
  wire [31:0] _GEN_24 = io_in_2_valid ? io_in_2_bits_rs2Data : io_in_3_bits_rs2Data;
  wire [31:0] _GEN_25 = io_in_2_valid ? io_in_2_bits_rdData : io_in_3_bits_rdData;
  wire        _GEN_26 =
    io_in_2_valid ? io_in_2_bits_operandReady : io_in_3_bits_operandReady;
  wire        _GEN_27 = io_in_2_valid ? io_in_2_bits_flushed : io_in_3_bits_flushed;
  wire [6:0]  _GEN_28 = io_in_2_valid ? io_in_2_bits_arfTag : io_in_3_bits_arfTag;
  wire        _GEN_29 = io_in_2_valid ? io_in_2_bits_arfValid : io_in_3_bits_arfValid;
  wire [31:0] _GEN_30 = io_in_2_valid ? io_in_2_bits_inst : io_in_3_bits_inst;
  wire [1:0]  _GEN_31 = io_in_1_valid ? 2'h1 : {1'h1, ~io_in_2_valid};
  wire        _GEN_32 = io_in_1_valid ? io_in_1_bits_retired : _GEN;
  wire [6:0]  _GEN_33 = io_in_1_valid ? io_in_1_bits_rdTag : _GEN_0;
  wire        _GEN_34 = io_in_1_valid ? io_in_1_bits_isBranch : _GEN_1;
  wire        _GEN_35 = io_in_1_valid ? io_in_1_bits_isJAL : _GEN_2;
  wire [1:0]  _GEN_36 = io_in_1_valid ? io_in_1_bits_lsType : _GEN_3;
  wire        _GEN_37 = io_in_1_valid ? io_in_1_bits_wakeup : _GEN_4;
  wire [1:0]  _GEN_38 = io_in_1_valid ? io_in_1_bits_opsrc1 : _GEN_5;
  wire [1:0]  _GEN_39 = io_in_1_valid ? io_in_1_bits_opsrc2 : _GEN_6;
  wire [1:0]  _GEN_40 = io_in_1_valid ? io_in_1_bits_writeRf : _GEN_7;
  wire [2:0]  _GEN_41 = io_in_1_valid ? io_in_1_bits_exEngine : _GEN_8;
  wire [5:0]  _GEN_42 = io_in_1_valid ? io_in_1_bits_exOp : _GEN_9;
  wire [5:0]  _GEN_43 = io_in_1_valid ? io_in_1_bits_lsOp : _GEN_10;
  wire        _GEN_44 = io_in_1_valid ? io_in_1_bits_exception : _GEN_11;
  wire        _GEN_45 = io_in_1_valid ? io_in_1_bits_taken : _GEN_12;
  wire [31:0] _GEN_46 = io_in_1_valid ? io_in_1_bits_imm : _GEN_13;
  wire [4:0]  _GEN_47 = io_in_1_valid ? io_in_1_bits_rs1 : _GEN_14;
  wire [4:0]  _GEN_48 = io_in_1_valid ? io_in_1_bits_rs2 : _GEN_15;
  wire [4:0]  _GEN_49 = io_in_1_valid ? io_in_1_bits_rd : _GEN_16;
  wire [31:0] _GEN_50 = io_in_1_valid ? io_in_1_bits_pc : _GEN_17;
  wire [31:0] _GEN_51 = io_in_1_valid ? io_in_1_bits_targetPC : _GEN_18;
  wire [6:0]  _GEN_52 = io_in_1_valid ? io_in_1_bits_rs1Tag : _GEN_19;
  wire        _GEN_53 = io_in_1_valid ? io_in_1_bits_rs1TagReady : _GEN_20;
  wire [6:0]  _GEN_54 = io_in_1_valid ? io_in_1_bits_rs2Tag : _GEN_21;
  wire        _GEN_55 = io_in_1_valid ? io_in_1_bits_rs2TagReady : _GEN_22;
  wire [31:0] _GEN_56 = io_in_1_valid ? io_in_1_bits_rs1Data : _GEN_23;
  wire [31:0] _GEN_57 = io_in_1_valid ? io_in_1_bits_rs2Data : _GEN_24;
  wire [31:0] _GEN_58 = io_in_1_valid ? io_in_1_bits_rdData : _GEN_25;
  wire        _GEN_59 = io_in_1_valid ? io_in_1_bits_operandReady : _GEN_26;
  wire        _GEN_60 = io_in_1_valid ? io_in_1_bits_flushed : _GEN_27;
  wire [6:0]  _GEN_61 = io_in_1_valid ? io_in_1_bits_arfTag : _GEN_28;
  wire        _GEN_62 = io_in_1_valid ? io_in_1_bits_arfValid : _GEN_29;
  wire [31:0] _GEN_63 = io_in_1_valid ? io_in_1_bits_inst : _GEN_30;
  assign io_out_valid = io_in_0_valid | io_in_1_valid | io_in_2_valid | io_in_3_valid;
  assign io_out_bits_retired = io_in_0_valid ? io_in_0_bits_retired : _GEN_32;
  assign io_out_bits_rdTag = io_in_0_valid ? io_in_0_bits_rdTag : _GEN_33;
  assign io_out_bits_isBranch = io_in_0_valid ? io_in_0_bits_isBranch : _GEN_34;
  assign io_out_bits_isJAL = io_in_0_valid ? io_in_0_bits_isJAL : _GEN_35;
  assign io_out_bits_lsType = io_in_0_valid ? io_in_0_bits_lsType : _GEN_36;
  assign io_out_bits_wakeup = io_in_0_valid ? io_in_0_bits_wakeup : _GEN_37;
  assign io_out_bits_opsrc1 = io_in_0_valid ? io_in_0_bits_opsrc1 : _GEN_38;
  assign io_out_bits_opsrc2 = io_in_0_valid ? io_in_0_bits_opsrc2 : _GEN_39;
  assign io_out_bits_writeRf = io_in_0_valid ? io_in_0_bits_writeRf : _GEN_40;
  assign io_out_bits_exEngine = io_in_0_valid ? io_in_0_bits_exEngine : _GEN_41;
  assign io_out_bits_exOp = io_in_0_valid ? io_in_0_bits_exOp : _GEN_42;
  assign io_out_bits_lsOp = io_in_0_valid ? io_in_0_bits_lsOp : _GEN_43;
  assign io_out_bits_exception = io_in_0_valid ? io_in_0_bits_exception : _GEN_44;
  assign io_out_bits_taken = io_in_0_valid ? io_in_0_bits_taken : _GEN_45;
  assign io_out_bits_imm = io_in_0_valid ? io_in_0_bits_imm : _GEN_46;
  assign io_out_bits_rs1 = io_in_0_valid ? io_in_0_bits_rs1 : _GEN_47;
  assign io_out_bits_rs2 = io_in_0_valid ? io_in_0_bits_rs2 : _GEN_48;
  assign io_out_bits_rd = io_in_0_valid ? io_in_0_bits_rd : _GEN_49;
  assign io_out_bits_pc = io_in_0_valid ? io_in_0_bits_pc : _GEN_50;
  assign io_out_bits_targetPC = io_in_0_valid ? io_in_0_bits_targetPC : _GEN_51;
  assign io_out_bits_rs1Tag = io_in_0_valid ? io_in_0_bits_rs1Tag : _GEN_52;
  assign io_out_bits_rs1TagReady = io_in_0_valid ? io_in_0_bits_rs1TagReady : _GEN_53;
  assign io_out_bits_rs2Tag = io_in_0_valid ? io_in_0_bits_rs2Tag : _GEN_54;
  assign io_out_bits_rs2TagReady = io_in_0_valid ? io_in_0_bits_rs2TagReady : _GEN_55;
  assign io_out_bits_rs1Data = io_in_0_valid ? io_in_0_bits_rs1Data : _GEN_56;
  assign io_out_bits_rs2Data = io_in_0_valid ? io_in_0_bits_rs2Data : _GEN_57;
  assign io_out_bits_rdData = io_in_0_valid ? io_in_0_bits_rdData : _GEN_58;
  assign io_out_bits_operandReady = io_in_0_valid ? io_in_0_bits_operandReady : _GEN_59;
  assign io_out_bits_flushed = io_in_0_valid ? io_in_0_bits_flushed : _GEN_60;
  assign io_out_bits_arfTag = io_in_0_valid ? io_in_0_bits_arfTag : _GEN_61;
  assign io_out_bits_arfValid = io_in_0_valid ? io_in_0_bits_arfValid : _GEN_62;
  assign io_out_bits_inst = io_in_0_valid ? io_in_0_bits_inst : _GEN_63;
  assign io_chosen = io_in_0_valid ? 2'h0 : _GEN_31;
endmodule

