// Generated by CIRCT firtool-1.76.0
module CSA3_2_6(
  input  wire [12:0] io_in_0,
  input  wire [12:0] io_in_1,
  input  wire [12:0] io_in_2,
  output wire [12:0] io_out_0,
  output wire [12:0] io_out_1
);

  wire a_xor_b = io_in_0[0] ^ io_in_1[0];
  wire a_xor_b_1 = io_in_0[1] ^ io_in_1[1];
  wire a_xor_b_2 = io_in_0[2] ^ io_in_1[2];
  wire a_xor_b_3 = io_in_0[3] ^ io_in_1[3];
  wire a_xor_b_4 = io_in_0[4] ^ io_in_1[4];
  wire a_xor_b_5 = io_in_0[5] ^ io_in_1[5];
  wire a_xor_b_6 = io_in_0[6] ^ io_in_1[6];
  wire a_xor_b_7 = io_in_0[7] ^ io_in_1[7];
  wire a_xor_b_8 = io_in_0[8] ^ io_in_1[8];
  wire a_xor_b_9 = io_in_0[9] ^ io_in_1[9];
  wire a_xor_b_10 = io_in_0[10] ^ io_in_1[10];
  wire a_xor_b_11 = io_in_0[11] ^ io_in_1[11];
  wire a_xor_b_12 = io_in_0[12] ^ io_in_1[12];
  assign io_out_0 =
    {a_xor_b_12 ^ io_in_2[12],
     a_xor_b_11 ^ io_in_2[11],
     a_xor_b_10 ^ io_in_2[10],
     a_xor_b_9 ^ io_in_2[9],
     a_xor_b_8 ^ io_in_2[8],
     a_xor_b_7 ^ io_in_2[7],
     a_xor_b_6 ^ io_in_2[6],
     a_xor_b_5 ^ io_in_2[5],
     a_xor_b_4 ^ io_in_2[4],
     a_xor_b_3 ^ io_in_2[3],
     a_xor_b_2 ^ io_in_2[2],
     a_xor_b_1 ^ io_in_2[1],
     a_xor_b ^ io_in_2[0]};
  assign io_out_1 =
    {io_in_0[12] & io_in_1[12] | a_xor_b_12 & io_in_2[12],
     io_in_0[11] & io_in_1[11] | a_xor_b_11 & io_in_2[11],
     io_in_0[10] & io_in_1[10] | a_xor_b_10 & io_in_2[10],
     io_in_0[9] & io_in_1[9] | a_xor_b_9 & io_in_2[9],
     io_in_0[8] & io_in_1[8] | a_xor_b_8 & io_in_2[8],
     io_in_0[7] & io_in_1[7] | a_xor_b_7 & io_in_2[7],
     io_in_0[6] & io_in_1[6] | a_xor_b_6 & io_in_2[6],
     io_in_0[5] & io_in_1[5] | a_xor_b_5 & io_in_2[5],
     io_in_0[4] & io_in_1[4] | a_xor_b_4 & io_in_2[4],
     io_in_0[3] & io_in_1[3] | a_xor_b_3 & io_in_2[3],
     io_in_0[2] & io_in_1[2] | a_xor_b_2 & io_in_2[2],
     io_in_0[1] & io_in_1[1] | a_xor_b_1 & io_in_2[1],
     io_in_0[0] & io_in_1[0] | a_xor_b & io_in_2[0]};
endmodule

