// Generated by CIRCT firtool-1.76.0
module CSR(
  input  wire clock,
  input  wire reset,
  output wire io_in_ready,
  input  wire io_in_valid,
  input  wire io_in_bits_flushed,
  input  wire io_flush
);

  CSRQueue csrq (
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (io_in_ready),
    .io_in_valid        (io_in_valid),
    .io_in_bits_flushed (io_in_bits_flushed),
    .io_flush           (io_flush)
  );
endmodule

