// Generated by CIRCT firtool-1.76.0
module CSRQueueRow(
  input  wire clock,
  input  wire reset,
  input  wire io_in_valid,
  input  wire io_in_bits_flushed,
  input  wire io_flush,
  output wire io_out_bits_flushed
);

  reg  row_flushed;
  wire _GEN = io_in_valid ? io_in_bits_flushed : row_flushed;
  always @(posedge clock) begin
    if (reset)
      row_flushed <= 1'h0;
    else
      row_flushed <= ~io_flush & _GEN;
  end // always @(posedge)
  assign io_out_bits_flushed = row_flushed;
endmodule

