// Generated by CIRCT firtool-1.76.0
module CSRQueue(
  input  wire clock,
  input  wire reset,
  output wire io_in_ready,
  input  wire io_in_valid,
  input  wire io_in_bits_flushed,
  input  wire io_flush
);

  wire       _demux_io_in_0_ready;
  wire       _demux_io_out_0_0_valid;
  wire       _demux_io_out_0_0_bits_flushed;
  wire       _demux_io_out_1_0_valid;
  wire       _demux_io_out_1_0_bits_flushed;
  wire       _demux_io_out_2_0_valid;
  wire       _demux_io_out_2_0_bits_flushed;
  wire       _demux_io_out_3_0_valid;
  wire       _demux_io_out_3_0_bits_flushed;
  wire       _demux_io_out_4_0_valid;
  wire       _demux_io_out_4_0_bits_flushed;
  wire       _demux_io_out_5_0_valid;
  wire       _demux_io_out_5_0_bits_flushed;
  wire       _demux_io_out_6_0_valid;
  wire       _demux_io_out_6_0_bits_flushed;
  wire       _demux_io_out_7_0_valid;
  wire       _demux_io_out_7_0_bits_flushed;
  wire       _rows_7_io_out_bits_flushed;
  wire       _rows_6_io_out_bits_flushed;
  wire       _rows_5_io_out_bits_flushed;
  wire       _rows_4_io_out_bits_flushed;
  wire       _rows_3_io_out_bits_flushed;
  wire       _rows_2_io_out_bits_flushed;
  wire       _rows_1_io_out_bits_flushed;
  wire       _rows_0_io_out_bits_flushed;
  reg        valid_0;
  reg        valid_1;
  reg        valid_2;
  reg        valid_3;
  reg        valid_4;
  reg        valid_5;
  reg        valid_6;
  reg        valid_7;
  reg  [2:0] enqPtr_value;
  reg  [2:0] deqPtr_value;
  reg        casez_tmp;
  always_comb begin
    casez (deqPtr_value)
      3'b000:
        casez_tmp = valid_0;
      3'b001:
        casez_tmp = valid_1;
      3'b010:
        casez_tmp = valid_2;
      3'b011:
        casez_tmp = valid_3;
      3'b100:
        casez_tmp = valid_4;
      3'b101:
        casez_tmp = valid_5;
      3'b110:
        casez_tmp = valid_6;
      default:
        casez_tmp = valid_7;
    endcase
  end // always_comb
  wire       full = enqPtr_value == deqPtr_value & casez_tmp;
  reg        casez_tmp_0;
  always_comb begin
    casez (deqPtr_value)
      3'b000:
        casez_tmp_0 = _rows_0_io_out_bits_flushed;
      3'b001:
        casez_tmp_0 = _rows_1_io_out_bits_flushed;
      3'b010:
        casez_tmp_0 = _rows_2_io_out_bits_flushed;
      3'b011:
        casez_tmp_0 = _rows_3_io_out_bits_flushed;
      3'b100:
        casez_tmp_0 = _rows_4_io_out_bits_flushed;
      3'b101:
        casez_tmp_0 = _rows_5_io_out_bits_flushed;
      3'b110:
        casez_tmp_0 = _rows_6_io_out_bits_flushed;
      default:
        casez_tmp_0 = _rows_7_io_out_bits_flushed;
    endcase
  end // always_comb
  reg        casez_tmp_1;
  always_comb begin
    casez (enqPtr_value)
      3'b000:
        casez_tmp_1 = valid_0;
      3'b001:
        casez_tmp_1 = valid_1;
      3'b010:
        casez_tmp_1 = valid_2;
      3'b011:
        casez_tmp_1 = valid_3;
      3'b100:
        casez_tmp_1 = valid_4;
      3'b101:
        casez_tmp_1 = valid_5;
      3'b110:
        casez_tmp_1 = valid_6;
      default:
        casez_tmp_1 = valid_7;
    endcase
  end // always_comb
  wire       _GEN = _demux_io_in_0_ready & io_in_valid & ~io_in_bits_flushed;
  wire       _GEN_0 = casez_tmp_0 & casez_tmp;
  always @(posedge clock) begin
    if (reset) begin
      valid_0 <= 1'h0;
      valid_1 <= 1'h0;
      valid_2 <= 1'h0;
      valid_3 <= 1'h0;
      valid_4 <= 1'h0;
      valid_5 <= 1'h0;
      valid_6 <= 1'h0;
      valid_7 <= 1'h0;
      enqPtr_value <= 3'h0;
      deqPtr_value <= 3'h0;
    end
    else begin
      valid_0 <= ~(_GEN_0 & deqPtr_value == 3'h0) & (_GEN & ~(|enqPtr_value) | valid_0);
      valid_1 <=
        ~(_GEN_0 & deqPtr_value == 3'h1) & (_GEN & enqPtr_value == 3'h1 | valid_1);
      valid_2 <=
        ~(_GEN_0 & deqPtr_value == 3'h2) & (_GEN & enqPtr_value == 3'h2 | valid_2);
      valid_3 <=
        ~(_GEN_0 & deqPtr_value == 3'h3) & (_GEN & enqPtr_value == 3'h3 | valid_3);
      valid_4 <=
        ~(_GEN_0 & deqPtr_value == 3'h4) & (_GEN & enqPtr_value == 3'h4 | valid_4);
      valid_5 <=
        ~(_GEN_0 & deqPtr_value == 3'h5) & (_GEN & enqPtr_value == 3'h5 | valid_5);
      valid_6 <=
        ~(_GEN_0 & deqPtr_value == 3'h6) & (_GEN & enqPtr_value == 3'h6 | valid_6);
      valid_7 <= ~(_GEN_0 & (&deqPtr_value)) & (_GEN & (&enqPtr_value) | valid_7);
      if (_GEN)
        enqPtr_value <= enqPtr_value + 3'h1;
      if (_GEN_0)
        deqPtr_value <= deqPtr_value + 3'h1;
    end
  end // always @(posedge)
  CSRQueueRow rows_0 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_0_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_0_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_0_io_out_bits_flushed)
  );
  CSRQueueRow rows_1 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_1_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_1_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_1_io_out_bits_flushed)
  );
  CSRQueueRow rows_2 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_2_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_2_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_2_io_out_bits_flushed)
  );
  CSRQueueRow rows_3 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_3_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_3_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_3_io_out_bits_flushed)
  );
  CSRQueueRow rows_4 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_4_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_4_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_4_io_out_bits_flushed)
  );
  CSRQueueRow rows_5 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_5_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_5_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_5_io_out_bits_flushed)
  );
  CSRQueueRow rows_6 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_6_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_6_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_6_io_out_bits_flushed)
  );
  CSRQueueRow rows_7 (
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (_demux_io_out_7_0_valid & ~io_in_bits_flushed & ~full),
    .io_in_bits_flushed  (_demux_io_out_7_0_bits_flushed),
    .io_flush            (io_flush),
    .io_out_bits_flushed (_rows_7_io_out_bits_flushed)
  );
  DCDemux_8 demux (
    .io_sel_0                (enqPtr_value),
    .io_in_0_ready           (_demux_io_in_0_ready),
    .io_in_0_valid           (io_in_valid),
    .io_in_0_bits_flushed    (io_in_bits_flushed),
    .io_out_0_0_ready        (~(|enqPtr_value) & ~full & ~casez_tmp_1),
    .io_out_0_0_valid        (_demux_io_out_0_0_valid),
    .io_out_0_0_bits_flushed (_demux_io_out_0_0_bits_flushed),
    .io_out_1_0_ready        (enqPtr_value == 3'h1 & ~full & ~casez_tmp_1),
    .io_out_1_0_valid        (_demux_io_out_1_0_valid),
    .io_out_1_0_bits_flushed (_demux_io_out_1_0_bits_flushed),
    .io_out_2_0_ready        (enqPtr_value == 3'h2 & ~full & ~casez_tmp_1),
    .io_out_2_0_valid        (_demux_io_out_2_0_valid),
    .io_out_2_0_bits_flushed (_demux_io_out_2_0_bits_flushed),
    .io_out_3_0_ready        (enqPtr_value == 3'h3 & ~full & ~casez_tmp_1),
    .io_out_3_0_valid        (_demux_io_out_3_0_valid),
    .io_out_3_0_bits_flushed (_demux_io_out_3_0_bits_flushed),
    .io_out_4_0_ready        (enqPtr_value == 3'h4 & ~full & ~casez_tmp_1),
    .io_out_4_0_valid        (_demux_io_out_4_0_valid),
    .io_out_4_0_bits_flushed (_demux_io_out_4_0_bits_flushed),
    .io_out_5_0_ready        (enqPtr_value == 3'h5 & ~full & ~casez_tmp_1),
    .io_out_5_0_valid        (_demux_io_out_5_0_valid),
    .io_out_5_0_bits_flushed (_demux_io_out_5_0_bits_flushed),
    .io_out_6_0_ready        (enqPtr_value == 3'h6 & ~full & ~casez_tmp_1),
    .io_out_6_0_valid        (_demux_io_out_6_0_valid),
    .io_out_6_0_bits_flushed (_demux_io_out_6_0_bits_flushed),
    .io_out_7_0_ready        ((&enqPtr_value) & ~full & ~casez_tmp_1),
    .io_out_7_0_valid        (_demux_io_out_7_0_valid),
    .io_out_7_0_bits_flushed (_demux_io_out_7_0_bits_flushed)
  );
  assign io_in_ready = _demux_io_in_0_ready;
endmodule

