// Generated by CIRCT firtool-1.76.0
module DCLeftShifter_3(
  output wire        io_in_0_ready,
  input  wire        io_in_0_valid,
  input  wire        io_in_0_bits_retired,
  input  wire [6:0]  io_in_0_bits_rdTag,
  input  wire        io_in_0_bits_isBranch,
  input  wire        io_in_0_bits_isJAL,
  input  wire [1:0]  io_in_0_bits_lsType,
  input  wire        io_in_0_bits_wakeup,
  input  wire [1:0]  io_in_0_bits_opsrc1,
  input  wire [1:0]  io_in_0_bits_opsrc2,
  input  wire [1:0]  io_in_0_bits_writeRf,
  input  wire [2:0]  io_in_0_bits_exEngine,
  input  wire [5:0]  io_in_0_bits_exOp,
  input  wire [5:0]  io_in_0_bits_lsOp,
  input  wire        io_in_0_bits_exception,
  input  wire        io_in_0_bits_taken,
  input  wire [31:0] io_in_0_bits_imm,
  input  wire [4:0]  io_in_0_bits_rs1,
  input  wire [4:0]  io_in_0_bits_rs2,
  input  wire [4:0]  io_in_0_bits_rd,
  input  wire [31:0] io_in_0_bits_pc,
  input  wire [31:0] io_in_0_bits_targetPC,
  input  wire        io_in_0_bits_rs1TagReady,
  input  wire        io_in_0_bits_rs2TagReady,
  input  wire [31:0] io_in_0_bits_rs1Data,
  input  wire [31:0] io_in_0_bits_rs2Data,
  input  wire [31:0] io_in_0_bits_rdData,
  input  wire        io_in_0_bits_operandReady,
  input  wire        io_in_0_bits_flushed,
  input  wire [6:0]  io_in_0_bits_arfTag,
  input  wire        io_in_0_bits_arfValid,
  input  wire [31:0] io_in_0_bits_inst,
  output wire        io_in_1_ready,
  input  wire        io_in_1_valid,
  input  wire        io_in_1_bits_retired,
  input  wire [6:0]  io_in_1_bits_rdTag,
  input  wire        io_in_1_bits_isBranch,
  input  wire        io_in_1_bits_isJAL,
  input  wire [1:0]  io_in_1_bits_lsType,
  input  wire        io_in_1_bits_wakeup,
  input  wire [1:0]  io_in_1_bits_opsrc1,
  input  wire [1:0]  io_in_1_bits_opsrc2,
  input  wire [1:0]  io_in_1_bits_writeRf,
  input  wire [2:0]  io_in_1_bits_exEngine,
  input  wire [5:0]  io_in_1_bits_exOp,
  input  wire [5:0]  io_in_1_bits_lsOp,
  input  wire        io_in_1_bits_exception,
  input  wire        io_in_1_bits_taken,
  input  wire [31:0] io_in_1_bits_imm,
  input  wire [4:0]  io_in_1_bits_rs1,
  input  wire [4:0]  io_in_1_bits_rs2,
  input  wire [4:0]  io_in_1_bits_rd,
  input  wire [31:0] io_in_1_bits_pc,
  input  wire [31:0] io_in_1_bits_targetPC,
  input  wire        io_in_1_bits_rs1TagReady,
  input  wire        io_in_1_bits_rs2TagReady,
  input  wire [31:0] io_in_1_bits_rs1Data,
  input  wire [31:0] io_in_1_bits_rs2Data,
  input  wire [31:0] io_in_1_bits_rdData,
  input  wire        io_in_1_bits_operandReady,
  input  wire        io_in_1_bits_flushed,
  input  wire [6:0]  io_in_1_bits_arfTag,
  input  wire        io_in_1_bits_arfValid,
  input  wire [31:0] io_in_1_bits_inst,
  input  wire        io_shamt,
  input  wire        io_out_0_ready,
  output wire        io_out_0_valid,
  output wire        io_out_0_bits_retired,
  output wire [6:0]  io_out_0_bits_rdTag,
  output wire        io_out_0_bits_isBranch,
  output wire        io_out_0_bits_isJAL,
  output wire [1:0]  io_out_0_bits_lsType,
  output wire        io_out_0_bits_wakeup,
  output wire [1:0]  io_out_0_bits_opsrc1,
  output wire [1:0]  io_out_0_bits_opsrc2,
  output wire [1:0]  io_out_0_bits_writeRf,
  output wire [2:0]  io_out_0_bits_exEngine,
  output wire [5:0]  io_out_0_bits_exOp,
  output wire [5:0]  io_out_0_bits_lsOp,
  output wire        io_out_0_bits_exception,
  output wire        io_out_0_bits_taken,
  output wire [31:0] io_out_0_bits_imm,
  output wire [4:0]  io_out_0_bits_rs1,
  output wire [4:0]  io_out_0_bits_rs2,
  output wire [4:0]  io_out_0_bits_rd,
  output wire [31:0] io_out_0_bits_pc,
  output wire [31:0] io_out_0_bits_targetPC,
  output wire        io_out_0_bits_rs1TagReady,
  output wire        io_out_0_bits_rs2TagReady,
  output wire [31:0] io_out_0_bits_rs1Data,
  output wire [31:0] io_out_0_bits_rs2Data,
  output wire [31:0] io_out_0_bits_rdData,
  output wire        io_out_0_bits_operandReady,
  output wire        io_out_0_bits_flushed,
  output wire [6:0]  io_out_0_bits_arfTag,
  output wire        io_out_0_bits_arfValid,
  output wire [31:0] io_out_0_bits_inst,
  input  wire        io_out_1_ready,
  output wire        io_out_1_valid,
  output wire        io_out_1_bits_retired,
  output wire [6:0]  io_out_1_bits_rdTag,
  output wire        io_out_1_bits_isBranch,
  output wire        io_out_1_bits_isJAL,
  output wire [1:0]  io_out_1_bits_lsType,
  output wire        io_out_1_bits_wakeup,
  output wire [1:0]  io_out_1_bits_opsrc1,
  output wire [1:0]  io_out_1_bits_opsrc2,
  output wire [1:0]  io_out_1_bits_writeRf,
  output wire [2:0]  io_out_1_bits_exEngine,
  output wire [5:0]  io_out_1_bits_exOp,
  output wire [5:0]  io_out_1_bits_lsOp,
  output wire        io_out_1_bits_exception,
  output wire        io_out_1_bits_taken,
  output wire [31:0] io_out_1_bits_imm,
  output wire [4:0]  io_out_1_bits_rs1,
  output wire [4:0]  io_out_1_bits_rs2,
  output wire [4:0]  io_out_1_bits_rd,
  output wire [31:0] io_out_1_bits_pc,
  output wire [31:0] io_out_1_bits_targetPC,
  output wire        io_out_1_bits_rs1TagReady,
  output wire        io_out_1_bits_rs2TagReady,
  output wire [31:0] io_out_1_bits_rs1Data,
  output wire [31:0] io_out_1_bits_rs2Data,
  output wire [31:0] io_out_1_bits_rdData,
  output wire        io_out_1_bits_operandReady,
  output wire        io_out_1_bits_flushed,
  output wire [6:0]  io_out_1_bits_arfTag,
  output wire        io_out_1_bits_arfValid,
  output wire [31:0] io_out_1_bits_inst
);

  wire [31:0] _GEN = io_shamt ? 32'h0 : io_in_0_bits_inst;
  wire [31:0] _GEN_0 = io_shamt ? io_in_1_bits_inst : 32'h0;
  wire [6:0]  _GEN_1 = io_shamt ? 7'h0 : io_in_0_bits_arfTag;
  wire [6:0]  _GEN_2 = io_shamt ? io_in_1_bits_arfTag : 7'h0;
  wire [31:0] _GEN_3 = io_shamt ? 32'h0 : io_in_0_bits_rdData;
  wire [31:0] _GEN_4 = io_shamt ? io_in_1_bits_rdData : 32'h0;
  wire [31:0] _GEN_5 = io_shamt ? 32'h0 : io_in_0_bits_rs2Data;
  wire [31:0] _GEN_6 = io_shamt ? io_in_1_bits_rs2Data : 32'h0;
  wire [31:0] _GEN_7 = io_shamt ? 32'h0 : io_in_0_bits_rs1Data;
  wire [31:0] _GEN_8 = io_shamt ? io_in_1_bits_rs1Data : 32'h0;
  wire [31:0] _GEN_9 = io_shamt ? 32'h0 : io_in_0_bits_targetPC;
  wire [31:0] _GEN_10 = io_shamt ? io_in_1_bits_targetPC : 32'h0;
  wire [31:0] _GEN_11 = io_shamt ? 32'h0 : io_in_0_bits_pc;
  wire [31:0] _GEN_12 = io_shamt ? io_in_1_bits_pc : 32'h0;
  wire [4:0]  _GEN_13 = io_shamt ? 5'h0 : io_in_0_bits_rd;
  wire [4:0]  _GEN_14 = io_shamt ? io_in_1_bits_rd : 5'h0;
  wire [4:0]  _GEN_15 = io_shamt ? 5'h0 : io_in_0_bits_rs2;
  wire [4:0]  _GEN_16 = io_shamt ? io_in_1_bits_rs2 : 5'h0;
  wire [4:0]  _GEN_17 = io_shamt ? 5'h0 : io_in_0_bits_rs1;
  wire [4:0]  _GEN_18 = io_shamt ? io_in_1_bits_rs1 : 5'h0;
  wire [31:0] _GEN_19 = io_shamt ? 32'h0 : io_in_0_bits_imm;
  wire [31:0] _GEN_20 = io_shamt ? io_in_1_bits_imm : 32'h0;
  wire [5:0]  _GEN_21 = io_shamt ? 6'h0 : io_in_0_bits_lsOp;
  wire [5:0]  _GEN_22 = io_shamt ? io_in_1_bits_lsOp : 6'h0;
  wire [5:0]  _GEN_23 = io_shamt ? 6'h0 : io_in_0_bits_exOp;
  wire [5:0]  _GEN_24 = io_shamt ? io_in_1_bits_exOp : 6'h0;
  wire [2:0]  _GEN_25 = io_shamt ? 3'h0 : io_in_0_bits_exEngine;
  wire [2:0]  _GEN_26 = io_shamt ? io_in_1_bits_exEngine : 3'h0;
  wire [1:0]  _GEN_27 = io_shamt ? 2'h0 : io_in_0_bits_writeRf;
  wire [1:0]  _GEN_28 = io_shamt ? io_in_1_bits_writeRf : 2'h0;
  wire [1:0]  _GEN_29 = io_shamt ? 2'h0 : io_in_0_bits_opsrc2;
  wire [1:0]  _GEN_30 = io_shamt ? io_in_1_bits_opsrc2 : 2'h0;
  wire [1:0]  _GEN_31 = io_shamt ? 2'h0 : io_in_0_bits_opsrc1;
  wire [1:0]  _GEN_32 = io_shamt ? io_in_1_bits_opsrc1 : 2'h0;
  wire [1:0]  _GEN_33 = io_shamt ? 2'h0 : io_in_0_bits_lsType;
  wire [1:0]  _GEN_34 = io_shamt ? io_in_1_bits_lsType : 2'h0;
  wire [6:0]  _GEN_35 = io_shamt ? 7'h0 : io_in_0_bits_rdTag;
  wire [6:0]  _GEN_36 = io_shamt ? io_in_1_bits_rdTag : 7'h0;
  wire [31:0] _GEN_37 = io_shamt ? 32'h0 : io_in_1_bits_inst;
  wire [31:0] _GEN_38 = io_shamt ? io_in_0_bits_inst : 32'h0;
  wire [6:0]  _GEN_39 = io_shamt ? 7'h0 : io_in_1_bits_arfTag;
  wire [6:0]  _GEN_40 = io_shamt ? io_in_0_bits_arfTag : 7'h0;
  wire [31:0] _GEN_41 = io_shamt ? 32'h0 : io_in_1_bits_rdData;
  wire [31:0] _GEN_42 = io_shamt ? io_in_0_bits_rdData : 32'h0;
  wire [31:0] _GEN_43 = io_shamt ? 32'h0 : io_in_1_bits_rs2Data;
  wire [31:0] _GEN_44 = io_shamt ? io_in_0_bits_rs2Data : 32'h0;
  wire [31:0] _GEN_45 = io_shamt ? 32'h0 : io_in_1_bits_rs1Data;
  wire [31:0] _GEN_46 = io_shamt ? io_in_0_bits_rs1Data : 32'h0;
  wire [31:0] _GEN_47 = io_shamt ? 32'h0 : io_in_1_bits_targetPC;
  wire [31:0] _GEN_48 = io_shamt ? io_in_0_bits_targetPC : 32'h0;
  wire [31:0] _GEN_49 = io_shamt ? 32'h0 : io_in_1_bits_pc;
  wire [31:0] _GEN_50 = io_shamt ? io_in_0_bits_pc : 32'h0;
  wire [4:0]  _GEN_51 = io_shamt ? 5'h0 : io_in_1_bits_rd;
  wire [4:0]  _GEN_52 = io_shamt ? io_in_0_bits_rd : 5'h0;
  wire [4:0]  _GEN_53 = io_shamt ? 5'h0 : io_in_1_bits_rs2;
  wire [4:0]  _GEN_54 = io_shamt ? io_in_0_bits_rs2 : 5'h0;
  wire [4:0]  _GEN_55 = io_shamt ? 5'h0 : io_in_1_bits_rs1;
  wire [4:0]  _GEN_56 = io_shamt ? io_in_0_bits_rs1 : 5'h0;
  wire [31:0] _GEN_57 = io_shamt ? 32'h0 : io_in_1_bits_imm;
  wire [31:0] _GEN_58 = io_shamt ? io_in_0_bits_imm : 32'h0;
  wire [5:0]  _GEN_59 = io_shamt ? 6'h0 : io_in_1_bits_lsOp;
  wire [5:0]  _GEN_60 = io_shamt ? io_in_0_bits_lsOp : 6'h0;
  wire [5:0]  _GEN_61 = io_shamt ? 6'h0 : io_in_1_bits_exOp;
  wire [5:0]  _GEN_62 = io_shamt ? io_in_0_bits_exOp : 6'h0;
  wire [2:0]  _GEN_63 = io_shamt ? 3'h0 : io_in_1_bits_exEngine;
  wire [2:0]  _GEN_64 = io_shamt ? io_in_0_bits_exEngine : 3'h0;
  wire [1:0]  _GEN_65 = io_shamt ? 2'h0 : io_in_1_bits_writeRf;
  wire [1:0]  _GEN_66 = io_shamt ? io_in_0_bits_writeRf : 2'h0;
  wire [1:0]  _GEN_67 = io_shamt ? 2'h0 : io_in_1_bits_opsrc2;
  wire [1:0]  _GEN_68 = io_shamt ? io_in_0_bits_opsrc2 : 2'h0;
  wire [1:0]  _GEN_69 = io_shamt ? 2'h0 : io_in_1_bits_opsrc1;
  wire [1:0]  _GEN_70 = io_shamt ? io_in_0_bits_opsrc1 : 2'h0;
  wire [1:0]  _GEN_71 = io_shamt ? 2'h0 : io_in_1_bits_lsType;
  wire [1:0]  _GEN_72 = io_shamt ? io_in_0_bits_lsType : 2'h0;
  wire [6:0]  _GEN_73 = io_shamt ? 7'h0 : io_in_1_bits_rdTag;
  wire [6:0]  _GEN_74 = io_shamt ? io_in_0_bits_rdTag : 7'h0;
  assign io_in_0_ready = ~io_shamt & io_out_0_ready | io_shamt & io_out_1_ready;
  assign io_in_1_ready = ~io_shamt & io_out_1_ready | io_shamt & io_out_0_ready;
  assign io_out_0_valid = ~io_shamt & io_in_0_valid | io_shamt & io_in_1_valid;
  assign io_out_0_bits_retired =
    ~io_shamt & io_in_0_bits_retired | io_shamt & io_in_1_bits_retired;
  assign io_out_0_bits_rdTag = _GEN_35 | _GEN_36;
  assign io_out_0_bits_isBranch =
    ~io_shamt & io_in_0_bits_isBranch | io_shamt & io_in_1_bits_isBranch;
  assign io_out_0_bits_isJAL =
    ~io_shamt & io_in_0_bits_isJAL | io_shamt & io_in_1_bits_isJAL;
  assign io_out_0_bits_lsType = _GEN_33 | _GEN_34;
  assign io_out_0_bits_wakeup =
    ~io_shamt & io_in_0_bits_wakeup | io_shamt & io_in_1_bits_wakeup;
  assign io_out_0_bits_opsrc1 = _GEN_31 | _GEN_32;
  assign io_out_0_bits_opsrc2 = _GEN_29 | _GEN_30;
  assign io_out_0_bits_writeRf = _GEN_27 | _GEN_28;
  assign io_out_0_bits_exEngine = _GEN_25 | _GEN_26;
  assign io_out_0_bits_exOp = _GEN_23 | _GEN_24;
  assign io_out_0_bits_lsOp = _GEN_21 | _GEN_22;
  assign io_out_0_bits_exception =
    ~io_shamt & io_in_0_bits_exception | io_shamt & io_in_1_bits_exception;
  assign io_out_0_bits_taken =
    ~io_shamt & io_in_0_bits_taken | io_shamt & io_in_1_bits_taken;
  assign io_out_0_bits_imm = _GEN_19 | _GEN_20;
  assign io_out_0_bits_rs1 = _GEN_17 | _GEN_18;
  assign io_out_0_bits_rs2 = _GEN_15 | _GEN_16;
  assign io_out_0_bits_rd = _GEN_13 | _GEN_14;
  assign io_out_0_bits_pc = _GEN_11 | _GEN_12;
  assign io_out_0_bits_targetPC = _GEN_9 | _GEN_10;
  assign io_out_0_bits_rs1TagReady =
    ~io_shamt & io_in_0_bits_rs1TagReady | io_shamt & io_in_1_bits_rs1TagReady;
  assign io_out_0_bits_rs2TagReady =
    ~io_shamt & io_in_0_bits_rs2TagReady | io_shamt & io_in_1_bits_rs2TagReady;
  assign io_out_0_bits_rs1Data = _GEN_7 | _GEN_8;
  assign io_out_0_bits_rs2Data = _GEN_5 | _GEN_6;
  assign io_out_0_bits_rdData = _GEN_3 | _GEN_4;
  assign io_out_0_bits_operandReady =
    ~io_shamt & io_in_0_bits_operandReady | io_shamt & io_in_1_bits_operandReady;
  assign io_out_0_bits_flushed =
    ~io_shamt & io_in_0_bits_flushed | io_shamt & io_in_1_bits_flushed;
  assign io_out_0_bits_arfTag = _GEN_1 | _GEN_2;
  assign io_out_0_bits_arfValid =
    ~io_shamt & io_in_0_bits_arfValid | io_shamt & io_in_1_bits_arfValid;
  assign io_out_0_bits_inst = _GEN | _GEN_0;
  assign io_out_1_valid = ~io_shamt & io_in_1_valid | io_shamt & io_in_0_valid;
  assign io_out_1_bits_retired =
    ~io_shamt & io_in_1_bits_retired | io_shamt & io_in_0_bits_retired;
  assign io_out_1_bits_rdTag = _GEN_73 | _GEN_74;
  assign io_out_1_bits_isBranch =
    ~io_shamt & io_in_1_bits_isBranch | io_shamt & io_in_0_bits_isBranch;
  assign io_out_1_bits_isJAL =
    ~io_shamt & io_in_1_bits_isJAL | io_shamt & io_in_0_bits_isJAL;
  assign io_out_1_bits_lsType = _GEN_71 | _GEN_72;
  assign io_out_1_bits_wakeup =
    ~io_shamt & io_in_1_bits_wakeup | io_shamt & io_in_0_bits_wakeup;
  assign io_out_1_bits_opsrc1 = _GEN_69 | _GEN_70;
  assign io_out_1_bits_opsrc2 = _GEN_67 | _GEN_68;
  assign io_out_1_bits_writeRf = _GEN_65 | _GEN_66;
  assign io_out_1_bits_exEngine = _GEN_63 | _GEN_64;
  assign io_out_1_bits_exOp = _GEN_61 | _GEN_62;
  assign io_out_1_bits_lsOp = _GEN_59 | _GEN_60;
  assign io_out_1_bits_exception =
    ~io_shamt & io_in_1_bits_exception | io_shamt & io_in_0_bits_exception;
  assign io_out_1_bits_taken =
    ~io_shamt & io_in_1_bits_taken | io_shamt & io_in_0_bits_taken;
  assign io_out_1_bits_imm = _GEN_57 | _GEN_58;
  assign io_out_1_bits_rs1 = _GEN_55 | _GEN_56;
  assign io_out_1_bits_rs2 = _GEN_53 | _GEN_54;
  assign io_out_1_bits_rd = _GEN_51 | _GEN_52;
  assign io_out_1_bits_pc = _GEN_49 | _GEN_50;
  assign io_out_1_bits_targetPC = _GEN_47 | _GEN_48;
  assign io_out_1_bits_rs1TagReady =
    ~io_shamt & io_in_1_bits_rs1TagReady | io_shamt & io_in_0_bits_rs1TagReady;
  assign io_out_1_bits_rs2TagReady =
    ~io_shamt & io_in_1_bits_rs2TagReady | io_shamt & io_in_0_bits_rs2TagReady;
  assign io_out_1_bits_rs1Data = _GEN_45 | _GEN_46;
  assign io_out_1_bits_rs2Data = _GEN_43 | _GEN_44;
  assign io_out_1_bits_rdData = _GEN_41 | _GEN_42;
  assign io_out_1_bits_operandReady =
    ~io_shamt & io_in_1_bits_operandReady | io_shamt & io_in_0_bits_operandReady;
  assign io_out_1_bits_flushed =
    ~io_shamt & io_in_1_bits_flushed | io_shamt & io_in_0_bits_flushed;
  assign io_out_1_bits_arfTag = _GEN_39 | _GEN_40;
  assign io_out_1_bits_arfValid =
    ~io_shamt & io_in_1_bits_arfValid | io_shamt & io_in_0_bits_arfValid;
  assign io_out_1_bits_inst = _GEN_37 | _GEN_38;
endmodule

