// Generated by CIRCT firtool-1.76.0
module DCPipelineRegister(
  input  wire        clock,
  input  wire        reset,
  output wire        io_in_ready,
  input  wire        io_in_valid,
  input  wire        io_in_bits_isBranch,
  input  wire        io_in_bits_isJAL,
  input  wire [1:0]  io_in_bits_lsType,
  input  wire [1:0]  io_in_bits_writeRf,
  input  wire [4:0]  io_in_bits_rd,
  input  wire [31:0] io_in_bits_pc,
  input  wire [6:0]  io_in_bits_rdTag,
  input  wire        io_in_bits_flushed,
  input  wire [6:0]  io_in_bits_arfTag,
  input  wire        io_in_bits_arfValid,
  input  wire [31:0] io_in_bits_inst,
  input  wire        io_valids_0,
  input  wire        io_out_ready,
  output wire        io_out_valid,
  output wire        io_out_bits_isBranch,
  output wire        io_out_bits_isJAL,
  output wire [1:0]  io_out_bits_lsType,
  output wire [1:0]  io_out_bits_writeRf,
  output wire [4:0]  io_out_bits_rd,
  output wire [31:0] io_out_bits_pc,
  output wire [6:0]  io_out_bits_rdTag,
  output wire        io_out_bits_flushed,
  output wire [6:0]  io_out_bits_arfTag,
  output wire        io_out_bits_arfValid,
  output wire [31:0] io_out_bits_inst
);

  reg        regData_isBranch;
  reg        regData_isJAL;
  reg [1:0]  regData_lsType;
  reg [1:0]  regData_writeRf;
  reg [4:0]  regData_rd;
  reg [31:0] regData_pc;
  reg [6:0]  regData_rdTag;
  reg        regData_flushed;
  reg [6:0]  regData_arfTag;
  reg        regData_arfValid;
  reg [31:0] regData_inst;
  reg        regValid;
  always @(posedge clock) begin
    if (reset) begin
      regData_isBranch <= 1'h0;
      regData_isJAL <= 1'h0;
      regData_lsType <= 2'h0;
      regData_writeRf <= 2'h0;
      regData_rd <= 5'h0;
      regData_pc <= 32'h0;
      regData_rdTag <= 7'h0;
      regData_flushed <= 1'h0;
      regData_arfTag <= 7'h0;
      regData_arfValid <= 1'h0;
      regData_inst <= 32'h0;
      regValid <= 1'h0;
    end
    else if (io_out_ready) begin
      regData_isBranch <= io_in_bits_isBranch;
      regData_isJAL <= io_in_bits_isJAL;
      regData_lsType <= io_in_bits_lsType;
      regData_writeRf <= io_in_bits_writeRf;
      regData_rd <= io_in_bits_rd;
      regData_pc <= io_in_bits_pc;
      regData_rdTag <= io_in_bits_rdTag;
      regData_flushed <= io_in_bits_flushed;
      regData_arfTag <= io_in_bits_arfTag;
      regData_arfValid <= io_in_bits_arfValid;
      regData_inst <= io_in_bits_inst;
      regValid <= io_in_valid;
    end
  end // always @(posedge)
  assign io_in_ready = ~io_valids_0 | io_in_valid & io_out_ready & io_valids_0;
  assign io_out_valid = regValid;
  assign io_out_bits_isBranch = regData_isBranch;
  assign io_out_bits_isJAL = regData_isJAL;
  assign io_out_bits_lsType = regData_lsType;
  assign io_out_bits_writeRf = regData_writeRf;
  assign io_out_bits_rd = regData_rd;
  assign io_out_bits_pc = regData_pc;
  assign io_out_bits_rdTag = regData_rdTag;
  assign io_out_bits_flushed = regData_flushed;
  assign io_out_bits_arfTag = regData_arfTag;
  assign io_out_bits_arfValid = regData_arfValid;
  assign io_out_bits_inst = regData_inst;
endmodule

