// Generated by CIRCT firtool-1.76.0
module DCQueueWriter(
  input  wire       clock,
  input  wire       reset,
  input  wire       io_out_0_ready,
  output wire       io_out_0_valid,
  output wire [6:0] io_out_0_bits_tag,
  input  wire       io_out_1_ready,
  output wire       io_out_1_valid,
  output wire [6:0] io_out_1_bits_tag,
  output wire       io_done
);

  reg [6:0] counter;
  reg       initialized;
  always @(posedge clock) begin
    if (reset) begin
      counter <= 7'h1;
      initialized <= 1'h0;
    end
    else begin
      if (~initialized & (&{io_out_1_ready, io_out_0_ready}))
        counter <= counter + 7'h2;
      initialized <= counter > 7'h4F & ~initialized | initialized;
    end
  end // always @(posedge)
  assign io_out_0_valid = ~initialized;
  assign io_out_0_bits_tag = counter;
  assign io_out_1_valid = ~initialized;
  assign io_out_1_bits_tag = counter + 7'h1;
  assign io_done = initialized;
endmodule

