// Generated by CIRCT firtool-1.76.0
module DCRightShifter(
  input  wire       io_in_0_valid,
  input  wire [7:0] io_in_0_bits_cacheData_0,
  input  wire [7:0] io_in_0_bits_cacheData_1,
  input  wire [7:0] io_in_0_bits_cacheData_2,
  input  wire [7:0] io_in_0_bits_cacheData_3,
  input  wire       io_in_0_bits_sqwStrobe_0,
  input  wire       io_in_0_bits_sqwStrobe_1,
  input  wire       io_in_0_bits_sqwStrobe_2,
  input  wire       io_in_0_bits_sqwStrobe_3,
  input  wire       io_in_1_valid,
  input  wire [7:0] io_in_1_bits_cacheData_0,
  input  wire [7:0] io_in_1_bits_cacheData_1,
  input  wire [7:0] io_in_1_bits_cacheData_2,
  input  wire [7:0] io_in_1_bits_cacheData_3,
  input  wire       io_in_1_bits_sqwStrobe_0,
  input  wire       io_in_1_bits_sqwStrobe_1,
  input  wire       io_in_1_bits_sqwStrobe_2,
  input  wire       io_in_1_bits_sqwStrobe_3,
  input  wire       io_in_2_valid,
  input  wire [7:0] io_in_2_bits_cacheData_0,
  input  wire [7:0] io_in_2_bits_cacheData_1,
  input  wire [7:0] io_in_2_bits_cacheData_2,
  input  wire [7:0] io_in_2_bits_cacheData_3,
  input  wire       io_in_2_bits_sqwStrobe_0,
  input  wire       io_in_2_bits_sqwStrobe_1,
  input  wire       io_in_2_bits_sqwStrobe_2,
  input  wire       io_in_2_bits_sqwStrobe_3,
  input  wire       io_in_3_valid,
  input  wire [7:0] io_in_3_bits_cacheData_0,
  input  wire [7:0] io_in_3_bits_cacheData_1,
  input  wire [7:0] io_in_3_bits_cacheData_2,
  input  wire [7:0] io_in_3_bits_cacheData_3,
  input  wire       io_in_3_bits_sqwStrobe_0,
  input  wire       io_in_3_bits_sqwStrobe_1,
  input  wire       io_in_3_bits_sqwStrobe_2,
  input  wire       io_in_3_bits_sqwStrobe_3,
  input  wire       io_in_4_valid,
  input  wire [7:0] io_in_4_bits_cacheData_0,
  input  wire [7:0] io_in_4_bits_cacheData_1,
  input  wire [7:0] io_in_4_bits_cacheData_2,
  input  wire [7:0] io_in_4_bits_cacheData_3,
  input  wire       io_in_4_bits_sqwStrobe_0,
  input  wire       io_in_4_bits_sqwStrobe_1,
  input  wire       io_in_4_bits_sqwStrobe_2,
  input  wire       io_in_4_bits_sqwStrobe_3,
  input  wire       io_in_5_valid,
  input  wire [7:0] io_in_5_bits_cacheData_0,
  input  wire [7:0] io_in_5_bits_cacheData_1,
  input  wire [7:0] io_in_5_bits_cacheData_2,
  input  wire [7:0] io_in_5_bits_cacheData_3,
  input  wire       io_in_5_bits_sqwStrobe_0,
  input  wire       io_in_5_bits_sqwStrobe_1,
  input  wire       io_in_5_bits_sqwStrobe_2,
  input  wire       io_in_5_bits_sqwStrobe_3,
  input  wire       io_in_6_valid,
  input  wire [7:0] io_in_6_bits_cacheData_0,
  input  wire [7:0] io_in_6_bits_cacheData_1,
  input  wire [7:0] io_in_6_bits_cacheData_2,
  input  wire [7:0] io_in_6_bits_cacheData_3,
  input  wire       io_in_6_bits_sqwStrobe_0,
  input  wire       io_in_6_bits_sqwStrobe_1,
  input  wire       io_in_6_bits_sqwStrobe_2,
  input  wire       io_in_6_bits_sqwStrobe_3,
  input  wire       io_in_7_valid,
  input  wire [7:0] io_in_7_bits_cacheData_0,
  input  wire [7:0] io_in_7_bits_cacheData_1,
  input  wire [7:0] io_in_7_bits_cacheData_2,
  input  wire [7:0] io_in_7_bits_cacheData_3,
  input  wire       io_in_7_bits_sqwStrobe_0,
  input  wire       io_in_7_bits_sqwStrobe_1,
  input  wire       io_in_7_bits_sqwStrobe_2,
  input  wire       io_in_7_bits_sqwStrobe_3,
  input  wire [2:0] io_shamt,
  output wire       io_out_0_valid,
  output wire [7:0] io_out_0_bits_cacheData_0,
  output wire [7:0] io_out_0_bits_cacheData_1,
  output wire [7:0] io_out_0_bits_cacheData_2,
  output wire [7:0] io_out_0_bits_cacheData_3,
  output wire       io_out_0_bits_sqwStrobe_0,
  output wire       io_out_0_bits_sqwStrobe_1,
  output wire       io_out_0_bits_sqwStrobe_2,
  output wire       io_out_0_bits_sqwStrobe_3,
  output wire       io_out_1_valid,
  output wire [7:0] io_out_1_bits_cacheData_0,
  output wire [7:0] io_out_1_bits_cacheData_1,
  output wire [7:0] io_out_1_bits_cacheData_2,
  output wire [7:0] io_out_1_bits_cacheData_3,
  output wire       io_out_1_bits_sqwStrobe_0,
  output wire       io_out_1_bits_sqwStrobe_1,
  output wire       io_out_1_bits_sqwStrobe_2,
  output wire       io_out_1_bits_sqwStrobe_3,
  output wire       io_out_2_valid,
  output wire [7:0] io_out_2_bits_cacheData_0,
  output wire [7:0] io_out_2_bits_cacheData_1,
  output wire [7:0] io_out_2_bits_cacheData_2,
  output wire [7:0] io_out_2_bits_cacheData_3,
  output wire       io_out_2_bits_sqwStrobe_0,
  output wire       io_out_2_bits_sqwStrobe_1,
  output wire       io_out_2_bits_sqwStrobe_2,
  output wire       io_out_2_bits_sqwStrobe_3,
  output wire       io_out_3_valid,
  output wire [7:0] io_out_3_bits_cacheData_0,
  output wire [7:0] io_out_3_bits_cacheData_1,
  output wire [7:0] io_out_3_bits_cacheData_2,
  output wire [7:0] io_out_3_bits_cacheData_3,
  output wire       io_out_3_bits_sqwStrobe_0,
  output wire       io_out_3_bits_sqwStrobe_1,
  output wire       io_out_3_bits_sqwStrobe_2,
  output wire       io_out_3_bits_sqwStrobe_3,
  output wire       io_out_4_valid,
  output wire [7:0] io_out_4_bits_cacheData_0,
  output wire [7:0] io_out_4_bits_cacheData_1,
  output wire [7:0] io_out_4_bits_cacheData_2,
  output wire [7:0] io_out_4_bits_cacheData_3,
  output wire       io_out_4_bits_sqwStrobe_0,
  output wire       io_out_4_bits_sqwStrobe_1,
  output wire       io_out_4_bits_sqwStrobe_2,
  output wire       io_out_4_bits_sqwStrobe_3,
  output wire       io_out_5_valid,
  output wire [7:0] io_out_5_bits_cacheData_0,
  output wire [7:0] io_out_5_bits_cacheData_1,
  output wire [7:0] io_out_5_bits_cacheData_2,
  output wire [7:0] io_out_5_bits_cacheData_3,
  output wire       io_out_5_bits_sqwStrobe_0,
  output wire       io_out_5_bits_sqwStrobe_1,
  output wire       io_out_5_bits_sqwStrobe_2,
  output wire       io_out_5_bits_sqwStrobe_3,
  output wire       io_out_6_valid,
  output wire [7:0] io_out_6_bits_cacheData_0,
  output wire [7:0] io_out_6_bits_cacheData_1,
  output wire [7:0] io_out_6_bits_cacheData_2,
  output wire [7:0] io_out_6_bits_cacheData_3,
  output wire       io_out_6_bits_sqwStrobe_0,
  output wire       io_out_6_bits_sqwStrobe_1,
  output wire       io_out_6_bits_sqwStrobe_2,
  output wire       io_out_6_bits_sqwStrobe_3,
  output wire       io_out_7_valid,
  output wire [7:0] io_out_7_bits_cacheData_0,
  output wire [7:0] io_out_7_bits_cacheData_1,
  output wire [7:0] io_out_7_bits_cacheData_2,
  output wire [7:0] io_out_7_bits_cacheData_3,
  output wire       io_out_7_bits_sqwStrobe_0,
  output wire       io_out_7_bits_sqwStrobe_1,
  output wire       io_out_7_bits_sqwStrobe_2,
  output wire       io_out_7_bits_sqwStrobe_3
);

  wire       _GEN = ~(io_shamt[0]) & io_in_0_valid | io_shamt[0] & io_in_1_valid;
  wire       _GEN_0 = ~(io_shamt[0]) & io_in_1_valid | io_shamt[0] & io_in_2_valid;
  wire       _GEN_1 = ~(io_shamt[0]) & io_in_2_valid | io_shamt[0] & io_in_3_valid;
  wire       _GEN_2 = ~(io_shamt[0]) & io_in_3_valid | io_shamt[0] & io_in_4_valid;
  wire       _GEN_3 = ~(io_shamt[0]) & io_in_4_valid | io_shamt[0] & io_in_5_valid;
  wire       _GEN_4 = ~(io_shamt[0]) & io_in_5_valid | io_shamt[0] & io_in_6_valid;
  wire       _GEN_5 = ~(io_shamt[0]) & io_in_6_valid | io_shamt[0] & io_in_7_valid;
  wire       _GEN_6 = ~(io_shamt[0]) & io_in_7_valid | io_shamt[0] & io_in_0_valid;
  wire       _GEN_7 = ~(io_shamt[1]) & _GEN | io_shamt[1] & _GEN_1;
  wire       _GEN_8 = ~(io_shamt[1]) & _GEN_0 | io_shamt[1] & _GEN_2;
  wire       _GEN_9 = ~(io_shamt[1]) & _GEN_1 | io_shamt[1] & _GEN_3;
  wire       _GEN_10 = ~(io_shamt[1]) & _GEN_2 | io_shamt[1] & _GEN_4;
  wire       _GEN_11 = ~(io_shamt[1]) & _GEN_3 | io_shamt[1] & _GEN_5;
  wire       _GEN_12 = ~(io_shamt[1]) & _GEN_4 | io_shamt[1] & _GEN_6;
  wire       _GEN_13 = ~(io_shamt[1]) & _GEN_5 | io_shamt[1] & _GEN;
  wire       _GEN_14 = ~(io_shamt[1]) & _GEN_6 | io_shamt[1] & _GEN_0;
  wire       _GEN_15 =
    ~(io_shamt[0]) & io_in_0_bits_sqwStrobe_0 | io_shamt[0] & io_in_1_bits_sqwStrobe_0;
  wire       _GEN_16 =
    ~(io_shamt[0]) & io_in_0_bits_sqwStrobe_1 | io_shamt[0] & io_in_1_bits_sqwStrobe_1;
  wire       _GEN_17 =
    ~(io_shamt[0]) & io_in_0_bits_sqwStrobe_2 | io_shamt[0] & io_in_1_bits_sqwStrobe_2;
  wire       _GEN_18 =
    ~(io_shamt[0]) & io_in_0_bits_sqwStrobe_3 | io_shamt[0] & io_in_1_bits_sqwStrobe_3;
  wire [7:0] _GEN_19 = io_shamt[0] ? 8'h0 : io_in_0_bits_cacheData_0;
  wire [7:0] _GEN_20 = io_shamt[0] ? io_in_1_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_21 = _GEN_19 | _GEN_20;
  wire [7:0] _GEN_22 = io_shamt[0] ? 8'h0 : io_in_0_bits_cacheData_1;
  wire [7:0] _GEN_23 = io_shamt[0] ? io_in_1_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_24 = _GEN_22 | _GEN_23;
  wire [7:0] _GEN_25 = io_shamt[0] ? 8'h0 : io_in_0_bits_cacheData_2;
  wire [7:0] _GEN_26 = io_shamt[0] ? io_in_1_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_27 = _GEN_25 | _GEN_26;
  wire [7:0] _GEN_28 = io_shamt[0] ? 8'h0 : io_in_0_bits_cacheData_3;
  wire [7:0] _GEN_29 = io_shamt[0] ? io_in_1_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_30 = _GEN_28 | _GEN_29;
  wire       _GEN_31 =
    ~(io_shamt[0]) & io_in_1_bits_sqwStrobe_0 | io_shamt[0] & io_in_2_bits_sqwStrobe_0;
  wire       _GEN_32 =
    ~(io_shamt[0]) & io_in_1_bits_sqwStrobe_1 | io_shamt[0] & io_in_2_bits_sqwStrobe_1;
  wire       _GEN_33 =
    ~(io_shamt[0]) & io_in_1_bits_sqwStrobe_2 | io_shamt[0] & io_in_2_bits_sqwStrobe_2;
  wire       _GEN_34 =
    ~(io_shamt[0]) & io_in_1_bits_sqwStrobe_3 | io_shamt[0] & io_in_2_bits_sqwStrobe_3;
  wire [7:0] _GEN_35 = io_shamt[0] ? 8'h0 : io_in_1_bits_cacheData_0;
  wire [7:0] _GEN_36 = io_shamt[0] ? io_in_2_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_37 = _GEN_35 | _GEN_36;
  wire [7:0] _GEN_38 = io_shamt[0] ? 8'h0 : io_in_1_bits_cacheData_1;
  wire [7:0] _GEN_39 = io_shamt[0] ? io_in_2_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_40 = _GEN_38 | _GEN_39;
  wire [7:0] _GEN_41 = io_shamt[0] ? 8'h0 : io_in_1_bits_cacheData_2;
  wire [7:0] _GEN_42 = io_shamt[0] ? io_in_2_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_43 = _GEN_41 | _GEN_42;
  wire [7:0] _GEN_44 = io_shamt[0] ? 8'h0 : io_in_1_bits_cacheData_3;
  wire [7:0] _GEN_45 = io_shamt[0] ? io_in_2_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_46 = _GEN_44 | _GEN_45;
  wire       _GEN_47 =
    ~(io_shamt[0]) & io_in_2_bits_sqwStrobe_0 | io_shamt[0] & io_in_3_bits_sqwStrobe_0;
  wire       _GEN_48 =
    ~(io_shamt[0]) & io_in_2_bits_sqwStrobe_1 | io_shamt[0] & io_in_3_bits_sqwStrobe_1;
  wire       _GEN_49 =
    ~(io_shamt[0]) & io_in_2_bits_sqwStrobe_2 | io_shamt[0] & io_in_3_bits_sqwStrobe_2;
  wire       _GEN_50 =
    ~(io_shamt[0]) & io_in_2_bits_sqwStrobe_3 | io_shamt[0] & io_in_3_bits_sqwStrobe_3;
  wire [7:0] _GEN_51 = io_shamt[0] ? 8'h0 : io_in_2_bits_cacheData_0;
  wire [7:0] _GEN_52 = io_shamt[0] ? io_in_3_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_53 = _GEN_51 | _GEN_52;
  wire [7:0] _GEN_54 = io_shamt[0] ? 8'h0 : io_in_2_bits_cacheData_1;
  wire [7:0] _GEN_55 = io_shamt[0] ? io_in_3_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_56 = _GEN_54 | _GEN_55;
  wire [7:0] _GEN_57 = io_shamt[0] ? 8'h0 : io_in_2_bits_cacheData_2;
  wire [7:0] _GEN_58 = io_shamt[0] ? io_in_3_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_59 = _GEN_57 | _GEN_58;
  wire [7:0] _GEN_60 = io_shamt[0] ? 8'h0 : io_in_2_bits_cacheData_3;
  wire [7:0] _GEN_61 = io_shamt[0] ? io_in_3_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_62 = _GEN_60 | _GEN_61;
  wire       _GEN_63 =
    ~(io_shamt[0]) & io_in_3_bits_sqwStrobe_0 | io_shamt[0] & io_in_4_bits_sqwStrobe_0;
  wire       _GEN_64 =
    ~(io_shamt[0]) & io_in_3_bits_sqwStrobe_1 | io_shamt[0] & io_in_4_bits_sqwStrobe_1;
  wire       _GEN_65 =
    ~(io_shamt[0]) & io_in_3_bits_sqwStrobe_2 | io_shamt[0] & io_in_4_bits_sqwStrobe_2;
  wire       _GEN_66 =
    ~(io_shamt[0]) & io_in_3_bits_sqwStrobe_3 | io_shamt[0] & io_in_4_bits_sqwStrobe_3;
  wire [7:0] _GEN_67 = io_shamt[0] ? 8'h0 : io_in_3_bits_cacheData_0;
  wire [7:0] _GEN_68 = io_shamt[0] ? io_in_4_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_69 = _GEN_67 | _GEN_68;
  wire [7:0] _GEN_70 = io_shamt[0] ? 8'h0 : io_in_3_bits_cacheData_1;
  wire [7:0] _GEN_71 = io_shamt[0] ? io_in_4_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_72 = _GEN_70 | _GEN_71;
  wire [7:0] _GEN_73 = io_shamt[0] ? 8'h0 : io_in_3_bits_cacheData_2;
  wire [7:0] _GEN_74 = io_shamt[0] ? io_in_4_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_75 = _GEN_73 | _GEN_74;
  wire [7:0] _GEN_76 = io_shamt[0] ? 8'h0 : io_in_3_bits_cacheData_3;
  wire [7:0] _GEN_77 = io_shamt[0] ? io_in_4_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_78 = _GEN_76 | _GEN_77;
  wire       _GEN_79 =
    ~(io_shamt[0]) & io_in_4_bits_sqwStrobe_0 | io_shamt[0] & io_in_5_bits_sqwStrobe_0;
  wire       _GEN_80 =
    ~(io_shamt[0]) & io_in_4_bits_sqwStrobe_1 | io_shamt[0] & io_in_5_bits_sqwStrobe_1;
  wire       _GEN_81 =
    ~(io_shamt[0]) & io_in_4_bits_sqwStrobe_2 | io_shamt[0] & io_in_5_bits_sqwStrobe_2;
  wire       _GEN_82 =
    ~(io_shamt[0]) & io_in_4_bits_sqwStrobe_3 | io_shamt[0] & io_in_5_bits_sqwStrobe_3;
  wire [7:0] _GEN_83 = io_shamt[0] ? 8'h0 : io_in_4_bits_cacheData_0;
  wire [7:0] _GEN_84 = io_shamt[0] ? io_in_5_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_85 = _GEN_83 | _GEN_84;
  wire [7:0] _GEN_86 = io_shamt[0] ? 8'h0 : io_in_4_bits_cacheData_1;
  wire [7:0] _GEN_87 = io_shamt[0] ? io_in_5_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_88 = _GEN_86 | _GEN_87;
  wire [7:0] _GEN_89 = io_shamt[0] ? 8'h0 : io_in_4_bits_cacheData_2;
  wire [7:0] _GEN_90 = io_shamt[0] ? io_in_5_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_91 = _GEN_89 | _GEN_90;
  wire [7:0] _GEN_92 = io_shamt[0] ? 8'h0 : io_in_4_bits_cacheData_3;
  wire [7:0] _GEN_93 = io_shamt[0] ? io_in_5_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_94 = _GEN_92 | _GEN_93;
  wire       _GEN_95 =
    ~(io_shamt[0]) & io_in_5_bits_sqwStrobe_0 | io_shamt[0] & io_in_6_bits_sqwStrobe_0;
  wire       _GEN_96 =
    ~(io_shamt[0]) & io_in_5_bits_sqwStrobe_1 | io_shamt[0] & io_in_6_bits_sqwStrobe_1;
  wire       _GEN_97 =
    ~(io_shamt[0]) & io_in_5_bits_sqwStrobe_2 | io_shamt[0] & io_in_6_bits_sqwStrobe_2;
  wire       _GEN_98 =
    ~(io_shamt[0]) & io_in_5_bits_sqwStrobe_3 | io_shamt[0] & io_in_6_bits_sqwStrobe_3;
  wire [7:0] _GEN_99 = io_shamt[0] ? 8'h0 : io_in_5_bits_cacheData_0;
  wire [7:0] _GEN_100 = io_shamt[0] ? io_in_6_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_101 = _GEN_99 | _GEN_100;
  wire [7:0] _GEN_102 = io_shamt[0] ? 8'h0 : io_in_5_bits_cacheData_1;
  wire [7:0] _GEN_103 = io_shamt[0] ? io_in_6_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_104 = _GEN_102 | _GEN_103;
  wire [7:0] _GEN_105 = io_shamt[0] ? 8'h0 : io_in_5_bits_cacheData_2;
  wire [7:0] _GEN_106 = io_shamt[0] ? io_in_6_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_107 = _GEN_105 | _GEN_106;
  wire [7:0] _GEN_108 = io_shamt[0] ? 8'h0 : io_in_5_bits_cacheData_3;
  wire [7:0] _GEN_109 = io_shamt[0] ? io_in_6_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_110 = _GEN_108 | _GEN_109;
  wire       _GEN_111 =
    ~(io_shamt[0]) & io_in_6_bits_sqwStrobe_0 | io_shamt[0] & io_in_7_bits_sqwStrobe_0;
  wire       _GEN_112 =
    ~(io_shamt[0]) & io_in_6_bits_sqwStrobe_1 | io_shamt[0] & io_in_7_bits_sqwStrobe_1;
  wire       _GEN_113 =
    ~(io_shamt[0]) & io_in_6_bits_sqwStrobe_2 | io_shamt[0] & io_in_7_bits_sqwStrobe_2;
  wire       _GEN_114 =
    ~(io_shamt[0]) & io_in_6_bits_sqwStrobe_3 | io_shamt[0] & io_in_7_bits_sqwStrobe_3;
  wire [7:0] _GEN_115 = io_shamt[0] ? 8'h0 : io_in_6_bits_cacheData_0;
  wire [7:0] _GEN_116 = io_shamt[0] ? io_in_7_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_117 = _GEN_115 | _GEN_116;
  wire [7:0] _GEN_118 = io_shamt[0] ? 8'h0 : io_in_6_bits_cacheData_1;
  wire [7:0] _GEN_119 = io_shamt[0] ? io_in_7_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_120 = _GEN_118 | _GEN_119;
  wire [7:0] _GEN_121 = io_shamt[0] ? 8'h0 : io_in_6_bits_cacheData_2;
  wire [7:0] _GEN_122 = io_shamt[0] ? io_in_7_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_123 = _GEN_121 | _GEN_122;
  wire [7:0] _GEN_124 = io_shamt[0] ? 8'h0 : io_in_6_bits_cacheData_3;
  wire [7:0] _GEN_125 = io_shamt[0] ? io_in_7_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_126 = _GEN_124 | _GEN_125;
  wire       _GEN_127 =
    ~(io_shamt[0]) & io_in_7_bits_sqwStrobe_0 | io_shamt[0] & io_in_0_bits_sqwStrobe_0;
  wire       _GEN_128 =
    ~(io_shamt[0]) & io_in_7_bits_sqwStrobe_1 | io_shamt[0] & io_in_0_bits_sqwStrobe_1;
  wire       _GEN_129 =
    ~(io_shamt[0]) & io_in_7_bits_sqwStrobe_2 | io_shamt[0] & io_in_0_bits_sqwStrobe_2;
  wire       _GEN_130 =
    ~(io_shamt[0]) & io_in_7_bits_sqwStrobe_3 | io_shamt[0] & io_in_0_bits_sqwStrobe_3;
  wire [7:0] _GEN_131 = io_shamt[0] ? 8'h0 : io_in_7_bits_cacheData_0;
  wire [7:0] _GEN_132 = io_shamt[0] ? io_in_0_bits_cacheData_0 : 8'h0;
  wire [7:0] _GEN_133 = _GEN_131 | _GEN_132;
  wire [7:0] _GEN_134 = io_shamt[0] ? 8'h0 : io_in_7_bits_cacheData_1;
  wire [7:0] _GEN_135 = io_shamt[0] ? io_in_0_bits_cacheData_1 : 8'h0;
  wire [7:0] _GEN_136 = _GEN_134 | _GEN_135;
  wire [7:0] _GEN_137 = io_shamt[0] ? 8'h0 : io_in_7_bits_cacheData_2;
  wire [7:0] _GEN_138 = io_shamt[0] ? io_in_0_bits_cacheData_2 : 8'h0;
  wire [7:0] _GEN_139 = _GEN_137 | _GEN_138;
  wire [7:0] _GEN_140 = io_shamt[0] ? 8'h0 : io_in_7_bits_cacheData_3;
  wire [7:0] _GEN_141 = io_shamt[0] ? io_in_0_bits_cacheData_3 : 8'h0;
  wire [7:0] _GEN_142 = _GEN_140 | _GEN_141;
  wire       _GEN_143 = ~(io_shamt[1]) & _GEN_15 | io_shamt[1] & _GEN_47;
  wire       _GEN_144 = ~(io_shamt[1]) & _GEN_16 | io_shamt[1] & _GEN_48;
  wire       _GEN_145 = ~(io_shamt[1]) & _GEN_17 | io_shamt[1] & _GEN_49;
  wire       _GEN_146 = ~(io_shamt[1]) & _GEN_18 | io_shamt[1] & _GEN_50;
  wire [7:0] _GEN_147 = io_shamt[1] ? 8'h0 : _GEN_21;
  wire [7:0] _GEN_148 = io_shamt[1] ? _GEN_53 : 8'h0;
  wire [7:0] _GEN_149 = _GEN_147 | _GEN_148;
  wire [7:0] _GEN_150 = io_shamt[1] ? 8'h0 : _GEN_24;
  wire [7:0] _GEN_151 = io_shamt[1] ? _GEN_56 : 8'h0;
  wire [7:0] _GEN_152 = _GEN_150 | _GEN_151;
  wire [7:0] _GEN_153 = io_shamt[1] ? 8'h0 : _GEN_27;
  wire [7:0] _GEN_154 = io_shamt[1] ? _GEN_59 : 8'h0;
  wire [7:0] _GEN_155 = _GEN_153 | _GEN_154;
  wire [7:0] _GEN_156 = io_shamt[1] ? 8'h0 : _GEN_30;
  wire [7:0] _GEN_157 = io_shamt[1] ? _GEN_62 : 8'h0;
  wire [7:0] _GEN_158 = _GEN_156 | _GEN_157;
  wire       _GEN_159 = ~(io_shamt[1]) & _GEN_31 | io_shamt[1] & _GEN_63;
  wire       _GEN_160 = ~(io_shamt[1]) & _GEN_32 | io_shamt[1] & _GEN_64;
  wire       _GEN_161 = ~(io_shamt[1]) & _GEN_33 | io_shamt[1] & _GEN_65;
  wire       _GEN_162 = ~(io_shamt[1]) & _GEN_34 | io_shamt[1] & _GEN_66;
  wire [7:0] _GEN_163 = io_shamt[1] ? 8'h0 : _GEN_37;
  wire [7:0] _GEN_164 = io_shamt[1] ? _GEN_69 : 8'h0;
  wire [7:0] _GEN_165 = _GEN_163 | _GEN_164;
  wire [7:0] _GEN_166 = io_shamt[1] ? 8'h0 : _GEN_40;
  wire [7:0] _GEN_167 = io_shamt[1] ? _GEN_72 : 8'h0;
  wire [7:0] _GEN_168 = _GEN_166 | _GEN_167;
  wire [7:0] _GEN_169 = io_shamt[1] ? 8'h0 : _GEN_43;
  wire [7:0] _GEN_170 = io_shamt[1] ? _GEN_75 : 8'h0;
  wire [7:0] _GEN_171 = _GEN_169 | _GEN_170;
  wire [7:0] _GEN_172 = io_shamt[1] ? 8'h0 : _GEN_46;
  wire [7:0] _GEN_173 = io_shamt[1] ? _GEN_78 : 8'h0;
  wire [7:0] _GEN_174 = _GEN_172 | _GEN_173;
  wire       _GEN_175 = ~(io_shamt[1]) & _GEN_47 | io_shamt[1] & _GEN_79;
  wire       _GEN_176 = ~(io_shamt[1]) & _GEN_48 | io_shamt[1] & _GEN_80;
  wire       _GEN_177 = ~(io_shamt[1]) & _GEN_49 | io_shamt[1] & _GEN_81;
  wire       _GEN_178 = ~(io_shamt[1]) & _GEN_50 | io_shamt[1] & _GEN_82;
  wire [7:0] _GEN_179 = io_shamt[1] ? 8'h0 : _GEN_53;
  wire [7:0] _GEN_180 = io_shamt[1] ? _GEN_85 : 8'h0;
  wire [7:0] _GEN_181 = _GEN_179 | _GEN_180;
  wire [7:0] _GEN_182 = io_shamt[1] ? 8'h0 : _GEN_56;
  wire [7:0] _GEN_183 = io_shamt[1] ? _GEN_88 : 8'h0;
  wire [7:0] _GEN_184 = _GEN_182 | _GEN_183;
  wire [7:0] _GEN_185 = io_shamt[1] ? 8'h0 : _GEN_59;
  wire [7:0] _GEN_186 = io_shamt[1] ? _GEN_91 : 8'h0;
  wire [7:0] _GEN_187 = _GEN_185 | _GEN_186;
  wire [7:0] _GEN_188 = io_shamt[1] ? 8'h0 : _GEN_62;
  wire [7:0] _GEN_189 = io_shamt[1] ? _GEN_94 : 8'h0;
  wire [7:0] _GEN_190 = _GEN_188 | _GEN_189;
  wire       _GEN_191 = ~(io_shamt[1]) & _GEN_63 | io_shamt[1] & _GEN_95;
  wire       _GEN_192 = ~(io_shamt[1]) & _GEN_64 | io_shamt[1] & _GEN_96;
  wire       _GEN_193 = ~(io_shamt[1]) & _GEN_65 | io_shamt[1] & _GEN_97;
  wire       _GEN_194 = ~(io_shamt[1]) & _GEN_66 | io_shamt[1] & _GEN_98;
  wire [7:0] _GEN_195 = io_shamt[1] ? 8'h0 : _GEN_69;
  wire [7:0] _GEN_196 = io_shamt[1] ? _GEN_101 : 8'h0;
  wire [7:0] _GEN_197 = _GEN_195 | _GEN_196;
  wire [7:0] _GEN_198 = io_shamt[1] ? 8'h0 : _GEN_72;
  wire [7:0] _GEN_199 = io_shamt[1] ? _GEN_104 : 8'h0;
  wire [7:0] _GEN_200 = _GEN_198 | _GEN_199;
  wire [7:0] _GEN_201 = io_shamt[1] ? 8'h0 : _GEN_75;
  wire [7:0] _GEN_202 = io_shamt[1] ? _GEN_107 : 8'h0;
  wire [7:0] _GEN_203 = _GEN_201 | _GEN_202;
  wire [7:0] _GEN_204 = io_shamt[1] ? 8'h0 : _GEN_78;
  wire [7:0] _GEN_205 = io_shamt[1] ? _GEN_110 : 8'h0;
  wire [7:0] _GEN_206 = _GEN_204 | _GEN_205;
  wire       _GEN_207 = ~(io_shamt[1]) & _GEN_79 | io_shamt[1] & _GEN_111;
  wire       _GEN_208 = ~(io_shamt[1]) & _GEN_80 | io_shamt[1] & _GEN_112;
  wire       _GEN_209 = ~(io_shamt[1]) & _GEN_81 | io_shamt[1] & _GEN_113;
  wire       _GEN_210 = ~(io_shamt[1]) & _GEN_82 | io_shamt[1] & _GEN_114;
  wire [7:0] _GEN_211 = io_shamt[1] ? 8'h0 : _GEN_85;
  wire [7:0] _GEN_212 = io_shamt[1] ? _GEN_117 : 8'h0;
  wire [7:0] _GEN_213 = _GEN_211 | _GEN_212;
  wire [7:0] _GEN_214 = io_shamt[1] ? 8'h0 : _GEN_88;
  wire [7:0] _GEN_215 = io_shamt[1] ? _GEN_120 : 8'h0;
  wire [7:0] _GEN_216 = _GEN_214 | _GEN_215;
  wire [7:0] _GEN_217 = io_shamt[1] ? 8'h0 : _GEN_91;
  wire [7:0] _GEN_218 = io_shamt[1] ? _GEN_123 : 8'h0;
  wire [7:0] _GEN_219 = _GEN_217 | _GEN_218;
  wire [7:0] _GEN_220 = io_shamt[1] ? 8'h0 : _GEN_94;
  wire [7:0] _GEN_221 = io_shamt[1] ? _GEN_126 : 8'h0;
  wire [7:0] _GEN_222 = _GEN_220 | _GEN_221;
  wire       _GEN_223 = ~(io_shamt[1]) & _GEN_95 | io_shamt[1] & _GEN_127;
  wire       _GEN_224 = ~(io_shamt[1]) & _GEN_96 | io_shamt[1] & _GEN_128;
  wire       _GEN_225 = ~(io_shamt[1]) & _GEN_97 | io_shamt[1] & _GEN_129;
  wire       _GEN_226 = ~(io_shamt[1]) & _GEN_98 | io_shamt[1] & _GEN_130;
  wire [7:0] _GEN_227 = io_shamt[1] ? 8'h0 : _GEN_101;
  wire [7:0] _GEN_228 = io_shamt[1] ? _GEN_133 : 8'h0;
  wire [7:0] _GEN_229 = _GEN_227 | _GEN_228;
  wire [7:0] _GEN_230 = io_shamt[1] ? 8'h0 : _GEN_104;
  wire [7:0] _GEN_231 = io_shamt[1] ? _GEN_136 : 8'h0;
  wire [7:0] _GEN_232 = _GEN_230 | _GEN_231;
  wire [7:0] _GEN_233 = io_shamt[1] ? 8'h0 : _GEN_107;
  wire [7:0] _GEN_234 = io_shamt[1] ? _GEN_139 : 8'h0;
  wire [7:0] _GEN_235 = _GEN_233 | _GEN_234;
  wire [7:0] _GEN_236 = io_shamt[1] ? 8'h0 : _GEN_110;
  wire [7:0] _GEN_237 = io_shamt[1] ? _GEN_142 : 8'h0;
  wire [7:0] _GEN_238 = _GEN_236 | _GEN_237;
  wire       _GEN_239 = ~(io_shamt[1]) & _GEN_111 | io_shamt[1] & _GEN_15;
  wire       _GEN_240 = ~(io_shamt[1]) & _GEN_112 | io_shamt[1] & _GEN_16;
  wire       _GEN_241 = ~(io_shamt[1]) & _GEN_113 | io_shamt[1] & _GEN_17;
  wire       _GEN_242 = ~(io_shamt[1]) & _GEN_114 | io_shamt[1] & _GEN_18;
  wire [7:0] _GEN_243 = io_shamt[1] ? 8'h0 : _GEN_117;
  wire [7:0] _GEN_244 = io_shamt[1] ? _GEN_21 : 8'h0;
  wire [7:0] _GEN_245 = _GEN_243 | _GEN_244;
  wire [7:0] _GEN_246 = io_shamt[1] ? 8'h0 : _GEN_120;
  wire [7:0] _GEN_247 = io_shamt[1] ? _GEN_24 : 8'h0;
  wire [7:0] _GEN_248 = _GEN_246 | _GEN_247;
  wire [7:0] _GEN_249 = io_shamt[1] ? 8'h0 : _GEN_123;
  wire [7:0] _GEN_250 = io_shamt[1] ? _GEN_27 : 8'h0;
  wire [7:0] _GEN_251 = _GEN_249 | _GEN_250;
  wire [7:0] _GEN_252 = io_shamt[1] ? 8'h0 : _GEN_126;
  wire [7:0] _GEN_253 = io_shamt[1] ? _GEN_30 : 8'h0;
  wire [7:0] _GEN_254 = _GEN_252 | _GEN_253;
  wire       _GEN_255 = ~(io_shamt[1]) & _GEN_127 | io_shamt[1] & _GEN_31;
  wire       _GEN_256 = ~(io_shamt[1]) & _GEN_128 | io_shamt[1] & _GEN_32;
  wire       _GEN_257 = ~(io_shamt[1]) & _GEN_129 | io_shamt[1] & _GEN_33;
  wire       _GEN_258 = ~(io_shamt[1]) & _GEN_130 | io_shamt[1] & _GEN_34;
  wire [7:0] _GEN_259 = io_shamt[1] ? 8'h0 : _GEN_133;
  wire [7:0] _GEN_260 = io_shamt[1] ? _GEN_37 : 8'h0;
  wire [7:0] _GEN_261 = _GEN_259 | _GEN_260;
  wire [7:0] _GEN_262 = io_shamt[1] ? 8'h0 : _GEN_136;
  wire [7:0] _GEN_263 = io_shamt[1] ? _GEN_40 : 8'h0;
  wire [7:0] _GEN_264 = _GEN_262 | _GEN_263;
  wire [7:0] _GEN_265 = io_shamt[1] ? 8'h0 : _GEN_139;
  wire [7:0] _GEN_266 = io_shamt[1] ? _GEN_43 : 8'h0;
  wire [7:0] _GEN_267 = _GEN_265 | _GEN_266;
  wire [7:0] _GEN_268 = io_shamt[1] ? 8'h0 : _GEN_142;
  wire [7:0] _GEN_269 = io_shamt[1] ? _GEN_46 : 8'h0;
  wire [7:0] _GEN_270 = _GEN_268 | _GEN_269;
  wire [7:0] _GEN_271 = io_shamt[2] ? 8'h0 : _GEN_149;
  wire [7:0] _GEN_272 = io_shamt[2] ? _GEN_213 : 8'h0;
  wire [7:0] _GEN_273 = io_shamt[2] ? 8'h0 : _GEN_152;
  wire [7:0] _GEN_274 = io_shamt[2] ? _GEN_216 : 8'h0;
  wire [7:0] _GEN_275 = io_shamt[2] ? 8'h0 : _GEN_155;
  wire [7:0] _GEN_276 = io_shamt[2] ? _GEN_219 : 8'h0;
  wire [7:0] _GEN_277 = io_shamt[2] ? 8'h0 : _GEN_158;
  wire [7:0] _GEN_278 = io_shamt[2] ? _GEN_222 : 8'h0;
  wire [7:0] _GEN_279 = io_shamt[2] ? 8'h0 : _GEN_165;
  wire [7:0] _GEN_280 = io_shamt[2] ? _GEN_229 : 8'h0;
  wire [7:0] _GEN_281 = io_shamt[2] ? 8'h0 : _GEN_168;
  wire [7:0] _GEN_282 = io_shamt[2] ? _GEN_232 : 8'h0;
  wire [7:0] _GEN_283 = io_shamt[2] ? 8'h0 : _GEN_171;
  wire [7:0] _GEN_284 = io_shamt[2] ? _GEN_235 : 8'h0;
  wire [7:0] _GEN_285 = io_shamt[2] ? 8'h0 : _GEN_174;
  wire [7:0] _GEN_286 = io_shamt[2] ? _GEN_238 : 8'h0;
  wire [7:0] _GEN_287 = io_shamt[2] ? 8'h0 : _GEN_181;
  wire [7:0] _GEN_288 = io_shamt[2] ? _GEN_245 : 8'h0;
  wire [7:0] _GEN_289 = io_shamt[2] ? 8'h0 : _GEN_184;
  wire [7:0] _GEN_290 = io_shamt[2] ? _GEN_248 : 8'h0;
  wire [7:0] _GEN_291 = io_shamt[2] ? 8'h0 : _GEN_187;
  wire [7:0] _GEN_292 = io_shamt[2] ? _GEN_251 : 8'h0;
  wire [7:0] _GEN_293 = io_shamt[2] ? 8'h0 : _GEN_190;
  wire [7:0] _GEN_294 = io_shamt[2] ? _GEN_254 : 8'h0;
  wire [7:0] _GEN_295 = io_shamt[2] ? 8'h0 : _GEN_197;
  wire [7:0] _GEN_296 = io_shamt[2] ? _GEN_261 : 8'h0;
  wire [7:0] _GEN_297 = io_shamt[2] ? 8'h0 : _GEN_200;
  wire [7:0] _GEN_298 = io_shamt[2] ? _GEN_264 : 8'h0;
  wire [7:0] _GEN_299 = io_shamt[2] ? 8'h0 : _GEN_203;
  wire [7:0] _GEN_300 = io_shamt[2] ? _GEN_267 : 8'h0;
  wire [7:0] _GEN_301 = io_shamt[2] ? 8'h0 : _GEN_206;
  wire [7:0] _GEN_302 = io_shamt[2] ? _GEN_270 : 8'h0;
  wire [7:0] _GEN_303 = io_shamt[2] ? 8'h0 : _GEN_213;
  wire [7:0] _GEN_304 = io_shamt[2] ? _GEN_149 : 8'h0;
  wire [7:0] _GEN_305 = io_shamt[2] ? 8'h0 : _GEN_216;
  wire [7:0] _GEN_306 = io_shamt[2] ? _GEN_152 : 8'h0;
  wire [7:0] _GEN_307 = io_shamt[2] ? 8'h0 : _GEN_219;
  wire [7:0] _GEN_308 = io_shamt[2] ? _GEN_155 : 8'h0;
  wire [7:0] _GEN_309 = io_shamt[2] ? 8'h0 : _GEN_222;
  wire [7:0] _GEN_310 = io_shamt[2] ? _GEN_158 : 8'h0;
  wire [7:0] _GEN_311 = io_shamt[2] ? 8'h0 : _GEN_229;
  wire [7:0] _GEN_312 = io_shamt[2] ? _GEN_165 : 8'h0;
  wire [7:0] _GEN_313 = io_shamt[2] ? 8'h0 : _GEN_232;
  wire [7:0] _GEN_314 = io_shamt[2] ? _GEN_168 : 8'h0;
  wire [7:0] _GEN_315 = io_shamt[2] ? 8'h0 : _GEN_235;
  wire [7:0] _GEN_316 = io_shamt[2] ? _GEN_171 : 8'h0;
  wire [7:0] _GEN_317 = io_shamt[2] ? 8'h0 : _GEN_238;
  wire [7:0] _GEN_318 = io_shamt[2] ? _GEN_174 : 8'h0;
  wire [7:0] _GEN_319 = io_shamt[2] ? 8'h0 : _GEN_245;
  wire [7:0] _GEN_320 = io_shamt[2] ? _GEN_181 : 8'h0;
  wire [7:0] _GEN_321 = io_shamt[2] ? 8'h0 : _GEN_248;
  wire [7:0] _GEN_322 = io_shamt[2] ? _GEN_184 : 8'h0;
  wire [7:0] _GEN_323 = io_shamt[2] ? 8'h0 : _GEN_251;
  wire [7:0] _GEN_324 = io_shamt[2] ? _GEN_187 : 8'h0;
  wire [7:0] _GEN_325 = io_shamt[2] ? 8'h0 : _GEN_254;
  wire [7:0] _GEN_326 = io_shamt[2] ? _GEN_190 : 8'h0;
  wire [7:0] _GEN_327 = io_shamt[2] ? 8'h0 : _GEN_261;
  wire [7:0] _GEN_328 = io_shamt[2] ? _GEN_197 : 8'h0;
  wire [7:0] _GEN_329 = io_shamt[2] ? 8'h0 : _GEN_264;
  wire [7:0] _GEN_330 = io_shamt[2] ? _GEN_200 : 8'h0;
  wire [7:0] _GEN_331 = io_shamt[2] ? 8'h0 : _GEN_267;
  wire [7:0] _GEN_332 = io_shamt[2] ? _GEN_203 : 8'h0;
  wire [7:0] _GEN_333 = io_shamt[2] ? 8'h0 : _GEN_270;
  wire [7:0] _GEN_334 = io_shamt[2] ? _GEN_206 : 8'h0;
  assign io_out_0_valid = ~(io_shamt[2]) & _GEN_7 | io_shamt[2] & _GEN_11;
  assign io_out_0_bits_cacheData_0 = _GEN_271 | _GEN_272;
  assign io_out_0_bits_cacheData_1 = _GEN_273 | _GEN_274;
  assign io_out_0_bits_cacheData_2 = _GEN_275 | _GEN_276;
  assign io_out_0_bits_cacheData_3 = _GEN_277 | _GEN_278;
  assign io_out_0_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_143 | io_shamt[2] & _GEN_207;
  assign io_out_0_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_144 | io_shamt[2] & _GEN_208;
  assign io_out_0_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_145 | io_shamt[2] & _GEN_209;
  assign io_out_0_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_146 | io_shamt[2] & _GEN_210;
  assign io_out_1_valid = ~(io_shamt[2]) & _GEN_8 | io_shamt[2] & _GEN_12;
  assign io_out_1_bits_cacheData_0 = _GEN_279 | _GEN_280;
  assign io_out_1_bits_cacheData_1 = _GEN_281 | _GEN_282;
  assign io_out_1_bits_cacheData_2 = _GEN_283 | _GEN_284;
  assign io_out_1_bits_cacheData_3 = _GEN_285 | _GEN_286;
  assign io_out_1_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_159 | io_shamt[2] & _GEN_223;
  assign io_out_1_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_160 | io_shamt[2] & _GEN_224;
  assign io_out_1_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_161 | io_shamt[2] & _GEN_225;
  assign io_out_1_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_162 | io_shamt[2] & _GEN_226;
  assign io_out_2_valid = ~(io_shamt[2]) & _GEN_9 | io_shamt[2] & _GEN_13;
  assign io_out_2_bits_cacheData_0 = _GEN_287 | _GEN_288;
  assign io_out_2_bits_cacheData_1 = _GEN_289 | _GEN_290;
  assign io_out_2_bits_cacheData_2 = _GEN_291 | _GEN_292;
  assign io_out_2_bits_cacheData_3 = _GEN_293 | _GEN_294;
  assign io_out_2_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_175 | io_shamt[2] & _GEN_239;
  assign io_out_2_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_176 | io_shamt[2] & _GEN_240;
  assign io_out_2_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_177 | io_shamt[2] & _GEN_241;
  assign io_out_2_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_178 | io_shamt[2] & _GEN_242;
  assign io_out_3_valid = ~(io_shamt[2]) & _GEN_10 | io_shamt[2] & _GEN_14;
  assign io_out_3_bits_cacheData_0 = _GEN_295 | _GEN_296;
  assign io_out_3_bits_cacheData_1 = _GEN_297 | _GEN_298;
  assign io_out_3_bits_cacheData_2 = _GEN_299 | _GEN_300;
  assign io_out_3_bits_cacheData_3 = _GEN_301 | _GEN_302;
  assign io_out_3_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_191 | io_shamt[2] & _GEN_255;
  assign io_out_3_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_192 | io_shamt[2] & _GEN_256;
  assign io_out_3_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_193 | io_shamt[2] & _GEN_257;
  assign io_out_3_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_194 | io_shamt[2] & _GEN_258;
  assign io_out_4_valid = ~(io_shamt[2]) & _GEN_11 | io_shamt[2] & _GEN_7;
  assign io_out_4_bits_cacheData_0 = _GEN_303 | _GEN_304;
  assign io_out_4_bits_cacheData_1 = _GEN_305 | _GEN_306;
  assign io_out_4_bits_cacheData_2 = _GEN_307 | _GEN_308;
  assign io_out_4_bits_cacheData_3 = _GEN_309 | _GEN_310;
  assign io_out_4_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_207 | io_shamt[2] & _GEN_143;
  assign io_out_4_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_208 | io_shamt[2] & _GEN_144;
  assign io_out_4_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_209 | io_shamt[2] & _GEN_145;
  assign io_out_4_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_210 | io_shamt[2] & _GEN_146;
  assign io_out_5_valid = ~(io_shamt[2]) & _GEN_12 | io_shamt[2] & _GEN_8;
  assign io_out_5_bits_cacheData_0 = _GEN_311 | _GEN_312;
  assign io_out_5_bits_cacheData_1 = _GEN_313 | _GEN_314;
  assign io_out_5_bits_cacheData_2 = _GEN_315 | _GEN_316;
  assign io_out_5_bits_cacheData_3 = _GEN_317 | _GEN_318;
  assign io_out_5_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_223 | io_shamt[2] & _GEN_159;
  assign io_out_5_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_224 | io_shamt[2] & _GEN_160;
  assign io_out_5_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_225 | io_shamt[2] & _GEN_161;
  assign io_out_5_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_226 | io_shamt[2] & _GEN_162;
  assign io_out_6_valid = ~(io_shamt[2]) & _GEN_13 | io_shamt[2] & _GEN_9;
  assign io_out_6_bits_cacheData_0 = _GEN_319 | _GEN_320;
  assign io_out_6_bits_cacheData_1 = _GEN_321 | _GEN_322;
  assign io_out_6_bits_cacheData_2 = _GEN_323 | _GEN_324;
  assign io_out_6_bits_cacheData_3 = _GEN_325 | _GEN_326;
  assign io_out_6_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_239 | io_shamt[2] & _GEN_175;
  assign io_out_6_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_240 | io_shamt[2] & _GEN_176;
  assign io_out_6_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_241 | io_shamt[2] & _GEN_177;
  assign io_out_6_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_242 | io_shamt[2] & _GEN_178;
  assign io_out_7_valid = ~(io_shamt[2]) & _GEN_14 | io_shamt[2] & _GEN_10;
  assign io_out_7_bits_cacheData_0 = _GEN_327 | _GEN_328;
  assign io_out_7_bits_cacheData_1 = _GEN_329 | _GEN_330;
  assign io_out_7_bits_cacheData_2 = _GEN_331 | _GEN_332;
  assign io_out_7_bits_cacheData_3 = _GEN_333 | _GEN_334;
  assign io_out_7_bits_sqwStrobe_0 = ~(io_shamt[2]) & _GEN_255 | io_shamt[2] & _GEN_191;
  assign io_out_7_bits_sqwStrobe_1 = ~(io_shamt[2]) & _GEN_256 | io_shamt[2] & _GEN_192;
  assign io_out_7_bits_sqwStrobe_2 = ~(io_shamt[2]) & _GEN_257 | io_shamt[2] & _GEN_193;
  assign io_out_7_bits_sqwStrobe_3 = ~(io_shamt[2]) & _GEN_258 | io_shamt[2] & _GEN_194;
endmodule

