// Generated by CIRCT firtool-1.76.0
module DCRRQueue_2(
  input  wire        clock,
  input  wire        reset,
  output wire        io_in_0_ready,
  input  wire        io_in_0_valid,
  input  wire        io_in_0_bits_isBranch,
  input  wire        io_in_0_bits_isJAL,
  input  wire [1:0]  io_in_0_bits_lsType,
  input  wire [1:0]  io_in_0_bits_writeRf,
  input  wire [4:0]  io_in_0_bits_rd,
  input  wire [31:0] io_in_0_bits_pc,
  input  wire [6:0]  io_in_0_bits_rdTag,
  input  wire        io_in_0_bits_flushed,
  input  wire [6:0]  io_in_0_bits_arfTag,
  input  wire        io_in_0_bits_arfValid,
  input  wire [31:0] io_in_0_bits_inst,
  output wire        io_in_1_ready,
  input  wire        io_in_1_valid,
  input  wire        io_in_1_bits_isBranch,
  input  wire        io_in_1_bits_isJAL,
  input  wire [1:0]  io_in_1_bits_lsType,
  input  wire [1:0]  io_in_1_bits_writeRf,
  input  wire [4:0]  io_in_1_bits_rd,
  input  wire [31:0] io_in_1_bits_pc,
  input  wire [6:0]  io_in_1_bits_rdTag,
  input  wire        io_in_1_bits_flushed,
  input  wire [6:0]  io_in_1_bits_arfTag,
  input  wire        io_in_1_bits_arfValid,
  input  wire [31:0] io_in_1_bits_inst,
  output wire [4:0]  io_count_0,
  output wire [4:0]  io_count_1,
  input  wire        io_out_0_ready,
  output wire        io_out_0_valid,
  output wire        io_out_0_bits_isBranch,
  output wire        io_out_0_bits_isJAL,
  output wire [1:0]  io_out_0_bits_lsType,
  output wire [1:0]  io_out_0_bits_writeRf,
  output wire [4:0]  io_out_0_bits_rd,
  output wire [31:0] io_out_0_bits_pc,
  output wire [6:0]  io_out_0_bits_rdTag,
  output wire        io_out_0_bits_flushed,
  output wire [6:0]  io_out_0_bits_arfTag,
  output wire        io_out_0_bits_arfValid,
  output wire [31:0] io_out_0_bits_inst,
  input  wire        io_out_1_ready,
  output wire        io_out_1_valid,
  output wire        io_out_1_bits_isBranch,
  output wire        io_out_1_bits_isJAL,
  output wire [1:0]  io_out_1_bits_lsType,
  output wire [1:0]  io_out_1_bits_writeRf,
  output wire [4:0]  io_out_1_bits_rd,
  output wire [31:0] io_out_1_bits_pc,
  output wire [6:0]  io_out_1_bits_rdTag,
  output wire        io_out_1_bits_flushed,
  output wire [6:0]  io_out_1_bits_arfTag,
  output wire        io_out_1_bits_arfValid,
  output wire [31:0] io_out_1_bits_inst
);

  wire        _rrshifter_io_out_0_valid;
  wire        _rrshifter_io_out_0_bits_isBranch;
  wire        _rrshifter_io_out_0_bits_isJAL;
  wire [1:0]  _rrshifter_io_out_0_bits_lsType;
  wire [1:0]  _rrshifter_io_out_0_bits_writeRf;
  wire [4:0]  _rrshifter_io_out_0_bits_rd;
  wire [31:0] _rrshifter_io_out_0_bits_pc;
  wire [6:0]  _rrshifter_io_out_0_bits_rdTag;
  wire        _rrshifter_io_out_0_bits_flushed;
  wire [6:0]  _rrshifter_io_out_0_bits_arfTag;
  wire        _rrshifter_io_out_0_bits_arfValid;
  wire [31:0] _rrshifter_io_out_0_bits_inst;
  wire        _rrshifter_io_out_1_valid;
  wire        _rrshifter_io_out_1_bits_isBranch;
  wire        _rrshifter_io_out_1_bits_isJAL;
  wire [1:0]  _rrshifter_io_out_1_bits_lsType;
  wire [1:0]  _rrshifter_io_out_1_bits_writeRf;
  wire [4:0]  _rrshifter_io_out_1_bits_rd;
  wire [31:0] _rrshifter_io_out_1_bits_pc;
  wire [6:0]  _rrshifter_io_out_1_bits_rdTag;
  wire        _rrshifter_io_out_1_bits_flushed;
  wire [6:0]  _rrshifter_io_out_1_bits_arfTag;
  wire        _rrshifter_io_out_1_bits_arfValid;
  wire [31:0] _rrshifter_io_out_1_bits_inst;
  wire        _queues_1_io_enq_ready;
  wire        _queues_0_io_enq_ready;
  wire [1:0]  _queues_1_io_deq_ready_T = {io_out_1_ready, io_out_0_ready};
  Queue16_RetireMI queues_0 (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_queues_0_io_enq_ready),
    .io_enq_valid         (_rrshifter_io_out_0_valid),
    .io_enq_bits_isBranch (_rrshifter_io_out_0_bits_isBranch),
    .io_enq_bits_isJAL    (_rrshifter_io_out_0_bits_isJAL),
    .io_enq_bits_lsType   (_rrshifter_io_out_0_bits_lsType),
    .io_enq_bits_writeRf  (_rrshifter_io_out_0_bits_writeRf),
    .io_enq_bits_rd       (_rrshifter_io_out_0_bits_rd),
    .io_enq_bits_pc       (_rrshifter_io_out_0_bits_pc),
    .io_enq_bits_rdTag    (_rrshifter_io_out_0_bits_rdTag),
    .io_enq_bits_flushed  (_rrshifter_io_out_0_bits_flushed),
    .io_enq_bits_arfTag   (_rrshifter_io_out_0_bits_arfTag),
    .io_enq_bits_arfValid (_rrshifter_io_out_0_bits_arfValid),
    .io_enq_bits_inst     (_rrshifter_io_out_0_bits_inst),
    .io_deq_ready         (&_queues_1_io_deq_ready_T),
    .io_deq_valid         (io_out_0_valid),
    .io_deq_bits_isBranch (io_out_0_bits_isBranch),
    .io_deq_bits_isJAL    (io_out_0_bits_isJAL),
    .io_deq_bits_lsType   (io_out_0_bits_lsType),
    .io_deq_bits_writeRf  (io_out_0_bits_writeRf),
    .io_deq_bits_rd       (io_out_0_bits_rd),
    .io_deq_bits_pc       (io_out_0_bits_pc),
    .io_deq_bits_rdTag    (io_out_0_bits_rdTag),
    .io_deq_bits_flushed  (io_out_0_bits_flushed),
    .io_deq_bits_arfTag   (io_out_0_bits_arfTag),
    .io_deq_bits_arfValid (io_out_0_bits_arfValid),
    .io_deq_bits_inst     (io_out_0_bits_inst),
    .io_count             (io_count_0)
  );
  Queue16_RetireMI queues_1 (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_queues_1_io_enq_ready),
    .io_enq_valid         (_rrshifter_io_out_1_valid),
    .io_enq_bits_isBranch (_rrshifter_io_out_1_bits_isBranch),
    .io_enq_bits_isJAL    (_rrshifter_io_out_1_bits_isJAL),
    .io_enq_bits_lsType   (_rrshifter_io_out_1_bits_lsType),
    .io_enq_bits_writeRf  (_rrshifter_io_out_1_bits_writeRf),
    .io_enq_bits_rd       (_rrshifter_io_out_1_bits_rd),
    .io_enq_bits_pc       (_rrshifter_io_out_1_bits_pc),
    .io_enq_bits_rdTag    (_rrshifter_io_out_1_bits_rdTag),
    .io_enq_bits_flushed  (_rrshifter_io_out_1_bits_flushed),
    .io_enq_bits_arfTag   (_rrshifter_io_out_1_bits_arfTag),
    .io_enq_bits_arfValid (_rrshifter_io_out_1_bits_arfValid),
    .io_enq_bits_inst     (_rrshifter_io_out_1_bits_inst),
    .io_deq_ready         (&_queues_1_io_deq_ready_T),
    .io_deq_valid         (io_out_1_valid),
    .io_deq_bits_isBranch (io_out_1_bits_isBranch),
    .io_deq_bits_isJAL    (io_out_1_bits_isJAL),
    .io_deq_bits_lsType   (io_out_1_bits_lsType),
    .io_deq_bits_writeRf  (io_out_1_bits_writeRf),
    .io_deq_bits_rd       (io_out_1_bits_rd),
    .io_deq_bits_pc       (io_out_1_bits_pc),
    .io_deq_bits_rdTag    (io_out_1_bits_rdTag),
    .io_deq_bits_flushed  (io_out_1_bits_flushed),
    .io_deq_bits_arfTag   (io_out_1_bits_arfTag),
    .io_deq_bits_arfValid (io_out_1_bits_arfValid),
    .io_deq_bits_inst     (io_out_1_bits_inst),
    .io_count             (io_count_1)
  );
  DCRRShifter_3 rrshifter (
    .clock                  (clock),
    .reset                  (reset),
    .io_in_0_ready          (io_in_0_ready),
    .io_in_0_valid          (io_in_0_valid),
    .io_in_0_bits_isBranch  (io_in_0_bits_isBranch),
    .io_in_0_bits_isJAL     (io_in_0_bits_isJAL),
    .io_in_0_bits_lsType    (io_in_0_bits_lsType),
    .io_in_0_bits_writeRf   (io_in_0_bits_writeRf),
    .io_in_0_bits_rd        (io_in_0_bits_rd),
    .io_in_0_bits_pc        (io_in_0_bits_pc),
    .io_in_0_bits_rdTag     (io_in_0_bits_rdTag),
    .io_in_0_bits_flushed   (io_in_0_bits_flushed),
    .io_in_0_bits_arfTag    (io_in_0_bits_arfTag),
    .io_in_0_bits_arfValid  (io_in_0_bits_arfValid),
    .io_in_0_bits_inst      (io_in_0_bits_inst),
    .io_in_1_ready          (io_in_1_ready),
    .io_in_1_valid          (io_in_1_valid),
    .io_in_1_bits_isBranch  (io_in_1_bits_isBranch),
    .io_in_1_bits_isJAL     (io_in_1_bits_isJAL),
    .io_in_1_bits_lsType    (io_in_1_bits_lsType),
    .io_in_1_bits_writeRf   (io_in_1_bits_writeRf),
    .io_in_1_bits_rd        (io_in_1_bits_rd),
    .io_in_1_bits_pc        (io_in_1_bits_pc),
    .io_in_1_bits_rdTag     (io_in_1_bits_rdTag),
    .io_in_1_bits_flushed   (io_in_1_bits_flushed),
    .io_in_1_bits_arfTag    (io_in_1_bits_arfTag),
    .io_in_1_bits_arfValid  (io_in_1_bits_arfValid),
    .io_in_1_bits_inst      (io_in_1_bits_inst),
    .io_out_0_ready         (_queues_0_io_enq_ready),
    .io_out_0_valid         (_rrshifter_io_out_0_valid),
    .io_out_0_bits_isBranch (_rrshifter_io_out_0_bits_isBranch),
    .io_out_0_bits_isJAL    (_rrshifter_io_out_0_bits_isJAL),
    .io_out_0_bits_lsType   (_rrshifter_io_out_0_bits_lsType),
    .io_out_0_bits_writeRf  (_rrshifter_io_out_0_bits_writeRf),
    .io_out_0_bits_rd       (_rrshifter_io_out_0_bits_rd),
    .io_out_0_bits_pc       (_rrshifter_io_out_0_bits_pc),
    .io_out_0_bits_rdTag    (_rrshifter_io_out_0_bits_rdTag),
    .io_out_0_bits_flushed  (_rrshifter_io_out_0_bits_flushed),
    .io_out_0_bits_arfTag   (_rrshifter_io_out_0_bits_arfTag),
    .io_out_0_bits_arfValid (_rrshifter_io_out_0_bits_arfValid),
    .io_out_0_bits_inst     (_rrshifter_io_out_0_bits_inst),
    .io_out_1_ready         (_queues_1_io_enq_ready),
    .io_out_1_valid         (_rrshifter_io_out_1_valid),
    .io_out_1_bits_isBranch (_rrshifter_io_out_1_bits_isBranch),
    .io_out_1_bits_isJAL    (_rrshifter_io_out_1_bits_isJAL),
    .io_out_1_bits_lsType   (_rrshifter_io_out_1_bits_lsType),
    .io_out_1_bits_writeRf  (_rrshifter_io_out_1_bits_writeRf),
    .io_out_1_bits_rd       (_rrshifter_io_out_1_bits_rd),
    .io_out_1_bits_pc       (_rrshifter_io_out_1_bits_pc),
    .io_out_1_bits_rdTag    (_rrshifter_io_out_1_bits_rdTag),
    .io_out_1_bits_flushed  (_rrshifter_io_out_1_bits_flushed),
    .io_out_1_bits_arfTag   (_rrshifter_io_out_1_bits_arfTag),
    .io_out_1_bits_arfValid (_rrshifter_io_out_1_bits_arfValid),
    .io_out_1_bits_inst     (_rrshifter_io_out_1_bits_inst)
  );
endmodule

