// Generated by CIRCT firtool-1.76.0
module ExecuteStage(
  input  wire        clock,
  input  wire        reset,
  output wire        io_aluIn_0_ready,
  input  wire        io_aluIn_0_valid,
  input  wire        io_aluIn_0_bits_retired,
  input  wire [6:0]  io_aluIn_0_bits_rdTag,
  input  wire        io_aluIn_0_bits_isBranch,
  input  wire        io_aluIn_0_bits_isJAL,
  input  wire [1:0]  io_aluIn_0_bits_lsType,
  input  wire        io_aluIn_0_bits_wakeup,
  input  wire [1:0]  io_aluIn_0_bits_opsrc1,
  input  wire [1:0]  io_aluIn_0_bits_opsrc2,
  input  wire [1:0]  io_aluIn_0_bits_writeRf,
  input  wire [2:0]  io_aluIn_0_bits_exEngine,
  input  wire [5:0]  io_aluIn_0_bits_exOp,
  input  wire [5:0]  io_aluIn_0_bits_lsOp,
  input  wire        io_aluIn_0_bits_exception,
  input  wire        io_aluIn_0_bits_taken,
  input  wire [31:0] io_aluIn_0_bits_imm,
  input  wire [4:0]  io_aluIn_0_bits_rs1,
  input  wire [4:0]  io_aluIn_0_bits_rs2,
  input  wire [4:0]  io_aluIn_0_bits_rd,
  input  wire [31:0] io_aluIn_0_bits_pc,
  input  wire [6:0]  io_aluIn_0_bits_rs1Tag,
  input  wire        io_aluIn_0_bits_rs1TagReady,
  input  wire [6:0]  io_aluIn_0_bits_rs2Tag,
  input  wire        io_aluIn_0_bits_rs2TagReady,
  input  wire [31:0] io_aluIn_0_bits_rs1Data,
  input  wire [31:0] io_aluIn_0_bits_rs2Data,
  input  wire        io_aluIn_0_bits_operandReady,
  input  wire        io_aluIn_0_bits_flushed,
  input  wire [6:0]  io_aluIn_0_bits_arfTag,
  input  wire        io_aluIn_0_bits_arfValid,
  input  wire [31:0] io_aluIn_0_bits_inst,
  output wire        io_aluIn_1_ready,
  input  wire        io_aluIn_1_valid,
  input  wire        io_aluIn_1_bits_retired,
  input  wire [6:0]  io_aluIn_1_bits_rdTag,
  input  wire        io_aluIn_1_bits_isBranch,
  input  wire        io_aluIn_1_bits_isJAL,
  input  wire [1:0]  io_aluIn_1_bits_lsType,
  input  wire        io_aluIn_1_bits_wakeup,
  input  wire [1:0]  io_aluIn_1_bits_opsrc1,
  input  wire [1:0]  io_aluIn_1_bits_opsrc2,
  input  wire [1:0]  io_aluIn_1_bits_writeRf,
  input  wire [2:0]  io_aluIn_1_bits_exEngine,
  input  wire [5:0]  io_aluIn_1_bits_exOp,
  input  wire [5:0]  io_aluIn_1_bits_lsOp,
  input  wire        io_aluIn_1_bits_exception,
  input  wire        io_aluIn_1_bits_taken,
  input  wire [31:0] io_aluIn_1_bits_imm,
  input  wire [4:0]  io_aluIn_1_bits_rs1,
  input  wire [4:0]  io_aluIn_1_bits_rs2,
  input  wire [4:0]  io_aluIn_1_bits_rd,
  input  wire [31:0] io_aluIn_1_bits_pc,
  input  wire [6:0]  io_aluIn_1_bits_rs1Tag,
  input  wire        io_aluIn_1_bits_rs1TagReady,
  input  wire [6:0]  io_aluIn_1_bits_rs2Tag,
  input  wire        io_aluIn_1_bits_rs2TagReady,
  input  wire [31:0] io_aluIn_1_bits_rs1Data,
  input  wire [31:0] io_aluIn_1_bits_rs2Data,
  input  wire        io_aluIn_1_bits_operandReady,
  input  wire        io_aluIn_1_bits_flushed,
  input  wire [6:0]  io_aluIn_1_bits_arfTag,
  input  wire        io_aluIn_1_bits_arfValid,
  input  wire [31:0] io_aluIn_1_bits_inst,
  input  wire        io_flush,
  output wire        io_imuIn_0_ready,
  input  wire        io_imuIn_0_valid,
  input  wire        io_imuIn_0_bits_retired,
  input  wire [6:0]  io_imuIn_0_bits_rdTag,
  input  wire        io_imuIn_0_bits_isBranch,
  input  wire        io_imuIn_0_bits_isJAL,
  input  wire [1:0]  io_imuIn_0_bits_lsType,
  input  wire        io_imuIn_0_bits_wakeup,
  input  wire [1:0]  io_imuIn_0_bits_opsrc1,
  input  wire [1:0]  io_imuIn_0_bits_opsrc2,
  input  wire [1:0]  io_imuIn_0_bits_writeRf,
  input  wire [2:0]  io_imuIn_0_bits_exEngine,
  input  wire [5:0]  io_imuIn_0_bits_exOp,
  input  wire [5:0]  io_imuIn_0_bits_lsOp,
  input  wire        io_imuIn_0_bits_exception,
  input  wire        io_imuIn_0_bits_taken,
  input  wire [31:0] io_imuIn_0_bits_imm,
  input  wire [4:0]  io_imuIn_0_bits_rs1,
  input  wire [4:0]  io_imuIn_0_bits_rs2,
  input  wire [4:0]  io_imuIn_0_bits_rd,
  input  wire [31:0] io_imuIn_0_bits_pc,
  input  wire [31:0] io_imuIn_0_bits_targetPC,
  input  wire [6:0]  io_imuIn_0_bits_rs1Tag,
  input  wire        io_imuIn_0_bits_rs1TagReady,
  input  wire [6:0]  io_imuIn_0_bits_rs2Tag,
  input  wire        io_imuIn_0_bits_rs2TagReady,
  input  wire [31:0] io_imuIn_0_bits_rs1Data,
  input  wire [31:0] io_imuIn_0_bits_rs2Data,
  input  wire        io_imuIn_0_bits_operandReady,
  input  wire        io_imuIn_0_bits_flushed,
  input  wire [6:0]  io_imuIn_0_bits_arfTag,
  input  wire        io_imuIn_0_bits_arfValid,
  input  wire [31:0] io_imuIn_0_bits_inst,
  output wire        io_iduIn_0_ready,
  input  wire        io_iduIn_0_valid,
  input  wire        io_iduIn_0_bits_retired,
  input  wire [6:0]  io_iduIn_0_bits_rdTag,
  input  wire        io_iduIn_0_bits_isBranch,
  input  wire        io_iduIn_0_bits_isJAL,
  input  wire [1:0]  io_iduIn_0_bits_lsType,
  input  wire        io_iduIn_0_bits_wakeup,
  input  wire [1:0]  io_iduIn_0_bits_opsrc1,
  input  wire [1:0]  io_iduIn_0_bits_opsrc2,
  input  wire [1:0]  io_iduIn_0_bits_writeRf,
  input  wire [2:0]  io_iduIn_0_bits_exEngine,
  input  wire [5:0]  io_iduIn_0_bits_exOp,
  input  wire [5:0]  io_iduIn_0_bits_lsOp,
  input  wire        io_iduIn_0_bits_exception,
  input  wire        io_iduIn_0_bits_taken,
  input  wire [31:0] io_iduIn_0_bits_imm,
  input  wire [4:0]  io_iduIn_0_bits_rs1,
  input  wire [4:0]  io_iduIn_0_bits_rs2,
  input  wire [4:0]  io_iduIn_0_bits_rd,
  input  wire [31:0] io_iduIn_0_bits_pc,
  input  wire [31:0] io_iduIn_0_bits_targetPC,
  input  wire [6:0]  io_iduIn_0_bits_rs1Tag,
  input  wire        io_iduIn_0_bits_rs1TagReady,
  input  wire [6:0]  io_iduIn_0_bits_rs2Tag,
  input  wire        io_iduIn_0_bits_rs2TagReady,
  input  wire [31:0] io_iduIn_0_bits_rs1Data,
  input  wire [31:0] io_iduIn_0_bits_rs2Data,
  input  wire        io_iduIn_0_bits_operandReady,
  input  wire        io_iduIn_0_bits_flushed,
  input  wire [6:0]  io_iduIn_0_bits_arfTag,
  input  wire        io_iduIn_0_bits_arfValid,
  input  wire [31:0] io_iduIn_0_bits_inst,
  output wire        io_csrIn_0_ready,
  input  wire        io_csrIn_0_valid,
  input  wire        io_csrIn_0_bits_flushed,
  output wire        io_forwardBus_0_valid,
  output wire [6:0]  io_forwardBus_0_bits_tag,
  output wire [31:0] io_forwardBus_0_bits_data,
  output wire        io_forwardBus_1_valid,
  output wire [6:0]  io_forwardBus_1_bits_tag,
  output wire [31:0] io_forwardBus_1_bits_data,
  output wire        io_out_0_valid,
  output wire [6:0]  io_out_0_bits_rdTag,
  output wire [1:0]  io_out_0_bits_lsType,
  output wire        io_out_0_bits_exception,
  output wire        io_out_0_bits_taken,
  output wire [31:0] io_out_0_bits_pc,
  output wire [31:0] io_out_0_bits_targetPC,
  output wire [31:0] io_out_0_bits_rs2Data,
  output wire [31:0] io_out_0_bits_rdData,
  output wire [31:0] io_out_0_bits_inst,
  output wire        io_out_1_valid,
  output wire [6:0]  io_out_1_bits_rdTag,
  output wire [1:0]  io_out_1_bits_lsType,
  output wire        io_out_1_bits_exception,
  output wire        io_out_1_bits_taken,
  output wire [31:0] io_out_1_bits_pc,
  output wire [31:0] io_out_1_bits_targetPC,
  output wire [31:0] io_out_1_bits_rs2Data,
  output wire [31:0] io_out_1_bits_rdData,
  output wire [31:0] io_out_1_bits_inst
);

  wire        _idus_0_io_out_valid;
  wire        _idus_0_io_out_bits_retired;
  wire [6:0]  _idus_0_io_out_bits_rdTag;
  wire        _idus_0_io_out_bits_isBranch;
  wire        _idus_0_io_out_bits_isJAL;
  wire [1:0]  _idus_0_io_out_bits_lsType;
  wire        _idus_0_io_out_bits_wakeup;
  wire [1:0]  _idus_0_io_out_bits_opsrc1;
  wire [1:0]  _idus_0_io_out_bits_opsrc2;
  wire [1:0]  _idus_0_io_out_bits_writeRf;
  wire [2:0]  _idus_0_io_out_bits_exEngine;
  wire [5:0]  _idus_0_io_out_bits_exOp;
  wire [5:0]  _idus_0_io_out_bits_lsOp;
  wire        _idus_0_io_out_bits_exception;
  wire        _idus_0_io_out_bits_taken;
  wire [31:0] _idus_0_io_out_bits_imm;
  wire [4:0]  _idus_0_io_out_bits_rs1;
  wire [4:0]  _idus_0_io_out_bits_rs2;
  wire [4:0]  _idus_0_io_out_bits_rd;
  wire [31:0] _idus_0_io_out_bits_pc;
  wire [31:0] _idus_0_io_out_bits_targetPC;
  wire [6:0]  _idus_0_io_out_bits_rs1Tag;
  wire        _idus_0_io_out_bits_rs1TagReady;
  wire [6:0]  _idus_0_io_out_bits_rs2Tag;
  wire        _idus_0_io_out_bits_rs2TagReady;
  wire [31:0] _idus_0_io_out_bits_rs1Data;
  wire [31:0] _idus_0_io_out_bits_rs2Data;
  wire [31:0] _idus_0_io_out_bits_rdData;
  wire        _idus_0_io_out_bits_operandReady;
  wire        _idus_0_io_out_bits_flushed;
  wire [6:0]  _idus_0_io_out_bits_arfTag;
  wire        _idus_0_io_out_bits_arfValid;
  wire [31:0] _idus_0_io_out_bits_inst;
  wire        _imus_0_io_out_valid;
  wire        _imus_0_io_out_bits_retired;
  wire [6:0]  _imus_0_io_out_bits_rdTag;
  wire        _imus_0_io_out_bits_isBranch;
  wire        _imus_0_io_out_bits_isJAL;
  wire [1:0]  _imus_0_io_out_bits_lsType;
  wire        _imus_0_io_out_bits_wakeup;
  wire [1:0]  _imus_0_io_out_bits_opsrc1;
  wire [1:0]  _imus_0_io_out_bits_opsrc2;
  wire [1:0]  _imus_0_io_out_bits_writeRf;
  wire [2:0]  _imus_0_io_out_bits_exEngine;
  wire [5:0]  _imus_0_io_out_bits_exOp;
  wire [5:0]  _imus_0_io_out_bits_lsOp;
  wire        _imus_0_io_out_bits_exception;
  wire        _imus_0_io_out_bits_taken;
  wire [31:0] _imus_0_io_out_bits_imm;
  wire [4:0]  _imus_0_io_out_bits_rs1;
  wire [4:0]  _imus_0_io_out_bits_rs2;
  wire [4:0]  _imus_0_io_out_bits_rd;
  wire [31:0] _imus_0_io_out_bits_pc;
  wire [31:0] _imus_0_io_out_bits_targetPC;
  wire [6:0]  _imus_0_io_out_bits_rs1Tag;
  wire        _imus_0_io_out_bits_rs1TagReady;
  wire [6:0]  _imus_0_io_out_bits_rs2Tag;
  wire        _imus_0_io_out_bits_rs2TagReady;
  wire [31:0] _imus_0_io_out_bits_rs1Data;
  wire [31:0] _imus_0_io_out_bits_rs2Data;
  wire [31:0] _imus_0_io_out_bits_rdData;
  wire        _imus_0_io_out_bits_operandReady;
  wire        _imus_0_io_out_bits_flushed;
  wire [6:0]  _imus_0_io_out_bits_arfTag;
  wire        _imus_0_io_out_bits_arfValid;
  wire [31:0] _imus_0_io_out_bits_inst;
  wire        _alus_1_io_out_valid;
  wire        _alus_1_io_out_bits_retired;
  wire [6:0]  _alus_1_io_out_bits_rdTag;
  wire        _alus_1_io_out_bits_isBranch;
  wire        _alus_1_io_out_bits_isJAL;
  wire [1:0]  _alus_1_io_out_bits_lsType;
  wire        _alus_1_io_out_bits_wakeup;
  wire [1:0]  _alus_1_io_out_bits_opsrc1;
  wire [1:0]  _alus_1_io_out_bits_opsrc2;
  wire [1:0]  _alus_1_io_out_bits_writeRf;
  wire [2:0]  _alus_1_io_out_bits_exEngine;
  wire [5:0]  _alus_1_io_out_bits_exOp;
  wire [5:0]  _alus_1_io_out_bits_lsOp;
  wire        _alus_1_io_out_bits_exception;
  wire        _alus_1_io_out_bits_taken;
  wire [31:0] _alus_1_io_out_bits_imm;
  wire [4:0]  _alus_1_io_out_bits_rs1;
  wire [4:0]  _alus_1_io_out_bits_rs2;
  wire [4:0]  _alus_1_io_out_bits_rd;
  wire [31:0] _alus_1_io_out_bits_pc;
  wire [31:0] _alus_1_io_out_bits_targetPC;
  wire [6:0]  _alus_1_io_out_bits_rs1Tag;
  wire        _alus_1_io_out_bits_rs1TagReady;
  wire [6:0]  _alus_1_io_out_bits_rs2Tag;
  wire        _alus_1_io_out_bits_rs2TagReady;
  wire [31:0] _alus_1_io_out_bits_rs1Data;
  wire [31:0] _alus_1_io_out_bits_rs2Data;
  wire [31:0] _alus_1_io_out_bits_rdData;
  wire        _alus_1_io_out_bits_operandReady;
  wire        _alus_1_io_out_bits_flushed;
  wire [6:0]  _alus_1_io_out_bits_arfTag;
  wire        _alus_1_io_out_bits_arfValid;
  wire [31:0] _alus_1_io_out_bits_inst;
  wire        _alus_0_io_out_valid;
  wire        _alus_0_io_out_bits_retired;
  wire [6:0]  _alus_0_io_out_bits_rdTag;
  wire        _alus_0_io_out_bits_isBranch;
  wire        _alus_0_io_out_bits_isJAL;
  wire [1:0]  _alus_0_io_out_bits_lsType;
  wire        _alus_0_io_out_bits_wakeup;
  wire [1:0]  _alus_0_io_out_bits_opsrc1;
  wire [1:0]  _alus_0_io_out_bits_opsrc2;
  wire [1:0]  _alus_0_io_out_bits_writeRf;
  wire [2:0]  _alus_0_io_out_bits_exEngine;
  wire [5:0]  _alus_0_io_out_bits_exOp;
  wire [5:0]  _alus_0_io_out_bits_lsOp;
  wire        _alus_0_io_out_bits_exception;
  wire        _alus_0_io_out_bits_taken;
  wire [31:0] _alus_0_io_out_bits_imm;
  wire [4:0]  _alus_0_io_out_bits_rs1;
  wire [4:0]  _alus_0_io_out_bits_rs2;
  wire [4:0]  _alus_0_io_out_bits_rd;
  wire [31:0] _alus_0_io_out_bits_pc;
  wire [31:0] _alus_0_io_out_bits_targetPC;
  wire [6:0]  _alus_0_io_out_bits_rs1Tag;
  wire        _alus_0_io_out_bits_rs1TagReady;
  wire [6:0]  _alus_0_io_out_bits_rs2Tag;
  wire        _alus_0_io_out_bits_rs2TagReady;
  wire [31:0] _alus_0_io_out_bits_rs1Data;
  wire [31:0] _alus_0_io_out_bits_rs2Data;
  wire [31:0] _alus_0_io_out_bits_rdData;
  wire        _alus_0_io_out_bits_operandReady;
  wire        _alus_0_io_out_bits_flushed;
  wire [6:0]  _alus_0_io_out_bits_arfTag;
  wire        _alus_0_io_out_bits_arfValid;
  wire [31:0] _alus_0_io_out_bits_inst;
  wire        _arbiter_io_in_0_ready;
  wire        _arbiter_io_in_1_ready;
  wire        _arbiter_io_in_2_ready;
  wire        _arbiter_io_in_3_ready;
  wire        _arbiter_io_out_0_valid;
  wire        _arbiter_io_out_0_bits_retired;
  wire [6:0]  _arbiter_io_out_0_bits_rdTag;
  wire        _arbiter_io_out_0_bits_isBranch;
  wire        _arbiter_io_out_0_bits_isJAL;
  wire [1:0]  _arbiter_io_out_0_bits_lsType;
  wire        _arbiter_io_out_0_bits_wakeup;
  wire [1:0]  _arbiter_io_out_0_bits_opsrc1;
  wire [1:0]  _arbiter_io_out_0_bits_opsrc2;
  wire [1:0]  _arbiter_io_out_0_bits_writeRf;
  wire [2:0]  _arbiter_io_out_0_bits_exEngine;
  wire [5:0]  _arbiter_io_out_0_bits_exOp;
  wire [5:0]  _arbiter_io_out_0_bits_lsOp;
  wire        _arbiter_io_out_0_bits_exception;
  wire        _arbiter_io_out_0_bits_taken;
  wire [31:0] _arbiter_io_out_0_bits_imm;
  wire [4:0]  _arbiter_io_out_0_bits_rs1;
  wire [4:0]  _arbiter_io_out_0_bits_rs2;
  wire [4:0]  _arbiter_io_out_0_bits_rd;
  wire [31:0] _arbiter_io_out_0_bits_pc;
  wire [31:0] _arbiter_io_out_0_bits_targetPC;
  wire [6:0]  _arbiter_io_out_0_bits_rs1Tag;
  wire        _arbiter_io_out_0_bits_rs1TagReady;
  wire [6:0]  _arbiter_io_out_0_bits_rs2Tag;
  wire        _arbiter_io_out_0_bits_rs2TagReady;
  wire [31:0] _arbiter_io_out_0_bits_rs1Data;
  wire [31:0] _arbiter_io_out_0_bits_rs2Data;
  wire [31:0] _arbiter_io_out_0_bits_rdData;
  wire        _arbiter_io_out_0_bits_operandReady;
  wire        _arbiter_io_out_0_bits_flushed;
  wire [6:0]  _arbiter_io_out_0_bits_arfTag;
  wire        _arbiter_io_out_0_bits_arfValid;
  wire [31:0] _arbiter_io_out_0_bits_inst;
  wire        _arbiter_io_out_1_valid;
  wire        _arbiter_io_out_1_bits_retired;
  wire [6:0]  _arbiter_io_out_1_bits_rdTag;
  wire        _arbiter_io_out_1_bits_isBranch;
  wire        _arbiter_io_out_1_bits_isJAL;
  wire [1:0]  _arbiter_io_out_1_bits_lsType;
  wire        _arbiter_io_out_1_bits_wakeup;
  wire [1:0]  _arbiter_io_out_1_bits_opsrc1;
  wire [1:0]  _arbiter_io_out_1_bits_opsrc2;
  wire [1:0]  _arbiter_io_out_1_bits_writeRf;
  wire [2:0]  _arbiter_io_out_1_bits_exEngine;
  wire [5:0]  _arbiter_io_out_1_bits_exOp;
  wire [5:0]  _arbiter_io_out_1_bits_lsOp;
  wire        _arbiter_io_out_1_bits_exception;
  wire        _arbiter_io_out_1_bits_taken;
  wire [31:0] _arbiter_io_out_1_bits_imm;
  wire [4:0]  _arbiter_io_out_1_bits_rs1;
  wire [4:0]  _arbiter_io_out_1_bits_rs2;
  wire [4:0]  _arbiter_io_out_1_bits_rd;
  wire [31:0] _arbiter_io_out_1_bits_pc;
  wire [31:0] _arbiter_io_out_1_bits_targetPC;
  wire [6:0]  _arbiter_io_out_1_bits_rs1Tag;
  wire        _arbiter_io_out_1_bits_rs1TagReady;
  wire [6:0]  _arbiter_io_out_1_bits_rs2Tag;
  wire        _arbiter_io_out_1_bits_rs2TagReady;
  wire [31:0] _arbiter_io_out_1_bits_rs1Data;
  wire [31:0] _arbiter_io_out_1_bits_rs2Data;
  wire [31:0] _arbiter_io_out_1_bits_rdData;
  wire        _arbiter_io_out_1_bits_operandReady;
  wire        _arbiter_io_out_1_bits_flushed;
  wire [6:0]  _arbiter_io_out_1_bits_arfTag;
  wire        _arbiter_io_out_1_bits_arfValid;
  wire [31:0] _arbiter_io_out_1_bits_inst;
  wire        _pRegs_1_io_in_ready;
  wire        _pRegs_0_io_in_ready;
  WoodMIPipelineRegister pRegs_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_ready              (_pRegs_0_io_in_ready),
    .io_in_valid              (_arbiter_io_out_0_valid),
    .io_in_bits_retired       (_arbiter_io_out_0_bits_retired),
    .io_in_bits_rdTag         (_arbiter_io_out_0_bits_rdTag),
    .io_in_bits_isBranch      (_arbiter_io_out_0_bits_isBranch),
    .io_in_bits_isJAL         (_arbiter_io_out_0_bits_isJAL),
    .io_in_bits_lsType        (_arbiter_io_out_0_bits_lsType),
    .io_in_bits_wakeup        (_arbiter_io_out_0_bits_wakeup),
    .io_in_bits_opsrc1        (_arbiter_io_out_0_bits_opsrc1),
    .io_in_bits_opsrc2        (_arbiter_io_out_0_bits_opsrc2),
    .io_in_bits_writeRf       (_arbiter_io_out_0_bits_writeRf),
    .io_in_bits_exEngine      (_arbiter_io_out_0_bits_exEngine),
    .io_in_bits_exOp          (_arbiter_io_out_0_bits_exOp),
    .io_in_bits_lsOp          (_arbiter_io_out_0_bits_lsOp),
    .io_in_bits_exception     (_arbiter_io_out_0_bits_exception),
    .io_in_bits_taken         (_arbiter_io_out_0_bits_taken),
    .io_in_bits_imm           (_arbiter_io_out_0_bits_imm),
    .io_in_bits_rs1           (_arbiter_io_out_0_bits_rs1),
    .io_in_bits_rs2           (_arbiter_io_out_0_bits_rs2),
    .io_in_bits_rd            (_arbiter_io_out_0_bits_rd),
    .io_in_bits_pc            (_arbiter_io_out_0_bits_pc),
    .io_in_bits_targetPC      (_arbiter_io_out_0_bits_targetPC),
    .io_in_bits_rs1Tag        (_arbiter_io_out_0_bits_rs1Tag),
    .io_in_bits_rs1TagReady   (_arbiter_io_out_0_bits_rs1TagReady),
    .io_in_bits_rs2Tag        (_arbiter_io_out_0_bits_rs2Tag),
    .io_in_bits_rs2TagReady   (_arbiter_io_out_0_bits_rs2TagReady),
    .io_in_bits_rs1Data       (_arbiter_io_out_0_bits_rs1Data),
    .io_in_bits_rs2Data       (_arbiter_io_out_0_bits_rs2Data),
    .io_in_bits_rdData        (_arbiter_io_out_0_bits_rdData),
    .io_in_bits_operandReady  (_arbiter_io_out_0_bits_operandReady),
    .io_in_bits_flushed       (_arbiter_io_out_0_bits_flushed),
    .io_in_bits_arfTag        (_arbiter_io_out_0_bits_arfTag),
    .io_in_bits_arfValid      (_arbiter_io_out_0_bits_arfValid),
    .io_in_bits_inst          (_arbiter_io_out_0_bits_inst),
    .io_flush                 (io_flush),
    .io_setflushed            (io_flush),
    .io_valids_0              (_arbiter_io_out_0_valid),
    .io_out_ready             (1'h1),
    .io_out_valid             (io_out_0_valid),
    .io_out_bits_retired      (/* unused */),
    .io_out_bits_rdTag        (io_out_0_bits_rdTag),
    .io_out_bits_isBranch     (/* unused */),
    .io_out_bits_isJAL        (/* unused */),
    .io_out_bits_lsType       (io_out_0_bits_lsType),
    .io_out_bits_wakeup       (/* unused */),
    .io_out_bits_opsrc1       (/* unused */),
    .io_out_bits_opsrc2       (/* unused */),
    .io_out_bits_writeRf      (/* unused */),
    .io_out_bits_exEngine     (/* unused */),
    .io_out_bits_exOp         (/* unused */),
    .io_out_bits_lsOp         (/* unused */),
    .io_out_bits_exception    (io_out_0_bits_exception),
    .io_out_bits_taken        (io_out_0_bits_taken),
    .io_out_bits_imm          (/* unused */),
    .io_out_bits_rs1          (/* unused */),
    .io_out_bits_rs2          (/* unused */),
    .io_out_bits_rd           (/* unused */),
    .io_out_bits_pc           (io_out_0_bits_pc),
    .io_out_bits_targetPC     (io_out_0_bits_targetPC),
    .io_out_bits_rs1Tag       (/* unused */),
    .io_out_bits_rs1TagReady  (/* unused */),
    .io_out_bits_rs2Tag       (/* unused */),
    .io_out_bits_rs2TagReady  (/* unused */),
    .io_out_bits_rs1Data      (/* unused */),
    .io_out_bits_rs2Data      (io_out_0_bits_rs2Data),
    .io_out_bits_rdData       (io_out_0_bits_rdData),
    .io_out_bits_operandReady (/* unused */),
    .io_out_bits_flushed      (/* unused */),
    .io_out_bits_arfTag       (/* unused */),
    .io_out_bits_arfValid     (/* unused */),
    .io_out_bits_inst         (io_out_0_bits_inst)
  );
  WoodMIPipelineRegister pRegs_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_ready              (_pRegs_1_io_in_ready),
    .io_in_valid              (_arbiter_io_out_1_valid),
    .io_in_bits_retired       (_arbiter_io_out_1_bits_retired),
    .io_in_bits_rdTag         (_arbiter_io_out_1_bits_rdTag),
    .io_in_bits_isBranch      (_arbiter_io_out_1_bits_isBranch),
    .io_in_bits_isJAL         (_arbiter_io_out_1_bits_isJAL),
    .io_in_bits_lsType        (_arbiter_io_out_1_bits_lsType),
    .io_in_bits_wakeup        (_arbiter_io_out_1_bits_wakeup),
    .io_in_bits_opsrc1        (_arbiter_io_out_1_bits_opsrc1),
    .io_in_bits_opsrc2        (_arbiter_io_out_1_bits_opsrc2),
    .io_in_bits_writeRf       (_arbiter_io_out_1_bits_writeRf),
    .io_in_bits_exEngine      (_arbiter_io_out_1_bits_exEngine),
    .io_in_bits_exOp          (_arbiter_io_out_1_bits_exOp),
    .io_in_bits_lsOp          (_arbiter_io_out_1_bits_lsOp),
    .io_in_bits_exception     (_arbiter_io_out_1_bits_exception),
    .io_in_bits_taken         (_arbiter_io_out_1_bits_taken),
    .io_in_bits_imm           (_arbiter_io_out_1_bits_imm),
    .io_in_bits_rs1           (_arbiter_io_out_1_bits_rs1),
    .io_in_bits_rs2           (_arbiter_io_out_1_bits_rs2),
    .io_in_bits_rd            (_arbiter_io_out_1_bits_rd),
    .io_in_bits_pc            (_arbiter_io_out_1_bits_pc),
    .io_in_bits_targetPC      (_arbiter_io_out_1_bits_targetPC),
    .io_in_bits_rs1Tag        (_arbiter_io_out_1_bits_rs1Tag),
    .io_in_bits_rs1TagReady   (_arbiter_io_out_1_bits_rs1TagReady),
    .io_in_bits_rs2Tag        (_arbiter_io_out_1_bits_rs2Tag),
    .io_in_bits_rs2TagReady   (_arbiter_io_out_1_bits_rs2TagReady),
    .io_in_bits_rs1Data       (_arbiter_io_out_1_bits_rs1Data),
    .io_in_bits_rs2Data       (_arbiter_io_out_1_bits_rs2Data),
    .io_in_bits_rdData        (_arbiter_io_out_1_bits_rdData),
    .io_in_bits_operandReady  (_arbiter_io_out_1_bits_operandReady),
    .io_in_bits_flushed       (_arbiter_io_out_1_bits_flushed),
    .io_in_bits_arfTag        (_arbiter_io_out_1_bits_arfTag),
    .io_in_bits_arfValid      (_arbiter_io_out_1_bits_arfValid),
    .io_in_bits_inst          (_arbiter_io_out_1_bits_inst),
    .io_flush                 (io_flush),
    .io_setflushed            (io_flush),
    .io_valids_0              (_arbiter_io_out_1_valid),
    .io_out_ready             (1'h1),
    .io_out_valid             (io_out_1_valid),
    .io_out_bits_retired      (/* unused */),
    .io_out_bits_rdTag        (io_out_1_bits_rdTag),
    .io_out_bits_isBranch     (/* unused */),
    .io_out_bits_isJAL        (/* unused */),
    .io_out_bits_lsType       (io_out_1_bits_lsType),
    .io_out_bits_wakeup       (/* unused */),
    .io_out_bits_opsrc1       (/* unused */),
    .io_out_bits_opsrc2       (/* unused */),
    .io_out_bits_writeRf      (/* unused */),
    .io_out_bits_exEngine     (/* unused */),
    .io_out_bits_exOp         (/* unused */),
    .io_out_bits_lsOp         (/* unused */),
    .io_out_bits_exception    (io_out_1_bits_exception),
    .io_out_bits_taken        (io_out_1_bits_taken),
    .io_out_bits_imm          (/* unused */),
    .io_out_bits_rs1          (/* unused */),
    .io_out_bits_rs2          (/* unused */),
    .io_out_bits_rd           (/* unused */),
    .io_out_bits_pc           (io_out_1_bits_pc),
    .io_out_bits_targetPC     (io_out_1_bits_targetPC),
    .io_out_bits_rs1Tag       (/* unused */),
    .io_out_bits_rs1TagReady  (/* unused */),
    .io_out_bits_rs2Tag       (/* unused */),
    .io_out_bits_rs2TagReady  (/* unused */),
    .io_out_bits_rs1Data      (/* unused */),
    .io_out_bits_rs2Data      (io_out_1_bits_rs2Data),
    .io_out_bits_rdData       (io_out_1_bits_rdData),
    .io_out_bits_operandReady (/* unused */),
    .io_out_bits_flushed      (/* unused */),
    .io_out_bits_arfTag       (/* unused */),
    .io_out_bits_arfValid     (/* unused */),
    .io_out_bits_inst         (io_out_1_bits_inst)
  );
  DCArbiter_10 arbiter (
    .io_in_0_ready              (_arbiter_io_in_0_ready),
    .io_in_0_valid              (_alus_0_io_out_valid),
    .io_in_0_bits_retired       (_alus_0_io_out_bits_retired),
    .io_in_0_bits_rdTag         (_alus_0_io_out_bits_rdTag),
    .io_in_0_bits_isBranch      (_alus_0_io_out_bits_isBranch),
    .io_in_0_bits_isJAL         (_alus_0_io_out_bits_isJAL),
    .io_in_0_bits_lsType        (_alus_0_io_out_bits_lsType),
    .io_in_0_bits_wakeup        (_alus_0_io_out_bits_wakeup),
    .io_in_0_bits_opsrc1        (_alus_0_io_out_bits_opsrc1),
    .io_in_0_bits_opsrc2        (_alus_0_io_out_bits_opsrc2),
    .io_in_0_bits_writeRf       (_alus_0_io_out_bits_writeRf),
    .io_in_0_bits_exEngine      (_alus_0_io_out_bits_exEngine),
    .io_in_0_bits_exOp          (_alus_0_io_out_bits_exOp),
    .io_in_0_bits_lsOp          (_alus_0_io_out_bits_lsOp),
    .io_in_0_bits_exception     (_alus_0_io_out_bits_exception),
    .io_in_0_bits_taken         (_alus_0_io_out_bits_taken),
    .io_in_0_bits_imm           (_alus_0_io_out_bits_imm),
    .io_in_0_bits_rs1           (_alus_0_io_out_bits_rs1),
    .io_in_0_bits_rs2           (_alus_0_io_out_bits_rs2),
    .io_in_0_bits_rd            (_alus_0_io_out_bits_rd),
    .io_in_0_bits_pc            (_alus_0_io_out_bits_pc),
    .io_in_0_bits_targetPC      (_alus_0_io_out_bits_targetPC),
    .io_in_0_bits_rs1Tag        (_alus_0_io_out_bits_rs1Tag),
    .io_in_0_bits_rs1TagReady   (_alus_0_io_out_bits_rs1TagReady),
    .io_in_0_bits_rs2Tag        (_alus_0_io_out_bits_rs2Tag),
    .io_in_0_bits_rs2TagReady   (_alus_0_io_out_bits_rs2TagReady),
    .io_in_0_bits_rs1Data       (_alus_0_io_out_bits_rs1Data),
    .io_in_0_bits_rs2Data       (_alus_0_io_out_bits_rs2Data),
    .io_in_0_bits_rdData        (_alus_0_io_out_bits_rdData),
    .io_in_0_bits_operandReady  (_alus_0_io_out_bits_operandReady),
    .io_in_0_bits_flushed       (_alus_0_io_out_bits_flushed),
    .io_in_0_bits_arfTag        (_alus_0_io_out_bits_arfTag),
    .io_in_0_bits_arfValid      (_alus_0_io_out_bits_arfValid),
    .io_in_0_bits_inst          (_alus_0_io_out_bits_inst),
    .io_in_1_ready              (_arbiter_io_in_1_ready),
    .io_in_1_valid              (_alus_1_io_out_valid),
    .io_in_1_bits_retired       (_alus_1_io_out_bits_retired),
    .io_in_1_bits_rdTag         (_alus_1_io_out_bits_rdTag),
    .io_in_1_bits_isBranch      (_alus_1_io_out_bits_isBranch),
    .io_in_1_bits_isJAL         (_alus_1_io_out_bits_isJAL),
    .io_in_1_bits_lsType        (_alus_1_io_out_bits_lsType),
    .io_in_1_bits_wakeup        (_alus_1_io_out_bits_wakeup),
    .io_in_1_bits_opsrc1        (_alus_1_io_out_bits_opsrc1),
    .io_in_1_bits_opsrc2        (_alus_1_io_out_bits_opsrc2),
    .io_in_1_bits_writeRf       (_alus_1_io_out_bits_writeRf),
    .io_in_1_bits_exEngine      (_alus_1_io_out_bits_exEngine),
    .io_in_1_bits_exOp          (_alus_1_io_out_bits_exOp),
    .io_in_1_bits_lsOp          (_alus_1_io_out_bits_lsOp),
    .io_in_1_bits_exception     (_alus_1_io_out_bits_exception),
    .io_in_1_bits_taken         (_alus_1_io_out_bits_taken),
    .io_in_1_bits_imm           (_alus_1_io_out_bits_imm),
    .io_in_1_bits_rs1           (_alus_1_io_out_bits_rs1),
    .io_in_1_bits_rs2           (_alus_1_io_out_bits_rs2),
    .io_in_1_bits_rd            (_alus_1_io_out_bits_rd),
    .io_in_1_bits_pc            (_alus_1_io_out_bits_pc),
    .io_in_1_bits_targetPC      (_alus_1_io_out_bits_targetPC),
    .io_in_1_bits_rs1Tag        (_alus_1_io_out_bits_rs1Tag),
    .io_in_1_bits_rs1TagReady   (_alus_1_io_out_bits_rs1TagReady),
    .io_in_1_bits_rs2Tag        (_alus_1_io_out_bits_rs2Tag),
    .io_in_1_bits_rs2TagReady   (_alus_1_io_out_bits_rs2TagReady),
    .io_in_1_bits_rs1Data       (_alus_1_io_out_bits_rs1Data),
    .io_in_1_bits_rs2Data       (_alus_1_io_out_bits_rs2Data),
    .io_in_1_bits_rdData        (_alus_1_io_out_bits_rdData),
    .io_in_1_bits_operandReady  (_alus_1_io_out_bits_operandReady),
    .io_in_1_bits_flushed       (_alus_1_io_out_bits_flushed),
    .io_in_1_bits_arfTag        (_alus_1_io_out_bits_arfTag),
    .io_in_1_bits_arfValid      (_alus_1_io_out_bits_arfValid),
    .io_in_1_bits_inst          (_alus_1_io_out_bits_inst),
    .io_in_2_ready              (_arbiter_io_in_2_ready),
    .io_in_2_valid              (_imus_0_io_out_valid),
    .io_in_2_bits_retired       (_imus_0_io_out_bits_retired),
    .io_in_2_bits_rdTag         (_imus_0_io_out_bits_rdTag),
    .io_in_2_bits_isBranch      (_imus_0_io_out_bits_isBranch),
    .io_in_2_bits_isJAL         (_imus_0_io_out_bits_isJAL),
    .io_in_2_bits_lsType        (_imus_0_io_out_bits_lsType),
    .io_in_2_bits_wakeup        (_imus_0_io_out_bits_wakeup),
    .io_in_2_bits_opsrc1        (_imus_0_io_out_bits_opsrc1),
    .io_in_2_bits_opsrc2        (_imus_0_io_out_bits_opsrc2),
    .io_in_2_bits_writeRf       (_imus_0_io_out_bits_writeRf),
    .io_in_2_bits_exEngine      (_imus_0_io_out_bits_exEngine),
    .io_in_2_bits_exOp          (_imus_0_io_out_bits_exOp),
    .io_in_2_bits_lsOp          (_imus_0_io_out_bits_lsOp),
    .io_in_2_bits_exception     (_imus_0_io_out_bits_exception),
    .io_in_2_bits_taken         (_imus_0_io_out_bits_taken),
    .io_in_2_bits_imm           (_imus_0_io_out_bits_imm),
    .io_in_2_bits_rs1           (_imus_0_io_out_bits_rs1),
    .io_in_2_bits_rs2           (_imus_0_io_out_bits_rs2),
    .io_in_2_bits_rd            (_imus_0_io_out_bits_rd),
    .io_in_2_bits_pc            (_imus_0_io_out_bits_pc),
    .io_in_2_bits_targetPC      (_imus_0_io_out_bits_targetPC),
    .io_in_2_bits_rs1Tag        (_imus_0_io_out_bits_rs1Tag),
    .io_in_2_bits_rs1TagReady   (_imus_0_io_out_bits_rs1TagReady),
    .io_in_2_bits_rs2Tag        (_imus_0_io_out_bits_rs2Tag),
    .io_in_2_bits_rs2TagReady   (_imus_0_io_out_bits_rs2TagReady),
    .io_in_2_bits_rs1Data       (_imus_0_io_out_bits_rs1Data),
    .io_in_2_bits_rs2Data       (_imus_0_io_out_bits_rs2Data),
    .io_in_2_bits_rdData        (_imus_0_io_out_bits_rdData),
    .io_in_2_bits_operandReady  (_imus_0_io_out_bits_operandReady),
    .io_in_2_bits_flushed       (_imus_0_io_out_bits_flushed),
    .io_in_2_bits_arfTag        (_imus_0_io_out_bits_arfTag),
    .io_in_2_bits_arfValid      (_imus_0_io_out_bits_arfValid),
    .io_in_2_bits_inst          (_imus_0_io_out_bits_inst),
    .io_in_3_ready              (_arbiter_io_in_3_ready),
    .io_in_3_valid              (_idus_0_io_out_valid),
    .io_in_3_bits_retired       (_idus_0_io_out_bits_retired),
    .io_in_3_bits_rdTag         (_idus_0_io_out_bits_rdTag),
    .io_in_3_bits_isBranch      (_idus_0_io_out_bits_isBranch),
    .io_in_3_bits_isJAL         (_idus_0_io_out_bits_isJAL),
    .io_in_3_bits_lsType        (_idus_0_io_out_bits_lsType),
    .io_in_3_bits_wakeup        (_idus_0_io_out_bits_wakeup),
    .io_in_3_bits_opsrc1        (_idus_0_io_out_bits_opsrc1),
    .io_in_3_bits_opsrc2        (_idus_0_io_out_bits_opsrc2),
    .io_in_3_bits_writeRf       (_idus_0_io_out_bits_writeRf),
    .io_in_3_bits_exEngine      (_idus_0_io_out_bits_exEngine),
    .io_in_3_bits_exOp          (_idus_0_io_out_bits_exOp),
    .io_in_3_bits_lsOp          (_idus_0_io_out_bits_lsOp),
    .io_in_3_bits_exception     (_idus_0_io_out_bits_exception),
    .io_in_3_bits_taken         (_idus_0_io_out_bits_taken),
    .io_in_3_bits_imm           (_idus_0_io_out_bits_imm),
    .io_in_3_bits_rs1           (_idus_0_io_out_bits_rs1),
    .io_in_3_bits_rs2           (_idus_0_io_out_bits_rs2),
    .io_in_3_bits_rd            (_idus_0_io_out_bits_rd),
    .io_in_3_bits_pc            (_idus_0_io_out_bits_pc),
    .io_in_3_bits_targetPC      (_idus_0_io_out_bits_targetPC),
    .io_in_3_bits_rs1Tag        (_idus_0_io_out_bits_rs1Tag),
    .io_in_3_bits_rs1TagReady   (_idus_0_io_out_bits_rs1TagReady),
    .io_in_3_bits_rs2Tag        (_idus_0_io_out_bits_rs2Tag),
    .io_in_3_bits_rs2TagReady   (_idus_0_io_out_bits_rs2TagReady),
    .io_in_3_bits_rs1Data       (_idus_0_io_out_bits_rs1Data),
    .io_in_3_bits_rs2Data       (_idus_0_io_out_bits_rs2Data),
    .io_in_3_bits_rdData        (_idus_0_io_out_bits_rdData),
    .io_in_3_bits_operandReady  (_idus_0_io_out_bits_operandReady),
    .io_in_3_bits_flushed       (_idus_0_io_out_bits_flushed),
    .io_in_3_bits_arfTag        (_idus_0_io_out_bits_arfTag),
    .io_in_3_bits_arfValid      (_idus_0_io_out_bits_arfValid),
    .io_in_3_bits_inst          (_idus_0_io_out_bits_inst),
    .io_out_0_ready             (_pRegs_0_io_in_ready),
    .io_out_0_valid             (_arbiter_io_out_0_valid),
    .io_out_0_bits_retired      (_arbiter_io_out_0_bits_retired),
    .io_out_0_bits_rdTag        (_arbiter_io_out_0_bits_rdTag),
    .io_out_0_bits_isBranch     (_arbiter_io_out_0_bits_isBranch),
    .io_out_0_bits_isJAL        (_arbiter_io_out_0_bits_isJAL),
    .io_out_0_bits_lsType       (_arbiter_io_out_0_bits_lsType),
    .io_out_0_bits_wakeup       (_arbiter_io_out_0_bits_wakeup),
    .io_out_0_bits_opsrc1       (_arbiter_io_out_0_bits_opsrc1),
    .io_out_0_bits_opsrc2       (_arbiter_io_out_0_bits_opsrc2),
    .io_out_0_bits_writeRf      (_arbiter_io_out_0_bits_writeRf),
    .io_out_0_bits_exEngine     (_arbiter_io_out_0_bits_exEngine),
    .io_out_0_bits_exOp         (_arbiter_io_out_0_bits_exOp),
    .io_out_0_bits_lsOp         (_arbiter_io_out_0_bits_lsOp),
    .io_out_0_bits_exception    (_arbiter_io_out_0_bits_exception),
    .io_out_0_bits_taken        (_arbiter_io_out_0_bits_taken),
    .io_out_0_bits_imm          (_arbiter_io_out_0_bits_imm),
    .io_out_0_bits_rs1          (_arbiter_io_out_0_bits_rs1),
    .io_out_0_bits_rs2          (_arbiter_io_out_0_bits_rs2),
    .io_out_0_bits_rd           (_arbiter_io_out_0_bits_rd),
    .io_out_0_bits_pc           (_arbiter_io_out_0_bits_pc),
    .io_out_0_bits_targetPC     (_arbiter_io_out_0_bits_targetPC),
    .io_out_0_bits_rs1Tag       (_arbiter_io_out_0_bits_rs1Tag),
    .io_out_0_bits_rs1TagReady  (_arbiter_io_out_0_bits_rs1TagReady),
    .io_out_0_bits_rs2Tag       (_arbiter_io_out_0_bits_rs2Tag),
    .io_out_0_bits_rs2TagReady  (_arbiter_io_out_0_bits_rs2TagReady),
    .io_out_0_bits_rs1Data      (_arbiter_io_out_0_bits_rs1Data),
    .io_out_0_bits_rs2Data      (_arbiter_io_out_0_bits_rs2Data),
    .io_out_0_bits_rdData       (_arbiter_io_out_0_bits_rdData),
    .io_out_0_bits_operandReady (_arbiter_io_out_0_bits_operandReady),
    .io_out_0_bits_flushed      (_arbiter_io_out_0_bits_flushed),
    .io_out_0_bits_arfTag       (_arbiter_io_out_0_bits_arfTag),
    .io_out_0_bits_arfValid     (_arbiter_io_out_0_bits_arfValid),
    .io_out_0_bits_inst         (_arbiter_io_out_0_bits_inst),
    .io_out_1_ready             (_pRegs_1_io_in_ready),
    .io_out_1_valid             (_arbiter_io_out_1_valid),
    .io_out_1_bits_retired      (_arbiter_io_out_1_bits_retired),
    .io_out_1_bits_rdTag        (_arbiter_io_out_1_bits_rdTag),
    .io_out_1_bits_isBranch     (_arbiter_io_out_1_bits_isBranch),
    .io_out_1_bits_isJAL        (_arbiter_io_out_1_bits_isJAL),
    .io_out_1_bits_lsType       (_arbiter_io_out_1_bits_lsType),
    .io_out_1_bits_wakeup       (_arbiter_io_out_1_bits_wakeup),
    .io_out_1_bits_opsrc1       (_arbiter_io_out_1_bits_opsrc1),
    .io_out_1_bits_opsrc2       (_arbiter_io_out_1_bits_opsrc2),
    .io_out_1_bits_writeRf      (_arbiter_io_out_1_bits_writeRf),
    .io_out_1_bits_exEngine     (_arbiter_io_out_1_bits_exEngine),
    .io_out_1_bits_exOp         (_arbiter_io_out_1_bits_exOp),
    .io_out_1_bits_lsOp         (_arbiter_io_out_1_bits_lsOp),
    .io_out_1_bits_exception    (_arbiter_io_out_1_bits_exception),
    .io_out_1_bits_taken        (_arbiter_io_out_1_bits_taken),
    .io_out_1_bits_imm          (_arbiter_io_out_1_bits_imm),
    .io_out_1_bits_rs1          (_arbiter_io_out_1_bits_rs1),
    .io_out_1_bits_rs2          (_arbiter_io_out_1_bits_rs2),
    .io_out_1_bits_rd           (_arbiter_io_out_1_bits_rd),
    .io_out_1_bits_pc           (_arbiter_io_out_1_bits_pc),
    .io_out_1_bits_targetPC     (_arbiter_io_out_1_bits_targetPC),
    .io_out_1_bits_rs1Tag       (_arbiter_io_out_1_bits_rs1Tag),
    .io_out_1_bits_rs1TagReady  (_arbiter_io_out_1_bits_rs1TagReady),
    .io_out_1_bits_rs2Tag       (_arbiter_io_out_1_bits_rs2Tag),
    .io_out_1_bits_rs2TagReady  (_arbiter_io_out_1_bits_rs2TagReady),
    .io_out_1_bits_rs1Data      (_arbiter_io_out_1_bits_rs1Data),
    .io_out_1_bits_rs2Data      (_arbiter_io_out_1_bits_rs2Data),
    .io_out_1_bits_rdData       (_arbiter_io_out_1_bits_rdData),
    .io_out_1_bits_operandReady (_arbiter_io_out_1_bits_operandReady),
    .io_out_1_bits_flushed      (_arbiter_io_out_1_bits_flushed),
    .io_out_1_bits_arfTag       (_arbiter_io_out_1_bits_arfTag),
    .io_out_1_bits_arfValid     (_arbiter_io_out_1_bits_arfValid),
    .io_out_1_bits_inst         (_arbiter_io_out_1_bits_inst)
  );
  ALU alus_0 (
    .io_in_ready              (io_aluIn_0_ready),
    .io_in_valid              (io_aluIn_0_valid),
    .io_in_bits_retired       (io_aluIn_0_bits_retired),
    .io_in_bits_rdTag         (io_aluIn_0_bits_rdTag),
    .io_in_bits_isBranch      (io_aluIn_0_bits_isBranch),
    .io_in_bits_isJAL         (io_aluIn_0_bits_isJAL),
    .io_in_bits_lsType        (io_aluIn_0_bits_lsType),
    .io_in_bits_wakeup        (io_aluIn_0_bits_wakeup),
    .io_in_bits_opsrc1        (io_aluIn_0_bits_opsrc1),
    .io_in_bits_opsrc2        (io_aluIn_0_bits_opsrc2),
    .io_in_bits_writeRf       (io_aluIn_0_bits_writeRf),
    .io_in_bits_exEngine      (io_aluIn_0_bits_exEngine),
    .io_in_bits_exOp          (io_aluIn_0_bits_exOp),
    .io_in_bits_lsOp          (io_aluIn_0_bits_lsOp),
    .io_in_bits_exception     (io_aluIn_0_bits_exception),
    .io_in_bits_taken         (io_aluIn_0_bits_taken),
    .io_in_bits_imm           (io_aluIn_0_bits_imm),
    .io_in_bits_rs1           (io_aluIn_0_bits_rs1),
    .io_in_bits_rs2           (io_aluIn_0_bits_rs2),
    .io_in_bits_rd            (io_aluIn_0_bits_rd),
    .io_in_bits_pc            (io_aluIn_0_bits_pc),
    .io_in_bits_rs1Tag        (io_aluIn_0_bits_rs1Tag),
    .io_in_bits_rs1TagReady   (io_aluIn_0_bits_rs1TagReady),
    .io_in_bits_rs2Tag        (io_aluIn_0_bits_rs2Tag),
    .io_in_bits_rs2TagReady   (io_aluIn_0_bits_rs2TagReady),
    .io_in_bits_rs1Data       (io_aluIn_0_bits_rs1Data),
    .io_in_bits_rs2Data       (io_aluIn_0_bits_rs2Data),
    .io_in_bits_operandReady  (io_aluIn_0_bits_operandReady),
    .io_in_bits_flushed       (io_aluIn_0_bits_flushed),
    .io_in_bits_arfTag        (io_aluIn_0_bits_arfTag),
    .io_in_bits_arfValid      (io_aluIn_0_bits_arfValid),
    .io_in_bits_inst          (io_aluIn_0_bits_inst),
    .io_out_ready             (_arbiter_io_in_0_ready),
    .io_out_valid             (_alus_0_io_out_valid),
    .io_out_bits_retired      (_alus_0_io_out_bits_retired),
    .io_out_bits_rdTag        (_alus_0_io_out_bits_rdTag),
    .io_out_bits_isBranch     (_alus_0_io_out_bits_isBranch),
    .io_out_bits_isJAL        (_alus_0_io_out_bits_isJAL),
    .io_out_bits_lsType       (_alus_0_io_out_bits_lsType),
    .io_out_bits_wakeup       (_alus_0_io_out_bits_wakeup),
    .io_out_bits_opsrc1       (_alus_0_io_out_bits_opsrc1),
    .io_out_bits_opsrc2       (_alus_0_io_out_bits_opsrc2),
    .io_out_bits_writeRf      (_alus_0_io_out_bits_writeRf),
    .io_out_bits_exEngine     (_alus_0_io_out_bits_exEngine),
    .io_out_bits_exOp         (_alus_0_io_out_bits_exOp),
    .io_out_bits_lsOp         (_alus_0_io_out_bits_lsOp),
    .io_out_bits_exception    (_alus_0_io_out_bits_exception),
    .io_out_bits_taken        (_alus_0_io_out_bits_taken),
    .io_out_bits_imm          (_alus_0_io_out_bits_imm),
    .io_out_bits_rs1          (_alus_0_io_out_bits_rs1),
    .io_out_bits_rs2          (_alus_0_io_out_bits_rs2),
    .io_out_bits_rd           (_alus_0_io_out_bits_rd),
    .io_out_bits_pc           (_alus_0_io_out_bits_pc),
    .io_out_bits_targetPC     (_alus_0_io_out_bits_targetPC),
    .io_out_bits_rs1Tag       (_alus_0_io_out_bits_rs1Tag),
    .io_out_bits_rs1TagReady  (_alus_0_io_out_bits_rs1TagReady),
    .io_out_bits_rs2Tag       (_alus_0_io_out_bits_rs2Tag),
    .io_out_bits_rs2TagReady  (_alus_0_io_out_bits_rs2TagReady),
    .io_out_bits_rs1Data      (_alus_0_io_out_bits_rs1Data),
    .io_out_bits_rs2Data      (_alus_0_io_out_bits_rs2Data),
    .io_out_bits_rdData       (_alus_0_io_out_bits_rdData),
    .io_out_bits_operandReady (_alus_0_io_out_bits_operandReady),
    .io_out_bits_flushed      (_alus_0_io_out_bits_flushed),
    .io_out_bits_arfTag       (_alus_0_io_out_bits_arfTag),
    .io_out_bits_arfValid     (_alus_0_io_out_bits_arfValid),
    .io_out_bits_inst         (_alus_0_io_out_bits_inst)
  );
  ALU alus_1 (
    .io_in_ready              (io_aluIn_1_ready),
    .io_in_valid              (io_aluIn_1_valid),
    .io_in_bits_retired       (io_aluIn_1_bits_retired),
    .io_in_bits_rdTag         (io_aluIn_1_bits_rdTag),
    .io_in_bits_isBranch      (io_aluIn_1_bits_isBranch),
    .io_in_bits_isJAL         (io_aluIn_1_bits_isJAL),
    .io_in_bits_lsType        (io_aluIn_1_bits_lsType),
    .io_in_bits_wakeup        (io_aluIn_1_bits_wakeup),
    .io_in_bits_opsrc1        (io_aluIn_1_bits_opsrc1),
    .io_in_bits_opsrc2        (io_aluIn_1_bits_opsrc2),
    .io_in_bits_writeRf       (io_aluIn_1_bits_writeRf),
    .io_in_bits_exEngine      (io_aluIn_1_bits_exEngine),
    .io_in_bits_exOp          (io_aluIn_1_bits_exOp),
    .io_in_bits_lsOp          (io_aluIn_1_bits_lsOp),
    .io_in_bits_exception     (io_aluIn_1_bits_exception),
    .io_in_bits_taken         (io_aluIn_1_bits_taken),
    .io_in_bits_imm           (io_aluIn_1_bits_imm),
    .io_in_bits_rs1           (io_aluIn_1_bits_rs1),
    .io_in_bits_rs2           (io_aluIn_1_bits_rs2),
    .io_in_bits_rd            (io_aluIn_1_bits_rd),
    .io_in_bits_pc            (io_aluIn_1_bits_pc),
    .io_in_bits_rs1Tag        (io_aluIn_1_bits_rs1Tag),
    .io_in_bits_rs1TagReady   (io_aluIn_1_bits_rs1TagReady),
    .io_in_bits_rs2Tag        (io_aluIn_1_bits_rs2Tag),
    .io_in_bits_rs2TagReady   (io_aluIn_1_bits_rs2TagReady),
    .io_in_bits_rs1Data       (io_aluIn_1_bits_rs1Data),
    .io_in_bits_rs2Data       (io_aluIn_1_bits_rs2Data),
    .io_in_bits_operandReady  (io_aluIn_1_bits_operandReady),
    .io_in_bits_flushed       (io_aluIn_1_bits_flushed),
    .io_in_bits_arfTag        (io_aluIn_1_bits_arfTag),
    .io_in_bits_arfValid      (io_aluIn_1_bits_arfValid),
    .io_in_bits_inst          (io_aluIn_1_bits_inst),
    .io_out_ready             (_arbiter_io_in_1_ready),
    .io_out_valid             (_alus_1_io_out_valid),
    .io_out_bits_retired      (_alus_1_io_out_bits_retired),
    .io_out_bits_rdTag        (_alus_1_io_out_bits_rdTag),
    .io_out_bits_isBranch     (_alus_1_io_out_bits_isBranch),
    .io_out_bits_isJAL        (_alus_1_io_out_bits_isJAL),
    .io_out_bits_lsType       (_alus_1_io_out_bits_lsType),
    .io_out_bits_wakeup       (_alus_1_io_out_bits_wakeup),
    .io_out_bits_opsrc1       (_alus_1_io_out_bits_opsrc1),
    .io_out_bits_opsrc2       (_alus_1_io_out_bits_opsrc2),
    .io_out_bits_writeRf      (_alus_1_io_out_bits_writeRf),
    .io_out_bits_exEngine     (_alus_1_io_out_bits_exEngine),
    .io_out_bits_exOp         (_alus_1_io_out_bits_exOp),
    .io_out_bits_lsOp         (_alus_1_io_out_bits_lsOp),
    .io_out_bits_exception    (_alus_1_io_out_bits_exception),
    .io_out_bits_taken        (_alus_1_io_out_bits_taken),
    .io_out_bits_imm          (_alus_1_io_out_bits_imm),
    .io_out_bits_rs1          (_alus_1_io_out_bits_rs1),
    .io_out_bits_rs2          (_alus_1_io_out_bits_rs2),
    .io_out_bits_rd           (_alus_1_io_out_bits_rd),
    .io_out_bits_pc           (_alus_1_io_out_bits_pc),
    .io_out_bits_targetPC     (_alus_1_io_out_bits_targetPC),
    .io_out_bits_rs1Tag       (_alus_1_io_out_bits_rs1Tag),
    .io_out_bits_rs1TagReady  (_alus_1_io_out_bits_rs1TagReady),
    .io_out_bits_rs2Tag       (_alus_1_io_out_bits_rs2Tag),
    .io_out_bits_rs2TagReady  (_alus_1_io_out_bits_rs2TagReady),
    .io_out_bits_rs1Data      (_alus_1_io_out_bits_rs1Data),
    .io_out_bits_rs2Data      (_alus_1_io_out_bits_rs2Data),
    .io_out_bits_rdData       (_alus_1_io_out_bits_rdData),
    .io_out_bits_operandReady (_alus_1_io_out_bits_operandReady),
    .io_out_bits_flushed      (_alus_1_io_out_bits_flushed),
    .io_out_bits_arfTag       (_alus_1_io_out_bits_arfTag),
    .io_out_bits_arfValid     (_alus_1_io_out_bits_arfValid),
    .io_out_bits_inst         (_alus_1_io_out_bits_inst)
  );
  IMU imus_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_ready              (io_imuIn_0_ready),
    .io_in_valid              (io_imuIn_0_valid),
    .io_in_bits_retired       (io_imuIn_0_bits_retired),
    .io_in_bits_rdTag         (io_imuIn_0_bits_rdTag),
    .io_in_bits_isBranch      (io_imuIn_0_bits_isBranch),
    .io_in_bits_isJAL         (io_imuIn_0_bits_isJAL),
    .io_in_bits_lsType        (io_imuIn_0_bits_lsType),
    .io_in_bits_wakeup        (io_imuIn_0_bits_wakeup),
    .io_in_bits_opsrc1        (io_imuIn_0_bits_opsrc1),
    .io_in_bits_opsrc2        (io_imuIn_0_bits_opsrc2),
    .io_in_bits_writeRf       (io_imuIn_0_bits_writeRf),
    .io_in_bits_exEngine      (io_imuIn_0_bits_exEngine),
    .io_in_bits_exOp          (io_imuIn_0_bits_exOp),
    .io_in_bits_lsOp          (io_imuIn_0_bits_lsOp),
    .io_in_bits_exception     (io_imuIn_0_bits_exception),
    .io_in_bits_taken         (io_imuIn_0_bits_taken),
    .io_in_bits_imm           (io_imuIn_0_bits_imm),
    .io_in_bits_rs1           (io_imuIn_0_bits_rs1),
    .io_in_bits_rs2           (io_imuIn_0_bits_rs2),
    .io_in_bits_rd            (io_imuIn_0_bits_rd),
    .io_in_bits_pc            (io_imuIn_0_bits_pc),
    .io_in_bits_targetPC      (io_imuIn_0_bits_targetPC),
    .io_in_bits_rs1Tag        (io_imuIn_0_bits_rs1Tag),
    .io_in_bits_rs1TagReady   (io_imuIn_0_bits_rs1TagReady),
    .io_in_bits_rs2Tag        (io_imuIn_0_bits_rs2Tag),
    .io_in_bits_rs2TagReady   (io_imuIn_0_bits_rs2TagReady),
    .io_in_bits_rs1Data       (io_imuIn_0_bits_rs1Data),
    .io_in_bits_rs2Data       (io_imuIn_0_bits_rs2Data),
    .io_in_bits_operandReady  (io_imuIn_0_bits_operandReady),
    .io_in_bits_flushed       (io_imuIn_0_bits_flushed),
    .io_in_bits_arfTag        (io_imuIn_0_bits_arfTag),
    .io_in_bits_arfValid      (io_imuIn_0_bits_arfValid),
    .io_in_bits_inst          (io_imuIn_0_bits_inst),
    .io_flush                 (io_flush),
    .io_out_ready             (_arbiter_io_in_2_ready),
    .io_out_valid             (_imus_0_io_out_valid),
    .io_out_bits_retired      (_imus_0_io_out_bits_retired),
    .io_out_bits_rdTag        (_imus_0_io_out_bits_rdTag),
    .io_out_bits_isBranch     (_imus_0_io_out_bits_isBranch),
    .io_out_bits_isJAL        (_imus_0_io_out_bits_isJAL),
    .io_out_bits_lsType       (_imus_0_io_out_bits_lsType),
    .io_out_bits_wakeup       (_imus_0_io_out_bits_wakeup),
    .io_out_bits_opsrc1       (_imus_0_io_out_bits_opsrc1),
    .io_out_bits_opsrc2       (_imus_0_io_out_bits_opsrc2),
    .io_out_bits_writeRf      (_imus_0_io_out_bits_writeRf),
    .io_out_bits_exEngine     (_imus_0_io_out_bits_exEngine),
    .io_out_bits_exOp         (_imus_0_io_out_bits_exOp),
    .io_out_bits_lsOp         (_imus_0_io_out_bits_lsOp),
    .io_out_bits_exception    (_imus_0_io_out_bits_exception),
    .io_out_bits_taken        (_imus_0_io_out_bits_taken),
    .io_out_bits_imm          (_imus_0_io_out_bits_imm),
    .io_out_bits_rs1          (_imus_0_io_out_bits_rs1),
    .io_out_bits_rs2          (_imus_0_io_out_bits_rs2),
    .io_out_bits_rd           (_imus_0_io_out_bits_rd),
    .io_out_bits_pc           (_imus_0_io_out_bits_pc),
    .io_out_bits_targetPC     (_imus_0_io_out_bits_targetPC),
    .io_out_bits_rs1Tag       (_imus_0_io_out_bits_rs1Tag),
    .io_out_bits_rs1TagReady  (_imus_0_io_out_bits_rs1TagReady),
    .io_out_bits_rs2Tag       (_imus_0_io_out_bits_rs2Tag),
    .io_out_bits_rs2TagReady  (_imus_0_io_out_bits_rs2TagReady),
    .io_out_bits_rs1Data      (_imus_0_io_out_bits_rs1Data),
    .io_out_bits_rs2Data      (_imus_0_io_out_bits_rs2Data),
    .io_out_bits_rdData       (_imus_0_io_out_bits_rdData),
    .io_out_bits_operandReady (_imus_0_io_out_bits_operandReady),
    .io_out_bits_flushed      (_imus_0_io_out_bits_flushed),
    .io_out_bits_arfTag       (_imus_0_io_out_bits_arfTag),
    .io_out_bits_arfValid     (_imus_0_io_out_bits_arfValid),
    .io_out_bits_inst         (_imus_0_io_out_bits_inst)
  );
  IDU idus_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_ready              (io_iduIn_0_ready),
    .io_in_valid              (io_iduIn_0_valid),
    .io_in_bits_retired       (io_iduIn_0_bits_retired),
    .io_in_bits_rdTag         (io_iduIn_0_bits_rdTag),
    .io_in_bits_isBranch      (io_iduIn_0_bits_isBranch),
    .io_in_bits_isJAL         (io_iduIn_0_bits_isJAL),
    .io_in_bits_lsType        (io_iduIn_0_bits_lsType),
    .io_in_bits_wakeup        (io_iduIn_0_bits_wakeup),
    .io_in_bits_opsrc1        (io_iduIn_0_bits_opsrc1),
    .io_in_bits_opsrc2        (io_iduIn_0_bits_opsrc2),
    .io_in_bits_writeRf       (io_iduIn_0_bits_writeRf),
    .io_in_bits_exEngine      (io_iduIn_0_bits_exEngine),
    .io_in_bits_exOp          (io_iduIn_0_bits_exOp),
    .io_in_bits_lsOp          (io_iduIn_0_bits_lsOp),
    .io_in_bits_exception     (io_iduIn_0_bits_exception),
    .io_in_bits_taken         (io_iduIn_0_bits_taken),
    .io_in_bits_imm           (io_iduIn_0_bits_imm),
    .io_in_bits_rs1           (io_iduIn_0_bits_rs1),
    .io_in_bits_rs2           (io_iduIn_0_bits_rs2),
    .io_in_bits_rd            (io_iduIn_0_bits_rd),
    .io_in_bits_pc            (io_iduIn_0_bits_pc),
    .io_in_bits_targetPC      (io_iduIn_0_bits_targetPC),
    .io_in_bits_rs1Tag        (io_iduIn_0_bits_rs1Tag),
    .io_in_bits_rs1TagReady   (io_iduIn_0_bits_rs1TagReady),
    .io_in_bits_rs2Tag        (io_iduIn_0_bits_rs2Tag),
    .io_in_bits_rs2TagReady   (io_iduIn_0_bits_rs2TagReady),
    .io_in_bits_rs1Data       (io_iduIn_0_bits_rs1Data),
    .io_in_bits_rs2Data       (io_iduIn_0_bits_rs2Data),
    .io_in_bits_operandReady  (io_iduIn_0_bits_operandReady),
    .io_in_bits_flushed       (io_iduIn_0_bits_flushed),
    .io_in_bits_arfTag        (io_iduIn_0_bits_arfTag),
    .io_in_bits_arfValid      (io_iduIn_0_bits_arfValid),
    .io_in_bits_inst          (io_iduIn_0_bits_inst),
    .io_flush                 (io_flush),
    .io_out_ready             (_arbiter_io_in_3_ready),
    .io_out_valid             (_idus_0_io_out_valid),
    .io_out_bits_retired      (_idus_0_io_out_bits_retired),
    .io_out_bits_rdTag        (_idus_0_io_out_bits_rdTag),
    .io_out_bits_isBranch     (_idus_0_io_out_bits_isBranch),
    .io_out_bits_isJAL        (_idus_0_io_out_bits_isJAL),
    .io_out_bits_lsType       (_idus_0_io_out_bits_lsType),
    .io_out_bits_wakeup       (_idus_0_io_out_bits_wakeup),
    .io_out_bits_opsrc1       (_idus_0_io_out_bits_opsrc1),
    .io_out_bits_opsrc2       (_idus_0_io_out_bits_opsrc2),
    .io_out_bits_writeRf      (_idus_0_io_out_bits_writeRf),
    .io_out_bits_exEngine     (_idus_0_io_out_bits_exEngine),
    .io_out_bits_exOp         (_idus_0_io_out_bits_exOp),
    .io_out_bits_lsOp         (_idus_0_io_out_bits_lsOp),
    .io_out_bits_exception    (_idus_0_io_out_bits_exception),
    .io_out_bits_taken        (_idus_0_io_out_bits_taken),
    .io_out_bits_imm          (_idus_0_io_out_bits_imm),
    .io_out_bits_rs1          (_idus_0_io_out_bits_rs1),
    .io_out_bits_rs2          (_idus_0_io_out_bits_rs2),
    .io_out_bits_rd           (_idus_0_io_out_bits_rd),
    .io_out_bits_pc           (_idus_0_io_out_bits_pc),
    .io_out_bits_targetPC     (_idus_0_io_out_bits_targetPC),
    .io_out_bits_rs1Tag       (_idus_0_io_out_bits_rs1Tag),
    .io_out_bits_rs1TagReady  (_idus_0_io_out_bits_rs1TagReady),
    .io_out_bits_rs2Tag       (_idus_0_io_out_bits_rs2Tag),
    .io_out_bits_rs2TagReady  (_idus_0_io_out_bits_rs2TagReady),
    .io_out_bits_rs1Data      (_idus_0_io_out_bits_rs1Data),
    .io_out_bits_rs2Data      (_idus_0_io_out_bits_rs2Data),
    .io_out_bits_rdData       (_idus_0_io_out_bits_rdData),
    .io_out_bits_operandReady (_idus_0_io_out_bits_operandReady),
    .io_out_bits_flushed      (_idus_0_io_out_bits_flushed),
    .io_out_bits_arfTag       (_idus_0_io_out_bits_arfTag),
    .io_out_bits_arfValid     (_idus_0_io_out_bits_arfValid),
    .io_out_bits_inst         (_idus_0_io_out_bits_inst)
  );
  CSR csrs_0 (
    .clock              (clock),
    .reset              (reset),
    .io_in_ready        (io_csrIn_0_ready),
    .io_in_valid        (io_csrIn_0_valid),
    .io_in_bits_flushed (io_csrIn_0_bits_flushed),
    .io_flush           (io_flush)
  );
  assign io_forwardBus_0_valid =
    _arbiter_io_out_0_valid & _arbiter_io_out_0_bits_lsType != 2'h1
    & _arbiter_io_out_0_bits_lsType != 2'h3;
  assign io_forwardBus_0_bits_tag = _arbiter_io_out_0_bits_rdTag;
  assign io_forwardBus_0_bits_data = _arbiter_io_out_0_bits_rdData;
  assign io_forwardBus_1_valid =
    _arbiter_io_out_1_valid & _arbiter_io_out_1_bits_lsType != 2'h1
    & _arbiter_io_out_1_bits_lsType != 2'h3;
  assign io_forwardBus_1_bits_tag = _arbiter_io_out_1_bits_rdTag;
  assign io_forwardBus_1_bits_data = _arbiter_io_out_1_bits_rdData;
endmodule

