// Generated by CIRCT firtool-1.76.0
module ICacheBankController(
  input  wire         clock,
  input  wire         reset,
  output wire         io_core_0_req_ready,
  input  wire         io_core_0_req_valid,
  input  wire [31:0]  io_core_0_req_bits_addr,
  input  wire         io_core_0_resp_ready,
  output wire         io_core_0_resp_valid,
  output wire [31:0]  io_core_0_resp_bits_data,
  output wire         io_core_1_req_ready,
  input  wire         io_core_1_req_valid,
  input  wire [31:0]  io_core_1_req_bits_addr,
  input  wire         io_core_1_resp_ready,
  output wire         io_core_1_resp_valid,
  output wire [31:0]  io_core_1_resp_bits_data,
  input  wire         io_mem_req_ready,
  output wire         io_mem_req_valid,
  output wire [31:0]  io_mem_req_bits_addr,
  input  wire         io_mem_resp_valid,
  input  wire [127:0] io_mem_resp_bits_data
);

  wire        _arbiter_io_out_0_valid;
  wire [31:0] _arbiter_io_out_0_bits_addr;
  wire        _memreqshifter_io_in_0_ready;
  wire        _memreqshifter_io_in_1_ready;
  wire        _memreqshifter_io_out_0_valid;
  wire [31:0] _memreqshifter_io_out_0_bits_addr;
  wire        _memreqshifter_io_out_1_valid;
  wire [31:0] _memreqshifter_io_out_1_bits_addr;
  wire        _corerespshifter_io_in_0_ready;
  wire        _corerespshifter_io_in_1_ready;
  wire        _corereqshifter_io_in_0_ready;
  wire        _corereqshifter_io_in_1_ready;
  wire        _corereqshifter_io_out_0_valid;
  wire [31:0] _corereqshifter_io_out_0_bits_addr;
  wire        _corereqshifter_io_out_1_valid;
  wire [31:0] _corereqshifter_io_out_1_bits_addr;
  wire        _icachebank_1_io_core_req_ready;
  wire        _icachebank_1_io_core_resp_valid;
  wire [31:0] _icachebank_1_io_core_resp_bits_data;
  wire        _icachebank_1_io_mem_req_valid;
  wire [31:0] _icachebank_1_io_mem_req_bits_addr;
  wire        _icachebank_0_io_core_req_ready;
  wire        _icachebank_0_io_core_resp_valid;
  wire [31:0] _icachebank_0_io_core_resp_bits_data;
  wire        _icachebank_0_io_mem_req_valid;
  wire [31:0] _icachebank_0_io_mem_req_bits_addr;
  reg         shamtReg;
  wire        _memreqshifter_io_shamt_T = 1'h0 - shamtReg;
  reg  [1:0]  memrespShamt;
  wire [31:0] _shiftedmemresp_T_5 = memrespShamt[0] ? 32'h0 : io_mem_resp_bits_data[31:0];
  wire [31:0] _shiftedmemresp_T_6 =
    memrespShamt[0] ? io_mem_resp_bits_data[127:96] : 32'h0;
  wire [31:0] _shiftedmemresp_T_8 =
    memrespShamt[0] ? 32'h0 : io_mem_resp_bits_data[63:32];
  wire [31:0] _shiftedmemresp_T_9 = memrespShamt[0] ? io_mem_resp_bits_data[31:0] : 32'h0;
  wire [31:0] _shiftedmemresp_T_11 =
    memrespShamt[0] ? 32'h0 : io_mem_resp_bits_data[95:64];
  wire [31:0] _shiftedmemresp_T_12 =
    memrespShamt[0] ? io_mem_resp_bits_data[63:32] : 32'h0;
  wire [31:0] _shiftedmemresp_T_14 =
    memrespShamt[0] ? 32'h0 : io_mem_resp_bits_data[127:96];
  wire [31:0] _shiftedmemresp_T_15 =
    memrespShamt[0] ? io_mem_resp_bits_data[95:64] : 32'h0;
  wire [31:0] _shiftedmemresp_T_20 =
    memrespShamt[1] ? 32'h0 : _shiftedmemresp_T_5 | _shiftedmemresp_T_6;
  wire [31:0] _shiftedmemresp_T_21 =
    memrespShamt[1] ? _shiftedmemresp_T_11 | _shiftedmemresp_T_12 : 32'h0;
  wire [31:0] _shiftedmemresp_T_23 =
    memrespShamt[1] ? 32'h0 : _shiftedmemresp_T_8 | _shiftedmemresp_T_9;
  wire [31:0] _shiftedmemresp_T_24 =
    memrespShamt[1] ? _shiftedmemresp_T_14 | _shiftedmemresp_T_15 : 32'h0;
  always @(posedge clock) begin
    if (reset) begin
      shamtReg <= 1'h0;
      memrespShamt <= 2'h0;
    end
    else begin
      if (_corereqshifter_io_in_0_ready & io_core_0_req_valid
          | _corereqshifter_io_in_1_ready & io_core_1_req_valid)
        shamtReg <= io_core_0_req_bits_addr[2];
      if (io_mem_req_ready & _arbiter_io_out_0_valid)
        memrespShamt <= {_arbiter_io_out_0_bits_addr[3], 1'h0};
    end
  end // always @(posedge)
  ICacheBank icachebank_0 (
    .clock                  (clock),
    .reset                  (reset),
    .io_core_req_ready      (_icachebank_0_io_core_req_ready),
    .io_core_req_valid      (_corereqshifter_io_out_0_valid),
    .io_core_req_bits_addr  (_corereqshifter_io_out_0_bits_addr),
    .io_core_resp_ready     (_corerespshifter_io_in_0_ready),
    .io_core_resp_valid     (_icachebank_0_io_core_resp_valid),
    .io_core_resp_bits_data (_icachebank_0_io_core_resp_bits_data),
    .io_mem_req_ready       (_memreqshifter_io_in_0_ready),
    .io_mem_req_valid       (_icachebank_0_io_mem_req_valid),
    .io_mem_req_bits_addr   (_icachebank_0_io_mem_req_bits_addr),
    .io_mem_resp_valid      (io_mem_resp_valid),
    .io_mem_resp_bits_data  (_shiftedmemresp_T_20 | _shiftedmemresp_T_21)
  );
  ICacheBank icachebank_1 (
    .clock                  (clock),
    .reset                  (reset),
    .io_core_req_ready      (_icachebank_1_io_core_req_ready),
    .io_core_req_valid      (_corereqshifter_io_out_1_valid),
    .io_core_req_bits_addr  (_corereqshifter_io_out_1_bits_addr),
    .io_core_resp_ready     (_corerespshifter_io_in_1_ready),
    .io_core_resp_valid     (_icachebank_1_io_core_resp_valid),
    .io_core_resp_bits_data (_icachebank_1_io_core_resp_bits_data),
    .io_mem_req_ready       (_memreqshifter_io_in_1_ready),
    .io_mem_req_valid       (_icachebank_1_io_mem_req_valid),
    .io_mem_req_bits_addr   (_icachebank_1_io_mem_req_bits_addr),
    .io_mem_resp_valid      (io_mem_resp_valid),
    .io_mem_resp_bits_data  (_shiftedmemresp_T_23 | _shiftedmemresp_T_24)
  );
  DCLeftShifter corereqshifter (
    .io_in_0_ready      (_corereqshifter_io_in_0_ready),
    .io_in_0_valid      (io_core_0_req_valid),
    .io_in_0_bits_addr  (io_core_0_req_bits_addr),
    .io_in_1_ready      (_corereqshifter_io_in_1_ready),
    .io_in_1_valid      (io_core_1_req_valid),
    .io_in_1_bits_addr  (io_core_1_req_bits_addr),
    .io_shamt           (io_core_0_req_bits_addr[2]),
    .io_out_0_ready     (_icachebank_0_io_core_req_ready),
    .io_out_0_valid     (_corereqshifter_io_out_0_valid),
    .io_out_0_bits_addr (_corereqshifter_io_out_0_bits_addr),
    .io_out_1_ready     (_icachebank_1_io_core_req_ready),
    .io_out_1_valid     (_corereqshifter_io_out_1_valid),
    .io_out_1_bits_addr (_corereqshifter_io_out_1_bits_addr)
  );
  DCLeftShifter_1 corerespshifter (
    .io_in_0_ready      (_corerespshifter_io_in_0_ready),
    .io_in_0_valid      (_icachebank_0_io_core_resp_valid),
    .io_in_0_bits_data  (_icachebank_0_io_core_resp_bits_data),
    .io_in_1_ready      (_corerespshifter_io_in_1_ready),
    .io_in_1_valid      (_icachebank_1_io_core_resp_valid),
    .io_in_1_bits_data  (_icachebank_1_io_core_resp_bits_data),
    .io_shamt           (_memreqshifter_io_shamt_T),
    .io_out_0_ready     (io_core_0_resp_ready),
    .io_out_0_valid     (io_core_0_resp_valid),
    .io_out_0_bits_data (io_core_0_resp_bits_data),
    .io_out_1_ready     (io_core_1_resp_ready),
    .io_out_1_valid     (io_core_1_resp_valid),
    .io_out_1_bits_data (io_core_1_resp_bits_data)
  );
  DCLeftShifter memreqshifter (
    .io_in_0_ready      (_memreqshifter_io_in_0_ready),
    .io_in_0_valid      (_icachebank_0_io_mem_req_valid),
    .io_in_0_bits_addr  (_icachebank_0_io_mem_req_bits_addr),
    .io_in_1_ready      (_memreqshifter_io_in_1_ready),
    .io_in_1_valid      (_icachebank_1_io_mem_req_valid),
    .io_in_1_bits_addr  (_icachebank_1_io_mem_req_bits_addr),
    .io_shamt           (_memreqshifter_io_shamt_T),
    .io_out_0_ready
      (io_mem_req_ready
       & _memreqshifter_io_out_0_bits_addr[31:3] == _arbiter_io_out_0_bits_addr[31:3]),
    .io_out_0_valid     (_memreqshifter_io_out_0_valid),
    .io_out_0_bits_addr (_memreqshifter_io_out_0_bits_addr),
    .io_out_1_ready
      (io_mem_req_ready
       & _memreqshifter_io_out_1_bits_addr[31:3] == _arbiter_io_out_0_bits_addr[31:3]),
    .io_out_1_valid     (_memreqshifter_io_out_1_valid),
    .io_out_1_bits_addr (_memreqshifter_io_out_1_bits_addr)
  );
  DCArbiter arbiter (
    .io_in_0_valid      (_memreqshifter_io_out_0_valid),
    .io_in_0_bits_addr  (_memreqshifter_io_out_0_bits_addr),
    .io_in_1_valid      (_memreqshifter_io_out_1_valid),
    .io_in_1_bits_addr  (_memreqshifter_io_out_1_bits_addr),
    .io_out_0_valid     (_arbiter_io_out_0_valid),
    .io_out_0_bits_addr (_arbiter_io_out_0_bits_addr)
  );
  assign io_core_0_req_ready = _corereqshifter_io_in_0_ready;
  assign io_core_1_req_ready = _corereqshifter_io_in_1_ready;
  assign io_mem_req_valid = _arbiter_io_out_0_valid;
  assign io_mem_req_bits_addr = _arbiter_io_out_0_bits_addr;
endmodule

