// Generated by CIRCT firtool-1.76.0
module IDU(
  input  wire        clock,
  input  wire        reset,
  output wire        io_in_ready,
  input  wire        io_in_valid,
  input  wire        io_in_bits_retired,
  input  wire [6:0]  io_in_bits_rdTag,
  input  wire        io_in_bits_isBranch,
  input  wire        io_in_bits_isJAL,
  input  wire [1:0]  io_in_bits_lsType,
  input  wire        io_in_bits_wakeup,
  input  wire [1:0]  io_in_bits_opsrc1,
  input  wire [1:0]  io_in_bits_opsrc2,
  input  wire [1:0]  io_in_bits_writeRf,
  input  wire [2:0]  io_in_bits_exEngine,
  input  wire [5:0]  io_in_bits_exOp,
  input  wire [5:0]  io_in_bits_lsOp,
  input  wire        io_in_bits_exception,
  input  wire        io_in_bits_taken,
  input  wire [31:0] io_in_bits_imm,
  input  wire [4:0]  io_in_bits_rs1,
  input  wire [4:0]  io_in_bits_rs2,
  input  wire [4:0]  io_in_bits_rd,
  input  wire [31:0] io_in_bits_pc,
  input  wire [31:0] io_in_bits_targetPC,
  input  wire [6:0]  io_in_bits_rs1Tag,
  input  wire        io_in_bits_rs1TagReady,
  input  wire [6:0]  io_in_bits_rs2Tag,
  input  wire        io_in_bits_rs2TagReady,
  input  wire [31:0] io_in_bits_rs1Data,
  input  wire [31:0] io_in_bits_rs2Data,
  input  wire        io_in_bits_operandReady,
  input  wire        io_in_bits_flushed,
  input  wire [6:0]  io_in_bits_arfTag,
  input  wire        io_in_bits_arfValid,
  input  wire [31:0] io_in_bits_inst,
  input  wire        io_flush,
  input  wire        io_out_ready,
  output wire        io_out_valid,
  output wire        io_out_bits_retired,
  output wire [6:0]  io_out_bits_rdTag,
  output wire        io_out_bits_isBranch,
  output wire        io_out_bits_isJAL,
  output wire [1:0]  io_out_bits_lsType,
  output wire        io_out_bits_wakeup,
  output wire [1:0]  io_out_bits_opsrc1,
  output wire [1:0]  io_out_bits_opsrc2,
  output wire [1:0]  io_out_bits_writeRf,
  output wire [2:0]  io_out_bits_exEngine,
  output wire [5:0]  io_out_bits_exOp,
  output wire [5:0]  io_out_bits_lsOp,
  output wire        io_out_bits_exception,
  output wire        io_out_bits_taken,
  output wire [31:0] io_out_bits_imm,
  output wire [4:0]  io_out_bits_rs1,
  output wire [4:0]  io_out_bits_rs2,
  output wire [4:0]  io_out_bits_rd,
  output wire [31:0] io_out_bits_pc,
  output wire [31:0] io_out_bits_targetPC,
  output wire [6:0]  io_out_bits_rs1Tag,
  output wire        io_out_bits_rs1TagReady,
  output wire [6:0]  io_out_bits_rs2Tag,
  output wire        io_out_bits_rs2TagReady,
  output wire [31:0] io_out_bits_rs1Data,
  output wire [31:0] io_out_bits_rs2Data,
  output wire [31:0] io_out_bits_rdData,
  output wire        io_out_bits_operandReady,
  output wire        io_out_bits_flushed,
  output wire [6:0]  io_out_bits_arfTag,
  output wire        io_out_bits_arfValid,
  output wire [31:0] io_out_bits_inst
);

  wire        _divider_io_in_ready;
  wire        _divider_io_out_valid;
  reg         mi_retired;
  reg  [6:0]  mi_rdTag;
  reg         mi_isBranch;
  reg         mi_isJAL;
  reg  [1:0]  mi_lsType;
  reg         mi_wakeup;
  reg  [1:0]  mi_opsrc1;
  reg  [1:0]  mi_opsrc2;
  reg  [1:0]  mi_writeRf;
  reg  [2:0]  mi_exEngine;
  reg  [5:0]  mi_exOp;
  reg  [5:0]  mi_lsOp;
  reg         mi_exception;
  reg         mi_taken;
  reg  [31:0] mi_imm;
  reg  [4:0]  mi_rs1;
  reg  [4:0]  mi_rs2;
  reg  [4:0]  mi_rd;
  reg  [31:0] mi_pc;
  reg  [31:0] mi_targetPC;
  reg  [6:0]  mi_rs1Tag;
  reg         mi_rs1TagReady;
  reg  [6:0]  mi_rs2Tag;
  reg         mi_rs2TagReady;
  reg  [31:0] mi_rs1Data;
  reg  [31:0] mi_rs2Data;
  reg         mi_operandReady;
  reg         mi_flushed;
  reg  [6:0]  mi_arfTag;
  reg         mi_arfValid;
  reg  [31:0] mi_inst;
  wire        _GEN = io_in_bits_exOp[1:0] == 2'h0;
  wire        _GEN_0 = io_in_bits_exOp[1:0] == 2'h2;
  wire        _GEN_1 = _divider_io_in_ready & io_in_valid;
  wire        _GEN_2 = io_out_ready & _divider_io_out_valid;
  wire        _GEN_3 = _GEN_1 & _GEN_2 | _GEN_1;
  wire        _GEN_4 = _GEN_3 ? io_in_bits_retired : ~_GEN_2 & mi_retired;
  wire        _GEN_5 = _GEN_3 ? io_in_bits_isBranch : ~_GEN_2 & mi_isBranch;
  wire        _GEN_6 = _GEN_3 ? io_in_bits_isJAL : ~_GEN_2 & mi_isJAL;
  wire        _GEN_7 = _GEN_3 ? io_in_bits_wakeup : ~_GEN_2 & mi_wakeup;
  wire        _GEN_8 = _GEN_3 ? io_in_bits_exception : ~_GEN_2 & mi_exception;
  wire        _GEN_9 = _GEN_3 ? io_in_bits_taken : ~_GEN_2 & mi_taken;
  wire        _GEN_10 = _GEN_3 ? io_in_bits_rs1TagReady : ~_GEN_2 & mi_rs1TagReady;
  wire        _GEN_11 = _GEN_3 ? io_in_bits_rs2TagReady : ~_GEN_2 & mi_rs2TagReady;
  wire        _GEN_12 = _GEN_3 ? io_in_bits_operandReady : ~_GEN_2 & mi_operandReady;
  wire        _GEN_13 = _GEN_3 ? io_in_bits_flushed : ~_GEN_2 & mi_flushed;
  wire        _GEN_14 = _GEN_3 ? io_in_bits_arfValid : ~_GEN_2 & mi_arfValid;
  always @(posedge clock) begin
    if (reset) begin
      mi_retired <= 1'h0;
      mi_rdTag <= 7'h0;
      mi_isBranch <= 1'h0;
      mi_isJAL <= 1'h0;
      mi_lsType <= 2'h0;
      mi_wakeup <= 1'h0;
      mi_opsrc1 <= 2'h0;
      mi_opsrc2 <= 2'h0;
      mi_writeRf <= 2'h0;
      mi_exEngine <= 3'h0;
      mi_exOp <= 6'h0;
      mi_lsOp <= 6'h0;
      mi_exception <= 1'h0;
      mi_taken <= 1'h0;
      mi_imm <= 32'h0;
      mi_rs1 <= 5'h0;
      mi_rs2 <= 5'h0;
      mi_rd <= 5'h0;
      mi_pc <= 32'h0;
      mi_targetPC <= 32'h0;
      mi_rs1Tag <= 7'h0;
      mi_rs1TagReady <= 1'h0;
      mi_rs2Tag <= 7'h0;
      mi_rs2TagReady <= 1'h0;
      mi_rs1Data <= 32'h0;
      mi_rs2Data <= 32'h0;
      mi_operandReady <= 1'h0;
      mi_flushed <= 1'h0;
      mi_arfTag <= 7'h0;
      mi_arfValid <= 1'h0;
      mi_inst <= 32'h0;
    end
    else begin
      mi_retired <= ~io_flush & _GEN_4;
      if (io_flush) begin
        mi_rdTag <= 7'h0;
        mi_lsType <= 2'h0;
        mi_opsrc1 <= 2'h0;
        mi_opsrc2 <= 2'h0;
        mi_writeRf <= 2'h0;
        mi_exEngine <= 3'h0;
        mi_exOp <= 6'h0;
        mi_lsOp <= 6'h0;
        mi_imm <= 32'h0;
        mi_rs1 <= 5'h0;
        mi_rs2 <= 5'h0;
        mi_rd <= 5'h0;
        mi_pc <= 32'h0;
        mi_targetPC <= 32'h0;
        mi_rs1Tag <= 7'h0;
        mi_rs2Tag <= 7'h0;
        mi_rs1Data <= 32'h0;
        mi_rs2Data <= 32'h0;
        mi_arfTag <= 7'h0;
        mi_inst <= 32'h0;
      end
      else if (_GEN_3) begin
        mi_rdTag <= io_in_bits_rdTag;
        mi_lsType <= io_in_bits_lsType;
        mi_opsrc1 <= io_in_bits_opsrc1;
        mi_opsrc2 <= io_in_bits_opsrc2;
        mi_writeRf <= io_in_bits_writeRf;
        mi_exEngine <= io_in_bits_exEngine;
        mi_exOp <= io_in_bits_exOp;
        mi_lsOp <= io_in_bits_lsOp;
        mi_imm <= io_in_bits_imm;
        mi_rs1 <= io_in_bits_rs1;
        mi_rs2 <= io_in_bits_rs2;
        mi_rd <= io_in_bits_rd;
        mi_pc <= io_in_bits_pc;
        mi_targetPC <= io_in_bits_targetPC;
        mi_rs1Tag <= io_in_bits_rs1Tag;
        mi_rs2Tag <= io_in_bits_rs2Tag;
        mi_rs1Data <= io_in_bits_rs1Data;
        mi_rs2Data <= io_in_bits_rs2Data;
        mi_arfTag <= io_in_bits_arfTag;
        mi_inst <= io_in_bits_inst;
      end
      else if (_GEN_2) begin
        mi_rdTag <= 7'h0;
        mi_lsType <= 2'h0;
        mi_opsrc1 <= 2'h0;
        mi_opsrc2 <= 2'h0;
        mi_writeRf <= 2'h0;
        mi_exEngine <= 3'h0;
        mi_exOp <= 6'h0;
        mi_lsOp <= 6'h0;
        mi_imm <= 32'h0;
        mi_rs1 <= 5'h0;
        mi_rs2 <= 5'h0;
        mi_rd <= 5'h0;
        mi_pc <= 32'h0;
        mi_targetPC <= 32'h0;
        mi_rs1Tag <= 7'h0;
        mi_rs2Tag <= 7'h0;
        mi_rs1Data <= 32'h0;
        mi_rs2Data <= 32'h0;
        mi_arfTag <= 7'h0;
        mi_inst <= 32'h0;
      end
      mi_isBranch <= ~io_flush & _GEN_5;
      mi_isJAL <= ~io_flush & _GEN_6;
      mi_wakeup <= ~io_flush & _GEN_7;
      mi_exception <= ~io_flush & _GEN_8;
      mi_taken <= ~io_flush & _GEN_9;
      mi_rs1TagReady <= ~io_flush & _GEN_10;
      mi_rs2TagReady <= ~io_flush & _GEN_11;
      mi_operandReady <= ~io_flush & _GEN_12;
      mi_flushed <= ~io_flush & _GEN_13;
      mi_arfValid <= ~io_flush & _GEN_14;
    end
  end // always @(posedge)
  SRT16DividerDataModule divider (
    .clock        (clock),
    .reset        (reset | io_flush),
    .io_src_0     (io_in_bits_rs1Data),
    .io_src_1     (io_in_bits_rs2Data),
    .io_valid     (io_in_valid),
    .io_sign      (_GEN | _GEN_0),
    .io_isHi
      (~(_GEN | io_in_bits_exOp[1:0] == 2'h1) & (_GEN_0 | (&(io_in_bits_exOp[1:0])))),
    .io_in_ready  (_divider_io_in_ready),
    .io_out_valid (_divider_io_out_valid),
    .io_out_data  (io_out_bits_rdData),
    .io_out_ready (io_out_ready)
  );
  assign io_in_ready = _divider_io_in_ready;
  assign io_out_valid = _divider_io_out_valid;
  assign io_out_bits_retired = mi_retired;
  assign io_out_bits_rdTag = mi_rdTag;
  assign io_out_bits_isBranch = mi_isBranch;
  assign io_out_bits_isJAL = mi_isJAL;
  assign io_out_bits_lsType = mi_lsType;
  assign io_out_bits_wakeup = mi_wakeup;
  assign io_out_bits_opsrc1 = mi_opsrc1;
  assign io_out_bits_opsrc2 = mi_opsrc2;
  assign io_out_bits_writeRf = mi_writeRf;
  assign io_out_bits_exEngine = mi_exEngine;
  assign io_out_bits_exOp = mi_exOp;
  assign io_out_bits_lsOp = mi_lsOp;
  assign io_out_bits_exception = mi_exception;
  assign io_out_bits_taken = mi_taken;
  assign io_out_bits_imm = mi_imm;
  assign io_out_bits_rs1 = mi_rs1;
  assign io_out_bits_rs2 = mi_rs2;
  assign io_out_bits_rd = mi_rd;
  assign io_out_bits_pc = mi_pc;
  assign io_out_bits_targetPC = mi_targetPC;
  assign io_out_bits_rs1Tag = mi_rs1Tag;
  assign io_out_bits_rs1TagReady = mi_rs1TagReady;
  assign io_out_bits_rs2Tag = mi_rs2Tag;
  assign io_out_bits_rs2TagReady = mi_rs2TagReady;
  assign io_out_bits_rs1Data = mi_rs1Data;
  assign io_out_bits_rs2Data = mi_rs2Data;
  assign io_out_bits_operandReady = mi_operandReady;
  assign io_out_bits_flushed = mi_flushed;
  assign io_out_bits_arfTag = mi_arfTag;
  assign io_out_bits_arfValid = mi_arfValid;
  assign io_out_bits_inst = mi_inst;
endmodule

