// Generated by CIRCT firtool-1.76.0
module LSExtend(
  input  wire [31:0] io_inData,
  input  wire [5:0]  io_inlsOp,
  output wire [31:0] io_out
);

  wire [31:0] _GEN =
    io_inlsOp[4:0] == 5'h4 ? {24'h0, io_inData[7:0]} : {16'h0, io_inData[15:0]};
  wire [31:0] _GEN_0 = io_inlsOp[4:0] == 5'h3 ? io_inData : _GEN;
  wire [31:0] _GEN_1 =
    io_inlsOp[4:0] == 5'h2 ? {{16{io_inData[15]}}, io_inData[15:0]} : _GEN_0;
  assign io_out = io_inlsOp[4:0] == 5'h1 ? {{24{io_inData[7]}}, io_inData[7:0]} : _GEN_1;
endmodule

