// Generated by CIRCT firtool-1.76.0
module LSOverrideOperands(
  input  wire [31:0] io_targetAddrI,
  input  wire [31:0] io_rs2DataI,
  input  wire [6:0]  io_rdTagI,
  input  wire        io_lsOperandBus_0_valid,
  input  wire [31:0] io_lsOperandBus_0_bits_targetAddr,
  input  wire [31:0] io_lsOperandBus_0_bits_rs2Data,
  input  wire [6:0]  io_lsOperandBus_0_bits_rdTag,
  input  wire        io_lsOperandBus_1_valid,
  input  wire [31:0] io_lsOperandBus_1_bits_targetAddr,
  input  wire [31:0] io_lsOperandBus_1_bits_rs2Data,
  input  wire [6:0]  io_lsOperandBus_1_bits_rdTag,
  output wire [31:0] io_targetAddrO,
  output wire [31:0] io_rs2DataO,
  output wire        io_operandReadyO
);

  wire        operandBusMatches_1;
  wire        operandBusMatches_0;
  wire [1:0]  _io_operandReadyO_T = {operandBusMatches_1, operandBusMatches_0};
  assign operandBusMatches_0 =
    io_lsOperandBus_0_valid & io_rdTagI == io_lsOperandBus_0_bits_rdTag;
  assign operandBusMatches_1 =
    io_lsOperandBus_1_valid & io_rdTagI == io_lsOperandBus_1_bits_rdTag;
  wire [31:0] _GEN =
    operandBusMatches_0
      ? io_lsOperandBus_0_bits_targetAddr
      : io_lsOperandBus_1_bits_targetAddr;
  wire [31:0] _GEN_0 =
    operandBusMatches_0 ? io_lsOperandBus_0_bits_rs2Data : io_lsOperandBus_1_bits_rs2Data;
  assign io_targetAddrO = (|_io_operandReadyO_T) ? _GEN : io_targetAddrI;
  assign io_rs2DataO = (|_io_operandReadyO_T) ? _GEN_0 : io_rs2DataI;
  assign io_operandReadyO = |_io_operandReadyO_T;
endmodule

