// Generated by CIRCT firtool-1.76.0
module LSOverrideRetire_1(
  input  wire       io_in_bits_retired,
  input  wire [6:0] io_in_bits_rdTag,
  input  wire       io_storeRetireBus_0_valid,
  input  wire [6:0] io_storeRetireBus_0_bits_tag,
  input  wire       io_storeRetireBus_1_valid,
  input  wire [6:0] io_storeRetireBus_1_bits_tag,
  output wire       io_out_bits_retired
);

  assign io_out_bits_retired =
    |{io_in_bits_retired,
      io_storeRetireBus_1_valid & io_in_bits_rdTag == io_storeRetireBus_1_bits_tag,
      io_storeRetireBus_0_valid & io_in_bits_rdTag == io_storeRetireBus_0_bits_tag};
endmodule

