// Generated by CIRCT firtool-1.76.0
module LSSQStage(
  input  wire        clock,
  input  wire        reset,
  output wire        io_in_ready,
  input  wire        io_in_valid,
  input  wire        io_in_bits_retired,
  input  wire [6:0]  io_in_bits_rdTag,
  input  wire        io_in_bits_store,
  input  wire [31:0] io_in_bits_addr,
  input  wire [31:0] io_in_bits_inst,
  input  wire [31:0] io_in_bits_pc,
  input  wire        io_in_bits_flushed,
  input  wire [5:0]  io_in_bits_lsOp,
  input  wire [7:0]  io_in_bits_cacheData_0,
  input  wire [7:0]  io_in_bits_cacheData_1,
  input  wire [7:0]  io_in_bits_cacheData_2,
  input  wire [7:0]  io_in_bits_cacheData_3,
  input  wire [7:0]  io_in_bits_sqData_0,
  input  wire [7:0]  io_in_bits_sqData_1,
  input  wire [7:0]  io_in_bits_sqData_2,
  input  wire [7:0]  io_in_bits_sqData_3,
  input  wire        io_in_bits_sqwStrobe_0,
  input  wire        io_in_bits_sqwStrobe_1,
  input  wire        io_in_bits_sqwStrobe_2,
  input  wire        io_in_bits_sqwStrobe_3,
  input  wire        io_storeRetireBus_0_valid,
  input  wire [6:0]  io_storeRetireBus_0_bits_tag,
  input  wire        io_storeRetireBus_1_valid,
  input  wire [6:0]  io_storeRetireBus_1_bits_tag,
  input  wire        io_flush,
  output wire        io_selfRetired,
  input  wire        io_out_ready,
  output wire        io_out_valid,
  output wire [6:0]  io_out_bits_rdTag,
  output wire        io_out_bits_store,
  output wire [31:0] io_out_bits_addr,
  output wire [31:0] io_out_bits_inst,
  output wire [31:0] io_out_bits_pc,
  output wire        io_out_bits_flushed,
  output wire [5:0]  io_out_bits_lsOp,
  output wire [7:0]  io_out_bits_cacheData_0,
  output wire [7:0]  io_out_bits_cacheData_1,
  output wire [7:0]  io_out_bits_cacheData_2,
  output wire [7:0]  io_out_bits_cacheData_3,
  output wire [7:0]  io_out_bits_sqData_0,
  output wire [7:0]  io_out_bits_sqData_1,
  output wire [7:0]  io_out_bits_sqData_2,
  output wire [7:0]  io_out_bits_sqData_3,
  output wire        io_out_bits_sqwStrobe_0,
  output wire        io_out_bits_sqwStrobe_1,
  output wire        io_out_bits_sqwStrobe_2,
  output wire        io_out_bits_sqwStrobe_3,
  input  wire        io_outPeriph_ready,
  output wire        io_outPeriph_valid,
  output wire        io_outPeriph_bits_retired,
  output wire [6:0]  io_outPeriph_bits_rdTag,
  output wire        io_outPeriph_bits_store,
  output wire [31:0] io_outPeriph_bits_addr,
  output wire [31:0] io_outPeriph_bits_inst,
  output wire [31:0] io_outPeriph_bits_pc,
  output wire        io_outPeriph_bits_flushed,
  output wire [5:0]  io_outPeriph_bits_lsOp,
  output wire [7:0]  io_outPeriph_bits_cacheData_0,
  output wire [7:0]  io_outPeriph_bits_cacheData_1,
  output wire [7:0]  io_outPeriph_bits_cacheData_2,
  output wire [7:0]  io_outPeriph_bits_cacheData_3,
  output wire [7:0]  io_outPeriph_bits_sqData_0,
  output wire [7:0]  io_outPeriph_bits_sqData_1,
  output wire [7:0]  io_outPeriph_bits_sqData_2,
  output wire [7:0]  io_outPeriph_bits_sqData_3,
  output wire        io_outPeriph_bits_sqwStrobe_0,
  output wire        io_outPeriph_bits_sqwStrobe_1,
  output wire        io_outPeriph_bits_sqwStrobe_2,
  output wire        io_outPeriph_bits_sqwStrobe_3
);

  wire        _sq_io_in_ready;
  wire        _sq_io_out_valid;
  wire        _sq_io_out_bits_retired;
  wire [6:0]  _sq_io_out_bits_rdTag;
  wire        _sq_io_out_bits_store;
  wire [31:0] _sq_io_out_bits_addr;
  wire [31:0] _sq_io_out_bits_inst;
  wire [31:0] _sq_io_out_bits_pc;
  wire        _sq_io_out_bits_flushed;
  wire [5:0]  _sq_io_out_bits_lsOp;
  wire [7:0]  _sq_io_out_bits_cacheData_0;
  wire [7:0]  _sq_io_out_bits_cacheData_1;
  wire [7:0]  _sq_io_out_bits_cacheData_2;
  wire [7:0]  _sq_io_out_bits_cacheData_3;
  wire [7:0]  _sq_io_out_bits_sqData_0;
  wire [7:0]  _sq_io_out_bits_sqData_1;
  wire [7:0]  _sq_io_out_bits_sqData_2;
  wire [7:0]  _sq_io_out_bits_sqData_3;
  wire        _sq_io_out_bits_sqwStrobe_0;
  wire        _sq_io_out_bits_sqwStrobe_1;
  wire        _sq_io_out_bits_sqwStrobe_2;
  wire        _sq_io_out_bits_sqwStrobe_3;
  wire        _arbiter_io_in_0_ready;
  wire        _arbiter_io_in_1_ready;
  wire        _arbiter_io_out_valid;
  wire        _arbiter_io_out_bits_retired;
  wire [6:0]  _arbiter_io_out_bits_rdTag;
  wire        _arbiter_io_out_bits_store;
  wire [31:0] _arbiter_io_out_bits_addr;
  wire [31:0] _arbiter_io_out_bits_inst;
  wire [31:0] _arbiter_io_out_bits_pc;
  wire        _arbiter_io_out_bits_flushed;
  wire [5:0]  _arbiter_io_out_bits_lsOp;
  wire [7:0]  _arbiter_io_out_bits_cacheData_0;
  wire [7:0]  _arbiter_io_out_bits_cacheData_1;
  wire [7:0]  _arbiter_io_out_bits_cacheData_2;
  wire [7:0]  _arbiter_io_out_bits_cacheData_3;
  wire [7:0]  _arbiter_io_out_bits_sqData_0;
  wire [7:0]  _arbiter_io_out_bits_sqData_1;
  wire [7:0]  _arbiter_io_out_bits_sqData_2;
  wire [7:0]  _arbiter_io_out_bits_sqData_3;
  wire        _arbiter_io_out_bits_sqwStrobe_0;
  wire        _arbiter_io_out_bits_sqwStrobe_1;
  wire        _arbiter_io_out_bits_sqwStrobe_2;
  wire        _arbiter_io_out_bits_sqwStrobe_3;
  wire        _periphDemux_io_in_0_ready;
  wire        _periphDemux_io_out_1_0_valid;
  wire        _periphDemux_io_out_1_0_bits_retired;
  wire [6:0]  _periphDemux_io_out_1_0_bits_rdTag;
  wire        _periphDemux_io_out_1_0_bits_store;
  wire [31:0] _periphDemux_io_out_1_0_bits_addr;
  wire [31:0] _periphDemux_io_out_1_0_bits_inst;
  wire [31:0] _periphDemux_io_out_1_0_bits_pc;
  wire        _periphDemux_io_out_1_0_bits_flushed;
  wire [5:0]  _periphDemux_io_out_1_0_bits_lsOp;
  wire [7:0]  _periphDemux_io_out_1_0_bits_cacheData_0;
  wire [7:0]  _periphDemux_io_out_1_0_bits_cacheData_1;
  wire [7:0]  _periphDemux_io_out_1_0_bits_cacheData_2;
  wire [7:0]  _periphDemux_io_out_1_0_bits_cacheData_3;
  wire [7:0]  _periphDemux_io_out_1_0_bits_sqData_0;
  wire [7:0]  _periphDemux_io_out_1_0_bits_sqData_1;
  wire [7:0]  _periphDemux_io_out_1_0_bits_sqData_2;
  wire [7:0]  _periphDemux_io_out_1_0_bits_sqData_3;
  wire        _periphDemux_io_out_1_0_bits_sqwStrobe_0;
  wire        _periphDemux_io_out_1_0_bits_sqwStrobe_1;
  wire        _periphDemux_io_out_1_0_bits_sqwStrobe_2;
  wire        _periphDemux_io_out_1_0_bits_sqwStrobe_3;
  wire        _cacheDemux_io_in_0_ready;
  wire        _cacheDemux_io_out_0_0_valid;
  wire        _cacheDemux_io_out_0_0_bits_retired;
  wire [6:0]  _cacheDemux_io_out_0_0_bits_rdTag;
  wire        _cacheDemux_io_out_0_0_bits_store;
  wire [31:0] _cacheDemux_io_out_0_0_bits_addr;
  wire [31:0] _cacheDemux_io_out_0_0_bits_inst;
  wire [31:0] _cacheDemux_io_out_0_0_bits_pc;
  wire        _cacheDemux_io_out_0_0_bits_flushed;
  wire [5:0]  _cacheDemux_io_out_0_0_bits_lsOp;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_cacheData_0;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_cacheData_1;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_cacheData_2;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_cacheData_3;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_sqData_0;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_sqData_1;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_sqData_2;
  wire [7:0]  _cacheDemux_io_out_0_0_bits_sqData_3;
  wire        _cacheDemux_io_out_0_0_bits_sqwStrobe_0;
  wire        _cacheDemux_io_out_0_0_bits_sqwStrobe_1;
  wire        _cacheDemux_io_out_0_0_bits_sqwStrobe_2;
  wire        _cacheDemux_io_out_0_0_bits_sqwStrobe_3;
  wire        _cacheDemux_io_out_1_0_valid;
  wire        _cacheDemux_io_out_1_0_bits_retired;
  wire [6:0]  _cacheDemux_io_out_1_0_bits_rdTag;
  wire        _cacheDemux_io_out_1_0_bits_store;
  wire [31:0] _cacheDemux_io_out_1_0_bits_addr;
  wire [31:0] _cacheDemux_io_out_1_0_bits_inst;
  wire [31:0] _cacheDemux_io_out_1_0_bits_pc;
  wire        _cacheDemux_io_out_1_0_bits_flushed;
  wire [5:0]  _cacheDemux_io_out_1_0_bits_lsOp;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_cacheData_0;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_cacheData_1;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_cacheData_2;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_cacheData_3;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_sqData_0;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_sqData_1;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_sqData_2;
  wire [7:0]  _cacheDemux_io_out_1_0_bits_sqData_3;
  wire        _cacheDemux_io_out_1_0_bits_sqwStrobe_0;
  wire        _cacheDemux_io_out_1_0_bits_sqwStrobe_1;
  wire        _cacheDemux_io_out_1_0_bits_sqwStrobe_2;
  wire        _cacheDemux_io_out_1_0_bits_sqwStrobe_3;
  wire        _outRetireOverrider_io_in_ready;
  wire        _outRetireOverrider_io_out_valid;
  wire        _outRetireOverrider_io_out_bits_retired;
  wire        _outRetireOverrider_io_out_bits_flushed;
  wire        _inRetireOverrider_io_out_valid;
  wire        _inRetireOverrider_io_out_bits_retired;
  wire [6:0]  _inRetireOverrider_io_out_bits_rdTag;
  wire        _inRetireOverrider_io_out_bits_store;
  wire [31:0] _inRetireOverrider_io_out_bits_addr;
  wire [31:0] _inRetireOverrider_io_out_bits_inst;
  wire [31:0] _inRetireOverrider_io_out_bits_pc;
  wire        _inRetireOverrider_io_out_bits_flushed;
  wire [5:0]  _inRetireOverrider_io_out_bits_lsOp;
  wire [7:0]  _inRetireOverrider_io_out_bits_cacheData_0;
  wire [7:0]  _inRetireOverrider_io_out_bits_cacheData_1;
  wire [7:0]  _inRetireOverrider_io_out_bits_cacheData_2;
  wire [7:0]  _inRetireOverrider_io_out_bits_cacheData_3;
  wire [7:0]  _inRetireOverrider_io_out_bits_sqData_0;
  wire [7:0]  _inRetireOverrider_io_out_bits_sqData_1;
  wire [7:0]  _inRetireOverrider_io_out_bits_sqData_2;
  wire [7:0]  _inRetireOverrider_io_out_bits_sqData_3;
  wire        _inRetireOverrider_io_out_bits_sqwStrobe_0;
  wire        _inRetireOverrider_io_out_bits_sqwStrobe_1;
  wire        _inRetireOverrider_io_out_bits_sqwStrobe_2;
  wire        _inRetireOverrider_io_out_bits_sqwStrobe_3;
  wire        flushed =
    _outRetireOverrider_io_out_bits_flushed | io_flush
    & ~_outRetireOverrider_io_out_bits_retired;
  LSOverrideRetire inRetireOverrider (
    .io_in_ready                  (io_in_ready),
    .io_in_valid                  (io_in_valid),
    .io_in_bits_retired           (io_in_bits_retired),
    .io_in_bits_rdTag             (io_in_bits_rdTag),
    .io_in_bits_store             (io_in_bits_store),
    .io_in_bits_addr              (io_in_bits_addr),
    .io_in_bits_inst              (io_in_bits_inst),
    .io_in_bits_pc                (io_in_bits_pc),
    .io_in_bits_flushed           (io_in_bits_flushed),
    .io_in_bits_lsOp              (io_in_bits_lsOp),
    .io_in_bits_cacheData_0       (io_in_bits_cacheData_0),
    .io_in_bits_cacheData_1       (io_in_bits_cacheData_1),
    .io_in_bits_cacheData_2       (io_in_bits_cacheData_2),
    .io_in_bits_cacheData_3       (io_in_bits_cacheData_3),
    .io_in_bits_sqData_0          (io_in_bits_sqData_0),
    .io_in_bits_sqData_1          (io_in_bits_sqData_1),
    .io_in_bits_sqData_2          (io_in_bits_sqData_2),
    .io_in_bits_sqData_3          (io_in_bits_sqData_3),
    .io_in_bits_sqwStrobe_0       (io_in_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1       (io_in_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2       (io_in_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3       (io_in_bits_sqwStrobe_3),
    .io_storeRetireBus_0_valid    (io_storeRetireBus_0_valid),
    .io_storeRetireBus_0_bits_tag (io_storeRetireBus_0_bits_tag),
    .io_storeRetireBus_1_valid    (io_storeRetireBus_1_valid),
    .io_storeRetireBus_1_bits_tag (io_storeRetireBus_1_bits_tag),
    .io_out_ready                 (_periphDemux_io_in_0_ready),
    .io_out_valid                 (_inRetireOverrider_io_out_valid),
    .io_out_bits_retired          (_inRetireOverrider_io_out_bits_retired),
    .io_out_bits_rdTag            (_inRetireOverrider_io_out_bits_rdTag),
    .io_out_bits_store            (_inRetireOverrider_io_out_bits_store),
    .io_out_bits_addr             (_inRetireOverrider_io_out_bits_addr),
    .io_out_bits_inst             (_inRetireOverrider_io_out_bits_inst),
    .io_out_bits_pc               (_inRetireOverrider_io_out_bits_pc),
    .io_out_bits_flushed          (_inRetireOverrider_io_out_bits_flushed),
    .io_out_bits_lsOp             (_inRetireOverrider_io_out_bits_lsOp),
    .io_out_bits_cacheData_0      (_inRetireOverrider_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1      (_inRetireOverrider_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2      (_inRetireOverrider_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3      (_inRetireOverrider_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0         (_inRetireOverrider_io_out_bits_sqData_0),
    .io_out_bits_sqData_1         (_inRetireOverrider_io_out_bits_sqData_1),
    .io_out_bits_sqData_2         (_inRetireOverrider_io_out_bits_sqData_2),
    .io_out_bits_sqData_3         (_inRetireOverrider_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0      (_inRetireOverrider_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1      (_inRetireOverrider_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2      (_inRetireOverrider_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3      (_inRetireOverrider_io_out_bits_sqwStrobe_3)
  );
  LSOverrideRetire outRetireOverrider (
    .io_in_ready                  (_outRetireOverrider_io_in_ready),
    .io_in_valid                  (_arbiter_io_out_valid),
    .io_in_bits_retired           (_arbiter_io_out_bits_retired),
    .io_in_bits_rdTag             (_arbiter_io_out_bits_rdTag),
    .io_in_bits_store             (_arbiter_io_out_bits_store),
    .io_in_bits_addr              (_arbiter_io_out_bits_addr),
    .io_in_bits_inst              (_arbiter_io_out_bits_inst),
    .io_in_bits_pc                (_arbiter_io_out_bits_pc),
    .io_in_bits_flushed           (_arbiter_io_out_bits_flushed),
    .io_in_bits_lsOp              (_arbiter_io_out_bits_lsOp),
    .io_in_bits_cacheData_0       (_arbiter_io_out_bits_cacheData_0),
    .io_in_bits_cacheData_1       (_arbiter_io_out_bits_cacheData_1),
    .io_in_bits_cacheData_2       (_arbiter_io_out_bits_cacheData_2),
    .io_in_bits_cacheData_3       (_arbiter_io_out_bits_cacheData_3),
    .io_in_bits_sqData_0          (_arbiter_io_out_bits_sqData_0),
    .io_in_bits_sqData_1          (_arbiter_io_out_bits_sqData_1),
    .io_in_bits_sqData_2          (_arbiter_io_out_bits_sqData_2),
    .io_in_bits_sqData_3          (_arbiter_io_out_bits_sqData_3),
    .io_in_bits_sqwStrobe_0       (_arbiter_io_out_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1       (_arbiter_io_out_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2       (_arbiter_io_out_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3       (_arbiter_io_out_bits_sqwStrobe_3),
    .io_storeRetireBus_0_valid    (io_storeRetireBus_0_valid),
    .io_storeRetireBus_0_bits_tag (io_storeRetireBus_0_bits_tag),
    .io_storeRetireBus_1_valid    (io_storeRetireBus_1_valid),
    .io_storeRetireBus_1_bits_tag (io_storeRetireBus_1_bits_tag),
    .io_out_ready                 (io_out_ready),
    .io_out_valid                 (_outRetireOverrider_io_out_valid),
    .io_out_bits_retired          (_outRetireOverrider_io_out_bits_retired),
    .io_out_bits_rdTag            (io_out_bits_rdTag),
    .io_out_bits_store            (io_out_bits_store),
    .io_out_bits_addr             (io_out_bits_addr),
    .io_out_bits_inst             (io_out_bits_inst),
    .io_out_bits_pc               (io_out_bits_pc),
    .io_out_bits_flushed          (_outRetireOverrider_io_out_bits_flushed),
    .io_out_bits_lsOp             (io_out_bits_lsOp),
    .io_out_bits_cacheData_0      (io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1      (io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2      (io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3      (io_out_bits_cacheData_3),
    .io_out_bits_sqData_0         (/* unused */),
    .io_out_bits_sqData_1         (/* unused */),
    .io_out_bits_sqData_2         (/* unused */),
    .io_out_bits_sqData_3         (/* unused */),
    .io_out_bits_sqwStrobe_0      (/* unused */),
    .io_out_bits_sqwStrobe_1      (/* unused */),
    .io_out_bits_sqwStrobe_2      (/* unused */),
    .io_out_bits_sqwStrobe_3      (/* unused */)
  );
  DCDemux cacheDemux (
    .io_sel_0                    (io_in_bits_store),
    .io_in_0_ready               (_cacheDemux_io_in_0_ready),
    .io_in_0_valid               (_periphDemux_io_out_1_0_valid),
    .io_in_0_bits_retired        (_periphDemux_io_out_1_0_bits_retired),
    .io_in_0_bits_rdTag          (_periphDemux_io_out_1_0_bits_rdTag),
    .io_in_0_bits_store          (_periphDemux_io_out_1_0_bits_store),
    .io_in_0_bits_addr           (_periphDemux_io_out_1_0_bits_addr),
    .io_in_0_bits_inst           (_periphDemux_io_out_1_0_bits_inst),
    .io_in_0_bits_pc             (_periphDemux_io_out_1_0_bits_pc),
    .io_in_0_bits_flushed        (_periphDemux_io_out_1_0_bits_flushed),
    .io_in_0_bits_lsOp           (_periphDemux_io_out_1_0_bits_lsOp),
    .io_in_0_bits_cacheData_0    (_periphDemux_io_out_1_0_bits_cacheData_0),
    .io_in_0_bits_cacheData_1    (_periphDemux_io_out_1_0_bits_cacheData_1),
    .io_in_0_bits_cacheData_2    (_periphDemux_io_out_1_0_bits_cacheData_2),
    .io_in_0_bits_cacheData_3    (_periphDemux_io_out_1_0_bits_cacheData_3),
    .io_in_0_bits_sqData_0       (_periphDemux_io_out_1_0_bits_sqData_0),
    .io_in_0_bits_sqData_1       (_periphDemux_io_out_1_0_bits_sqData_1),
    .io_in_0_bits_sqData_2       (_periphDemux_io_out_1_0_bits_sqData_2),
    .io_in_0_bits_sqData_3       (_periphDemux_io_out_1_0_bits_sqData_3),
    .io_in_0_bits_sqwStrobe_0    (_periphDemux_io_out_1_0_bits_sqwStrobe_0),
    .io_in_0_bits_sqwStrobe_1    (_periphDemux_io_out_1_0_bits_sqwStrobe_1),
    .io_in_0_bits_sqwStrobe_2    (_periphDemux_io_out_1_0_bits_sqwStrobe_2),
    .io_in_0_bits_sqwStrobe_3    (_periphDemux_io_out_1_0_bits_sqwStrobe_3),
    .io_out_0_0_ready            (_arbiter_io_in_0_ready),
    .io_out_0_0_valid            (_cacheDemux_io_out_0_0_valid),
    .io_out_0_0_bits_retired     (_cacheDemux_io_out_0_0_bits_retired),
    .io_out_0_0_bits_rdTag       (_cacheDemux_io_out_0_0_bits_rdTag),
    .io_out_0_0_bits_store       (_cacheDemux_io_out_0_0_bits_store),
    .io_out_0_0_bits_addr        (_cacheDemux_io_out_0_0_bits_addr),
    .io_out_0_0_bits_inst        (_cacheDemux_io_out_0_0_bits_inst),
    .io_out_0_0_bits_pc          (_cacheDemux_io_out_0_0_bits_pc),
    .io_out_0_0_bits_flushed     (_cacheDemux_io_out_0_0_bits_flushed),
    .io_out_0_0_bits_lsOp        (_cacheDemux_io_out_0_0_bits_lsOp),
    .io_out_0_0_bits_cacheData_0 (_cacheDemux_io_out_0_0_bits_cacheData_0),
    .io_out_0_0_bits_cacheData_1 (_cacheDemux_io_out_0_0_bits_cacheData_1),
    .io_out_0_0_bits_cacheData_2 (_cacheDemux_io_out_0_0_bits_cacheData_2),
    .io_out_0_0_bits_cacheData_3 (_cacheDemux_io_out_0_0_bits_cacheData_3),
    .io_out_0_0_bits_sqData_0    (_cacheDemux_io_out_0_0_bits_sqData_0),
    .io_out_0_0_bits_sqData_1    (_cacheDemux_io_out_0_0_bits_sqData_1),
    .io_out_0_0_bits_sqData_2    (_cacheDemux_io_out_0_0_bits_sqData_2),
    .io_out_0_0_bits_sqData_3    (_cacheDemux_io_out_0_0_bits_sqData_3),
    .io_out_0_0_bits_sqwStrobe_0 (_cacheDemux_io_out_0_0_bits_sqwStrobe_0),
    .io_out_0_0_bits_sqwStrobe_1 (_cacheDemux_io_out_0_0_bits_sqwStrobe_1),
    .io_out_0_0_bits_sqwStrobe_2 (_cacheDemux_io_out_0_0_bits_sqwStrobe_2),
    .io_out_0_0_bits_sqwStrobe_3 (_cacheDemux_io_out_0_0_bits_sqwStrobe_3),
    .io_out_1_0_ready            (_sq_io_in_ready),
    .io_out_1_0_valid            (_cacheDemux_io_out_1_0_valid),
    .io_out_1_0_bits_retired     (_cacheDemux_io_out_1_0_bits_retired),
    .io_out_1_0_bits_rdTag       (_cacheDemux_io_out_1_0_bits_rdTag),
    .io_out_1_0_bits_store       (_cacheDemux_io_out_1_0_bits_store),
    .io_out_1_0_bits_addr        (_cacheDemux_io_out_1_0_bits_addr),
    .io_out_1_0_bits_inst        (_cacheDemux_io_out_1_0_bits_inst),
    .io_out_1_0_bits_pc          (_cacheDemux_io_out_1_0_bits_pc),
    .io_out_1_0_bits_flushed     (_cacheDemux_io_out_1_0_bits_flushed),
    .io_out_1_0_bits_lsOp        (_cacheDemux_io_out_1_0_bits_lsOp),
    .io_out_1_0_bits_cacheData_0 (_cacheDemux_io_out_1_0_bits_cacheData_0),
    .io_out_1_0_bits_cacheData_1 (_cacheDemux_io_out_1_0_bits_cacheData_1),
    .io_out_1_0_bits_cacheData_2 (_cacheDemux_io_out_1_0_bits_cacheData_2),
    .io_out_1_0_bits_cacheData_3 (_cacheDemux_io_out_1_0_bits_cacheData_3),
    .io_out_1_0_bits_sqData_0    (_cacheDemux_io_out_1_0_bits_sqData_0),
    .io_out_1_0_bits_sqData_1    (_cacheDemux_io_out_1_0_bits_sqData_1),
    .io_out_1_0_bits_sqData_2    (_cacheDemux_io_out_1_0_bits_sqData_2),
    .io_out_1_0_bits_sqData_3    (_cacheDemux_io_out_1_0_bits_sqData_3),
    .io_out_1_0_bits_sqwStrobe_0 (_cacheDemux_io_out_1_0_bits_sqwStrobe_0),
    .io_out_1_0_bits_sqwStrobe_1 (_cacheDemux_io_out_1_0_bits_sqwStrobe_1),
    .io_out_1_0_bits_sqwStrobe_2 (_cacheDemux_io_out_1_0_bits_sqwStrobe_2),
    .io_out_1_0_bits_sqwStrobe_3 (_cacheDemux_io_out_1_0_bits_sqwStrobe_3)
  );
  DCDemux periphDemux (
    .io_sel_0
      (~(~(io_in_bits_addr[31]) & (|(io_in_bits_addr[31:29])))),
    .io_in_0_ready               (_periphDemux_io_in_0_ready),
    .io_in_0_valid               (_inRetireOverrider_io_out_valid),
    .io_in_0_bits_retired        (_inRetireOverrider_io_out_bits_retired),
    .io_in_0_bits_rdTag          (_inRetireOverrider_io_out_bits_rdTag),
    .io_in_0_bits_store          (_inRetireOverrider_io_out_bits_store),
    .io_in_0_bits_addr           (_inRetireOverrider_io_out_bits_addr),
    .io_in_0_bits_inst           (_inRetireOverrider_io_out_bits_inst),
    .io_in_0_bits_pc             (_inRetireOverrider_io_out_bits_pc),
    .io_in_0_bits_flushed        (_inRetireOverrider_io_out_bits_flushed),
    .io_in_0_bits_lsOp           (_inRetireOverrider_io_out_bits_lsOp),
    .io_in_0_bits_cacheData_0    (_inRetireOverrider_io_out_bits_cacheData_0),
    .io_in_0_bits_cacheData_1    (_inRetireOverrider_io_out_bits_cacheData_1),
    .io_in_0_bits_cacheData_2    (_inRetireOverrider_io_out_bits_cacheData_2),
    .io_in_0_bits_cacheData_3    (_inRetireOverrider_io_out_bits_cacheData_3),
    .io_in_0_bits_sqData_0       (_inRetireOverrider_io_out_bits_sqData_0),
    .io_in_0_bits_sqData_1       (_inRetireOverrider_io_out_bits_sqData_1),
    .io_in_0_bits_sqData_2       (_inRetireOverrider_io_out_bits_sqData_2),
    .io_in_0_bits_sqData_3       (_inRetireOverrider_io_out_bits_sqData_3),
    .io_in_0_bits_sqwStrobe_0    (_inRetireOverrider_io_out_bits_sqwStrobe_0),
    .io_in_0_bits_sqwStrobe_1    (_inRetireOverrider_io_out_bits_sqwStrobe_1),
    .io_in_0_bits_sqwStrobe_2    (_inRetireOverrider_io_out_bits_sqwStrobe_2),
    .io_in_0_bits_sqwStrobe_3    (_inRetireOverrider_io_out_bits_sqwStrobe_3),
    .io_out_0_0_ready            (io_outPeriph_ready),
    .io_out_0_0_valid            (io_outPeriph_valid),
    .io_out_0_0_bits_retired     (io_outPeriph_bits_retired),
    .io_out_0_0_bits_rdTag       (io_outPeriph_bits_rdTag),
    .io_out_0_0_bits_store       (io_outPeriph_bits_store),
    .io_out_0_0_bits_addr        (io_outPeriph_bits_addr),
    .io_out_0_0_bits_inst        (io_outPeriph_bits_inst),
    .io_out_0_0_bits_pc          (io_outPeriph_bits_pc),
    .io_out_0_0_bits_flushed     (io_outPeriph_bits_flushed),
    .io_out_0_0_bits_lsOp        (io_outPeriph_bits_lsOp),
    .io_out_0_0_bits_cacheData_0 (io_outPeriph_bits_cacheData_0),
    .io_out_0_0_bits_cacheData_1 (io_outPeriph_bits_cacheData_1),
    .io_out_0_0_bits_cacheData_2 (io_outPeriph_bits_cacheData_2),
    .io_out_0_0_bits_cacheData_3 (io_outPeriph_bits_cacheData_3),
    .io_out_0_0_bits_sqData_0    (io_outPeriph_bits_sqData_0),
    .io_out_0_0_bits_sqData_1    (io_outPeriph_bits_sqData_1),
    .io_out_0_0_bits_sqData_2    (io_outPeriph_bits_sqData_2),
    .io_out_0_0_bits_sqData_3    (io_outPeriph_bits_sqData_3),
    .io_out_0_0_bits_sqwStrobe_0 (io_outPeriph_bits_sqwStrobe_0),
    .io_out_0_0_bits_sqwStrobe_1 (io_outPeriph_bits_sqwStrobe_1),
    .io_out_0_0_bits_sqwStrobe_2 (io_outPeriph_bits_sqwStrobe_2),
    .io_out_0_0_bits_sqwStrobe_3 (io_outPeriph_bits_sqwStrobe_3),
    .io_out_1_0_ready            (_cacheDemux_io_in_0_ready),
    .io_out_1_0_valid            (_periphDemux_io_out_1_0_valid),
    .io_out_1_0_bits_retired     (_periphDemux_io_out_1_0_bits_retired),
    .io_out_1_0_bits_rdTag       (_periphDemux_io_out_1_0_bits_rdTag),
    .io_out_1_0_bits_store       (_periphDemux_io_out_1_0_bits_store),
    .io_out_1_0_bits_addr        (_periphDemux_io_out_1_0_bits_addr),
    .io_out_1_0_bits_inst        (_periphDemux_io_out_1_0_bits_inst),
    .io_out_1_0_bits_pc          (_periphDemux_io_out_1_0_bits_pc),
    .io_out_1_0_bits_flushed     (_periphDemux_io_out_1_0_bits_flushed),
    .io_out_1_0_bits_lsOp        (_periphDemux_io_out_1_0_bits_lsOp),
    .io_out_1_0_bits_cacheData_0 (_periphDemux_io_out_1_0_bits_cacheData_0),
    .io_out_1_0_bits_cacheData_1 (_periphDemux_io_out_1_0_bits_cacheData_1),
    .io_out_1_0_bits_cacheData_2 (_periphDemux_io_out_1_0_bits_cacheData_2),
    .io_out_1_0_bits_cacheData_3 (_periphDemux_io_out_1_0_bits_cacheData_3),
    .io_out_1_0_bits_sqData_0    (_periphDemux_io_out_1_0_bits_sqData_0),
    .io_out_1_0_bits_sqData_1    (_periphDemux_io_out_1_0_bits_sqData_1),
    .io_out_1_0_bits_sqData_2    (_periphDemux_io_out_1_0_bits_sqData_2),
    .io_out_1_0_bits_sqData_3    (_periphDemux_io_out_1_0_bits_sqData_3),
    .io_out_1_0_bits_sqwStrobe_0 (_periphDemux_io_out_1_0_bits_sqwStrobe_0),
    .io_out_1_0_bits_sqwStrobe_1 (_periphDemux_io_out_1_0_bits_sqwStrobe_1),
    .io_out_1_0_bits_sqwStrobe_2 (_periphDemux_io_out_1_0_bits_sqwStrobe_2),
    .io_out_1_0_bits_sqwStrobe_3 (_periphDemux_io_out_1_0_bits_sqwStrobe_3)
  );
  Arbiter2_LSCMI arbiter (
    .io_in_0_ready            (_arbiter_io_in_0_ready),
    .io_in_0_valid            (_cacheDemux_io_out_0_0_valid),
    .io_in_0_bits_retired     (_cacheDemux_io_out_0_0_bits_retired),
    .io_in_0_bits_rdTag       (_cacheDemux_io_out_0_0_bits_rdTag),
    .io_in_0_bits_store       (_cacheDemux_io_out_0_0_bits_store),
    .io_in_0_bits_addr        (_cacheDemux_io_out_0_0_bits_addr),
    .io_in_0_bits_inst        (_cacheDemux_io_out_0_0_bits_inst),
    .io_in_0_bits_pc          (_cacheDemux_io_out_0_0_bits_pc),
    .io_in_0_bits_flushed     (_cacheDemux_io_out_0_0_bits_flushed),
    .io_in_0_bits_lsOp        (_cacheDemux_io_out_0_0_bits_lsOp),
    .io_in_0_bits_cacheData_0 (_cacheDemux_io_out_0_0_bits_cacheData_0),
    .io_in_0_bits_cacheData_1 (_cacheDemux_io_out_0_0_bits_cacheData_1),
    .io_in_0_bits_cacheData_2 (_cacheDemux_io_out_0_0_bits_cacheData_2),
    .io_in_0_bits_cacheData_3 (_cacheDemux_io_out_0_0_bits_cacheData_3),
    .io_in_0_bits_sqData_0    (_cacheDemux_io_out_0_0_bits_sqData_0),
    .io_in_0_bits_sqData_1    (_cacheDemux_io_out_0_0_bits_sqData_1),
    .io_in_0_bits_sqData_2    (_cacheDemux_io_out_0_0_bits_sqData_2),
    .io_in_0_bits_sqData_3    (_cacheDemux_io_out_0_0_bits_sqData_3),
    .io_in_0_bits_sqwStrobe_0 (_cacheDemux_io_out_0_0_bits_sqwStrobe_0),
    .io_in_0_bits_sqwStrobe_1 (_cacheDemux_io_out_0_0_bits_sqwStrobe_1),
    .io_in_0_bits_sqwStrobe_2 (_cacheDemux_io_out_0_0_bits_sqwStrobe_2),
    .io_in_0_bits_sqwStrobe_3 (_cacheDemux_io_out_0_0_bits_sqwStrobe_3),
    .io_in_1_ready            (_arbiter_io_in_1_ready),
    .io_in_1_valid            (_sq_io_out_valid),
    .io_in_1_bits_retired     (_sq_io_out_bits_retired),
    .io_in_1_bits_rdTag       (_sq_io_out_bits_rdTag),
    .io_in_1_bits_store       (_sq_io_out_bits_store),
    .io_in_1_bits_addr        (_sq_io_out_bits_addr),
    .io_in_1_bits_inst        (_sq_io_out_bits_inst),
    .io_in_1_bits_pc          (_sq_io_out_bits_pc),
    .io_in_1_bits_flushed     (_sq_io_out_bits_flushed),
    .io_in_1_bits_lsOp        (_sq_io_out_bits_lsOp),
    .io_in_1_bits_cacheData_0 (_sq_io_out_bits_cacheData_0),
    .io_in_1_bits_cacheData_1 (_sq_io_out_bits_cacheData_1),
    .io_in_1_bits_cacheData_2 (_sq_io_out_bits_cacheData_2),
    .io_in_1_bits_cacheData_3 (_sq_io_out_bits_cacheData_3),
    .io_in_1_bits_sqData_0    (_sq_io_out_bits_sqData_0),
    .io_in_1_bits_sqData_1    (_sq_io_out_bits_sqData_1),
    .io_in_1_bits_sqData_2    (_sq_io_out_bits_sqData_2),
    .io_in_1_bits_sqData_3    (_sq_io_out_bits_sqData_3),
    .io_in_1_bits_sqwStrobe_0 (_sq_io_out_bits_sqwStrobe_0),
    .io_in_1_bits_sqwStrobe_1 (_sq_io_out_bits_sqwStrobe_1),
    .io_in_1_bits_sqwStrobe_2 (_sq_io_out_bits_sqwStrobe_2),
    .io_in_1_bits_sqwStrobe_3 (_sq_io_out_bits_sqwStrobe_3),
    .io_out_ready             (_outRetireOverrider_io_in_ready),
    .io_out_valid             (_arbiter_io_out_valid),
    .io_out_bits_retired      (_arbiter_io_out_bits_retired),
    .io_out_bits_rdTag        (_arbiter_io_out_bits_rdTag),
    .io_out_bits_store        (_arbiter_io_out_bits_store),
    .io_out_bits_addr         (_arbiter_io_out_bits_addr),
    .io_out_bits_inst         (_arbiter_io_out_bits_inst),
    .io_out_bits_pc           (_arbiter_io_out_bits_pc),
    .io_out_bits_flushed      (_arbiter_io_out_bits_flushed),
    .io_out_bits_lsOp         (_arbiter_io_out_bits_lsOp),
    .io_out_bits_cacheData_0  (_arbiter_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1  (_arbiter_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2  (_arbiter_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3  (_arbiter_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0     (_arbiter_io_out_bits_sqData_0),
    .io_out_bits_sqData_1     (_arbiter_io_out_bits_sqData_1),
    .io_out_bits_sqData_2     (_arbiter_io_out_bits_sqData_2),
    .io_out_bits_sqData_3     (_arbiter_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0  (_arbiter_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1  (_arbiter_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2  (_arbiter_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3  (_arbiter_io_out_bits_sqwStrobe_3)
  );
  LSStoreQueue sq (
    .clock                          (clock),
    .reset                          (reset),
    .io_in_ready                    (_sq_io_in_ready),
    .io_in_valid                    (_cacheDemux_io_out_1_0_valid),
    .io_in_bits_retired             (_cacheDemux_io_out_1_0_bits_retired),
    .io_in_bits_rdTag               (_cacheDemux_io_out_1_0_bits_rdTag),
    .io_in_bits_store               (_cacheDemux_io_out_1_0_bits_store),
    .io_in_bits_addr                (_cacheDemux_io_out_1_0_bits_addr),
    .io_in_bits_inst                (_cacheDemux_io_out_1_0_bits_inst),
    .io_in_bits_pc                  (_cacheDemux_io_out_1_0_bits_pc),
    .io_in_bits_flushed             (_cacheDemux_io_out_1_0_bits_flushed),
    .io_in_bits_lsOp                (_cacheDemux_io_out_1_0_bits_lsOp),
    .io_in_bits_cacheData_0         (_cacheDemux_io_out_1_0_bits_cacheData_0),
    .io_in_bits_cacheData_1         (_cacheDemux_io_out_1_0_bits_cacheData_1),
    .io_in_bits_cacheData_2         (_cacheDemux_io_out_1_0_bits_cacheData_2),
    .io_in_bits_cacheData_3         (_cacheDemux_io_out_1_0_bits_cacheData_3),
    .io_in_bits_sqData_0            (_cacheDemux_io_out_1_0_bits_sqData_0),
    .io_in_bits_sqData_1            (_cacheDemux_io_out_1_0_bits_sqData_1),
    .io_in_bits_sqData_2            (_cacheDemux_io_out_1_0_bits_sqData_2),
    .io_in_bits_sqData_3            (_cacheDemux_io_out_1_0_bits_sqData_3),
    .io_in_bits_sqwStrobe_0         (_cacheDemux_io_out_1_0_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1         (_cacheDemux_io_out_1_0_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2         (_cacheDemux_io_out_1_0_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3         (_cacheDemux_io_out_1_0_bits_sqwStrobe_3),
    .io_camReadIn                   (io_in_bits_addr),
    .io_storeRetireBus_0_valid      (io_storeRetireBus_0_valid),
    .io_storeRetireBus_0_bits_tag   (io_storeRetireBus_0_bits_tag),
    .io_storeRetireBus_1_valid      (io_storeRetireBus_1_valid),
    .io_storeRetireBus_1_bits_tag   (io_storeRetireBus_1_bits_tag),
    .io_flush                       (io_flush),
    .io_camReadOut_bits_sqData_0    (io_out_bits_sqData_0),
    .io_camReadOut_bits_sqData_1    (io_out_bits_sqData_1),
    .io_camReadOut_bits_sqData_2    (io_out_bits_sqData_2),
    .io_camReadOut_bits_sqData_3    (io_out_bits_sqData_3),
    .io_camReadOut_bits_sqwStrobe_0 (io_out_bits_sqwStrobe_0),
    .io_camReadOut_bits_sqwStrobe_1 (io_out_bits_sqwStrobe_1),
    .io_camReadOut_bits_sqwStrobe_2 (io_out_bits_sqwStrobe_2),
    .io_camReadOut_bits_sqwStrobe_3 (io_out_bits_sqwStrobe_3),
    .io_out_ready                   (_arbiter_io_in_1_ready),
    .io_out_valid                   (_sq_io_out_valid),
    .io_out_bits_retired            (_sq_io_out_bits_retired),
    .io_out_bits_rdTag              (_sq_io_out_bits_rdTag),
    .io_out_bits_store              (_sq_io_out_bits_store),
    .io_out_bits_addr               (_sq_io_out_bits_addr),
    .io_out_bits_inst               (_sq_io_out_bits_inst),
    .io_out_bits_pc                 (_sq_io_out_bits_pc),
    .io_out_bits_flushed            (_sq_io_out_bits_flushed),
    .io_out_bits_lsOp               (_sq_io_out_bits_lsOp),
    .io_out_bits_cacheData_0        (_sq_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1        (_sq_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2        (_sq_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3        (_sq_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0           (_sq_io_out_bits_sqData_0),
    .io_out_bits_sqData_1           (_sq_io_out_bits_sqData_1),
    .io_out_bits_sqData_2           (_sq_io_out_bits_sqData_2),
    .io_out_bits_sqData_3           (_sq_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0        (_sq_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1        (_sq_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2        (_sq_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3        (_sq_io_out_bits_sqwStrobe_3)
  );
  assign io_selfRetired = _outRetireOverrider_io_out_bits_retired;
  assign io_out_valid = ~flushed & _outRetireOverrider_io_out_valid;
  assign io_out_bits_flushed = flushed;
endmodule

