// Generated by CIRCT firtool-1.76.0
module LSUnit(
  input  wire         clock,
  input  wire         reset,
  output wire         io_in_0_ready,
  input  wire         io_in_0_valid,
  input  wire         io_in_0_bits_retired,
  input  wire [6:0]   io_in_0_bits_rdTag,
  input  wire         io_in_0_bits_isBranch,
  input  wire         io_in_0_bits_isJAL,
  input  wire [1:0]   io_in_0_bits_lsType,
  input  wire         io_in_0_bits_wakeup,
  input  wire [1:0]   io_in_0_bits_opsrc1,
  input  wire [1:0]   io_in_0_bits_opsrc2,
  input  wire [1:0]   io_in_0_bits_writeRf,
  input  wire [2:0]   io_in_0_bits_exEngine,
  input  wire [5:0]   io_in_0_bits_exOp,
  input  wire [5:0]   io_in_0_bits_lsOp,
  input  wire         io_in_0_bits_exception,
  input  wire         io_in_0_bits_taken,
  input  wire [31:0]  io_in_0_bits_imm,
  input  wire [4:0]   io_in_0_bits_rs1,
  input  wire [4:0]   io_in_0_bits_rs2,
  input  wire [4:0]   io_in_0_bits_rd,
  input  wire [31:0]  io_in_0_bits_pc,
  input  wire [31:0]  io_in_0_bits_targetPC,
  input  wire [6:0]   io_in_0_bits_rs1Tag,
  input  wire         io_in_0_bits_rs1TagReady,
  input  wire [6:0]   io_in_0_bits_rs2Tag,
  input  wire         io_in_0_bits_rs2TagReady,
  input  wire [31:0]  io_in_0_bits_rs1Data,
  input  wire [31:0]  io_in_0_bits_rs2Data,
  input  wire [31:0]  io_in_0_bits_rdData,
  input  wire         io_in_0_bits_operandReady,
  input  wire         io_in_0_bits_flushed,
  input  wire [6:0]   io_in_0_bits_arfTag,
  input  wire         io_in_0_bits_arfValid,
  input  wire [31:0]  io_in_0_bits_inst,
  output wire         io_in_1_ready,
  input  wire         io_in_1_valid,
  input  wire         io_in_1_bits_retired,
  input  wire [6:0]   io_in_1_bits_rdTag,
  input  wire         io_in_1_bits_isBranch,
  input  wire         io_in_1_bits_isJAL,
  input  wire [1:0]   io_in_1_bits_lsType,
  input  wire         io_in_1_bits_wakeup,
  input  wire [1:0]   io_in_1_bits_opsrc1,
  input  wire [1:0]   io_in_1_bits_opsrc2,
  input  wire [1:0]   io_in_1_bits_writeRf,
  input  wire [2:0]   io_in_1_bits_exEngine,
  input  wire [5:0]   io_in_1_bits_exOp,
  input  wire [5:0]   io_in_1_bits_lsOp,
  input  wire         io_in_1_bits_exception,
  input  wire         io_in_1_bits_taken,
  input  wire [31:0]  io_in_1_bits_imm,
  input  wire [4:0]   io_in_1_bits_rs1,
  input  wire [4:0]   io_in_1_bits_rs2,
  input  wire [4:0]   io_in_1_bits_rd,
  input  wire [31:0]  io_in_1_bits_pc,
  input  wire [31:0]  io_in_1_bits_targetPC,
  input  wire [6:0]   io_in_1_bits_rs1Tag,
  input  wire         io_in_1_bits_rs1TagReady,
  input  wire [6:0]   io_in_1_bits_rs2Tag,
  input  wire         io_in_1_bits_rs2TagReady,
  input  wire [31:0]  io_in_1_bits_rs1Data,
  input  wire [31:0]  io_in_1_bits_rs2Data,
  input  wire [31:0]  io_in_1_bits_rdData,
  input  wire         io_in_1_bits_operandReady,
  input  wire         io_in_1_bits_flushed,
  input  wire [6:0]   io_in_1_bits_arfTag,
  input  wire         io_in_1_bits_arfValid,
  input  wire [31:0]  io_in_1_bits_inst,
  input  wire         io_storeRetireBus_0_valid,
  input  wire [6:0]   io_storeRetireBus_0_bits_tag,
  input  wire         io_storeRetireBus_1_valid,
  input  wire [6:0]   io_storeRetireBus_1_bits_tag,
  input  wire         io_lsOperandBus_0_valid,
  input  wire [31:0]  io_lsOperandBus_0_bits_targetAddr,
  input  wire [31:0]  io_lsOperandBus_0_bits_rs2Data,
  input  wire [6:0]   io_lsOperandBus_0_bits_rdTag,
  input  wire         io_lsOperandBus_1_valid,
  input  wire [31:0]  io_lsOperandBus_1_bits_targetAddr,
  input  wire [31:0]  io_lsOperandBus_1_bits_rs2Data,
  input  wire [6:0]   io_lsOperandBus_1_bits_rdTag,
  input  wire         io_flush,
  output wire         io_selfRetired_0,
  output wire         io_selfRetired_1,
  output wire         io_out_0_valid,
  output wire [6:0]   io_out_0_bits_tag,
  output wire [31:0]  io_out_0_bits_data,
  input  wire         io_mem_req_ready,
  output wire         io_mem_req_valid,
  output wire [31:0]  io_mem_req_bits_addr,
  output wire [127:0] io_mem_req_bits_data,
  output wire         io_mem_req_bits_wen,
  output wire         io_mem_resp_ready,
  input  wire         io_mem_resp_valid,
  input  wire [127:0] io_mem_resp_bits_data,
  input  wire         io_uart_rx,
  output wire         io_uart_tx
);

  wire        _uart_io_wb_ack;
  wire [31:0] _uart_io_wb_dat_o;
  wire        _lswishbone_io_in_ready;
  wire        _lswishbone_io_out_valid;
  wire        _lswishbone_io_out_bits_retired;
  wire [6:0]  _lswishbone_io_out_bits_rdTag;
  wire        _lswishbone_io_out_bits_store;
  wire [31:0] _lswishbone_io_out_bits_addr;
  wire [31:0] _lswishbone_io_out_bits_inst;
  wire [31:0] _lswishbone_io_out_bits_pc;
  wire        _lswishbone_io_out_bits_flushed;
  wire [5:0]  _lswishbone_io_out_bits_lsOp;
  wire [7:0]  _lswishbone_io_out_bits_cacheData_0;
  wire [7:0]  _lswishbone_io_out_bits_cacheData_1;
  wire [7:0]  _lswishbone_io_out_bits_cacheData_2;
  wire [7:0]  _lswishbone_io_out_bits_cacheData_3;
  wire [7:0]  _lswishbone_io_out_bits_sqData_0;
  wire [7:0]  _lswishbone_io_out_bits_sqData_1;
  wire [7:0]  _lswishbone_io_out_bits_sqData_2;
  wire [7:0]  _lswishbone_io_out_bits_sqData_3;
  wire        _lswishbone_io_out_bits_sqwStrobe_0;
  wire        _lswishbone_io_out_bits_sqwStrobe_1;
  wire        _lswishbone_io_out_bits_sqwStrobe_2;
  wire        _lswishbone_io_out_bits_sqwStrobe_3;
  wire [3:0]  _lswishbone_io_wb_adr;
  wire [31:0] _lswishbone_io_wb_dat_o;
  wire        _lswishbone_io_wb_we;
  wire        _lswishbone_io_wb_stb;
  wire [3:0]  _lswishbone_io_wb_sel;
  wire        _lswishbone_io_wb_cyc;
  wire        _lsducstage_io_in_ready;
  wire        _lsducstage_io_out_valid;
  wire [6:0]  _lsducstage_io_out_bits_rdTag;
  wire [31:0] _lsducstage_io_out_bits_addr;
  wire [31:0] _lsducstage_io_out_bits_inst;
  wire [31:0] _lsducstage_io_out_bits_pc;
  wire        _lsducstage_io_out_bits_flushed;
  wire [5:0]  _lsducstage_io_out_bits_lsOp;
  wire [7:0]  _lsducstage_io_out_bits_cacheData_0;
  wire [7:0]  _lsducstage_io_out_bits_cacheData_1;
  wire [7:0]  _lsducstage_io_out_bits_cacheData_2;
  wire [7:0]  _lsducstage_io_out_bits_cacheData_3;
  wire [7:0]  _lsducstage_io_out_bits_sqData_0;
  wire [7:0]  _lsducstage_io_out_bits_sqData_1;
  wire [7:0]  _lsducstage_io_out_bits_sqData_2;
  wire [7:0]  _lsducstage_io_out_bits_sqData_3;
  wire        _lsducstage_io_out_bits_sqwStrobe_0;
  wire        _lsducstage_io_out_bits_sqwStrobe_1;
  wire        _lsducstage_io_out_bits_sqwStrobe_2;
  wire        _lsducstage_io_out_bits_sqwStrobe_3;
  wire        _lssqstage_io_in_ready;
  wire        _lssqstage_io_selfRetired;
  wire        _lssqstage_io_out_valid;
  wire [6:0]  _lssqstage_io_out_bits_rdTag;
  wire        _lssqstage_io_out_bits_store;
  wire [31:0] _lssqstage_io_out_bits_addr;
  wire [31:0] _lssqstage_io_out_bits_inst;
  wire [31:0] _lssqstage_io_out_bits_pc;
  wire        _lssqstage_io_out_bits_flushed;
  wire [5:0]  _lssqstage_io_out_bits_lsOp;
  wire [7:0]  _lssqstage_io_out_bits_cacheData_0;
  wire [7:0]  _lssqstage_io_out_bits_cacheData_1;
  wire [7:0]  _lssqstage_io_out_bits_cacheData_2;
  wire [7:0]  _lssqstage_io_out_bits_cacheData_3;
  wire [7:0]  _lssqstage_io_out_bits_sqData_0;
  wire [7:0]  _lssqstage_io_out_bits_sqData_1;
  wire [7:0]  _lssqstage_io_out_bits_sqData_2;
  wire [7:0]  _lssqstage_io_out_bits_sqData_3;
  wire        _lssqstage_io_out_bits_sqwStrobe_0;
  wire        _lssqstage_io_out_bits_sqwStrobe_1;
  wire        _lssqstage_io_out_bits_sqwStrobe_2;
  wire        _lssqstage_io_out_bits_sqwStrobe_3;
  wire        _lssqstage_io_outPeriph_valid;
  wire        _lssqstage_io_outPeriph_bits_retired;
  wire [6:0]  _lssqstage_io_outPeriph_bits_rdTag;
  wire        _lssqstage_io_outPeriph_bits_store;
  wire [31:0] _lssqstage_io_outPeriph_bits_addr;
  wire [31:0] _lssqstage_io_outPeriph_bits_inst;
  wire [31:0] _lssqstage_io_outPeriph_bits_pc;
  wire        _lssqstage_io_outPeriph_bits_flushed;
  wire [5:0]  _lssqstage_io_outPeriph_bits_lsOp;
  wire [7:0]  _lssqstage_io_outPeriph_bits_cacheData_0;
  wire [7:0]  _lssqstage_io_outPeriph_bits_cacheData_1;
  wire [7:0]  _lssqstage_io_outPeriph_bits_cacheData_2;
  wire [7:0]  _lssqstage_io_outPeriph_bits_cacheData_3;
  wire [7:0]  _lssqstage_io_outPeriph_bits_sqData_0;
  wire [7:0]  _lssqstage_io_outPeriph_bits_sqData_1;
  wire [7:0]  _lssqstage_io_outPeriph_bits_sqData_2;
  wire [7:0]  _lssqstage_io_outPeriph_bits_sqData_3;
  wire        _lssqstage_io_outPeriph_bits_sqwStrobe_0;
  wire        _lssqstage_io_outPeriph_bits_sqwStrobe_1;
  wire        _lssqstage_io_outPeriph_bits_sqwStrobe_2;
  wire        _lssqstage_io_outPeriph_bits_sqwStrobe_3;
  wire        _lsscstage_io_out_valid;
  wire        _lsscstage_io_out_bits_retired;
  wire [6:0]  _lsscstage_io_out_bits_rdTag;
  wire        _lsscstage_io_out_bits_store;
  wire [31:0] _lsscstage_io_out_bits_addr;
  wire [31:0] _lsscstage_io_out_bits_inst;
  wire [31:0] _lsscstage_io_out_bits_pc;
  wire        _lsscstage_io_out_bits_flushed;
  wire [5:0]  _lsscstage_io_out_bits_lsOp;
  wire [7:0]  _lsscstage_io_out_bits_cacheData_0;
  wire [7:0]  _lsscstage_io_out_bits_cacheData_1;
  wire [7:0]  _lsscstage_io_out_bits_cacheData_2;
  wire [7:0]  _lsscstage_io_out_bits_cacheData_3;
  wire [7:0]  _lsscstage_io_out_bits_sqData_0;
  wire [7:0]  _lsscstage_io_out_bits_sqData_1;
  wire [7:0]  _lsscstage_io_out_bits_sqData_2;
  wire [7:0]  _lsscstage_io_out_bits_sqData_3;
  wire        _lsscstage_io_out_bits_sqwStrobe_0;
  wire        _lsscstage_io_out_bits_sqwStrobe_1;
  wire        _lsscstage_io_out_bits_sqwStrobe_2;
  wire        _lsscstage_io_out_bits_sqwStrobe_3;
  wire [31:0] _inputOperandsOverrider_1_io_targetAddrO;
  wire [31:0] _inputOperandsOverrider_1_io_rs2DataO;
  wire        _inputOperandsOverrider_1_io_operandReadyO;
  wire [31:0] _inputOperandsOverrider_0_io_targetAddrO;
  wire [31:0] _inputOperandsOverrider_0_io_rs2DataO;
  wire        _inputOperandsOverrider_0_io_operandReadyO;
  wire        inOverridenOperands_0_bits_operandReady =
    _inputOperandsOverrider_0_io_operandReadyO
      ? _inputOperandsOverrider_0_io_operandReadyO
      : io_in_0_bits_operandReady;
  wire [31:0] inOverridenOperands_0_bits_rdData =
    _inputOperandsOverrider_0_io_operandReadyO
      ? _inputOperandsOverrider_0_io_targetAddrO
      : io_in_0_bits_rdData;
  wire [31:0] inOverridenOperands_0_bits_rs2Data =
    _inputOperandsOverrider_0_io_operandReadyO
      ? _inputOperandsOverrider_0_io_rs2DataO
      : io_in_0_bits_rs2Data;
  wire        inOverridenOperands_1_bits_operandReady =
    _inputOperandsOverrider_1_io_operandReadyO
      ? _inputOperandsOverrider_1_io_operandReadyO
      : io_in_1_bits_operandReady;
  wire [31:0] inOverridenOperands_1_bits_rdData =
    _inputOperandsOverrider_1_io_operandReadyO
      ? _inputOperandsOverrider_1_io_targetAddrO
      : io_in_1_bits_rdData;
  wire [31:0] inOverridenOperands_1_bits_rs2Data =
    _inputOperandsOverrider_1_io_operandReadyO
      ? _inputOperandsOverrider_1_io_rs2DataO
      : io_in_1_bits_rs2Data;
  LSOverrideOperands inputOperandsOverrider_0 (
    .io_targetAddrI                    ({30'h0, io_in_0_bits_opsrc1}),
    .io_rs2DataI                       ({30'h0, io_in_0_bits_opsrc2}),
    .io_rdTagI                         (io_in_0_bits_rdTag),
    .io_lsOperandBus_0_valid           (io_lsOperandBus_0_valid),
    .io_lsOperandBus_0_bits_targetAddr (io_lsOperandBus_0_bits_targetAddr),
    .io_lsOperandBus_0_bits_rs2Data    (io_lsOperandBus_0_bits_rs2Data),
    .io_lsOperandBus_0_bits_rdTag      (io_lsOperandBus_0_bits_rdTag),
    .io_lsOperandBus_1_valid           (io_lsOperandBus_1_valid),
    .io_lsOperandBus_1_bits_targetAddr (io_lsOperandBus_1_bits_targetAddr),
    .io_lsOperandBus_1_bits_rs2Data    (io_lsOperandBus_1_bits_rs2Data),
    .io_lsOperandBus_1_bits_rdTag      (io_lsOperandBus_1_bits_rdTag),
    .io_targetAddrO                    (_inputOperandsOverrider_0_io_targetAddrO),
    .io_rs2DataO                       (_inputOperandsOverrider_0_io_rs2DataO),
    .io_operandReadyO                  (_inputOperandsOverrider_0_io_operandReadyO)
  );
  LSOverrideOperands inputOperandsOverrider_1 (
    .io_targetAddrI                    ({30'h0, io_in_1_bits_opsrc1}),
    .io_rs2DataI                       ({30'h0, io_in_1_bits_opsrc2}),
    .io_rdTagI                         (io_in_1_bits_rdTag),
    .io_lsOperandBus_0_valid           (io_lsOperandBus_0_valid),
    .io_lsOperandBus_0_bits_targetAddr (io_lsOperandBus_0_bits_targetAddr),
    .io_lsOperandBus_0_bits_rs2Data    (io_lsOperandBus_0_bits_rs2Data),
    .io_lsOperandBus_0_bits_rdTag      (io_lsOperandBus_0_bits_rdTag),
    .io_lsOperandBus_1_valid           (io_lsOperandBus_1_valid),
    .io_lsOperandBus_1_bits_targetAddr (io_lsOperandBus_1_bits_targetAddr),
    .io_lsOperandBus_1_bits_rs2Data    (io_lsOperandBus_1_bits_rs2Data),
    .io_lsOperandBus_1_bits_rdTag      (io_lsOperandBus_1_bits_rdTag),
    .io_targetAddrO                    (_inputOperandsOverrider_1_io_targetAddrO),
    .io_rs2DataO                       (_inputOperandsOverrider_1_io_rs2DataO),
    .io_operandReadyO                  (_inputOperandsOverrider_1_io_operandReadyO)
  );
  LSScheduleStage lsscstage (
    .clock                             (clock),
    .reset                             (reset),
    .io_in_0_ready                     (io_in_0_ready),
    .io_in_0_valid                     (io_in_0_valid),
    .io_in_0_bits_retired              (io_in_0_bits_retired),
    .io_in_0_bits_rdTag                (io_in_0_bits_rdTag),
    .io_in_0_bits_isBranch             (io_in_0_bits_isBranch),
    .io_in_0_bits_isJAL                (io_in_0_bits_isJAL),
    .io_in_0_bits_lsType               (io_in_0_bits_lsType),
    .io_in_0_bits_wakeup               (io_in_0_bits_wakeup),
    .io_in_0_bits_opsrc1               (io_in_0_bits_opsrc1),
    .io_in_0_bits_opsrc2               (io_in_0_bits_opsrc2),
    .io_in_0_bits_writeRf              (io_in_0_bits_writeRf),
    .io_in_0_bits_exEngine             (io_in_0_bits_exEngine),
    .io_in_0_bits_exOp                 (io_in_0_bits_exOp),
    .io_in_0_bits_lsOp                 (io_in_0_bits_lsOp),
    .io_in_0_bits_exception            (io_in_0_bits_exception),
    .io_in_0_bits_taken                (io_in_0_bits_taken),
    .io_in_0_bits_imm                  (io_in_0_bits_imm),
    .io_in_0_bits_rs1                  (io_in_0_bits_rs1),
    .io_in_0_bits_rs2                  (io_in_0_bits_rs2),
    .io_in_0_bits_rd                   (io_in_0_bits_rd),
    .io_in_0_bits_pc                   (io_in_0_bits_pc),
    .io_in_0_bits_targetPC             (io_in_0_bits_targetPC),
    .io_in_0_bits_rs1Tag               (io_in_0_bits_rs1Tag),
    .io_in_0_bits_rs1TagReady          (io_in_0_bits_rs1TagReady),
    .io_in_0_bits_rs2Tag               (io_in_0_bits_rs2Tag),
    .io_in_0_bits_rs2TagReady          (io_in_0_bits_rs2TagReady),
    .io_in_0_bits_rs1Data              (io_in_0_bits_rs1Data),
    .io_in_0_bits_rs2Data              (inOverridenOperands_0_bits_rs2Data),
    .io_in_0_bits_rdData               (inOverridenOperands_0_bits_rdData),
    .io_in_0_bits_operandReady         (inOverridenOperands_0_bits_operandReady),
    .io_in_0_bits_flushed              (io_in_0_bits_flushed),
    .io_in_0_bits_arfTag               (io_in_0_bits_arfTag),
    .io_in_0_bits_arfValid             (io_in_0_bits_arfValid),
    .io_in_0_bits_inst                 (io_in_0_bits_inst),
    .io_in_1_ready                     (io_in_1_ready),
    .io_in_1_valid                     (io_in_1_valid),
    .io_in_1_bits_retired              (io_in_1_bits_retired),
    .io_in_1_bits_rdTag                (io_in_1_bits_rdTag),
    .io_in_1_bits_isBranch             (io_in_1_bits_isBranch),
    .io_in_1_bits_isJAL                (io_in_1_bits_isJAL),
    .io_in_1_bits_lsType               (io_in_1_bits_lsType),
    .io_in_1_bits_wakeup               (io_in_1_bits_wakeup),
    .io_in_1_bits_opsrc1               (io_in_1_bits_opsrc1),
    .io_in_1_bits_opsrc2               (io_in_1_bits_opsrc2),
    .io_in_1_bits_writeRf              (io_in_1_bits_writeRf),
    .io_in_1_bits_exEngine             (io_in_1_bits_exEngine),
    .io_in_1_bits_exOp                 (io_in_1_bits_exOp),
    .io_in_1_bits_lsOp                 (io_in_1_bits_lsOp),
    .io_in_1_bits_exception            (io_in_1_bits_exception),
    .io_in_1_bits_taken                (io_in_1_bits_taken),
    .io_in_1_bits_imm                  (io_in_1_bits_imm),
    .io_in_1_bits_rs1                  (io_in_1_bits_rs1),
    .io_in_1_bits_rs2                  (io_in_1_bits_rs2),
    .io_in_1_bits_rd                   (io_in_1_bits_rd),
    .io_in_1_bits_pc                   (io_in_1_bits_pc),
    .io_in_1_bits_targetPC             (io_in_1_bits_targetPC),
    .io_in_1_bits_rs1Tag               (io_in_1_bits_rs1Tag),
    .io_in_1_bits_rs1TagReady          (io_in_1_bits_rs1TagReady),
    .io_in_1_bits_rs2Tag               (io_in_1_bits_rs2Tag),
    .io_in_1_bits_rs2TagReady          (io_in_1_bits_rs2TagReady),
    .io_in_1_bits_rs1Data              (io_in_1_bits_rs1Data),
    .io_in_1_bits_rs2Data              (inOverridenOperands_1_bits_rs2Data),
    .io_in_1_bits_rdData               (inOverridenOperands_1_bits_rdData),
    .io_in_1_bits_operandReady         (inOverridenOperands_1_bits_operandReady),
    .io_in_1_bits_flushed              (io_in_1_bits_flushed),
    .io_in_1_bits_arfTag               (io_in_1_bits_arfTag),
    .io_in_1_bits_arfValid             (io_in_1_bits_arfValid),
    .io_in_1_bits_inst                 (io_in_1_bits_inst),
    .io_lsOperandBus_0_valid           (io_lsOperandBus_0_valid),
    .io_lsOperandBus_0_bits_targetAddr (io_lsOperandBus_0_bits_targetAddr),
    .io_lsOperandBus_0_bits_rs2Data    (io_lsOperandBus_0_bits_rs2Data),
    .io_lsOperandBus_0_bits_rdTag      (io_lsOperandBus_0_bits_rdTag),
    .io_lsOperandBus_1_valid           (io_lsOperandBus_1_valid),
    .io_lsOperandBus_1_bits_targetAddr (io_lsOperandBus_1_bits_targetAddr),
    .io_lsOperandBus_1_bits_rs2Data    (io_lsOperandBus_1_bits_rs2Data),
    .io_lsOperandBus_1_bits_rdTag      (io_lsOperandBus_1_bits_rdTag),
    .io_storeRetireBus_0_valid         (io_storeRetireBus_0_valid),
    .io_storeRetireBus_0_bits_tag      (io_storeRetireBus_0_bits_tag),
    .io_storeRetireBus_1_valid         (io_storeRetireBus_1_valid),
    .io_storeRetireBus_1_bits_tag      (io_storeRetireBus_1_bits_tag),
    .io_flush                          (io_flush),
    .io_frontRetired                   (_lssqstage_io_selfRetired),
    .io_selfRetired_0                  (io_selfRetired_0),
    .io_selfRetired_1                  (io_selfRetired_1),
    .io_out_ready                      (_lssqstage_io_in_ready),
    .io_out_valid                      (_lsscstage_io_out_valid),
    .io_out_bits_retired               (_lsscstage_io_out_bits_retired),
    .io_out_bits_rdTag                 (_lsscstage_io_out_bits_rdTag),
    .io_out_bits_store                 (_lsscstage_io_out_bits_store),
    .io_out_bits_addr                  (_lsscstage_io_out_bits_addr),
    .io_out_bits_inst                  (_lsscstage_io_out_bits_inst),
    .io_out_bits_pc                    (_lsscstage_io_out_bits_pc),
    .io_out_bits_flushed               (_lsscstage_io_out_bits_flushed),
    .io_out_bits_lsOp                  (_lsscstage_io_out_bits_lsOp),
    .io_out_bits_cacheData_0           (_lsscstage_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1           (_lsscstage_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2           (_lsscstage_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3           (_lsscstage_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0              (_lsscstage_io_out_bits_sqData_0),
    .io_out_bits_sqData_1              (_lsscstage_io_out_bits_sqData_1),
    .io_out_bits_sqData_2              (_lsscstage_io_out_bits_sqData_2),
    .io_out_bits_sqData_3              (_lsscstage_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0           (_lsscstage_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1           (_lsscstage_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2           (_lsscstage_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3           (_lsscstage_io_out_bits_sqwStrobe_3)
  );
  LSSQStage lssqstage (
    .clock                         (clock),
    .reset                         (reset),
    .io_in_ready                   (_lssqstage_io_in_ready),
    .io_in_valid                   (_lsscstage_io_out_valid),
    .io_in_bits_retired            (_lsscstage_io_out_bits_retired),
    .io_in_bits_rdTag              (_lsscstage_io_out_bits_rdTag),
    .io_in_bits_store              (_lsscstage_io_out_bits_store),
    .io_in_bits_addr               (_lsscstage_io_out_bits_addr),
    .io_in_bits_inst               (_lsscstage_io_out_bits_inst),
    .io_in_bits_pc                 (_lsscstage_io_out_bits_pc),
    .io_in_bits_flushed            (_lsscstage_io_out_bits_flushed),
    .io_in_bits_lsOp               (_lsscstage_io_out_bits_lsOp),
    .io_in_bits_cacheData_0        (_lsscstage_io_out_bits_cacheData_0),
    .io_in_bits_cacheData_1        (_lsscstage_io_out_bits_cacheData_1),
    .io_in_bits_cacheData_2        (_lsscstage_io_out_bits_cacheData_2),
    .io_in_bits_cacheData_3        (_lsscstage_io_out_bits_cacheData_3),
    .io_in_bits_sqData_0           (_lsscstage_io_out_bits_sqData_0),
    .io_in_bits_sqData_1           (_lsscstage_io_out_bits_sqData_1),
    .io_in_bits_sqData_2           (_lsscstage_io_out_bits_sqData_2),
    .io_in_bits_sqData_3           (_lsscstage_io_out_bits_sqData_3),
    .io_in_bits_sqwStrobe_0        (_lsscstage_io_out_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1        (_lsscstage_io_out_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2        (_lsscstage_io_out_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3        (_lsscstage_io_out_bits_sqwStrobe_3),
    .io_storeRetireBus_0_valid     (io_storeRetireBus_0_valid),
    .io_storeRetireBus_0_bits_tag  (io_storeRetireBus_0_bits_tag),
    .io_storeRetireBus_1_valid     (io_storeRetireBus_1_valid),
    .io_storeRetireBus_1_bits_tag  (io_storeRetireBus_1_bits_tag),
    .io_flush                      (io_flush),
    .io_selfRetired                (_lssqstage_io_selfRetired),
    .io_out_ready                  (_lsducstage_io_in_ready),
    .io_out_valid                  (_lssqstage_io_out_valid),
    .io_out_bits_rdTag             (_lssqstage_io_out_bits_rdTag),
    .io_out_bits_store             (_lssqstage_io_out_bits_store),
    .io_out_bits_addr              (_lssqstage_io_out_bits_addr),
    .io_out_bits_inst              (_lssqstage_io_out_bits_inst),
    .io_out_bits_pc                (_lssqstage_io_out_bits_pc),
    .io_out_bits_flushed           (_lssqstage_io_out_bits_flushed),
    .io_out_bits_lsOp              (_lssqstage_io_out_bits_lsOp),
    .io_out_bits_cacheData_0       (_lssqstage_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1       (_lssqstage_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2       (_lssqstage_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3       (_lssqstage_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0          (_lssqstage_io_out_bits_sqData_0),
    .io_out_bits_sqData_1          (_lssqstage_io_out_bits_sqData_1),
    .io_out_bits_sqData_2          (_lssqstage_io_out_bits_sqData_2),
    .io_out_bits_sqData_3          (_lssqstage_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0       (_lssqstage_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1       (_lssqstage_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2       (_lssqstage_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3       (_lssqstage_io_out_bits_sqwStrobe_3),
    .io_outPeriph_ready            (_lswishbone_io_in_ready),
    .io_outPeriph_valid            (_lssqstage_io_outPeriph_valid),
    .io_outPeriph_bits_retired     (_lssqstage_io_outPeriph_bits_retired),
    .io_outPeriph_bits_rdTag       (_lssqstage_io_outPeriph_bits_rdTag),
    .io_outPeriph_bits_store       (_lssqstage_io_outPeriph_bits_store),
    .io_outPeriph_bits_addr        (_lssqstage_io_outPeriph_bits_addr),
    .io_outPeriph_bits_inst        (_lssqstage_io_outPeriph_bits_inst),
    .io_outPeriph_bits_pc          (_lssqstage_io_outPeriph_bits_pc),
    .io_outPeriph_bits_flushed     (_lssqstage_io_outPeriph_bits_flushed),
    .io_outPeriph_bits_lsOp        (_lssqstage_io_outPeriph_bits_lsOp),
    .io_outPeriph_bits_cacheData_0 (_lssqstage_io_outPeriph_bits_cacheData_0),
    .io_outPeriph_bits_cacheData_1 (_lssqstage_io_outPeriph_bits_cacheData_1),
    .io_outPeriph_bits_cacheData_2 (_lssqstage_io_outPeriph_bits_cacheData_2),
    .io_outPeriph_bits_cacheData_3 (_lssqstage_io_outPeriph_bits_cacheData_3),
    .io_outPeriph_bits_sqData_0    (_lssqstage_io_outPeriph_bits_sqData_0),
    .io_outPeriph_bits_sqData_1    (_lssqstage_io_outPeriph_bits_sqData_1),
    .io_outPeriph_bits_sqData_2    (_lssqstage_io_outPeriph_bits_sqData_2),
    .io_outPeriph_bits_sqData_3    (_lssqstage_io_outPeriph_bits_sqData_3),
    .io_outPeriph_bits_sqwStrobe_0 (_lssqstage_io_outPeriph_bits_sqwStrobe_0),
    .io_outPeriph_bits_sqwStrobe_1 (_lssqstage_io_outPeriph_bits_sqwStrobe_1),
    .io_outPeriph_bits_sqwStrobe_2 (_lssqstage_io_outPeriph_bits_sqwStrobe_2),
    .io_outPeriph_bits_sqwStrobe_3 (_lssqstage_io_outPeriph_bits_sqwStrobe_3)
  );
  LSDCacheWrapper lsducstage (
    .clock                   (clock),
    .reset                   (reset),
    .io_in_ready             (_lsducstage_io_in_ready),
    .io_in_valid             (_lssqstage_io_out_valid),
    .io_in_bits_rdTag        (_lssqstage_io_out_bits_rdTag),
    .io_in_bits_store        (_lssqstage_io_out_bits_store),
    .io_in_bits_addr         (_lssqstage_io_out_bits_addr),
    .io_in_bits_inst         (_lssqstage_io_out_bits_inst),
    .io_in_bits_pc           (_lssqstage_io_out_bits_pc),
    .io_in_bits_flushed      (_lssqstage_io_out_bits_flushed),
    .io_in_bits_lsOp         (_lssqstage_io_out_bits_lsOp),
    .io_in_bits_cacheData_0  (_lssqstage_io_out_bits_cacheData_0),
    .io_in_bits_cacheData_1  (_lssqstage_io_out_bits_cacheData_1),
    .io_in_bits_cacheData_2  (_lssqstage_io_out_bits_cacheData_2),
    .io_in_bits_cacheData_3  (_lssqstage_io_out_bits_cacheData_3),
    .io_in_bits_sqData_0     (_lssqstage_io_out_bits_sqData_0),
    .io_in_bits_sqData_1     (_lssqstage_io_out_bits_sqData_1),
    .io_in_bits_sqData_2     (_lssqstage_io_out_bits_sqData_2),
    .io_in_bits_sqData_3     (_lssqstage_io_out_bits_sqData_3),
    .io_in_bits_sqwStrobe_0  (_lssqstage_io_out_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1  (_lssqstage_io_out_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2  (_lssqstage_io_out_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3  (_lssqstage_io_out_bits_sqwStrobe_3),
    .io_flush                (io_flush),
    .io_out_valid            (_lsducstage_io_out_valid),
    .io_out_bits_rdTag       (_lsducstage_io_out_bits_rdTag),
    .io_out_bits_addr        (_lsducstage_io_out_bits_addr),
    .io_out_bits_inst        (_lsducstage_io_out_bits_inst),
    .io_out_bits_pc          (_lsducstage_io_out_bits_pc),
    .io_out_bits_flushed     (_lsducstage_io_out_bits_flushed),
    .io_out_bits_lsOp        (_lsducstage_io_out_bits_lsOp),
    .io_out_bits_cacheData_0 (_lsducstage_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1 (_lsducstage_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2 (_lsducstage_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3 (_lsducstage_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0    (_lsducstage_io_out_bits_sqData_0),
    .io_out_bits_sqData_1    (_lsducstage_io_out_bits_sqData_1),
    .io_out_bits_sqData_2    (_lsducstage_io_out_bits_sqData_2),
    .io_out_bits_sqData_3    (_lsducstage_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0 (_lsducstage_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1 (_lsducstage_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2 (_lsducstage_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3 (_lsducstage_io_out_bits_sqwStrobe_3),
    .io_mem_req_ready        (io_mem_req_ready),
    .io_mem_req_valid        (io_mem_req_valid),
    .io_mem_req_bits_addr    (io_mem_req_bits_addr),
    .io_mem_req_bits_data    (io_mem_req_bits_data),
    .io_mem_req_bits_wen     (io_mem_req_bits_wen),
    .io_mem_resp_ready       (io_mem_resp_ready),
    .io_mem_resp_valid       (io_mem_resp_valid),
    .io_mem_resp_bits_data   (io_mem_resp_bits_data)
  );
  LSWriteback lswbstage (
    .io_in_valid                  (_lsducstage_io_out_valid),
    .io_in_bits_rdTag             (_lsducstage_io_out_bits_rdTag),
    .io_in_bits_addr              (_lsducstage_io_out_bits_addr),
    .io_in_bits_inst              (_lsducstage_io_out_bits_inst),
    .io_in_bits_pc                (_lsducstage_io_out_bits_pc),
    .io_in_bits_flushed           (_lsducstage_io_out_bits_flushed),
    .io_in_bits_lsOp              (_lsducstage_io_out_bits_lsOp),
    .io_in_bits_cacheData_0       (_lsducstage_io_out_bits_cacheData_0),
    .io_in_bits_cacheData_1       (_lsducstage_io_out_bits_cacheData_1),
    .io_in_bits_cacheData_2       (_lsducstage_io_out_bits_cacheData_2),
    .io_in_bits_cacheData_3       (_lsducstage_io_out_bits_cacheData_3),
    .io_in_bits_sqData_0          (_lsducstage_io_out_bits_sqData_0),
    .io_in_bits_sqData_1          (_lsducstage_io_out_bits_sqData_1),
    .io_in_bits_sqData_2          (_lsducstage_io_out_bits_sqData_2),
    .io_in_bits_sqData_3          (_lsducstage_io_out_bits_sqData_3),
    .io_in_bits_sqwStrobe_0       (_lsducstage_io_out_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1       (_lsducstage_io_out_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2       (_lsducstage_io_out_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3       (_lsducstage_io_out_bits_sqwStrobe_3),
    .io_inPeriph_valid            (_lswishbone_io_out_valid),
    .io_inPeriph_bits_retired     (_lswishbone_io_out_bits_retired),
    .io_inPeriph_bits_rdTag       (_lswishbone_io_out_bits_rdTag),
    .io_inPeriph_bits_store       (_lswishbone_io_out_bits_store),
    .io_inPeriph_bits_addr        (_lswishbone_io_out_bits_addr),
    .io_inPeriph_bits_inst        (_lswishbone_io_out_bits_inst),
    .io_inPeriph_bits_pc          (_lswishbone_io_out_bits_pc),
    .io_inPeriph_bits_flushed     (_lswishbone_io_out_bits_flushed),
    .io_inPeriph_bits_lsOp        (_lswishbone_io_out_bits_lsOp),
    .io_inPeriph_bits_cacheData_0 (_lswishbone_io_out_bits_cacheData_0),
    .io_inPeriph_bits_cacheData_1 (_lswishbone_io_out_bits_cacheData_1),
    .io_inPeriph_bits_cacheData_2 (_lswishbone_io_out_bits_cacheData_2),
    .io_inPeriph_bits_cacheData_3 (_lswishbone_io_out_bits_cacheData_3),
    .io_inPeriph_bits_sqData_0    (_lswishbone_io_out_bits_sqData_0),
    .io_inPeriph_bits_sqData_1    (_lswishbone_io_out_bits_sqData_1),
    .io_inPeriph_bits_sqData_2    (_lswishbone_io_out_bits_sqData_2),
    .io_inPeriph_bits_sqData_3    (_lswishbone_io_out_bits_sqData_3),
    .io_inPeriph_bits_sqwStrobe_0 (_lswishbone_io_out_bits_sqwStrobe_0),
    .io_inPeriph_bits_sqwStrobe_1 (_lswishbone_io_out_bits_sqwStrobe_1),
    .io_inPeriph_bits_sqwStrobe_2 (_lswishbone_io_out_bits_sqwStrobe_2),
    .io_inPeriph_bits_sqwStrobe_3 (_lswishbone_io_out_bits_sqwStrobe_3),
    .io_out_0_valid               (io_out_0_valid),
    .io_out_0_bits_tag            (io_out_0_bits_tag),
    .io_out_0_bits_data           (io_out_0_bits_data)
  );
  LSWishboneMaster lswishbone (
    .clock                   (clock),
    .reset                   (reset),
    .io_in_ready             (_lswishbone_io_in_ready),
    .io_in_valid             (_lssqstage_io_outPeriph_valid),
    .io_in_bits_retired      (_lssqstage_io_outPeriph_bits_retired),
    .io_in_bits_rdTag        (_lssqstage_io_outPeriph_bits_rdTag),
    .io_in_bits_store        (_lssqstage_io_outPeriph_bits_store),
    .io_in_bits_addr         (_lssqstage_io_outPeriph_bits_addr),
    .io_in_bits_inst         (_lssqstage_io_outPeriph_bits_inst),
    .io_in_bits_pc           (_lssqstage_io_outPeriph_bits_pc),
    .io_in_bits_flushed      (_lssqstage_io_outPeriph_bits_flushed),
    .io_in_bits_lsOp         (_lssqstage_io_outPeriph_bits_lsOp),
    .io_in_bits_cacheData_0  (_lssqstage_io_outPeriph_bits_cacheData_0),
    .io_in_bits_cacheData_1  (_lssqstage_io_outPeriph_bits_cacheData_1),
    .io_in_bits_cacheData_2  (_lssqstage_io_outPeriph_bits_cacheData_2),
    .io_in_bits_cacheData_3  (_lssqstage_io_outPeriph_bits_cacheData_3),
    .io_in_bits_sqData_0     (_lssqstage_io_outPeriph_bits_sqData_0),
    .io_in_bits_sqData_1     (_lssqstage_io_outPeriph_bits_sqData_1),
    .io_in_bits_sqData_2     (_lssqstage_io_outPeriph_bits_sqData_2),
    .io_in_bits_sqData_3     (_lssqstage_io_outPeriph_bits_sqData_3),
    .io_in_bits_sqwStrobe_0  (_lssqstage_io_outPeriph_bits_sqwStrobe_0),
    .io_in_bits_sqwStrobe_1  (_lssqstage_io_outPeriph_bits_sqwStrobe_1),
    .io_in_bits_sqwStrobe_2  (_lssqstage_io_outPeriph_bits_sqwStrobe_2),
    .io_in_bits_sqwStrobe_3  (_lssqstage_io_outPeriph_bits_sqwStrobe_3),
    .io_out_valid            (_lswishbone_io_out_valid),
    .io_out_bits_retired     (_lswishbone_io_out_bits_retired),
    .io_out_bits_rdTag       (_lswishbone_io_out_bits_rdTag),
    .io_out_bits_store       (_lswishbone_io_out_bits_store),
    .io_out_bits_addr        (_lswishbone_io_out_bits_addr),
    .io_out_bits_inst        (_lswishbone_io_out_bits_inst),
    .io_out_bits_pc          (_lswishbone_io_out_bits_pc),
    .io_out_bits_flushed     (_lswishbone_io_out_bits_flushed),
    .io_out_bits_lsOp        (_lswishbone_io_out_bits_lsOp),
    .io_out_bits_cacheData_0 (_lswishbone_io_out_bits_cacheData_0),
    .io_out_bits_cacheData_1 (_lswishbone_io_out_bits_cacheData_1),
    .io_out_bits_cacheData_2 (_lswishbone_io_out_bits_cacheData_2),
    .io_out_bits_cacheData_3 (_lswishbone_io_out_bits_cacheData_3),
    .io_out_bits_sqData_0    (_lswishbone_io_out_bits_sqData_0),
    .io_out_bits_sqData_1    (_lswishbone_io_out_bits_sqData_1),
    .io_out_bits_sqData_2    (_lswishbone_io_out_bits_sqData_2),
    .io_out_bits_sqData_3    (_lswishbone_io_out_bits_sqData_3),
    .io_out_bits_sqwStrobe_0 (_lswishbone_io_out_bits_sqwStrobe_0),
    .io_out_bits_sqwStrobe_1 (_lswishbone_io_out_bits_sqwStrobe_1),
    .io_out_bits_sqwStrobe_2 (_lswishbone_io_out_bits_sqwStrobe_2),
    .io_out_bits_sqwStrobe_3 (_lswishbone_io_out_bits_sqwStrobe_3),
    .io_wb_adr               (_lswishbone_io_wb_adr),
    .io_wb_dat_o             (_lswishbone_io_wb_dat_o),
    .io_wb_we                (_lswishbone_io_wb_we),
    .io_wb_stb               (_lswishbone_io_wb_stb),
    .io_wb_sel               (_lswishbone_io_wb_sel),
    .io_wb_cyc               (_lswishbone_io_wb_cyc),
    .io_wb_ack               (_uart_io_wb_ack),
    .io_wb_dat_i             (_uart_io_wb_dat_o)
  );
  UARTController uart (
    .clock       (clock),
    .reset       (reset),
    .io_wb_adr   (_lswishbone_io_wb_adr),
    .io_wb_dat_i (_lswishbone_io_wb_dat_o),
    .io_wb_we    (_lswishbone_io_wb_we),
    .io_wb_stb   (_lswishbone_io_wb_stb),
    .io_wb_sel   (_lswishbone_io_wb_sel),
    .io_wb_cyc   (_lswishbone_io_wb_cyc),
    .io_wb_ack   (_uart_io_wb_ack),
    .io_wb_dat_o (_uart_io_wb_dat_o),
    .io_uart_rx  (io_uart_rx),
    .io_uart_tx  (io_uart_tx)
  );
endmodule

