// Generated by CIRCT firtool-1.76.0
module OverrideArfTagFromBus(
  input  wire        io_in_valid,
  input  wire        io_in_bits_isBranch,
  input  wire        io_in_bits_isJAL,
  input  wire [1:0]  io_in_bits_lsType,
  input  wire [1:0]  io_in_bits_writeRf,
  input  wire [4:0]  io_in_bits_rd,
  input  wire [31:0] io_in_bits_pc,
  input  wire [6:0]  io_in_bits_rdTag,
  input  wire        io_in_bits_flushed,
  input  wire [6:0]  io_in_bits_arfTag,
  input  wire        io_in_bits_arfValid,
  input  wire [31:0] io_in_bits_inst,
  input  wire        io_inBus_0_valid,
  input  wire [6:0]  io_inBus_0_bits_tag,
  input  wire [4:0]  io_inBus_0_bits_rd,
  input  wire        io_inBus_1_valid,
  input  wire [6:0]  io_inBus_1_bits_tag,
  input  wire [4:0]  io_inBus_1_bits_rd,
  output wire        io_out_valid,
  output wire        io_out_bits_isBranch,
  output wire        io_out_bits_isJAL,
  output wire [1:0]  io_out_bits_lsType,
  output wire [1:0]  io_out_bits_writeRf,
  output wire [4:0]  io_out_bits_rd,
  output wire [31:0] io_out_bits_pc,
  output wire [6:0]  io_out_bits_rdTag,
  output wire        io_out_bits_flushed,
  output wire [6:0]  io_out_bits_arfTag,
  output wire        io_out_bits_arfValid,
  output wire [31:0] io_out_bits_inst
);

  wire       rdMatches_0 = io_in_bits_rd == io_inBus_0_bits_rd & io_inBus_0_valid;
  wire [6:0] _GEN = rdMatches_0 ? io_inBus_0_bits_tag : io_inBus_1_bits_tag;
  assign io_out_valid = io_in_valid;
  assign io_out_bits_isBranch = io_in_bits_isBranch;
  assign io_out_bits_isJAL = io_in_bits_isJAL;
  assign io_out_bits_lsType = io_in_bits_lsType;
  assign io_out_bits_writeRf = io_in_bits_writeRf;
  assign io_out_bits_rd = io_in_bits_rd;
  assign io_out_bits_pc = io_in_bits_pc;
  assign io_out_bits_rdTag = io_in_bits_rdTag;
  assign io_out_bits_flushed = io_in_bits_flushed;
  assign io_out_bits_arfTag =
    (|{io_in_bits_rd == io_inBus_1_bits_rd & io_inBus_1_valid, rdMatches_0})
      ? _GEN
      : io_in_bits_arfTag;
  assign io_out_bits_arfValid = io_in_bits_arfValid;
  assign io_out_bits_inst = io_in_bits_inst;
endmodule

