// Generated by CIRCT firtool-1.76.0
// VCS coverage exclude_file
module ram_16x7(
  input  wire [3:0] R0_addr,
  input  wire       R0_en,
  input  wire       R0_clk,
  output wire [6:0] R0_data,
  input  wire [3:0] W0_addr,
  input  wire       W0_en,
  input  wire       W0_clk,
  input  wire [6:0] W0_data
);

  reg [6:0] Memory[0:15];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 7'bx;
endmodule

