// Generated by CIRCT firtool-1.76.0
module ROBStage(
  input  wire        clock,
  input  wire        reset,
  output wire        io_in_0_ready,
  input  wire        io_in_0_valid,
  input  wire [6:0]  io_in_0_bits_rdTag,
  input  wire        io_in_0_bits_isBranch,
  input  wire        io_in_0_bits_isJAL,
  input  wire [1:0]  io_in_0_bits_lsType,
  input  wire [1:0]  io_in_0_bits_writeRf,
  input  wire [4:0]  io_in_0_bits_rd,
  input  wire [31:0] io_in_0_bits_pc,
  input  wire        io_in_0_bits_flushed,
  input  wire [6:0]  io_in_0_bits_arfTag,
  input  wire        io_in_0_bits_arfValid,
  input  wire [31:0] io_in_0_bits_inst,
  output wire        io_in_1_ready,
  input  wire        io_in_1_valid,
  input  wire [6:0]  io_in_1_bits_rdTag,
  input  wire        io_in_1_bits_isBranch,
  input  wire        io_in_1_bits_isJAL,
  input  wire [1:0]  io_in_1_bits_lsType,
  input  wire [1:0]  io_in_1_bits_writeRf,
  input  wire [4:0]  io_in_1_bits_rd,
  input  wire [31:0] io_in_1_bits_pc,
  input  wire        io_in_1_bits_flushed,
  input  wire [6:0]  io_in_1_bits_arfTag,
  input  wire        io_in_1_bits_arfValid,
  input  wire [31:0] io_in_1_bits_inst,
  input  wire        io_flush,
  input  wire        io_out_0_ready,
  output wire        io_out_0_valid,
  output wire        io_out_0_bits_isBranch,
  output wire        io_out_0_bits_isJAL,
  output wire [1:0]  io_out_0_bits_lsType,
  output wire [1:0]  io_out_0_bits_writeRf,
  output wire [4:0]  io_out_0_bits_rd,
  output wire [31:0] io_out_0_bits_pc,
  output wire [6:0]  io_out_0_bits_rdTag,
  output wire        io_out_0_bits_flushed,
  output wire [6:0]  io_out_0_bits_arfTag,
  output wire        io_out_0_bits_arfValid,
  output wire [31:0] io_out_0_bits_inst,
  input  wire        io_out_1_ready,
  output wire        io_out_1_valid,
  output wire        io_out_1_bits_isBranch,
  output wire        io_out_1_bits_isJAL,
  output wire [1:0]  io_out_1_bits_lsType,
  output wire [1:0]  io_out_1_bits_writeRf,
  output wire [4:0]  io_out_1_bits_rd,
  output wire [31:0] io_out_1_bits_pc,
  output wire [6:0]  io_out_1_bits_rdTag,
  output wire        io_out_1_bits_flushed,
  output wire [6:0]  io_out_1_bits_arfTag,
  output wire        io_out_1_bits_arfValid,
  output wire [31:0] io_out_1_bits_inst,
  output wire [31:0] io_firstPC_bits
);

  wire        _pRegs_1_io_in_ready;
  wire        _pRegs_1_io_out_valid;
  wire        _pRegs_0_io_in_ready;
  wire        _pRegs_0_io_out_valid;
  wire [4:0]  _q_io_count_0;
  wire [4:0]  _q_io_count_1;
  wire        _q_io_out_0_valid;
  wire        _q_io_out_0_bits_isBranch;
  wire        _q_io_out_0_bits_isJAL;
  wire [1:0]  _q_io_out_0_bits_lsType;
  wire [1:0]  _q_io_out_0_bits_writeRf;
  wire [4:0]  _q_io_out_0_bits_rd;
  wire [31:0] _q_io_out_0_bits_pc;
  wire [6:0]  _q_io_out_0_bits_rdTag;
  wire        _q_io_out_0_bits_flushed;
  wire [6:0]  _q_io_out_0_bits_arfTag;
  wire        _q_io_out_0_bits_arfValid;
  wire [31:0] _q_io_out_0_bits_inst;
  wire        _q_io_out_1_valid;
  wire        _q_io_out_1_bits_isBranch;
  wire        _q_io_out_1_bits_isJAL;
  wire [1:0]  _q_io_out_1_bits_lsType;
  wire [1:0]  _q_io_out_1_bits_writeRf;
  wire [4:0]  _q_io_out_1_bits_rd;
  wire [31:0] _q_io_out_1_bits_pc;
  wire [6:0]  _q_io_out_1_bits_rdTag;
  wire        _q_io_out_1_bits_flushed;
  wire [6:0]  _q_io_out_1_bits_arfTag;
  wire        _q_io_out_1_bits_arfValid;
  wire [31:0] _q_io_out_1_bits_inst;
  reg  [4:0]  savedCounts_0;
  reg  [4:0]  savedCounts_1;
  wire [1:0]  pRegs_0_io_in_bits_writeRf =
    (|{io_flush, savedCounts_0}) ? 2'h0 : _q_io_out_0_bits_writeRf;
  wire [1:0]  pRegs_1_io_in_bits_writeRf =
    (|{io_flush, savedCounts_1}) ? 2'h0 : _q_io_out_1_bits_writeRf;
  always @(posedge clock) begin
    if (reset) begin
      savedCounts_0 <= 5'h0;
      savedCounts_1 <= 5'h0;
    end
    else begin
      if ((|savedCounts_0) & io_out_0_ready & _pRegs_0_io_out_valid)
        savedCounts_0 <= savedCounts_0 - 5'h1;
      else if (io_flush & (|_q_io_count_0))
        savedCounts_0 <= _q_io_count_0 - {4'h0, ~io_in_0_valid};
      if ((|savedCounts_1) & io_out_1_ready & _pRegs_1_io_out_valid)
        savedCounts_1 <= savedCounts_1 - 5'h1;
      else if (io_flush & (|_q_io_count_1))
        savedCounts_1 <= _q_io_count_1 - {4'h0, ~io_in_1_valid};
    end
  end // always @(posedge)
  DCRRQueue_2 q (
    .clock                  (clock),
    .reset                  (reset),
    .io_in_0_ready          (io_in_0_ready),
    .io_in_0_valid          (io_in_0_valid),
    .io_in_0_bits_isBranch  (io_in_0_bits_isBranch),
    .io_in_0_bits_isJAL     (io_in_0_bits_isJAL),
    .io_in_0_bits_lsType    (io_in_0_bits_lsType),
    .io_in_0_bits_writeRf   (io_in_0_bits_writeRf),
    .io_in_0_bits_rd        (io_in_0_bits_rd),
    .io_in_0_bits_pc        (io_in_0_bits_pc),
    .io_in_0_bits_rdTag     (io_in_0_bits_rdTag),
    .io_in_0_bits_flushed   (io_in_0_bits_flushed | io_flush),
    .io_in_0_bits_arfTag    (io_in_0_bits_arfTag),
    .io_in_0_bits_arfValid  (io_in_0_bits_arfValid),
    .io_in_0_bits_inst      (io_in_0_bits_inst),
    .io_in_1_ready          (io_in_1_ready),
    .io_in_1_valid          (io_in_1_valid),
    .io_in_1_bits_isBranch  (io_in_1_bits_isBranch),
    .io_in_1_bits_isJAL     (io_in_1_bits_isJAL),
    .io_in_1_bits_lsType    (io_in_1_bits_lsType),
    .io_in_1_bits_writeRf   (io_in_1_bits_writeRf),
    .io_in_1_bits_rd        (io_in_1_bits_rd),
    .io_in_1_bits_pc        (io_in_1_bits_pc),
    .io_in_1_bits_rdTag     (io_in_1_bits_rdTag),
    .io_in_1_bits_flushed   (io_in_1_bits_flushed | io_flush),
    .io_in_1_bits_arfTag    (io_in_1_bits_arfTag),
    .io_in_1_bits_arfValid  (io_in_1_bits_arfValid),
    .io_in_1_bits_inst      (io_in_1_bits_inst),
    .io_count_0             (_q_io_count_0),
    .io_count_1             (_q_io_count_1),
    .io_out_0_ready         (_pRegs_0_io_in_ready),
    .io_out_0_valid         (_q_io_out_0_valid),
    .io_out_0_bits_isBranch (_q_io_out_0_bits_isBranch),
    .io_out_0_bits_isJAL    (_q_io_out_0_bits_isJAL),
    .io_out_0_bits_lsType   (_q_io_out_0_bits_lsType),
    .io_out_0_bits_writeRf  (_q_io_out_0_bits_writeRf),
    .io_out_0_bits_rd       (_q_io_out_0_bits_rd),
    .io_out_0_bits_pc       (_q_io_out_0_bits_pc),
    .io_out_0_bits_rdTag    (_q_io_out_0_bits_rdTag),
    .io_out_0_bits_flushed  (_q_io_out_0_bits_flushed),
    .io_out_0_bits_arfTag   (_q_io_out_0_bits_arfTag),
    .io_out_0_bits_arfValid (_q_io_out_0_bits_arfValid),
    .io_out_0_bits_inst     (_q_io_out_0_bits_inst),
    .io_out_1_ready         (_pRegs_1_io_in_ready),
    .io_out_1_valid         (_q_io_out_1_valid),
    .io_out_1_bits_isBranch (_q_io_out_1_bits_isBranch),
    .io_out_1_bits_isJAL    (_q_io_out_1_bits_isJAL),
    .io_out_1_bits_lsType   (_q_io_out_1_bits_lsType),
    .io_out_1_bits_writeRf  (_q_io_out_1_bits_writeRf),
    .io_out_1_bits_rd       (_q_io_out_1_bits_rd),
    .io_out_1_bits_pc       (_q_io_out_1_bits_pc),
    .io_out_1_bits_rdTag    (_q_io_out_1_bits_rdTag),
    .io_out_1_bits_flushed  (_q_io_out_1_bits_flushed),
    .io_out_1_bits_arfTag   (_q_io_out_1_bits_arfTag),
    .io_out_1_bits_arfValid (_q_io_out_1_bits_arfValid),
    .io_out_1_bits_inst     (_q_io_out_1_bits_inst)
  );
  DCPipelineRegister pRegs_0 (
    .clock                (clock),
    .reset                (reset),
    .io_in_ready          (_pRegs_0_io_in_ready),
    .io_in_valid          (_q_io_out_0_valid),
    .io_in_bits_isBranch  (_q_io_out_0_bits_isBranch),
    .io_in_bits_isJAL     (_q_io_out_0_bits_isJAL),
    .io_in_bits_lsType    (_q_io_out_0_bits_lsType),
    .io_in_bits_writeRf   (pRegs_0_io_in_bits_writeRf),
    .io_in_bits_rd        (_q_io_out_0_bits_rd),
    .io_in_bits_pc        (_q_io_out_0_bits_pc),
    .io_in_bits_rdTag     (_q_io_out_0_bits_rdTag),
    .io_in_bits_flushed   (|{_q_io_out_0_bits_flushed | io_flush, savedCounts_0}),
    .io_in_bits_arfTag    (_q_io_out_0_bits_arfTag),
    .io_in_bits_arfValid  (_q_io_out_0_bits_arfValid),
    .io_in_bits_inst      (_q_io_out_0_bits_inst),
    .io_valids_0          (_q_io_out_0_valid),
    .io_out_ready         (io_out_0_ready),
    .io_out_valid         (_pRegs_0_io_out_valid),
    .io_out_bits_isBranch (io_out_0_bits_isBranch),
    .io_out_bits_isJAL    (io_out_0_bits_isJAL),
    .io_out_bits_lsType   (io_out_0_bits_lsType),
    .io_out_bits_writeRf  (io_out_0_bits_writeRf),
    .io_out_bits_rd       (io_out_0_bits_rd),
    .io_out_bits_pc       (io_out_0_bits_pc),
    .io_out_bits_rdTag    (io_out_0_bits_rdTag),
    .io_out_bits_flushed  (io_out_0_bits_flushed),
    .io_out_bits_arfTag   (io_out_0_bits_arfTag),
    .io_out_bits_arfValid (io_out_0_bits_arfValid),
    .io_out_bits_inst     (io_out_0_bits_inst)
  );
  DCPipelineRegister pRegs_1 (
    .clock                (clock),
    .reset                (reset),
    .io_in_ready          (_pRegs_1_io_in_ready),
    .io_in_valid          (_q_io_out_1_valid),
    .io_in_bits_isBranch  (_q_io_out_1_bits_isBranch),
    .io_in_bits_isJAL     (_q_io_out_1_bits_isJAL),
    .io_in_bits_lsType    (_q_io_out_1_bits_lsType),
    .io_in_bits_writeRf   (pRegs_1_io_in_bits_writeRf),
    .io_in_bits_rd        (_q_io_out_1_bits_rd),
    .io_in_bits_pc        (_q_io_out_1_bits_pc),
    .io_in_bits_rdTag     (_q_io_out_1_bits_rdTag),
    .io_in_bits_flushed   (|{_q_io_out_1_bits_flushed | io_flush, savedCounts_1}),
    .io_in_bits_arfTag    (_q_io_out_1_bits_arfTag),
    .io_in_bits_arfValid  (_q_io_out_1_bits_arfValid),
    .io_in_bits_inst      (_q_io_out_1_bits_inst),
    .io_valids_0          (_q_io_out_1_valid),
    .io_out_ready         (io_out_1_ready),
    .io_out_valid         (_pRegs_1_io_out_valid),
    .io_out_bits_isBranch (io_out_1_bits_isBranch),
    .io_out_bits_isJAL    (io_out_1_bits_isJAL),
    .io_out_bits_lsType   (io_out_1_bits_lsType),
    .io_out_bits_writeRf  (io_out_1_bits_writeRf),
    .io_out_bits_rd       (io_out_1_bits_rd),
    .io_out_bits_pc       (io_out_1_bits_pc),
    .io_out_bits_rdTag    (io_out_1_bits_rdTag),
    .io_out_bits_flushed  (io_out_1_bits_flushed),
    .io_out_bits_arfTag   (io_out_1_bits_arfTag),
    .io_out_bits_arfValid (io_out_1_bits_arfValid),
    .io_out_bits_inst     (io_out_1_bits_inst)
  );
  assign io_out_0_valid = _pRegs_0_io_out_valid;
  assign io_out_1_valid = _pRegs_1_io_out_valid;
  assign io_firstPC_bits = _q_io_out_0_bits_pc;
endmodule

