// Generated by CIRCT firtool-1.76.0
module SRT16DividerDataModule(
  input  wire        clock,
  input  wire        reset,
  input  wire [31:0] io_src_0,
  input  wire [31:0] io_src_1,
  input  wire        io_valid,
  input  wire        io_sign,
  input  wire        io_isHi,
  output wire        io_in_ready,
  output wire        io_out_valid,
  output wire [31:0] io_out_data,
  input  wire        io_out_ready
);

  wire [31:0] _rightShifter_io_out;
  wire [12:0] _signs2_csa_spec_4_3_io_out_0;
  wire [12:0] _signs2_csa_spec_4_3_io_out_1;
  wire [12:0] _signs2_csa_spec_4_2_io_out_0;
  wire [12:0] _signs2_csa_spec_4_2_io_out_1;
  wire [12:0] _signs2_csa_spec_4_1_io_out_0;
  wire [12:0] _signs2_csa_spec_4_1_io_out_1;
  wire [12:0] _signs2_csa_spec_4_0_io_out_0;
  wire [12:0] _signs2_csa_spec_4_0_io_out_1;
  wire [12:0] _csa_spec_4_io_out_0;
  wire [12:0] _csa_spec_4_io_out_1;
  wire [12:0] _signs2_csa_spec_3_3_io_out_0;
  wire [12:0] _signs2_csa_spec_3_3_io_out_1;
  wire [12:0] _signs2_csa_spec_3_2_io_out_0;
  wire [12:0] _signs2_csa_spec_3_2_io_out_1;
  wire [12:0] _signs2_csa_spec_3_1_io_out_0;
  wire [12:0] _signs2_csa_spec_3_1_io_out_1;
  wire [12:0] _signs2_csa_spec_3_0_io_out_0;
  wire [12:0] _signs2_csa_spec_3_0_io_out_1;
  wire [12:0] _csa_spec_3_io_out_0;
  wire [12:0] _csa_spec_3_io_out_1;
  wire [12:0] _signs2_csa_spec_2_3_io_out_0;
  wire [12:0] _signs2_csa_spec_2_3_io_out_1;
  wire [12:0] _signs2_csa_spec_2_2_io_out_0;
  wire [12:0] _signs2_csa_spec_2_2_io_out_1;
  wire [12:0] _signs2_csa_spec_2_1_io_out_0;
  wire [12:0] _signs2_csa_spec_2_1_io_out_1;
  wire [12:0] _signs2_csa_spec_2_0_io_out_0;
  wire [12:0] _signs2_csa_spec_2_0_io_out_1;
  wire [12:0] _csa_spec_2_io_out_0;
  wire [12:0] _csa_spec_2_io_out_1;
  wire [12:0] _signs2_csa_spec_1_3_io_out_0;
  wire [12:0] _signs2_csa_spec_1_3_io_out_1;
  wire [12:0] _signs2_csa_spec_1_2_io_out_0;
  wire [12:0] _signs2_csa_spec_1_2_io_out_1;
  wire [12:0] _signs2_csa_spec_1_1_io_out_0;
  wire [12:0] _signs2_csa_spec_1_1_io_out_1;
  wire [12:0] _signs2_csa_spec_1_0_io_out_0;
  wire [12:0] _signs2_csa_spec_1_0_io_out_1;
  wire [12:0] _csa_spec_1_io_out_0;
  wire [12:0] _csa_spec_1_io_out_1;
  wire [12:0] _signs2_csa_spec_0_3_io_out_0;
  wire [12:0] _signs2_csa_spec_0_3_io_out_1;
  wire [12:0] _signs2_csa_spec_0_2_io_out_0;
  wire [12:0] _signs2_csa_spec_0_2_io_out_1;
  wire [12:0] _signs2_csa_spec_0_1_io_out_0;
  wire [12:0] _signs2_csa_spec_0_1_io_out_1;
  wire [12:0] _signs2_csa_spec_0_0_io_out_0;
  wire [12:0] _signs2_csa_spec_0_0_io_out_1;
  wire [12:0] _csa_spec_0_io_out_0;
  wire [12:0] _csa_spec_0_io_out_1;
  wire [35:0] _csa_sel_wide_2_io_out_0;
  wire [35:0] _csa_sel_wide_2_io_out_1;
  wire [35:0] _csa_sel_wide_1_io_out_0;
  wire [35:0] _csa_sel_wide_1_io_out_1;
  wire [9:0]  _signs_csa_sel_3_io_out_0;
  wire [9:0]  _signs_csa_sel_3_io_out_1;
  wire [9:0]  _signs_csa_sel_2_io_out_0;
  wire [9:0]  _signs_csa_sel_2_io_out_1;
  wire [9:0]  _signs_csa_sel_1_io_out_0;
  wire [9:0]  _signs_csa_sel_1_io_out_1;
  wire [9:0]  _signs_csa_sel_0_io_out_0;
  wire [9:0]  _signs_csa_sel_0_io_out_1;
  reg  [6:0]  state;
  reg  [31:0] quotIterReg;
  reg  [31:0] quotM1IterReg;
  reg         specialReg;
  reg  [31:0] aReg;
  reg         isHi_r;
  reg         dSignReg;
  reg  [31:0] aAbsReg;
  reg  [31:0] dAbsReg;
  reg  [31:0] aNormReg;
  reg  [31:0] dNormReg;
  wire [4:0]  _aLZC_T_34 = aAbsReg[2] ? 5'h1D : {4'hF, ~(aAbsReg[1])};
  wire [4:0]  _aLZC_T_35 = aAbsReg[3] ? 5'h1C : _aLZC_T_34;
  wire [4:0]  _aLZC_T_36 = aAbsReg[4] ? 5'h1B : _aLZC_T_35;
  wire [4:0]  _aLZC_T_37 = aAbsReg[5] ? 5'h1A : _aLZC_T_36;
  wire [4:0]  _aLZC_T_38 = aAbsReg[6] ? 5'h19 : _aLZC_T_37;
  wire [4:0]  _aLZC_T_39 = aAbsReg[7] ? 5'h18 : _aLZC_T_38;
  wire [4:0]  _aLZC_T_40 = aAbsReg[8] ? 5'h17 : _aLZC_T_39;
  wire [4:0]  _aLZC_T_41 = aAbsReg[9] ? 5'h16 : _aLZC_T_40;
  wire [4:0]  _aLZC_T_42 = aAbsReg[10] ? 5'h15 : _aLZC_T_41;
  wire [4:0]  _aLZC_T_43 = aAbsReg[11] ? 5'h14 : _aLZC_T_42;
  wire [4:0]  _aLZC_T_44 = aAbsReg[12] ? 5'h13 : _aLZC_T_43;
  wire [4:0]  _aLZC_T_45 = aAbsReg[13] ? 5'h12 : _aLZC_T_44;
  wire [4:0]  _aLZC_T_46 = aAbsReg[14] ? 5'h11 : _aLZC_T_45;
  wire [4:0]  _aLZC_T_47 = aAbsReg[15] ? 5'h10 : _aLZC_T_46;
  wire [4:0]  _aLZC_T_48 = aAbsReg[16] ? 5'hF : _aLZC_T_47;
  wire [4:0]  _aLZC_T_49 = aAbsReg[17] ? 5'hE : _aLZC_T_48;
  wire [4:0]  _aLZC_T_50 = aAbsReg[18] ? 5'hD : _aLZC_T_49;
  wire [4:0]  _aLZC_T_51 = aAbsReg[19] ? 5'hC : _aLZC_T_50;
  wire [4:0]  _aLZC_T_52 = aAbsReg[20] ? 5'hB : _aLZC_T_51;
  wire [4:0]  _aLZC_T_53 = aAbsReg[21] ? 5'hA : _aLZC_T_52;
  wire [4:0]  _aLZC_T_54 = aAbsReg[22] ? 5'h9 : _aLZC_T_53;
  wire [4:0]  _aLZC_T_55 = aAbsReg[23] ? 5'h8 : _aLZC_T_54;
  wire [4:0]  _aLZC_T_56 = aAbsReg[24] ? 5'h7 : _aLZC_T_55;
  wire [4:0]  _aLZC_T_57 = aAbsReg[25] ? 5'h6 : _aLZC_T_56;
  wire [4:0]  _aLZC_T_58 = aAbsReg[26] ? 5'h5 : _aLZC_T_57;
  wire [4:0]  _aLZC_T_59 = aAbsReg[27] ? 5'h4 : _aLZC_T_58;
  wire [4:0]  _aLZC_T_60 = aAbsReg[28] ? 5'h3 : _aLZC_T_59;
  wire [4:0]  _aLZC_T_61 = aAbsReg[29] ? 5'h2 : _aLZC_T_60;
  wire [4:0]  _aLZC_T_62 = aAbsReg[30] ? 5'h1 : _aLZC_T_61;
  wire [4:0]  _aLZC_T_63 = aAbsReg[31] ? 5'h0 : _aLZC_T_62;
  wire [4:0]  _dLZC_T_34 = dAbsReg[2] ? 5'h1D : {4'hF, ~(dAbsReg[1])};
  wire [4:0]  _dLZC_T_35 = dAbsReg[3] ? 5'h1C : _dLZC_T_34;
  wire [4:0]  _dLZC_T_36 = dAbsReg[4] ? 5'h1B : _dLZC_T_35;
  wire [4:0]  _dLZC_T_37 = dAbsReg[5] ? 5'h1A : _dLZC_T_36;
  wire [4:0]  _dLZC_T_38 = dAbsReg[6] ? 5'h19 : _dLZC_T_37;
  wire [4:0]  _dLZC_T_39 = dAbsReg[7] ? 5'h18 : _dLZC_T_38;
  wire [4:0]  _dLZC_T_40 = dAbsReg[8] ? 5'h17 : _dLZC_T_39;
  wire [4:0]  _dLZC_T_41 = dAbsReg[9] ? 5'h16 : _dLZC_T_40;
  wire [4:0]  _dLZC_T_42 = dAbsReg[10] ? 5'h15 : _dLZC_T_41;
  wire [4:0]  _dLZC_T_43 = dAbsReg[11] ? 5'h14 : _dLZC_T_42;
  wire [4:0]  _dLZC_T_44 = dAbsReg[12] ? 5'h13 : _dLZC_T_43;
  wire [4:0]  _dLZC_T_45 = dAbsReg[13] ? 5'h12 : _dLZC_T_44;
  wire [4:0]  _dLZC_T_46 = dAbsReg[14] ? 5'h11 : _dLZC_T_45;
  wire [4:0]  _dLZC_T_47 = dAbsReg[15] ? 5'h10 : _dLZC_T_46;
  wire [4:0]  _dLZC_T_48 = dAbsReg[16] ? 5'hF : _dLZC_T_47;
  wire [4:0]  _dLZC_T_49 = dAbsReg[17] ? 5'hE : _dLZC_T_48;
  wire [4:0]  _dLZC_T_50 = dAbsReg[18] ? 5'hD : _dLZC_T_49;
  wire [4:0]  _dLZC_T_51 = dAbsReg[19] ? 5'hC : _dLZC_T_50;
  wire [4:0]  _dLZC_T_52 = dAbsReg[20] ? 5'hB : _dLZC_T_51;
  wire [4:0]  _dLZC_T_53 = dAbsReg[21] ? 5'hA : _dLZC_T_52;
  wire [4:0]  _dLZC_T_54 = dAbsReg[22] ? 5'h9 : _dLZC_T_53;
  wire [4:0]  _dLZC_T_55 = dAbsReg[23] ? 5'h8 : _dLZC_T_54;
  wire [4:0]  _dLZC_T_56 = dAbsReg[24] ? 5'h7 : _dLZC_T_55;
  wire [4:0]  _dLZC_T_57 = dAbsReg[25] ? 5'h6 : _dLZC_T_56;
  wire [4:0]  _dLZC_T_58 = dAbsReg[26] ? 5'h5 : _dLZC_T_57;
  wire [4:0]  _dLZC_T_59 = dAbsReg[27] ? 5'h4 : _dLZC_T_58;
  wire [4:0]  _dLZC_T_60 = dAbsReg[28] ? 5'h3 : _dLZC_T_59;
  wire [4:0]  _dLZC_T_61 = dAbsReg[29] ? 5'h2 : _dLZC_T_60;
  wire [4:0]  _dLZC_T_62 = dAbsReg[30] ? 5'h1 : _dLZC_T_61;
  wire [4:0]  _dLZC_T_63 = dAbsReg[31] ? 5'h0 : _dLZC_T_62;
  reg  [5:0]  aLZCReg;
  reg  [5:0]  dLZCReg;
  wire [4:0]  _lzcRegDiff_T_4 = dLZCReg[4:0] - aLZCReg[4:0];
  wire        dIsZero = dNormReg == 32'h0;
  reg         aTooSmall;
  wire        special = (&_dLZC_T_63) | dIsZero | aTooSmall;
  reg  [31:0] quotSpecialReg;
  reg  [31:0] remSpecialReg;
  reg         quotSignReg;
  reg         rSignReg;
  reg  [2:0]  iterNumReg;
  reg  [4:0]  qPrevReg;
  reg  [35:0] rSumReg;
  reg  [35:0] rCarryReg;
  wire        _GEN = dNormReg[30:28] == 3'h1;
  reg  [6:0]  casez_tmp;
  wire [6:0]  _GEN_0 = {4'h3, _GEN, 2'h2};
  always_comb begin
    casez (dNormReg[30:28])
      3'b000:
        casez_tmp = _GEN_0;
      3'b001:
        casez_tmp = _GEN_0;
      3'b010:
        casez_tmp = 7'h20;
      3'b011:
        casez_tmp = 7'h24;
      3'b100:
        casez_tmp = 7'h26;
      3'b101:
        casez_tmp = 7'h2A;
      3'b110:
        casez_tmp = 7'h2C;
      default:
        casez_tmp = 7'h30;
    endcase
  end // always_comb
  reg  [6:0]  casez_tmp_0;
  always_comb begin
    casez (dNormReg[30:28])
      3'b000:
        casez_tmp_0 = 7'h68;
      3'b001:
        casez_tmp_0 = 7'h64;
      3'b010:
        casez_tmp_0 = 7'h62;
      3'b011:
        casez_tmp_0 = 7'h5E;
      3'b100:
        casez_tmp_0 = 7'h5C;
      3'b101:
        casez_tmp_0 = 7'h58;
      3'b110:
        casez_tmp_0 = 7'h56;
      default:
        casez_tmp_0 = 7'h52;
    endcase
  end // always_comb
  reg  [35:0] udNegReg_0;
  reg  [35:0] udNegReg_1;
  reg  [35:0] udNegReg_3;
  reg  [35:0] udNegReg_4;
  reg  [9:0]  rudPmNegReg_0_0;
  reg  [9:0]  rudPmNegReg_0_1;
  reg  [9:0]  rudPmNegReg_0_2;
  reg  [9:0]  rudPmNegReg_0_3;
  reg  [9:0]  rudPmNegReg_1_0;
  reg  [9:0]  rudPmNegReg_1_1;
  reg  [9:0]  rudPmNegReg_1_2;
  reg  [9:0]  rudPmNegReg_1_3;
  reg  [9:0]  rudPmNegReg_2_0;
  reg  [9:0]  rudPmNegReg_2_1;
  reg  [9:0]  rudPmNegReg_2_2;
  reg  [9:0]  rudPmNegReg_2_3;
  reg  [9:0]  rudPmNegReg_3_0;
  reg  [9:0]  rudPmNegReg_3_1;
  reg  [9:0]  rudPmNegReg_3_2;
  reg  [9:0]  rudPmNegReg_3_3;
  reg  [9:0]  rudPmNegReg_4_0;
  reg  [9:0]  rudPmNegReg_4_1;
  reg  [9:0]  rudPmNegReg_4_2;
  reg  [9:0]  rudPmNegReg_4_3;
  reg  [12:0] r2udPmNegReg_0_0;
  reg  [12:0] r2udPmNegReg_0_1;
  reg  [12:0] r2udPmNegReg_0_2;
  reg  [12:0] r2udPmNegReg_0_3;
  reg  [12:0] r2udPmNegReg_1_0;
  reg  [12:0] r2udPmNegReg_1_1;
  reg  [12:0] r2udPmNegReg_1_2;
  reg  [12:0] r2udPmNegReg_1_3;
  reg  [12:0] r2udPmNegReg_2_0;
  reg  [12:0] r2udPmNegReg_2_1;
  reg  [12:0] r2udPmNegReg_2_2;
  reg  [12:0] r2udPmNegReg_2_3;
  reg  [12:0] r2udPmNegReg_3_0;
  reg  [12:0] r2udPmNegReg_3_1;
  reg  [12:0] r2udPmNegReg_3_2;
  reg  [12:0] r2udPmNegReg_3_3;
  reg  [12:0] r2udPmNegReg_4_0;
  reg  [12:0] r2udPmNegReg_4_1;
  reg  [12:0] r2udPmNegReg_4_2;
  reg  [12:0] r2udPmNegReg_4_3;
  wire [9:0]  _signs_csa_sel_0_io_in_2_T_5 = qPrevReg[0] ? rudPmNegReg_0_0 : 10'h0;
  wire [9:0]  _signs_csa_sel_0_io_in_2_T_6 = qPrevReg[1] ? rudPmNegReg_1_0 : 10'h0;
  wire [9:0]  _signs_csa_sel_0_io_in_2_T_7 = qPrevReg[2] ? rudPmNegReg_2_0 : 10'h0;
  wire [9:0]  _signs_csa_sel_0_io_in_2_T_8 = qPrevReg[3] ? rudPmNegReg_3_0 : 10'h0;
  wire [9:0]  _signs_csa_sel_0_io_in_2_T_9 = qPrevReg[4] ? rudPmNegReg_4_0 : 10'h0;
  wire [9:0]  _signs_T_2 =
    _signs_csa_sel_0_io_out_0 + {_signs_csa_sel_0_io_out_1[8:0], 1'h0};
  wire [9:0]  _signs_csa_sel_1_io_in_2_T_14 = qPrevReg[0] ? rudPmNegReg_0_1 : 10'h0;
  wire [9:0]  _signs_csa_sel_1_io_in_2_T_15 = qPrevReg[1] ? rudPmNegReg_1_1 : 10'h0;
  wire [9:0]  _signs_csa_sel_1_io_in_2_T_16 = qPrevReg[2] ? rudPmNegReg_2_1 : 10'h0;
  wire [9:0]  _signs_csa_sel_1_io_in_2_T_17 = qPrevReg[3] ? rudPmNegReg_3_1 : 10'h0;
  wire [9:0]  _signs_csa_sel_1_io_in_2_T_18 = qPrevReg[4] ? rudPmNegReg_4_1 : 10'h0;
  wire [9:0]  _signs_T_7 =
    _signs_csa_sel_1_io_out_0 + {_signs_csa_sel_1_io_out_1[8:0], 1'h0};
  wire [9:0]  _signs_csa_sel_2_io_in_2_T_23 = qPrevReg[0] ? rudPmNegReg_0_2 : 10'h0;
  wire [9:0]  _signs_csa_sel_2_io_in_2_T_24 = qPrevReg[1] ? rudPmNegReg_1_2 : 10'h0;
  wire [9:0]  _signs_csa_sel_2_io_in_2_T_25 = qPrevReg[2] ? rudPmNegReg_2_2 : 10'h0;
  wire [9:0]  _signs_csa_sel_2_io_in_2_T_26 = qPrevReg[3] ? rudPmNegReg_3_2 : 10'h0;
  wire [9:0]  _signs_csa_sel_2_io_in_2_T_27 = qPrevReg[4] ? rudPmNegReg_4_2 : 10'h0;
  wire [9:0]  _signs_T_12 =
    _signs_csa_sel_2_io_out_0 + {_signs_csa_sel_2_io_out_1[8:0], 1'h0};
  wire [9:0]  _signs_csa_sel_3_io_in_2_T_32 = qPrevReg[0] ? rudPmNegReg_0_3 : 10'h0;
  wire [9:0]  _signs_csa_sel_3_io_in_2_T_33 = qPrevReg[1] ? rudPmNegReg_1_3 : 10'h0;
  wire [9:0]  _signs_csa_sel_3_io_in_2_T_34 = qPrevReg[2] ? rudPmNegReg_2_3 : 10'h0;
  wire [9:0]  _signs_csa_sel_3_io_in_2_T_35 = qPrevReg[3] ? rudPmNegReg_3_3 : 10'h0;
  wire [9:0]  _signs_csa_sel_3_io_in_2_T_36 = qPrevReg[4] ? rudPmNegReg_4_3 : 10'h0;
  wire [9:0]  _signs_T_17 =
    _signs_csa_sel_3_io_out_0 + {_signs_csa_sel_3_io_out_1[8:0], 1'h0};
  wire        qNext_sel_q_0 = _signs_T_2[9] & _signs_T_7[9] & _signs_T_12[9];
  wire        qNext_sel_q_1 = ~(_signs_T_2[9]) & _signs_T_7[9] & _signs_T_12[9];
  wire        qNext_sel_q_2 = _signs_T_12[9] & ~(_signs_T_7[9]);
  wire        qNext_sel_q_3 = _signs_T_17[9] & ~(_signs_T_12[9]) & ~(_signs_T_7[9]);
  wire        qNext_sel_q_4 = ~(_signs_T_17[9]) & ~(_signs_T_12[9]) & ~(_signs_T_7[9]);
  wire [33:0] _csa_sel_wide_1_io_in_2_T_5 = qPrevReg[0] ? udNegReg_0[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_1_io_in_2_T_6 = qPrevReg[1] ? udNegReg_1[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_1_io_in_2_T_8 = qPrevReg[3] ? udNegReg_3[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_1_io_in_2_T_9 = qPrevReg[4] ? udNegReg_4[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_2_io_in_2_T_5 = qNext_sel_q_0 ? udNegReg_0[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_2_io_in_2_T_6 = qNext_sel_q_1 ? udNegReg_1[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_2_io_in_2_T_8 = qNext_sel_q_3 ? udNegReg_3[33:0] : 34'h0;
  wire [33:0] _csa_sel_wide_2_io_in_2_T_9 = qNext_sel_q_4 ? udNegReg_4[33:0] : 34'h0;
  wire        _quotM1IterNext_T = _lzcRegDiff_T_4[1] ^ ~(_lzcRegDiff_T_4[0]);
  wire [35:0] rSumIter =
    _quotM1IterNext_T & ~(|iterNumReg)
      ? _csa_sel_wide_1_io_out_0
      : _csa_sel_wide_2_io_out_0;
  wire [34:0] _GEN_1 =
    _quotM1IterNext_T & ~(|iterNumReg)
      ? _csa_sel_wide_1_io_out_1[34:0]
      : _csa_sel_wide_2_io_out_1[34:0];
  wire [12:0] _signs2_csa_spec_0_0_io_in_2_T_5 = qPrevReg[0] ? r2udPmNegReg_0_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_0_io_in_2_T_6 = qPrevReg[1] ? r2udPmNegReg_1_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_0_io_in_2_T_7 = qPrevReg[2] ? r2udPmNegReg_2_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_0_io_in_2_T_8 = qPrevReg[3] ? r2udPmNegReg_3_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_0_io_in_2_T_9 = qPrevReg[4] ? r2udPmNegReg_4_0 : 13'h0;
  wire [12:0] _signs2_T_2 =
    _signs2_csa_spec_0_0_io_out_0 + {_signs2_csa_spec_0_0_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_0_1_io_in_2_T_14 = qPrevReg[0] ? r2udPmNegReg_0_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_1_io_in_2_T_15 = qPrevReg[1] ? r2udPmNegReg_1_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_1_io_in_2_T_16 = qPrevReg[2] ? r2udPmNegReg_2_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_1_io_in_2_T_17 = qPrevReg[3] ? r2udPmNegReg_3_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_1_io_in_2_T_18 = qPrevReg[4] ? r2udPmNegReg_4_1 : 13'h0;
  wire [12:0] _signs2_T_7 =
    _signs2_csa_spec_0_1_io_out_0 + {_signs2_csa_spec_0_1_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_0_2_io_in_2_T_23 = qPrevReg[0] ? r2udPmNegReg_0_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_2_io_in_2_T_24 = qPrevReg[1] ? r2udPmNegReg_1_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_2_io_in_2_T_25 = qPrevReg[2] ? r2udPmNegReg_2_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_2_io_in_2_T_26 = qPrevReg[3] ? r2udPmNegReg_3_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_2_io_in_2_T_27 = qPrevReg[4] ? r2udPmNegReg_4_2 : 13'h0;
  wire [12:0] _signs2_T_12 =
    _signs2_csa_spec_0_2_io_out_0 + {_signs2_csa_spec_0_2_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_0_3_io_in_2_T_32 = qPrevReg[0] ? r2udPmNegReg_0_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_3_io_in_2_T_33 = qPrevReg[1] ? r2udPmNegReg_1_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_3_io_in_2_T_34 = qPrevReg[2] ? r2udPmNegReg_2_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_3_io_in_2_T_35 = qPrevReg[3] ? r2udPmNegReg_3_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_0_3_io_in_2_T_36 = qPrevReg[4] ? r2udPmNegReg_4_3 : 13'h0;
  wire [12:0] _signs2_T_17 =
    _signs2_csa_spec_0_3_io_out_0 + {_signs2_csa_spec_0_3_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_1_0_io_in_2_T_5 = qPrevReg[0] ? r2udPmNegReg_0_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_0_io_in_2_T_6 = qPrevReg[1] ? r2udPmNegReg_1_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_0_io_in_2_T_7 = qPrevReg[2] ? r2udPmNegReg_2_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_0_io_in_2_T_8 = qPrevReg[3] ? r2udPmNegReg_3_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_0_io_in_2_T_9 = qPrevReg[4] ? r2udPmNegReg_4_0 : 13'h0;
  wire [12:0] _signs2_T_22 =
    _signs2_csa_spec_1_0_io_out_0 + {_signs2_csa_spec_1_0_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_1_1_io_in_2_T_14 = qPrevReg[0] ? r2udPmNegReg_0_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_1_io_in_2_T_15 = qPrevReg[1] ? r2udPmNegReg_1_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_1_io_in_2_T_16 = qPrevReg[2] ? r2udPmNegReg_2_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_1_io_in_2_T_17 = qPrevReg[3] ? r2udPmNegReg_3_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_1_io_in_2_T_18 = qPrevReg[4] ? r2udPmNegReg_4_1 : 13'h0;
  wire [12:0] _signs2_T_27 =
    _signs2_csa_spec_1_1_io_out_0 + {_signs2_csa_spec_1_1_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_1_2_io_in_2_T_23 = qPrevReg[0] ? r2udPmNegReg_0_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_2_io_in_2_T_24 = qPrevReg[1] ? r2udPmNegReg_1_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_2_io_in_2_T_25 = qPrevReg[2] ? r2udPmNegReg_2_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_2_io_in_2_T_26 = qPrevReg[3] ? r2udPmNegReg_3_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_2_io_in_2_T_27 = qPrevReg[4] ? r2udPmNegReg_4_2 : 13'h0;
  wire [12:0] _signs2_T_32 =
    _signs2_csa_spec_1_2_io_out_0 + {_signs2_csa_spec_1_2_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_1_3_io_in_2_T_32 = qPrevReg[0] ? r2udPmNegReg_0_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_3_io_in_2_T_33 = qPrevReg[1] ? r2udPmNegReg_1_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_3_io_in_2_T_34 = qPrevReg[2] ? r2udPmNegReg_2_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_3_io_in_2_T_35 = qPrevReg[3] ? r2udPmNegReg_3_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_1_3_io_in_2_T_36 = qPrevReg[4] ? r2udPmNegReg_4_3 : 13'h0;
  wire [12:0] _signs2_T_37 =
    _signs2_csa_spec_1_3_io_out_0 + {_signs2_csa_spec_1_3_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_2_0_io_in_2_T_5 = qPrevReg[0] ? r2udPmNegReg_0_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_0_io_in_2_T_6 = qPrevReg[1] ? r2udPmNegReg_1_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_0_io_in_2_T_7 = qPrevReg[2] ? r2udPmNegReg_2_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_0_io_in_2_T_8 = qPrevReg[3] ? r2udPmNegReg_3_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_0_io_in_2_T_9 = qPrevReg[4] ? r2udPmNegReg_4_0 : 13'h0;
  wire [12:0] _signs2_T_42 =
    _signs2_csa_spec_2_0_io_out_0 + {_signs2_csa_spec_2_0_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_2_1_io_in_2_T_14 = qPrevReg[0] ? r2udPmNegReg_0_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_1_io_in_2_T_15 = qPrevReg[1] ? r2udPmNegReg_1_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_1_io_in_2_T_16 = qPrevReg[2] ? r2udPmNegReg_2_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_1_io_in_2_T_17 = qPrevReg[3] ? r2udPmNegReg_3_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_1_io_in_2_T_18 = qPrevReg[4] ? r2udPmNegReg_4_1 : 13'h0;
  wire [12:0] _signs2_T_47 =
    _signs2_csa_spec_2_1_io_out_0 + {_signs2_csa_spec_2_1_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_2_2_io_in_2_T_23 = qPrevReg[0] ? r2udPmNegReg_0_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_2_io_in_2_T_24 = qPrevReg[1] ? r2udPmNegReg_1_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_2_io_in_2_T_25 = qPrevReg[2] ? r2udPmNegReg_2_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_2_io_in_2_T_26 = qPrevReg[3] ? r2udPmNegReg_3_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_2_io_in_2_T_27 = qPrevReg[4] ? r2udPmNegReg_4_2 : 13'h0;
  wire [12:0] _signs2_T_52 =
    _signs2_csa_spec_2_2_io_out_0 + {_signs2_csa_spec_2_2_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_2_3_io_in_2_T_32 = qPrevReg[0] ? r2udPmNegReg_0_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_3_io_in_2_T_33 = qPrevReg[1] ? r2udPmNegReg_1_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_3_io_in_2_T_34 = qPrevReg[2] ? r2udPmNegReg_2_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_3_io_in_2_T_35 = qPrevReg[3] ? r2udPmNegReg_3_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_2_3_io_in_2_T_36 = qPrevReg[4] ? r2udPmNegReg_4_3 : 13'h0;
  wire [12:0] _signs2_T_57 =
    _signs2_csa_spec_2_3_io_out_0 + {_signs2_csa_spec_2_3_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_3_0_io_in_2_T_5 = qPrevReg[0] ? r2udPmNegReg_0_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_0_io_in_2_T_6 = qPrevReg[1] ? r2udPmNegReg_1_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_0_io_in_2_T_7 = qPrevReg[2] ? r2udPmNegReg_2_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_0_io_in_2_T_8 = qPrevReg[3] ? r2udPmNegReg_3_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_0_io_in_2_T_9 = qPrevReg[4] ? r2udPmNegReg_4_0 : 13'h0;
  wire [12:0] _signs2_T_62 =
    _signs2_csa_spec_3_0_io_out_0 + {_signs2_csa_spec_3_0_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_3_1_io_in_2_T_14 = qPrevReg[0] ? r2udPmNegReg_0_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_1_io_in_2_T_15 = qPrevReg[1] ? r2udPmNegReg_1_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_1_io_in_2_T_16 = qPrevReg[2] ? r2udPmNegReg_2_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_1_io_in_2_T_17 = qPrevReg[3] ? r2udPmNegReg_3_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_1_io_in_2_T_18 = qPrevReg[4] ? r2udPmNegReg_4_1 : 13'h0;
  wire [12:0] _signs2_T_67 =
    _signs2_csa_spec_3_1_io_out_0 + {_signs2_csa_spec_3_1_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_3_2_io_in_2_T_23 = qPrevReg[0] ? r2udPmNegReg_0_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_2_io_in_2_T_24 = qPrevReg[1] ? r2udPmNegReg_1_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_2_io_in_2_T_25 = qPrevReg[2] ? r2udPmNegReg_2_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_2_io_in_2_T_26 = qPrevReg[3] ? r2udPmNegReg_3_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_2_io_in_2_T_27 = qPrevReg[4] ? r2udPmNegReg_4_2 : 13'h0;
  wire [12:0] _signs2_T_72 =
    _signs2_csa_spec_3_2_io_out_0 + {_signs2_csa_spec_3_2_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_3_3_io_in_2_T_32 = qPrevReg[0] ? r2udPmNegReg_0_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_3_io_in_2_T_33 = qPrevReg[1] ? r2udPmNegReg_1_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_3_io_in_2_T_34 = qPrevReg[2] ? r2udPmNegReg_2_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_3_io_in_2_T_35 = qPrevReg[3] ? r2udPmNegReg_3_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_3_3_io_in_2_T_36 = qPrevReg[4] ? r2udPmNegReg_4_3 : 13'h0;
  wire [12:0] _signs2_T_77 =
    _signs2_csa_spec_3_3_io_out_0 + {_signs2_csa_spec_3_3_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_4_0_io_in_2_T_5 = qPrevReg[0] ? r2udPmNegReg_0_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_0_io_in_2_T_6 = qPrevReg[1] ? r2udPmNegReg_1_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_0_io_in_2_T_7 = qPrevReg[2] ? r2udPmNegReg_2_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_0_io_in_2_T_8 = qPrevReg[3] ? r2udPmNegReg_3_0 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_0_io_in_2_T_9 = qPrevReg[4] ? r2udPmNegReg_4_0 : 13'h0;
  wire [12:0] _signs2_T_82 =
    _signs2_csa_spec_4_0_io_out_0 + {_signs2_csa_spec_4_0_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_4_1_io_in_2_T_14 = qPrevReg[0] ? r2udPmNegReg_0_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_1_io_in_2_T_15 = qPrevReg[1] ? r2udPmNegReg_1_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_1_io_in_2_T_16 = qPrevReg[2] ? r2udPmNegReg_2_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_1_io_in_2_T_17 = qPrevReg[3] ? r2udPmNegReg_3_1 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_1_io_in_2_T_18 = qPrevReg[4] ? r2udPmNegReg_4_1 : 13'h0;
  wire [12:0] _signs2_T_87 =
    _signs2_csa_spec_4_1_io_out_0 + {_signs2_csa_spec_4_1_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_4_2_io_in_2_T_23 = qPrevReg[0] ? r2udPmNegReg_0_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_2_io_in_2_T_24 = qPrevReg[1] ? r2udPmNegReg_1_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_2_io_in_2_T_25 = qPrevReg[2] ? r2udPmNegReg_2_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_2_io_in_2_T_26 = qPrevReg[3] ? r2udPmNegReg_3_2 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_2_io_in_2_T_27 = qPrevReg[4] ? r2udPmNegReg_4_2 : 13'h0;
  wire [12:0] _signs2_T_92 =
    _signs2_csa_spec_4_2_io_out_0 + {_signs2_csa_spec_4_2_io_out_1[11:0], 1'h0};
  wire [12:0] _signs2_csa_spec_4_3_io_in_2_T_32 = qPrevReg[0] ? r2udPmNegReg_0_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_3_io_in_2_T_33 = qPrevReg[1] ? r2udPmNegReg_1_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_3_io_in_2_T_34 = qPrevReg[2] ? r2udPmNegReg_2_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_3_io_in_2_T_35 = qPrevReg[3] ? r2udPmNegReg_3_3 : 13'h0;
  wire [12:0] _signs2_csa_spec_4_3_io_in_2_T_36 = qPrevReg[4] ? r2udPmNegReg_4_3 : 13'h0;
  wire [12:0] _signs2_T_97 =
    _signs2_csa_spec_4_3_io_out_0 + {_signs2_csa_spec_4_3_io_out_1[11:0], 1'h0};
  wire [4:0]  _qNext2_T_5 =
    qNext_sel_q_0
      ? {~(_signs2_T_17[12]) & ~(_signs2_T_12[12]) & ~(_signs2_T_7[12]),
         _signs2_T_17[12] & ~(_signs2_T_12[12]) & ~(_signs2_T_7[12]),
         _signs2_T_12[12] & ~(_signs2_T_7[12]),
         ~(_signs2_T_2[12]) & _signs2_T_7[12] & _signs2_T_12[12],
         _signs2_T_2[12] & _signs2_T_7[12] & _signs2_T_12[12]}
      : 5'h0;
  wire [4:0]  _qNext2_T_6 =
    qNext_sel_q_1
      ? {~(_signs2_T_37[12]) & ~(_signs2_T_32[12]) & ~(_signs2_T_27[12]),
         _signs2_T_37[12] & ~(_signs2_T_32[12]) & ~(_signs2_T_27[12]),
         _signs2_T_32[12] & ~(_signs2_T_27[12]),
         ~(_signs2_T_22[12]) & _signs2_T_27[12] & _signs2_T_32[12],
         _signs2_T_22[12] & _signs2_T_27[12] & _signs2_T_32[12]}
      : 5'h0;
  wire [4:0]  _qNext2_T_7 =
    qNext_sel_q_2
      ? {~(_signs2_T_57[12]) & ~(_signs2_T_52[12]) & ~(_signs2_T_47[12]),
         _signs2_T_57[12] & ~(_signs2_T_52[12]) & ~(_signs2_T_47[12]),
         _signs2_T_52[12] & ~(_signs2_T_47[12]),
         ~(_signs2_T_42[12]) & _signs2_T_47[12] & _signs2_T_52[12],
         _signs2_T_42[12] & _signs2_T_47[12] & _signs2_T_52[12]}
      : 5'h0;
  wire [4:0]  _qNext2_T_8 =
    qNext_sel_q_3
      ? {~(_signs2_T_77[12]) & ~(_signs2_T_72[12]) & ~(_signs2_T_67[12]),
         _signs2_T_77[12] & ~(_signs2_T_72[12]) & ~(_signs2_T_67[12]),
         _signs2_T_72[12] & ~(_signs2_T_67[12]),
         ~(_signs2_T_62[12]) & _signs2_T_67[12] & _signs2_T_72[12],
         _signs2_T_62[12] & _signs2_T_67[12] & _signs2_T_72[12]}
      : 5'h0;
  wire [4:0]  _qNext2_T_9 =
    qNext_sel_q_4
      ? {~(_signs2_T_97[12]) & ~(_signs2_T_92[12]) & ~(_signs2_T_87[12]),
         _signs2_T_97[12] & ~(_signs2_T_92[12]) & ~(_signs2_T_87[12]),
         _signs2_T_92[12] & ~(_signs2_T_87[12]),
         ~(_signs2_T_82[12]) & _signs2_T_87[12] & _signs2_T_92[12],
         _signs2_T_82[12] & _signs2_T_87[12] & _signs2_T_92[12]}
      : 5'h0;
  reg  [32:0] rNextReg;
  reg  [32:0] rNextPdReg;
  wire        needCorr = rSignReg ? ~(rNextReg[32]) & (|rNextReg) : rNextReg[32];
  wire [32:0] rPreShifted = needCorr ? rNextPdReg : rNextReg;
  reg  [31:0] rFinal;
  reg  [31:0] qFinal;
  wire [62:0] _aNorm_T_2 = {31'h0, aAbsReg} << _aLZC_T_63;
  wire [62:0] _dNorm_T_2 = {31'h0, dAbsReg} << _dLZC_T_63;
  wire [5:0]  _lzcWireDiff_T_4 = {1'h0, _dLZC_T_63} - {1'h0, _aLZC_T_63};
  wire [31:0] _quotSpecial_T_3 = dSignReg ? 32'h0 - aReg : aReg;
  wire [31:0] _quotSpecial_T_4 = aTooSmall ? 32'h0 : _quotSpecial_T_3;
  wire [4:0]  _iterNum_T_2 = _lzcRegDiff_T_4 + 5'h1;
  wire [4:0]  mInitPos1 =
    (&(dNormReg[30:28]))
      ? 5'h8
      : {3'h1,
         dNormReg[30:28] == 3'h6 | dNormReg[30:28] == 3'h5 | dNormReg[30:28] == 3'h4
           | dNormReg[30:28] == 3'h3,
         1'h0};
  wire [4:0]  _mInitPos2_T_4 =
    dNormReg[30:28] == 3'h2 ? 5'hF : {3'h3, dNormReg[30:28] == 3'h1, 1'h0};
  wire [4:0]  _mInitPos2_T_6 = dNormReg[30:28] == 3'h3 ? 5'h10 : _mInitPos2_T_4;
  wire [4:0]  _mInitPos2_T_8 = dNormReg[30:28] == 3'h4 ? 5'h12 : _mInitPos2_T_6;
  wire [4:0]  _mInitPos2_T_10 = dNormReg[30:28] == 3'h5 ? 5'h14 : _mInitPos2_T_8;
  wire [4:0]  mInitPos2 =
    (&(dNormReg[30:28])) | dNormReg[30:28] == 3'h6 ? 5'h16 : _mInitPos2_T_10;
  wire [9:0]  _GEN_2 = {2'h0, dNormReg[31:24]};
  wire [9:0]  _GEN_3 = {3'h0, dNormReg[31:25]};
  wire [12:0] _GEN_4 = {2'h0, dNormReg[31:21]};
  wire [12:0] _GEN_5 = {3'h0, dNormReg[31:22]};
  wire [35:0] _rNext_T_4 = ~rSumReg + ~rCarryReg + 36'h2;
  wire [35:0] _rNextPd_T_8 = ~rSumReg + ~rCarryReg + {1'h1, ~dNormReg, 3'h7} + 36'h3;
  wire [31:0] _qFinal_T = needCorr ? quotM1IterReg : quotIterReg;
  wire        in_fire = io_valid & state[0];
  wire [31:0] _aInverter_T_2 = state[0] ? io_src_0 : quotIterReg;
  wire [31:0] aInverter = 32'h0 - _aInverter_T_2;
  wire [31:0] _dInverter_T_2 = state[0] ? io_src_1 : quotM1IterReg;
  wire [31:0] dInverter = 32'h0 - _dInverter_T_2;
  wire        aSign = io_sign & io_src_0[31];
  wire        dSign = io_sign & io_src_1[31];
  wire [32:0] _rSumInit_T_2 = _lzcRegDiff_T_4[0] ? {1'h0, aNormReg} : {aNormReg, 1'h0};
  wire [32:0] dNeg = 33'h0 - {1'h0, dNormReg};
  wire        _GEN_6 = dNormReg[30:28] == 3'h4;
  wire        _GEN_7 = dNormReg[30:28] == 3'h5;
  wire        _GEN_8 = dNormReg[30:28] == 3'h6;
  wire        _GEN_9 = dNormReg[30:28] == 3'h3 | dNormReg[30:28] == 3'h2 | _GEN;
  wire [6:0]  _GEN_10 =
    (&(dNormReg[30:28])) | _GEN_8 | _GEN_7 | _GEN_6 ? 7'h8 : {5'h1, _GEN_9, 1'h0};
  wire [6:0]  _GEN_11 = _GEN_6 ? 7'h7B : {6'h3E, ~_GEN_9};
  wire [6:0]  _GEN_12 = (&(dNormReg[30:28])) | _GEN_8 | _GEN_7 ? 7'h7A : _GEN_11;
  wire [1:0]  _GEN_13 = {2{dNeg[32]}};
  wire [31:0] _GEN_14 = {quotIterReg[29:0], 2'h1};
  wire [31:0] _GEN_15 = {quotIterReg[29:0], 2'h0};
  wire [31:0] _GEN_16 = {quotM1IterReg[29:0], 2'h3};
  wire [31:0] _GEN_17 = {quotM1IterReg[29:0], 2'h2};
  wire [31:0] _quotHalfIter_quotNext_T_24 = qPrevReg[0] ? _GEN_17 : 32'h0;
  wire [31:0] _quotHalfIter_quotNext_T_23 = qPrevReg[1] ? _GEN_16 : 32'h0;
  wire [31:0] _quotHalfIter_quotNext_T_22 = qPrevReg[2] ? _GEN_15 : 32'h0;
  wire [31:0] _quotHalfIter_quotNext_T_21 = qPrevReg[3] ? _GEN_14 : 32'h0;
  wire [31:0] _quotHalfIter_quotNext_T_20 =
    qPrevReg[4] ? {quotIterReg[29:0], 2'h2} : 32'h0;
  wire [31:0] quotHalfIter_quotNext =
    _quotHalfIter_quotNext_T_20 | _quotHalfIter_quotNext_T_21
    | _quotHalfIter_quotNext_T_22 | _quotHalfIter_quotNext_T_23
    | _quotHalfIter_quotNext_T_24;
  wire [31:0] _quotM1HalfIter_quotM1Next_T_24 =
    qPrevReg[0] ? {quotM1IterReg[29:0], 2'h1} : 32'h0;
  wire [31:0] _quotM1HalfIter_quotM1Next_T_23 = qPrevReg[1] ? _GEN_17 : 32'h0;
  wire [31:0] _quotM1HalfIter_quotM1Next_T_22 = qPrevReg[2] ? _GEN_16 : 32'h0;
  wire [31:0] _quotM1HalfIter_quotM1Next_T_21 = qPrevReg[3] ? _GEN_15 : 32'h0;
  wire [31:0] _quotM1HalfIter_quotM1Next_T_20 = qPrevReg[4] ? _GEN_14 : 32'h0;
  wire [31:0] quotM1HalfIter_quotM1Next =
    _quotM1HalfIter_quotM1Next_T_20 | _quotM1HalfIter_quotM1Next_T_21
    | _quotM1HalfIter_quotM1Next_T_22 | _quotM1HalfIter_quotM1Next_T_23
    | _quotM1HalfIter_quotM1Next_T_24;
  wire [31:0] _GEN_18 = {quotHalfIter_quotNext[29:0], 2'h1};
  wire [31:0] _GEN_19 = {quotHalfIter_quotNext[29:0], 2'h0};
  wire [31:0] _GEN_20 = {quotM1HalfIter_quotM1Next[29:0], 2'h3};
  wire [31:0] _GEN_21 = {quotM1HalfIter_quotM1Next[29:0], 2'h2};
  wire [35:0] _rNextPd_T_10 = rSumReg + rCarryReg;
  wire [31:0] _quotIterNext_quotNext_T_24 = qNext_sel_q_0 ? _GEN_21 : 32'h0;
  wire [31:0] _quotIterNext_quotNext_T_23 = qNext_sel_q_1 ? _GEN_20 : 32'h0;
  wire [31:0] _quotIterNext_quotNext_T_22 = qNext_sel_q_2 ? _GEN_19 : 32'h0;
  wire [31:0] _quotIterNext_quotNext_T_21 = qNext_sel_q_3 ? _GEN_18 : 32'h0;
  wire [31:0] _quotIterNext_quotNext_T_20 =
    qNext_sel_q_4 ? {quotHalfIter_quotNext[29:0], 2'h2} : 32'h0;
  wire [31:0] _quotM1IterNext_quotM1Next_T_24 =
    qNext_sel_q_0 ? {quotM1HalfIter_quotM1Next[29:0], 2'h1} : 32'h0;
  wire [31:0] _quotM1IterNext_quotM1Next_T_23 = qNext_sel_q_1 ? _GEN_21 : 32'h0;
  wire [31:0] _quotM1IterNext_quotM1Next_T_22 = qNext_sel_q_2 ? _GEN_20 : 32'h0;
  wire [31:0] _quotM1IterNext_quotM1Next_T_21 = qNext_sel_q_3 ? _GEN_19 : 32'h0;
  wire [31:0] _quotM1IterNext_quotM1Next_T_20 = qNext_sel_q_4 ? _GEN_18 : 32'h0;
  wire [4:0]  rSumInitTrunc = {1'h0, _rSumInit_T_2[32:29]};
  wire [4:0]  _qInit_T_6 = rSumInitTrunc >= mInitPos1 ? 5'h8 : 5'h4;
  wire [4:0]  qInit = rSumInitTrunc >= mInitPos2 ? 5'h10 : _qInit_T_6;
  wire [2:0]  _GEN_22 = {3{casez_tmp[6]}};
  wire [9:0]  _GEN_23 = {_GEN_22, casez_tmp};
  wire [1:0]  _GEN_24 = {2{_GEN_10[6]}};
  wire [9:0]  _GEN_25 = {_GEN_24, _GEN_10, 1'h0};
  wire [1:0]  _GEN_26 = {2{_GEN_12[6]}};
  wire [9:0]  _GEN_27 = {_GEN_26, _GEN_12, 1'h0};
  wire [2:0]  _GEN_28 = {3{casez_tmp_0[6]}};
  wire [9:0]  _GEN_29 = {_GEN_28, casez_tmp_0};
  wire [9:0]  _GEN_30 = {_GEN_13, dNeg[32:25]};
  wire [4:0]  _GEN_31 = {5{casez_tmp[6]}};
  wire [12:0] _GEN_32 = {_GEN_31, casez_tmp, 1'h0};
  wire [3:0]  _GEN_33 = {4{_GEN_10[6]}};
  wire [12:0] _GEN_34 = {_GEN_33, _GEN_10, 2'h0};
  wire [3:0]  _GEN_35 = {4{_GEN_12[6]}};
  wire [12:0] _GEN_36 = {_GEN_35, _GEN_12, 2'h0};
  wire [4:0]  _GEN_37 = {5{casez_tmp_0[6]}};
  wire [12:0] _GEN_38 = {_GEN_37, casez_tmp_0, 1'h0};
  wire [12:0] _GEN_39 = {_GEN_13, dNeg[32:22]};
  wire [12:0] _GEN_40 = {dNeg[32], dNeg[32:21]};
  wire [35:0] _rNextPd_T_13 = _rNextPd_T_10 + {1'h0, dNormReg, 3'h0};
  always @(posedge clock) begin
    if (reset)
      state <= 7'h1;
    else if (state[0] & in_fire)
      state <= 7'h2;
    else if (state[1])
      state <= 7'h4;
    else if (state[2])
      state <= special ? 7'h20 : 7'h8;
    else if (state[3])
      state <= (|iterNumReg) ? 7'h8 : 7'h10;
    else if (state[4])
      state <= 7'h20;
    else if (state[5])
      state <= 7'h40;
    else if (state[6] & io_out_ready)
      state <= 7'h1;
    if (state[2] | state[3] | state[4]) begin
      if (state[3])
        quotIterReg <=
          _quotM1IterNext_T & ~(|iterNumReg)
            ? quotHalfIter_quotNext
            : _quotIterNext_quotNext_T_20 | _quotIterNext_quotNext_T_21
              | _quotIterNext_quotNext_T_22 | _quotIterNext_quotNext_T_23
              | _quotIterNext_quotNext_T_24;
      else if (state[2])
        quotIterReg <= 32'h0;
      else if (quotSignReg)
        quotIterReg <= aInverter;
    end
    if (state[2] | state[3] | state[4]) begin
      if (state[3])
        quotM1IterReg <=
          _quotM1IterNext_T & ~(|iterNumReg)
            ? quotM1HalfIter_quotM1Next
            : _quotM1IterNext_quotM1Next_T_20 | _quotM1IterNext_quotM1Next_T_21
              | _quotM1IterNext_quotM1Next_T_22 | _quotM1IterNext_quotM1Next_T_23
              | _quotM1IterNext_quotM1Next_T_24;
      else if (state[2])
        quotM1IterReg <= 32'h0;
      else if (quotSignReg)
        quotM1IterReg <= dInverter;
    end
    if (state[2])
      specialReg <= special;
    if (in_fire) begin
      aReg <= io_src_0;
      isHi_r <= io_isHi;
      dSignReg <= dSign;
      aAbsReg <= aSign ? aInverter : io_src_0;
      dAbsReg <= dSign ? dInverter : io_src_1;
      rSignReg <= aSign;
    end
    if (state[1])
      aNormReg <= _aNorm_T_2[31:0];
    if (state[1])
      dNormReg <= _dNorm_T_2[31:0];
    if (state[1])
      aLZCReg <= {1'h0, _aLZC_T_63};
    if (state[1])
      dLZCReg <= {1'h0, _dLZC_T_63};
    if (state[1])
      aTooSmall <= _lzcWireDiff_T_4[5];
    if (state[2])
      quotSpecialReg <= dIsZero ? 32'hFFFFFFFF : _quotSpecial_T_4;
    if (state[2])
      remSpecialReg <= dIsZero | aTooSmall ? aReg : 32'h0;
    if (in_fire | state[2] & dIsZero)
      quotSignReg <= ~(state[0]) | aSign ^ dSign;
    if (state[2] | state[3])
      iterNumReg <= state[2] ? _iterNum_T_2[4:2] : iterNumReg - 3'h1;
    if (state[2] | state[3])
      qPrevReg <=
        state[2]
          ? qInit
          : _qNext2_T_5 | _qNext2_T_6 | _qNext2_T_7 | _qNext2_T_8 | _qNext2_T_9;
    if (state[2] | state[3])
      rSumReg <= state[2] ? {3'h0, _rSumInit_T_2} : rSumIter;
    if (state[2] | state[3])
      rCarryReg <= state[2] ? 36'h0 : {_GEN_1, 1'h0};
    if (state[2]) begin
      udNegReg_0 <= {2'h0, dNormReg, 2'h0};
      udNegReg_1 <= {3'h0, dNormReg, 1'h0};
      udNegReg_3 <= {_GEN_13, dNeg, 1'h0};
      udNegReg_4 <= {dNeg[32], dNeg, 2'h0};
    end
    if (state[2]) begin
      rudPmNegReg_0_0 <= _GEN_2 + _GEN_23;
      rudPmNegReg_0_1 <= _GEN_2 + _GEN_25;
      rudPmNegReg_0_2 <= _GEN_2 + _GEN_27;
      rudPmNegReg_0_3 <= _GEN_2 + _GEN_29;
      rudPmNegReg_1_0 <= _GEN_3 + _GEN_23;
      rudPmNegReg_1_1 <= _GEN_3 + _GEN_25;
      rudPmNegReg_1_2 <= _GEN_3 + _GEN_27;
      rudPmNegReg_1_3 <= _GEN_3 + _GEN_29;
      rudPmNegReg_2_0 <= {_GEN_22, casez_tmp};
      rudPmNegReg_2_1 <= {_GEN_24, _GEN_10, 1'h0};
      rudPmNegReg_2_2 <= {_GEN_26, _GEN_12, 1'h0};
      rudPmNegReg_2_3 <= {_GEN_28, casez_tmp_0};
      rudPmNegReg_3_0 <= _GEN_30 + _GEN_23;
      rudPmNegReg_3_1 <= _GEN_30 + _GEN_25;
      rudPmNegReg_3_2 <= _GEN_30 + _GEN_27;
      rudPmNegReg_3_3 <= _GEN_30 + _GEN_29;
      rudPmNegReg_4_0 <= {dNeg[32], dNeg[32:24]} + _GEN_23;
      rudPmNegReg_4_1 <= {dNeg[32], dNeg[32:24]} + _GEN_25;
      rudPmNegReg_4_2 <= {dNeg[32], dNeg[32:24]} + _GEN_27;
      rudPmNegReg_4_3 <= {dNeg[32], dNeg[32:24]} + _GEN_29;
    end
    if (state[2]) begin
      r2udPmNegReg_0_0 <= _GEN_4 + _GEN_32;
      r2udPmNegReg_0_1 <= _GEN_4 + _GEN_34;
      r2udPmNegReg_0_2 <= _GEN_4 + _GEN_36;
      r2udPmNegReg_0_3 <= _GEN_4 + _GEN_38;
      r2udPmNegReg_1_0 <= _GEN_5 + _GEN_32;
      r2udPmNegReg_1_1 <= _GEN_5 + _GEN_34;
      r2udPmNegReg_1_2 <= _GEN_5 + _GEN_36;
      r2udPmNegReg_1_3 <= _GEN_5 + _GEN_38;
      r2udPmNegReg_2_0 <= {_GEN_31, casez_tmp, 1'h0};
      r2udPmNegReg_2_1 <= {_GEN_33, _GEN_10, 2'h0};
      r2udPmNegReg_2_2 <= {_GEN_35, _GEN_12, 2'h0};
      r2udPmNegReg_2_3 <= {_GEN_37, casez_tmp_0, 1'h0};
      r2udPmNegReg_3_0 <= _GEN_39 + _GEN_32;
      r2udPmNegReg_3_1 <= _GEN_39 + _GEN_34;
      r2udPmNegReg_3_2 <= _GEN_39 + _GEN_36;
      r2udPmNegReg_3_3 <= _GEN_39 + _GEN_38;
      r2udPmNegReg_4_0 <= _GEN_40 + _GEN_32;
      r2udPmNegReg_4_1 <= _GEN_40 + _GEN_34;
      r2udPmNegReg_4_2 <= _GEN_40 + _GEN_36;
      r2udPmNegReg_4_3 <= _GEN_40 + _GEN_38;
    end
    if (state[4])
      rNextReg <= rSignReg ? _rNext_T_4[35:3] : _rNextPd_T_10[35:3];
    if (state[4])
      rNextPdReg <= rSignReg ? _rNextPd_T_8[35:3] : _rNextPd_T_13[35:3];
    if (state[5])
      rFinal <= specialReg ? remSpecialReg : _rightShifter_io_out;
    if (state[5])
      qFinal <= specialReg ? quotSpecialReg : _qFinal_T;
  end // always @(posedge)
  CSA3_2 signs_csa_sel_0 (
    .io_in_0  (rSumReg[35:26]),
    .io_in_1  (rCarryReg[35:26]),
    .io_in_2
      (_signs_csa_sel_0_io_in_2_T_5 | _signs_csa_sel_0_io_in_2_T_6
       | _signs_csa_sel_0_io_in_2_T_7 | _signs_csa_sel_0_io_in_2_T_8
       | _signs_csa_sel_0_io_in_2_T_9),
    .io_out_0 (_signs_csa_sel_0_io_out_0),
    .io_out_1 (_signs_csa_sel_0_io_out_1)
  );
  CSA3_2 signs_csa_sel_1 (
    .io_in_0  (rSumReg[35:26]),
    .io_in_1  (rCarryReg[35:26]),
    .io_in_2
      (_signs_csa_sel_1_io_in_2_T_14 | _signs_csa_sel_1_io_in_2_T_15
       | _signs_csa_sel_1_io_in_2_T_16 | _signs_csa_sel_1_io_in_2_T_17
       | _signs_csa_sel_1_io_in_2_T_18),
    .io_out_0 (_signs_csa_sel_1_io_out_0),
    .io_out_1 (_signs_csa_sel_1_io_out_1)
  );
  CSA3_2 signs_csa_sel_2 (
    .io_in_0  (rSumReg[35:26]),
    .io_in_1  (rCarryReg[35:26]),
    .io_in_2
      (_signs_csa_sel_2_io_in_2_T_23 | _signs_csa_sel_2_io_in_2_T_24
       | _signs_csa_sel_2_io_in_2_T_25 | _signs_csa_sel_2_io_in_2_T_26
       | _signs_csa_sel_2_io_in_2_T_27),
    .io_out_0 (_signs_csa_sel_2_io_out_0),
    .io_out_1 (_signs_csa_sel_2_io_out_1)
  );
  CSA3_2 signs_csa_sel_3 (
    .io_in_0  (rSumReg[35:26]),
    .io_in_1  (rCarryReg[35:26]),
    .io_in_2
      (_signs_csa_sel_3_io_in_2_T_32 | _signs_csa_sel_3_io_in_2_T_33
       | _signs_csa_sel_3_io_in_2_T_34 | _signs_csa_sel_3_io_in_2_T_35
       | _signs_csa_sel_3_io_in_2_T_36),
    .io_out_0 (_signs_csa_sel_3_io_out_0),
    .io_out_1 (_signs_csa_sel_3_io_out_1)
  );
  CSA3_2_4 csa_sel_wide_1 (
    .io_in_0  ({rSumReg[33:0], 2'h0}),
    .io_in_1  ({rCarryReg[33:0], 2'h0}),
    .io_in_2
      ({_csa_sel_wide_1_io_in_2_T_5 | _csa_sel_wide_1_io_in_2_T_6
          | _csa_sel_wide_1_io_in_2_T_8 | _csa_sel_wide_1_io_in_2_T_9,
        2'h0}),
    .io_out_0 (_csa_sel_wide_1_io_out_0),
    .io_out_1 (_csa_sel_wide_1_io_out_1)
  );
  CSA3_2_4 csa_sel_wide_2 (
    .io_in_0  ({_csa_sel_wide_1_io_out_0[33:0], 2'h0}),
    .io_in_1  ({_csa_sel_wide_1_io_out_1[32:0], 3'h0}),
    .io_in_2
      ({_csa_sel_wide_2_io_in_2_T_5 | _csa_sel_wide_2_io_in_2_T_6
          | _csa_sel_wide_2_io_in_2_T_8 | _csa_sel_wide_2_io_in_2_T_9,
        2'h0}),
    .io_out_0 (_csa_sel_wide_2_io_out_0),
    .io_out_1 (_csa_sel_wide_2_io_out_1)
  );
  CSA3_2_6 csa_spec_0 (
    .io_in_0  (rSumReg[35:23]),
    .io_in_1  (rCarryReg[35:23]),
    .io_in_2  ({{3{udNegReg_0[34]}}, udNegReg_0[34:25]}),
    .io_out_0 (_csa_spec_0_io_out_0),
    .io_out_1 (_csa_spec_0_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_0_0 (
    .io_in_0  (_csa_spec_0_io_out_0),
    .io_in_1  ({_csa_spec_0_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_0_0_io_in_2_T_5 | _signs2_csa_spec_0_0_io_in_2_T_6
       | _signs2_csa_spec_0_0_io_in_2_T_7 | _signs2_csa_spec_0_0_io_in_2_T_8
       | _signs2_csa_spec_0_0_io_in_2_T_9),
    .io_out_0 (_signs2_csa_spec_0_0_io_out_0),
    .io_out_1 (_signs2_csa_spec_0_0_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_0_1 (
    .io_in_0  (_csa_spec_0_io_out_0),
    .io_in_1  ({_csa_spec_0_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_0_1_io_in_2_T_14 | _signs2_csa_spec_0_1_io_in_2_T_15
       | _signs2_csa_spec_0_1_io_in_2_T_16 | _signs2_csa_spec_0_1_io_in_2_T_17
       | _signs2_csa_spec_0_1_io_in_2_T_18),
    .io_out_0 (_signs2_csa_spec_0_1_io_out_0),
    .io_out_1 (_signs2_csa_spec_0_1_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_0_2 (
    .io_in_0  (_csa_spec_0_io_out_0),
    .io_in_1  ({_csa_spec_0_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_0_2_io_in_2_T_23 | _signs2_csa_spec_0_2_io_in_2_T_24
       | _signs2_csa_spec_0_2_io_in_2_T_25 | _signs2_csa_spec_0_2_io_in_2_T_26
       | _signs2_csa_spec_0_2_io_in_2_T_27),
    .io_out_0 (_signs2_csa_spec_0_2_io_out_0),
    .io_out_1 (_signs2_csa_spec_0_2_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_0_3 (
    .io_in_0  (_csa_spec_0_io_out_0),
    .io_in_1  ({_csa_spec_0_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_0_3_io_in_2_T_32 | _signs2_csa_spec_0_3_io_in_2_T_33
       | _signs2_csa_spec_0_3_io_in_2_T_34 | _signs2_csa_spec_0_3_io_in_2_T_35
       | _signs2_csa_spec_0_3_io_in_2_T_36),
    .io_out_0 (_signs2_csa_spec_0_3_io_out_0),
    .io_out_1 (_signs2_csa_spec_0_3_io_out_1)
  );
  CSA3_2_6 csa_spec_1 (
    .io_in_0  (rSumReg[35:23]),
    .io_in_1  (rCarryReg[35:23]),
    .io_in_2  ({{3{udNegReg_1[34]}}, udNegReg_1[34:25]}),
    .io_out_0 (_csa_spec_1_io_out_0),
    .io_out_1 (_csa_spec_1_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_1_0 (
    .io_in_0  (_csa_spec_1_io_out_0),
    .io_in_1  ({_csa_spec_1_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_1_0_io_in_2_T_5 | _signs2_csa_spec_1_0_io_in_2_T_6
       | _signs2_csa_spec_1_0_io_in_2_T_7 | _signs2_csa_spec_1_0_io_in_2_T_8
       | _signs2_csa_spec_1_0_io_in_2_T_9),
    .io_out_0 (_signs2_csa_spec_1_0_io_out_0),
    .io_out_1 (_signs2_csa_spec_1_0_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_1_1 (
    .io_in_0  (_csa_spec_1_io_out_0),
    .io_in_1  ({_csa_spec_1_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_1_1_io_in_2_T_14 | _signs2_csa_spec_1_1_io_in_2_T_15
       | _signs2_csa_spec_1_1_io_in_2_T_16 | _signs2_csa_spec_1_1_io_in_2_T_17
       | _signs2_csa_spec_1_1_io_in_2_T_18),
    .io_out_0 (_signs2_csa_spec_1_1_io_out_0),
    .io_out_1 (_signs2_csa_spec_1_1_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_1_2 (
    .io_in_0  (_csa_spec_1_io_out_0),
    .io_in_1  ({_csa_spec_1_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_1_2_io_in_2_T_23 | _signs2_csa_spec_1_2_io_in_2_T_24
       | _signs2_csa_spec_1_2_io_in_2_T_25 | _signs2_csa_spec_1_2_io_in_2_T_26
       | _signs2_csa_spec_1_2_io_in_2_T_27),
    .io_out_0 (_signs2_csa_spec_1_2_io_out_0),
    .io_out_1 (_signs2_csa_spec_1_2_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_1_3 (
    .io_in_0  (_csa_spec_1_io_out_0),
    .io_in_1  ({_csa_spec_1_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_1_3_io_in_2_T_32 | _signs2_csa_spec_1_3_io_in_2_T_33
       | _signs2_csa_spec_1_3_io_in_2_T_34 | _signs2_csa_spec_1_3_io_in_2_T_35
       | _signs2_csa_spec_1_3_io_in_2_T_36),
    .io_out_0 (_signs2_csa_spec_1_3_io_out_0),
    .io_out_1 (_signs2_csa_spec_1_3_io_out_1)
  );
  CSA3_2_6 csa_spec_2 (
    .io_in_0  (rSumReg[35:23]),
    .io_in_1  (rCarryReg[35:23]),
    .io_in_2  (13'h0),
    .io_out_0 (_csa_spec_2_io_out_0),
    .io_out_1 (_csa_spec_2_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_2_0 (
    .io_in_0  (_csa_spec_2_io_out_0),
    .io_in_1  ({_csa_spec_2_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_2_0_io_in_2_T_5 | _signs2_csa_spec_2_0_io_in_2_T_6
       | _signs2_csa_spec_2_0_io_in_2_T_7 | _signs2_csa_spec_2_0_io_in_2_T_8
       | _signs2_csa_spec_2_0_io_in_2_T_9),
    .io_out_0 (_signs2_csa_spec_2_0_io_out_0),
    .io_out_1 (_signs2_csa_spec_2_0_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_2_1 (
    .io_in_0  (_csa_spec_2_io_out_0),
    .io_in_1  ({_csa_spec_2_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_2_1_io_in_2_T_14 | _signs2_csa_spec_2_1_io_in_2_T_15
       | _signs2_csa_spec_2_1_io_in_2_T_16 | _signs2_csa_spec_2_1_io_in_2_T_17
       | _signs2_csa_spec_2_1_io_in_2_T_18),
    .io_out_0 (_signs2_csa_spec_2_1_io_out_0),
    .io_out_1 (_signs2_csa_spec_2_1_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_2_2 (
    .io_in_0  (_csa_spec_2_io_out_0),
    .io_in_1  ({_csa_spec_2_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_2_2_io_in_2_T_23 | _signs2_csa_spec_2_2_io_in_2_T_24
       | _signs2_csa_spec_2_2_io_in_2_T_25 | _signs2_csa_spec_2_2_io_in_2_T_26
       | _signs2_csa_spec_2_2_io_in_2_T_27),
    .io_out_0 (_signs2_csa_spec_2_2_io_out_0),
    .io_out_1 (_signs2_csa_spec_2_2_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_2_3 (
    .io_in_0  (_csa_spec_2_io_out_0),
    .io_in_1  ({_csa_spec_2_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_2_3_io_in_2_T_32 | _signs2_csa_spec_2_3_io_in_2_T_33
       | _signs2_csa_spec_2_3_io_in_2_T_34 | _signs2_csa_spec_2_3_io_in_2_T_35
       | _signs2_csa_spec_2_3_io_in_2_T_36),
    .io_out_0 (_signs2_csa_spec_2_3_io_out_0),
    .io_out_1 (_signs2_csa_spec_2_3_io_out_1)
  );
  CSA3_2_6 csa_spec_3 (
    .io_in_0  (rSumReg[35:23]),
    .io_in_1  (rCarryReg[35:23]),
    .io_in_2  ({{3{udNegReg_3[34]}}, udNegReg_3[34:25]}),
    .io_out_0 (_csa_spec_3_io_out_0),
    .io_out_1 (_csa_spec_3_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_3_0 (
    .io_in_0  (_csa_spec_3_io_out_0),
    .io_in_1  ({_csa_spec_3_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_3_0_io_in_2_T_5 | _signs2_csa_spec_3_0_io_in_2_T_6
       | _signs2_csa_spec_3_0_io_in_2_T_7 | _signs2_csa_spec_3_0_io_in_2_T_8
       | _signs2_csa_spec_3_0_io_in_2_T_9),
    .io_out_0 (_signs2_csa_spec_3_0_io_out_0),
    .io_out_1 (_signs2_csa_spec_3_0_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_3_1 (
    .io_in_0  (_csa_spec_3_io_out_0),
    .io_in_1  ({_csa_spec_3_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_3_1_io_in_2_T_14 | _signs2_csa_spec_3_1_io_in_2_T_15
       | _signs2_csa_spec_3_1_io_in_2_T_16 | _signs2_csa_spec_3_1_io_in_2_T_17
       | _signs2_csa_spec_3_1_io_in_2_T_18),
    .io_out_0 (_signs2_csa_spec_3_1_io_out_0),
    .io_out_1 (_signs2_csa_spec_3_1_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_3_2 (
    .io_in_0  (_csa_spec_3_io_out_0),
    .io_in_1  ({_csa_spec_3_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_3_2_io_in_2_T_23 | _signs2_csa_spec_3_2_io_in_2_T_24
       | _signs2_csa_spec_3_2_io_in_2_T_25 | _signs2_csa_spec_3_2_io_in_2_T_26
       | _signs2_csa_spec_3_2_io_in_2_T_27),
    .io_out_0 (_signs2_csa_spec_3_2_io_out_0),
    .io_out_1 (_signs2_csa_spec_3_2_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_3_3 (
    .io_in_0  (_csa_spec_3_io_out_0),
    .io_in_1  ({_csa_spec_3_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_3_3_io_in_2_T_32 | _signs2_csa_spec_3_3_io_in_2_T_33
       | _signs2_csa_spec_3_3_io_in_2_T_34 | _signs2_csa_spec_3_3_io_in_2_T_35
       | _signs2_csa_spec_3_3_io_in_2_T_36),
    .io_out_0 (_signs2_csa_spec_3_3_io_out_0),
    .io_out_1 (_signs2_csa_spec_3_3_io_out_1)
  );
  CSA3_2_6 csa_spec_4 (
    .io_in_0  (rSumReg[35:23]),
    .io_in_1  (rCarryReg[35:23]),
    .io_in_2  ({{3{udNegReg_4[34]}}, udNegReg_4[34:25]}),
    .io_out_0 (_csa_spec_4_io_out_0),
    .io_out_1 (_csa_spec_4_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_4_0 (
    .io_in_0  (_csa_spec_4_io_out_0),
    .io_in_1  ({_csa_spec_4_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_4_0_io_in_2_T_5 | _signs2_csa_spec_4_0_io_in_2_T_6
       | _signs2_csa_spec_4_0_io_in_2_T_7 | _signs2_csa_spec_4_0_io_in_2_T_8
       | _signs2_csa_spec_4_0_io_in_2_T_9),
    .io_out_0 (_signs2_csa_spec_4_0_io_out_0),
    .io_out_1 (_signs2_csa_spec_4_0_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_4_1 (
    .io_in_0  (_csa_spec_4_io_out_0),
    .io_in_1  ({_csa_spec_4_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_4_1_io_in_2_T_14 | _signs2_csa_spec_4_1_io_in_2_T_15
       | _signs2_csa_spec_4_1_io_in_2_T_16 | _signs2_csa_spec_4_1_io_in_2_T_17
       | _signs2_csa_spec_4_1_io_in_2_T_18),
    .io_out_0 (_signs2_csa_spec_4_1_io_out_0),
    .io_out_1 (_signs2_csa_spec_4_1_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_4_2 (
    .io_in_0  (_csa_spec_4_io_out_0),
    .io_in_1  ({_csa_spec_4_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_4_2_io_in_2_T_23 | _signs2_csa_spec_4_2_io_in_2_T_24
       | _signs2_csa_spec_4_2_io_in_2_T_25 | _signs2_csa_spec_4_2_io_in_2_T_26
       | _signs2_csa_spec_4_2_io_in_2_T_27),
    .io_out_0 (_signs2_csa_spec_4_2_io_out_0),
    .io_out_1 (_signs2_csa_spec_4_2_io_out_1)
  );
  CSA3_2_6 signs2_csa_spec_4_3 (
    .io_in_0  (_csa_spec_4_io_out_0),
    .io_in_1  ({_csa_spec_4_io_out_1[11:0], 1'h0}),
    .io_in_2
      (_signs2_csa_spec_4_3_io_in_2_T_32 | _signs2_csa_spec_4_3_io_in_2_T_33
       | _signs2_csa_spec_4_3_io_in_2_T_34 | _signs2_csa_spec_4_3_io_in_2_T_35
       | _signs2_csa_spec_4_3_io_in_2_T_36),
    .io_out_0 (_signs2_csa_spec_4_3_io_out_0),
    .io_out_1 (_signs2_csa_spec_4_3_io_out_1)
  );
  RightShifter rightShifter (
    .io_shiftNum (dLZCReg[4:0]),
    .io_in       (rPreShifted[31:0]),
    .io_msb      ((|rPreShifted) & rSignReg),
    .io_out      (_rightShifter_io_out)
  );
  assign io_in_ready = state[0];
  assign io_out_valid = state[6];
  assign io_out_data = isHi_r ? rFinal : qFinal;
endmodule

