// Generated by CIRCT firtool-1.76.0
module WoodLSRetireMIPipelineRegister(
  input  wire        clock,
  input  wire        reset,
  input  wire        io_in_valid,
  input  wire        io_in_bits_retired,
  input  wire [6:0]  io_in_bits_rdTag,
  input  wire        io_in_bits_isBranch,
  input  wire        io_in_bits_isJAL,
  input  wire [1:0]  io_in_bits_lsType,
  input  wire        io_in_bits_wakeup,
  input  wire [1:0]  io_in_bits_opsrc1,
  input  wire [1:0]  io_in_bits_opsrc2,
  input  wire [1:0]  io_in_bits_writeRf,
  input  wire [2:0]  io_in_bits_exEngine,
  input  wire [5:0]  io_in_bits_exOp,
  input  wire [5:0]  io_in_bits_lsOp,
  input  wire        io_in_bits_exception,
  input  wire        io_in_bits_taken,
  input  wire [31:0] io_in_bits_imm,
  input  wire [4:0]  io_in_bits_rs1,
  input  wire [4:0]  io_in_bits_rs2,
  input  wire [4:0]  io_in_bits_rd,
  input  wire [31:0] io_in_bits_pc,
  input  wire [31:0] io_in_bits_targetPC,
  input  wire [6:0]  io_in_bits_rs1Tag,
  input  wire        io_in_bits_rs1TagReady,
  input  wire [6:0]  io_in_bits_rs2Tag,
  input  wire        io_in_bits_rs2TagReady,
  input  wire [31:0] io_in_bits_rs1Data,
  input  wire [31:0] io_in_bits_rs2Data,
  input  wire [31:0] io_in_bits_rdData,
  input  wire        io_in_bits_operandReady,
  input  wire        io_in_bits_flushed,
  input  wire [6:0]  io_in_bits_arfTag,
  input  wire        io_in_bits_arfValid,
  input  wire [31:0] io_in_bits_inst,
  input  wire        io_setflushed,
  input  wire        io_frontRetired,
  input  wire        io_lsOperandBus_0_valid,
  input  wire [31:0] io_lsOperandBus_0_bits_targetAddr,
  input  wire [31:0] io_lsOperandBus_0_bits_rs2Data,
  input  wire [6:0]  io_lsOperandBus_0_bits_rdTag,
  input  wire        io_lsOperandBus_1_valid,
  input  wire [31:0] io_lsOperandBus_1_bits_targetAddr,
  input  wire [31:0] io_lsOperandBus_1_bits_rs2Data,
  input  wire [6:0]  io_lsOperandBus_1_bits_rdTag,
  input  wire        io_out_ready,
  output wire        io_out_valid,
  output wire        io_out_bits_retired,
  output wire [6:0]  io_out_bits_rdTag,
  output wire        io_out_bits_isBranch,
  output wire        io_out_bits_isJAL,
  output wire [1:0]  io_out_bits_lsType,
  output wire        io_out_bits_wakeup,
  output wire [1:0]  io_out_bits_opsrc1,
  output wire [1:0]  io_out_bits_opsrc2,
  output wire [1:0]  io_out_bits_writeRf,
  output wire [2:0]  io_out_bits_exEngine,
  output wire [5:0]  io_out_bits_exOp,
  output wire [5:0]  io_out_bits_lsOp,
  output wire        io_out_bits_exception,
  output wire        io_out_bits_taken,
  output wire [31:0] io_out_bits_imm,
  output wire [4:0]  io_out_bits_rs1,
  output wire [4:0]  io_out_bits_rs2,
  output wire [4:0]  io_out_bits_rd,
  output wire [31:0] io_out_bits_pc,
  output wire [31:0] io_out_bits_targetPC,
  output wire [6:0]  io_out_bits_rs1Tag,
  output wire        io_out_bits_rs1TagReady,
  output wire [6:0]  io_out_bits_rs2Tag,
  output wire        io_out_bits_rs2TagReady,
  output wire [31:0] io_out_bits_rs1Data,
  output wire [31:0] io_out_bits_rs2Data,
  output wire [31:0] io_out_bits_rdData,
  output wire        io_out_bits_operandReady,
  output wire        io_out_bits_flushed,
  output wire [6:0]  io_out_bits_arfTag,
  output wire        io_out_bits_arfValid,
  output wire [31:0] io_out_bits_inst
);

  reg         regData_retired;
  reg  [6:0]  regData_rdTag;
  reg         regData_isBranch;
  reg         regData_isJAL;
  reg  [1:0]  regData_lsType;
  reg         regData_wakeup;
  reg  [1:0]  regData_opsrc1;
  reg  [1:0]  regData_opsrc2;
  reg  [1:0]  regData_writeRf;
  reg  [2:0]  regData_exEngine;
  reg  [5:0]  regData_exOp;
  reg  [5:0]  regData_lsOp;
  reg         regData_exception;
  reg         regData_taken;
  reg  [31:0] regData_imm;
  reg  [4:0]  regData_rs1;
  reg  [4:0]  regData_rs2;
  reg  [4:0]  regData_rd;
  reg  [31:0] regData_pc;
  reg  [31:0] regData_targetPC;
  reg  [6:0]  regData_rs1Tag;
  reg         regData_rs1TagReady;
  reg  [6:0]  regData_rs2Tag;
  reg         regData_rs2TagReady;
  reg  [31:0] regData_rs1Data;
  reg  [31:0] regData_rs2Data;
  reg  [31:0] regData_rdData;
  reg         regData_operandReady;
  reg         regData_flushed;
  reg  [6:0]  regData_arfTag;
  reg         regData_arfValid;
  reg  [31:0] regData_inst;
  reg         regValid;
  wire        operandBusMatches_0;
  wire        operandBusMatchIndex = ~operandBusMatches_0;
  assign operandBusMatches_0 =
    io_lsOperandBus_0_valid & regData_rdTag == io_lsOperandBus_0_bits_rdTag;
  wire        operandBusMatches_1 =
    io_lsOperandBus_1_valid & regData_rdTag == io_lsOperandBus_1_bits_rdTag;
  wire        _regValidNext_T_2 = io_setflushed & io_out_ready;
  wire        _GEN =
    _regValidNext_T_2 & io_in_bits_retired | _regValidNext_T_2 & ~io_in_bits_retired
    | ~(io_setflushed & ~io_out_ready & io_frontRetired | io_setflushed & ~io_out_ready
        & ~io_frontRetired | ~(~io_setflushed & io_out_ready));
  wire [1:0]  _regDataNext_operandReady_T_9 = {operandBusMatches_1, operandBusMatches_0};
  wire [31:0] _GEN_0 =
    operandBusMatchIndex
      ? io_lsOperandBus_1_bits_targetAddr
      : io_lsOperandBus_0_bits_targetAddr;
  wire [31:0] _GEN_1 =
    operandBusMatchIndex
      ? io_lsOperandBus_1_bits_rs2Data
      : io_lsOperandBus_0_bits_rs2Data;
  wire        _GEN_2 = io_setflushed | io_out_ready;
  wire [2:0]  _GEN_3 = {regData_operandReady, operandBusMatches_1, operandBusMatches_0};
  wire        regDataNextInvalidForwards_flushed =
    _GEN ? io_in_bits_flushed : regData_flushed;
  wire        _regValidNext_T_18 = ~io_setflushed & io_out_ready ? io_in_valid : regValid;
  wire        _regValidNext_T_20 =
    io_setflushed & ~io_out_ready & io_frontRetired
      ? regValid
      : ~(io_setflushed & ~io_out_ready & ~io_frontRetired) & _regValidNext_T_18;
  always @(posedge clock) begin
    if (reset) begin
      regData_retired <= 1'h0;
      regData_rdTag <= 7'h0;
      regData_isBranch <= 1'h0;
      regData_isJAL <= 1'h0;
      regData_lsType <= 2'h0;
      regData_wakeup <= 1'h0;
      regData_opsrc1 <= 2'h0;
      regData_opsrc2 <= 2'h0;
      regData_writeRf <= 2'h0;
      regData_exEngine <= 3'h0;
      regData_exOp <= 6'h0;
      regData_lsOp <= 6'h0;
      regData_exception <= 1'h0;
      regData_taken <= 1'h0;
      regData_imm <= 32'h0;
      regData_rs1 <= 5'h0;
      regData_rs2 <= 5'h0;
      regData_rd <= 5'h0;
      regData_pc <= 32'h0;
      regData_targetPC <= 32'h0;
      regData_rs1Tag <= 7'h0;
      regData_rs1TagReady <= 1'h0;
      regData_rs2Tag <= 7'h0;
      regData_rs2TagReady <= 1'h0;
      regData_rs1Data <= 32'h0;
      regData_rs2Data <= 32'h0;
      regData_rdData <= 32'h0;
      regData_operandReady <= 1'h0;
      regData_flushed <= 1'h0;
      regData_arfTag <= 7'h0;
      regData_arfValid <= 1'h0;
      regData_inst <= 32'h0;
      regValid <= 1'h0;
    end
    else begin
      if (io_setflushed & ~io_out_ready & io_frontRetired | ~io_setflushed
          & ~io_out_ready)
        regData_retired <= regData_retired | io_frontRetired;
      else if (_GEN)
        regData_retired <= io_in_bits_retired;
      if (_GEN) begin
        regData_rdTag <= io_in_bits_rdTag;
        regData_isBranch <= io_in_bits_isBranch;
        regData_isJAL <= io_in_bits_isJAL;
        regData_lsType <= io_in_bits_lsType;
        regData_wakeup <= io_in_bits_wakeup;
        regData_opsrc1 <= io_in_bits_opsrc1;
        regData_opsrc2 <= io_in_bits_opsrc2;
        regData_writeRf <= io_in_bits_writeRf;
        regData_exEngine <= io_in_bits_exEngine;
        regData_exOp <= io_in_bits_exOp;
        regData_lsOp <= io_in_bits_lsOp;
        regData_exception <= io_in_bits_exception;
        regData_taken <= io_in_bits_taken;
        regData_imm <= io_in_bits_imm;
        regData_rs1 <= io_in_bits_rs1;
        regData_rs2 <= io_in_bits_rs2;
        regData_rd <= io_in_bits_rd;
        regData_pc <= io_in_bits_pc;
        regData_targetPC <= io_in_bits_targetPC;
        regData_rs1Tag <= io_in_bits_rs1Tag;
        regData_rs1TagReady <= io_in_bits_rs1TagReady;
        regData_rs2Tag <= io_in_bits_rs2Tag;
        regData_rs2TagReady <= io_in_bits_rs2TagReady;
        regData_rs1Data <= io_in_bits_rs1Data;
      end
      if (io_setflushed & ~io_out_ready & io_frontRetired) begin
        if (|_regDataNext_operandReady_T_9)
          regData_rs2Data <= _GEN_1;
      end
      else if (_GEN_2) begin
        if (_GEN)
          regData_rs2Data <= io_in_bits_rs2Data;
      end
      else if (|_regDataNext_operandReady_T_9)
        regData_rs2Data <= _GEN_1;
      if (io_setflushed & ~io_out_ready & io_frontRetired) begin
        if (|_regDataNext_operandReady_T_9)
          regData_rdData <= _GEN_0;
      end
      else if (_GEN_2) begin
        if (_GEN)
          regData_rdData <= io_in_bits_rdData;
      end
      else if (|_regDataNext_operandReady_T_9)
        regData_rdData <= _GEN_0;
      if (io_setflushed & ~io_out_ready & io_frontRetired)
        regData_operandReady <= |_GEN_3;
      else if (_GEN_2) begin
        if (_GEN)
          regData_operandReady <= io_in_bits_operandReady;
      end
      else
        regData_operandReady <= |_GEN_3;
      regData_flushed <=
        _regValidNext_T_2 & ~io_in_bits_retired | io_setflushed & ~io_out_ready
        & ~io_frontRetired | regDataNextInvalidForwards_flushed;
      if (_GEN) begin
        regData_arfTag <= io_in_bits_arfTag;
        regData_arfValid <= io_in_bits_arfValid;
        regData_inst <= io_in_bits_inst;
      end
      regValid <=
        _regValidNext_T_2 & io_in_bits_retired
          ? io_in_valid
          : ~(_regValidNext_T_2 & ~io_in_bits_retired) & _regValidNext_T_20;
    end
  end // always @(posedge)
  assign io_out_valid = regValid;
  assign io_out_bits_retired = regData_retired;
  assign io_out_bits_rdTag = regData_rdTag;
  assign io_out_bits_isBranch = regData_isBranch;
  assign io_out_bits_isJAL = regData_isJAL;
  assign io_out_bits_lsType = regData_lsType;
  assign io_out_bits_wakeup = regData_wakeup;
  assign io_out_bits_opsrc1 = regData_opsrc1;
  assign io_out_bits_opsrc2 = regData_opsrc2;
  assign io_out_bits_writeRf = regData_writeRf;
  assign io_out_bits_exEngine = regData_exEngine;
  assign io_out_bits_exOp = regData_exOp;
  assign io_out_bits_lsOp = regData_lsOp;
  assign io_out_bits_exception = regData_exception;
  assign io_out_bits_taken = regData_taken;
  assign io_out_bits_imm = regData_imm;
  assign io_out_bits_rs1 = regData_rs1;
  assign io_out_bits_rs2 = regData_rs2;
  assign io_out_bits_rd = regData_rd;
  assign io_out_bits_pc = regData_pc;
  assign io_out_bits_targetPC = regData_targetPC;
  assign io_out_bits_rs1Tag = regData_rs1Tag;
  assign io_out_bits_rs1TagReady = regData_rs1TagReady;
  assign io_out_bits_rs2Tag = regData_rs2Tag;
  assign io_out_bits_rs2TagReady = regData_rs2TagReady;
  assign io_out_bits_rs1Data = regData_rs1Data;
  assign io_out_bits_rs2Data = regData_rs2Data;
  assign io_out_bits_rdData = regData_rdData;
  assign io_out_bits_operandReady = regData_operandReady;
  assign io_out_bits_flushed = regData_flushed;
  assign io_out_bits_arfTag = regData_arfTag;
  assign io_out_bits_arfValid = regData_arfValid;
  assign io_out_bits_inst = regData_inst;
endmodule

