// Generated by CIRCT firtool-1.76.0
module WoodDut(
  input  wire clock,
  input  wire reset,
  input  wire io_wreset,
  input  wire io_uart_rx,
  output wire io_uart_tx
);

  wire         _wood_io_icachemem_req_valid;
  wire [31:0]  _wood_io_icachemem_req_bits_addr;
  wire         _wood_io_dcachemem_req_valid;
  wire [31:0]  _wood_io_dcachemem_req_bits_addr;
  wire [127:0] _wood_io_dcachemem_req_bits_data;
  wire         _wood_io_dcachemem_req_bits_wen;
  wire         _wood_io_dcachemem_resp_ready;
  wire         _mem_io_req_ready;
  wire         _mem_io_resp_valid;
  wire [127:0] _mem_io_resp_bits_data;
  reg  [1:0]   state;
  wire         _GEN = state == 2'h0;
  wire         _GEN_0 = state == 2'h1;
  wire         wood_io_icachemem_resp_valid = ~_GEN & _GEN_0 & _mem_io_resp_valid;
  wire [127:0] wood_io_icachemem_resp_bits_data =
    _GEN | ~_GEN_0 ? 128'h0 : _mem_io_resp_bits_data;
  wire         _GEN_1 = state == 2'h2;
  wire         _GEN_2 = _GEN | _GEN_0;
  wire         _GEN_3 =
    _GEN_0 ? _wood_io_icachemem_req_valid : _GEN_1 & _wood_io_dcachemem_req_valid;
  reg  [31:0]  casez_tmp;
  always_comb begin
    casez (state)
      2'b00:
        casez_tmp = 32'h0;
      2'b01:
        casez_tmp = _wood_io_icachemem_req_bits_addr;
      2'b10:
        casez_tmp = _wood_io_dcachemem_req_bits_addr;
      default:
        casez_tmp = 32'h0;
    endcase
  end // always_comb
  wire         wood_io_dcachemem_resp_valid = ~_GEN_2 & _GEN_1 & _mem_io_resp_valid;
  wire [127:0] wood_io_dcachemem_resp_bits_data =
    _GEN_2 | ~_GEN_1 ? 128'h0 : _mem_io_resp_bits_data;
  wire         _GEN_4 =
    _GEN_0
      ? wood_io_icachemem_resp_valid
      : _wood_io_dcachemem_resp_ready & wood_io_dcachemem_resp_valid;
  always @(posedge clock) begin
    if (reset)
      state <= 2'h0;
    else if (_GEN) begin
      if (_wood_io_icachemem_req_valid)
        state <= 2'h1;
      else if (_wood_io_dcachemem_req_valid)
        state <= 2'h2;
    end
    else if (_GEN_4)
      state <= 2'h0;
  end // always @(posedge)
  MainMemory mem (
    .clock             (clock),
    .reset             (reset),
    .io_req_ready      (_mem_io_req_ready),
    .io_req_valid      (~_GEN & _GEN_3),
    .io_req_bits_addr  (casez_tmp),
    .io_req_bits_data  (_wood_io_dcachemem_req_bits_data),
    .io_req_bits_wen   (_wood_io_dcachemem_req_bits_wen),
    .io_resp_ready     (~_GEN & (_GEN_0 | _GEN_1 & _wood_io_dcachemem_resp_ready)),
    .io_resp_valid     (_mem_io_resp_valid),
    .io_resp_bits_data (_mem_io_resp_bits_data)
  );
  Wood wood (
    .clock                       (clock),
    .reset                       (io_wreset),
    .io_icachemem_req_ready      (~_GEN & _GEN_0 & _mem_io_req_ready),
    .io_icachemem_req_valid      (_wood_io_icachemem_req_valid),
    .io_icachemem_req_bits_addr  (_wood_io_icachemem_req_bits_addr),
    .io_icachemem_resp_valid     (wood_io_icachemem_resp_valid),
    .io_icachemem_resp_bits_data (wood_io_icachemem_resp_bits_data),
    .io_dcachemem_req_ready      (~_GEN_2 & _GEN_1 & _mem_io_req_ready),
    .io_dcachemem_req_valid      (_wood_io_dcachemem_req_valid),
    .io_dcachemem_req_bits_addr  (_wood_io_dcachemem_req_bits_addr),
    .io_dcachemem_req_bits_data  (_wood_io_dcachemem_req_bits_data),
    .io_dcachemem_req_bits_wen   (_wood_io_dcachemem_req_bits_wen),
    .io_dcachemem_resp_ready     (_wood_io_dcachemem_resp_ready),
    .io_dcachemem_resp_valid     (wood_io_dcachemem_resp_valid),
    .io_dcachemem_resp_bits_data (wood_io_dcachemem_resp_bits_data),
    .io_uart_rx                  (io_uart_rx),
    .io_uart_tx                  (io_uart_tx)
  );
endmodule

